### ISSUE TITLE
As a sysadmin, I want to be able to select from several different batch data entry UI configurations of fields for the same object so I can expose different fields to different users.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#10]
- FieldSets should be used for maximum functionality
- existing list settings will need to be removed

Consider redesign over incremental improvements.

**Comment by davidhabib** [comment]
**lurch: attach W-007352

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZaAAI" target="_blank">W-007352</a>

**Comment by cdcarter** [comment]
**Sprint Reportback**

The "product vision and roadmap" team identified that a new BDE tool would be a boon for the NPSP. This is a tool that would be used to enter constituents and related records.

Other people: The conversation occurred between Tracy, Jennifer from Heller, Adam from KELL, Patricia (didn't catch her affiliation) and I facilitated the session.

Current Status: We spent a 1.5 hour session creating a user story map, identifying key features that other products have, and ultimately arguing a while and then reaching a shared understanding of what a reasonable scope for an initial version of this feature can be.

Next Steps: I will be drawing up some wireframes and writing a very broad spec of the future that this team is looking to see. Tracy wants this to then be delivered to the community so "someone can build it". I don't know if the advisory board (or certain members thereof) will argue for that someone to be the fdtn, or an external contributor, but the goal of that session was just to deliver a spec. Adam Kramer will also be screenshotting Blackbaud Luminate BDE, though those screenshots will not affect the wireframes I deliver. 

What do I need?: I do not need any resources to deliver this spec. I do think that the adv board needs to decide if it is actually useful for the community to develop a massive spec like this with no identified developer on the horizon, but that's more me than this project talking.

Where are you working: I have a pile of flip chart pages that I'm working from. They are in my room.

**Comment by cdcarter** [comment]
**Deliverables**

I've distilled the post it notes and conversations that happened in the Oct Sprint Session into a Story Map available at https://cdcarter.storiesonboard.com/m/batch-data-entry-tool and a set of sketches available at http://imgur.com/a/w0C0P.

@judisohn suggested that the best place to track this work was here. There is no developer or further "champion" of this feature identified yet, but we wanted a place to park what was done.

**Comment by melissabarber** [comment]
This has been marked as "Never" internally.
