### ISSUE TITLE
BUG: NPSP Data Importer fails to process if Data Import custom settings are saved for the first time.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1094]
I get an upsert error.  need to handle this case and do an insert instead?  I guess maybe custom settings don't handle upserts the same as other objects?

This is the error I get with the managed package.  I can't seem to reproduce in my DE Org.

Upsert failed. First exception on row 0 with id a0ei0000005M6rFAAS; first error: INVALID_CROSS_REFERENCE_KEY, invalid cross reference id: []

**Comment by Zosoled** [comment]
I think I may have come across this in my sandbox org...? After searching, finally found this issue from https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/BDI_DataImport_API.cls#L79. I'm don't think the hack is working in my case. I set the initial default Data Import Settings directly through the setup menu, and the importer worked after that. Deleting the custom settings caused it to start failing again.

**Comment by davidhabib** [comment]
#1457 just went in a few days ago and hasn't been push upgraded yet.  version 3.36
