### ISSUE TITLE
BUG: NPSP Data Importer ignores Home Address for an import record that only has Account1 and no Contacts. 

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1097]
Should either generate an error and marked the di as failed, or at least mark the Home Address Import Status field as "ignored".

It might be generating this error, even though the Account gets created:

Update failed. First exception on row 0; first error: MISSING_ARGUMENT, Id not specified in an update call: []

I'm not sure since this is marked on the record with failed for import status, and yet the Account is created and the lookup set on the import record.

**Comment by JavierFerreira** [comment]
**lurch: attach W-032951
