### ISSUE TITLE
As a user, I can have the NPSP Data Importer create different contact roles when importing opportunities.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1110]
From John Fine: 

It would be super cool when creating Opps that are assigned to Account1 if there were an option to create a Contact Role record also, assigned to Contact 1 (COntactID=Contact1, Role={user-chosen-value, Primary=user-chosen-value). Often in the input data, there is a reason that the COntact was listed on the same row as the Account and Opp (ex: that person is the donor, and the Opp is the Foundation from where the check arrived).

**Comment by kbromer** [comment]
**lurch attach W-007271

**Comment by judisohn** [comment]
**lurch: attach W-007271

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYHAAY" target="_blank">W-007271</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.160 (Beta 10)
