### ISSUE TITLE
As a user, I would like to use NPSP Data Importer in a "dry run" mode where it shows which records will be matched vs created, as well as any errors it can already detect, but it wouldn't actually save any changes to the databse (other than the di records).

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1153]
request from Jon Fine and seconded by Judi Sohn.  hub thread: https://powerofus.force.com/0D58000001aznuJ

**Comment by kbromer** [comment]
**lurch: attach W-007273

**Comment by davidhabib** [comment]
**lurch: attach W-007273

**Comment by mpusto** [comment]
Idea here: https://powerofus.force.com/hub-ideas/1023

**Comment by davidhabib** [comment]
**lurch: attach W-007273

**Comment by mrbelvedere** [comment]
Included in beta release 3.119 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.119
