### ISSUE TITLE
NPSP 3.0 installation fails if custom fiscal years are enabled due to BDE FS references to Fiscal, FiscalQuarter, and FiscalYear fields

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/Cumulus#1155]
There is not really a use case for batch data entry writing to the Fiscal, FiscalQuarter, and FiscalYear fields as they are automatically populated by the system.  However, if custom fiscal years are configured in the org, these fields are not available.  The fact that they're referenced in the available fields of the BDE field sets causes an installation failure.

The fix is to remove those fields from the BDE field sets' available fields.

**Comment by mrbelvedere** [comment]
Included in production release version 3.30
