### ISSUE TITLE
As a developer, I need to be confident that my code will run and pass tests in all org configurations

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1160]
We need an ftest org as part of our testing framework.  At a minimum, it should have by default the following enabled:

1. Multicurrency
2. A second, non-english language as default
3. State and Country Picklists
4. Possibly Person Accounts?

What other config options am I missing? 

@davidhabib @jlantz

**Comment by ceiroa** [comment]
To load large amounts of data for testing, we can consider the "Demo Data Creator for SE" app: https://org62.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000008OIA&fId=0D53000001v6xJr

**Comment by kbromer** [comment]
closed by W-007268
