### ISSUE TITLE
As an NPSP developer, I would like a set of manual test cases to be run once per release.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1162]
Document some common failure prone user flows in a test org with uncommon features activated that can be run once per release as a smoke test.

**Comment by kbromer** [comment]
I'm going to close this for now.  This is "hire more QA" and is a story for me.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fshAAA" target="_blank">W-008278</a>

**Comment by davisagli** [comment]
This is part of our process these days.
