### ISSUE TITLE
As a user, I'd like to be able to translate the contact roles and still have the soft credits rollups working

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1183]
From https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001eDlUz

**Comment by kbromer** [comment]
**lurch: attach W-007277

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYNAAY" target="_blank">W-007277</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
