### ISSUE TITLE
As a developer, I want all code to be run through TDTM or equivalent, for consistency

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1195]
All triggers and controllers use TDTM, but we need to review batch, future, and especially schedulable calls to make sure that they also use it.

For example, this is an error that seems to be coming from an schedulable:

------------
Apex script unhandled exception by user/organization: 005A0000001Hv2g/00DA0000000ARMg

Failed to process batch for class 'npsp.RLLP_OppSoftCreditRollup_BATCH' for job id '707F000001iliJY'

caused by: System.DmlException: Update failed. First exception on row 191 with id 003F000001aXN05IAG; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, There is already another Primary Account Contact.  Please uncheck the box and try to save again.PrimaryContact Diana Chapman Walsh 003F000001aXN05IAG: [Primary_Account_Contact__c]

Class.npsp.RLLP_OppRollup.rollupSoftCredits: line 685, column 1
Class.npsp.RLLP_OppSoftCreditRollup_BATCH.execute: line 56, column 1

------------

(Searching for "label:npsp-errors class.npsp" in the error emails gives you all the existing npsp errors.)

**Comment by ceiroa** [comment]
Caveat for Batch classes: we should not capture exception and log errors in their execute method, because if we don't let the exception bubble up the stack, then the batch will think it all succeeded. If we were to log it, and then propagate the exception, the transaction would get rolled back, and the logging would be erased.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
