### ISSUE TITLE
NPSP Settings pages should have links to appropriate documentation.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1208]
Each settings page should have a link to a specific knowledge article/page about that setting page. Settings pages don't all exist and will need to be created before this story can me fully completed. We can consider breaking this story into smaller pieces for the help articles that are already available.

**Comment by kbromer** [comment]
**lurch: attach W-007322

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ6AAI" target="_blank">W-007322</a>

**Comment by mpusto** [comment]
Revised in 3.73
