### ISSUE TITLE
BUG: HH_ManageHHAccount page throws error: Maximum stack depth reached: 1 

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1210]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001gqSCm

**Comment by davidhabib** [comment]
The user currently complaining of this wasn't able to reproduce after I logged into their org, and added the primary contact field from account on the field set.  I can only assume the user may have added a field on a related object, not directly on account, into the field set and that caused an error at page load.
