### ISSUE TITLE
Availability of Membership Status and Membership Span fields

### ISSUE THREAD

**Issue by alphasys** [SalesforceFoundation/Cumulus#1214]
The previous version of the NPSP allowed the household custom object to show the Membership Span and Membership Status fields. However with the recent upgrade where Households are managed in Accounts, these fields are no longer available.

It would be great if these fields could be available to the Account object and have the Membership Grace Period configuration setting apply to it.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.31 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.31

**Comment by kshvetz** [comment]
I came across these non-migrated objects when recently upgrading our Salesforce NPSP 3.0 org from 1-to-1 to the newer Household Account model.  Can someone explain to me what these fields meant or were used for... I'm just curious?   (I don't come from the non-profit world...they were all blank)

Membership Span (npo02__Membership_Span__c)
Membership Status (npo02__Membership_Status__c)

**Comment by njjc** [comment]
Hi @kshvetz, those fields are auto-calculated based on whether the contact/account has any related Opportunities with the Membership fields filled out: npe01__Member_Level__c, npe01__Membership_Start_Date__c, npe01__Membership_End_Date__c, npe01__Membership_Origin__c.

The span is how long they were a member for, and the Status is calculated based on the latest Membership End Date for a closed/won membership opportunity.
