### ISSUE TITLE
Pledged payments not set to closed lost on recurring donation closure when updated from trigger

### ISSUE THREAD

**Issue by Filikin** [SalesforceFoundation/Cumulus#1215]
I have manually tested creating a recurring donation and then updating the Open Ended Status from Open to Closed.  In this scenario all the related donations that previously had a stage of Pledged are changed to Closed Lost.

However, when I update the Open Ended Status on a recurring donation within a trigger, no change is being made to the Stage on the related donation records.

Can you suggest why this might be the case?

**Comment by davidhabib** [comment]
@Filikin are you still running into this problem?  Can you attach us a short version of code that replicates the problem?  Note that we do use a flag internally to avoid recursive changes to the RD or its Opps.  So if you are writing code that inserts or modifies the RD twice, that would cause a problem.  The first insert/modify sets the flag and does its work.  If the code then doesn't go out of context, as it would from a user action, then the second modify comes in, and the flag is still set, and it bails out.

**Comment by davidhabib** [comment]
closing since I haven't heard anything back and we can't reproduce this problem.
