### ISSUE TITLE
LD_LeadConvertOverride (LeadConvertOverride) does not update mapping fields following a merge

### ISSUE THREAD

**Issue by mHiscock** [SalesforceFoundation/Cumulus#1216]
Using this override on lead conversion. (NPSP v3)
If you set-up lead conversion mapping between a custom field on lead, to a custom field on contact
then attempt to do a merge during lead conversion it does not appear to process the leading conversion mappings. i.e. the updated value on leads is not taken across to the updated contact.
Is this a know issue/constraint?

Investigate default behavior for lead conversion update of a contact.

**Comment by davidhabib** [comment]
@mHiscock I cannot reproduce this problem with NPSP 3.0.  I created a lead mapping of preferred phone and preferred email from lead to contact, and it worked fine.  Can you please provide more details on reproducing this problem.  thanks.

**Comment by davidhabib** [comment]
@mHiscock Never mind.  I misread your report and first tried creating a new contact, which correctly supports mapped fields.  Unfortunately, if you merge a lead with an existing field, Salesforce will only copy fields from the lead if the contact field is empty.  From the Salesforce Lead User Guide:

"Salesforce adds information from the lead into empty fields; Salesforce does not overwrite existing account and contact data."
