### ISSUE TITLE
As a user, I would like to see if my custom naming formats are invalid

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1218]
Currently, if you use a custom naming format, you have to move the cursor to another field and then come back to see how it's going to look. A person that enters three invalid formats and then saves (without moving to any other field) will not see any "invalid field" message:

![screen shot 2014-12-16 at 10 06 32 am](https://cloud.githubusercontent.com/assets/1894238/5456755/61d79e3e-850b-11e4-9ff6-4d6e06852204.png)

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
