### ISSUE TITLE
Non-selective query against large object types for Contact table

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1225]
First reported here: 
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001igHvK&emtm=1418850277944&s1nid=0DB800000004Fa7&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000003egB0

@davidhabib @ceiroa here's an issue to work off of, I'll add findings here

**Comment by mrbelvedere** [comment]
Included in production release version 3.30
