### ISSUE TITLE
As a user, I would like to be able to specify an org's primary contact when using the NPSP Data Importer.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1234]
feature reqeust from John Fine: https://powerofus.force.com/0D58000001ihlkn

**Comment by kbromer** [comment]
**lurch: attach W-007244

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXqAAI" target="_blank">W-007244</a>

**Comment by melissabarber** [comment]
Included in release 3.161
