### ISSUE TITLE
Checkbox loses its default value of 'checked' in Batch Data Entry

### ISSUE THREAD

**Issue by pherzogchc** [SalesforceFoundation/Cumulus#1239]
I have a custom field that is a checkbox and the default value is set to checked.  The Batch Data Entry module does not keep the checkbox set to default - even when using the push pin feature.

![screen shot 2014-12-28 at 9 29 55 pm](https://cloud.githubusercontent.com/assets/9168719/5566005/3cd051c0-8eda-11e4-97de-2b37b246a6ff.png)
![screen shot 2014-12-28 at 9 29 33 pm](https://cloud.githubusercontent.com/assets/9168719/5566006/3e9a850c-8eda-11e4-8951-78df9492666e.png)

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 14) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32

**Comment by pherzogchc** [comment]
We are continuing to have problems with checkboxes remaining checked.  The attached screen shot shows that we created a new donation with the Tax Deductible checkbox checked and the pin selected and the result was unpinned.  The default value of the checkbox is checked and it still remains unchecked.  

![screen shot 2015-05-06 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/9168719/7503198/fe96f00c-f406-11e4-94c3-25813b15c1a7.png)

**Comment by kbromer** [comment]
**lurch: attach W-007383

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ca6AAA" target="_blank">W-007383</a>

**Comment by pherzogchc** [comment]
Has this been closed?  The bug is still a problem for us.  
 
![screen shot 2015-10-08 at 4 56 13 pm](https://cloud.githubusercontent.com/assets/9168719/10381059/865946fc-6ddd-11e5-9450-d1d577a3b722.png)

**Comment by kbromer** [comment]
Nope, just attaching it to our internal tracking system

**Comment by pherzogchc** [comment]
Great!!

On Thursday, October 8, 2015, Kevin Bromer <notifications@github.com> wrote:

> Nope, just attaching it to our internal tracking system
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1239#issuecomment-146699533>
> .
>


-- 
Peter Herzog
Discipleship Pastor
Chapel Hill church
W: 651.681.1658
M: 612.940.1467

**Comment by njjc** [comment]
This has been marked as "Never" internally.
