### ISSUE TITLE
As a user of the Household model converter, I'd like the primary contact to be set by contact created date if no giving information is available

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1243]
Probably just need to order this query: 

https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CONV_Account_Conversion_BATCH.cls#L78

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
