### ISSUE TITLE
BUG: Seasonal address tests fail January 2015

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1244]
http://ci.salesforcefoundation.org/job/Cumulus_dev/884/consoleFull#151252163474022756-574a-4673-bd0d-e114a2a1fd70

**Comment by mrbelvedere** [comment]
Included in beta release version 3.30 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.30
