### ISSUE TITLE
TEST: As a developer, I'd like to have test methods and sample data for load testing

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1250]
Thanks to @jlantz we are getting limits numbers for each test case in our CI process. This would be even more useful if we could run test cases against large data sets, 100k+ rows per object.

An issue to think about is namespacing: different data sets would be needed for managed vs unmanaged environments.

Using the data import class is another thing to consider.

**Comment by kbromer** [comment]
i assume this is captured in the other LDV issues
