### ISSUE TITLE
As a user, I would like to be able to use recurring donations fortnightly

### ISSUE THREAD

**Issue by jwood13** [SalesforceFoundation/Cumulus#1252]
In my current organisation, many people pay fortnightly, matching when their pay comes in,  rather than weekly or monthly,
Whilst the 1st and 15th option for installment period does work for this most of the time, in many months, there are 3 ends of fortnights rather than only the two generated by the 1st and 15th options, requiring a new donation to be generated manually
It would be useful if a fortnightly option was available in the installment period selection, that calculated by adding 14 days rather than  selecting the 1st or 15th of the month

**Comment by kbromer** [comment]
You should be able to do this currently.  Check out 'Custom Installment Periods' in the NPSP Settings and NPSP docs for more info
