### ISSUE TITLE
As a developer, I want to delete the duplicate methods from BDE_DescribeHelper_UTIL that duplicate methods in UTIL_Describe

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1258]
The following methods exist in both classes:

fillMapsForObject(string objectName)
fillFieldMapsForObject(string objectName, string fieldName)
fillFieldMapsForObject(string objectName)
getPrototypeObject(String objectName)
getObjectLabel(String objectName)
getObjectDescribe(String objectName) 
isObjectIdThisType(Id salesforceId, String objectName)
getAllFieldsDescribe(String objectName)
 getFieldType(String objectName, String fieldName)

**Comment by davidhabib** [comment]
if there are additional methods in BDE_DescribeHelper that our generic, we should also just move them into UTIL_Describe, so all these helpers live together in one place.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.31 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.31
