### ISSUE TITLE
As a user, I'd like to be able to use multi-word countries when using Google Geocoding address validation

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1259]
We are not encoding the country name. As a result, it fails if the user enters something like "United States" instead of "US." We just get a "400: Bad Request" as response.

**Comment by kbromer** [comment]
Google's not as smart as we thought!

**Comment by kbromer** [comment]
https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_GoogleGeoAPI_Validator.cls#L81

@ceiroa was it clear in your investigation if Google would support properly encoded spaced country names, or it needed to be the 2 character country codes?  Seems like it would impact states as well (North Dakota)

**Comment by ceiroa** [comment]
Google supports properly encoded multi-word country name, and properly encoded multi-word state names. We are already properly encoding states.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.31 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.31
