### ISSUE TITLE
BUG: HH_ManageHHAccount page incorrectly shows no contacts in household

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1262]
Per [this hub thread](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001lVlBJ&emtm=1420995039284&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4). Was able to log in and verify issue, no errors or exceptions are thrown.

**Comment by kbromer** [comment]
This cropped up before on the hub, @davidhabib do you recall the fix here?

**Comment by davidhabib** [comment]
sounds vaguely familiar, but I don't recall.  I'll see if I can find an old issue.

**Comment by davidhabib** [comment]
couldn't find any old issue that sounds the same.  @njjc did you try running Health Check in this org?  that might help identify some issues.

**Comment by njjc** [comment]
I haven't, I'll do it now.

On Mon, Jan 12, 2015 at 10:58 AM, David Habib <notifications@github.com>
wrote:

> couldn't find any old issue that sounds the same. @njjc
> <https://github.com/njjc> did you try running Health Check in this org?
> that might help identify some issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1262#issuecomment-69591952>
> .
>



-- 
Nicolas Campbell | Force.com Developer |* Salesforce Foundation*

**Comment by njjc** [comment]
![Some hh accounts without contacts, although not the one I was trying to view.](https://cloud.githubusercontent.com/assets/1018198/5705981/3a63811a-9a4b-11e4-88ed-fd2a55d813ef.png)

**Comment by njjc** [comment]
That was weird. 
![image](https://cloud.githubusercontent.com/assets/1018198/5706000/5a49f9aa-9a4b-11e4-9e17-c325e566d2d8.png)

**Comment by davidhabib** [comment]
do all account fail to show contacts in the ManageHouseholdUI page, or just some of them?  any chance it is one of the three found here?

**Comment by njjc** [comment]
It happens on every Household. The data for the households I've tried is set up correctly.

**Comment by njjc** [comment]
This was a strange interaction with the [DataSan AppExchange app](https://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HlOZEA0). Customer resolved the issue by disabling the third party app. I've suggested sending them our code in an attempt for them to fix the issue.

**Comment by davidhabib** [comment]
nice job tracking this down!


David Habib | Senior Force.com Developer | salesforcefoundation.org
