### ISSUE TITLE
As a external developer, I'd like to be able to access and modify the Address Custom Settings through the NPSP API

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1263]
The Addr_Verification_Settings__c was defined as protected, and it's therefore not accessible outside the managed package. We should make it public, though the only way to do that would be to deprecate it and replace it with a different one (all refs would need to be updated... install script would need to transfer everyone to the new one...).

**Comment by kbromer** [comment]
Wasn't that a security review issue?

**Comment by ceiroa** [comment]
You are right, we made this change as prescribed by the security review:

![screen shot 2015-01-14 at 10 03 17 am](https://cloud.githubusercontent.com/assets/1894238/5742127/6c9f51a0-9bd5-11e4-8421-50da7f66c458.png)

I will leave it as-is then, and not provide access to it in the API.
