### ISSUE TITLE
As a user, I want the ability to mark a contact as deceased, as well as some simple automation around that process

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1267]
Automate Do Not Contact, Email Opt-out, Exclude from Household Naming fields.

**Comment by njjc** [comment]
Add "Do Not Contact" checkbox, with similar automation. Exclude those contacts from [canned reports](https://github.com/SalesforceFoundation/CumulusReports).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 18) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
