### ISSUE TITLE
As a developer, I need to add back (with different names) the opportunity bde fieldsets, which got removed by mistake from the packaging org

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1271]
Release 3.30 removed the Opportunity BDE_Entry_FS and BDE_List_FS fieldsets. We need to put them back, although they'll need to be renamed, as the platform does not let us add them back  with the same name. Code references to them will need to be rewritten to work with the old and new names.

The Account AllAccounts view was also removed, but this one does not need to be put back.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.31 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.31
