### ISSUE TITLE
As a developer, I'd like to investigate the usage of Login Flows to improve the new user experience for the NPSP

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1278]
Might be worth investigating this feature as we think more comprehensively about the new user experience and onboarding process

https://help.salesforce.com/apex/HTViewHelpDoc?id=security_login_flow_create.htm&language=en_US

**Comment by davidhabib** [comment]
all the samples really point towards using it to enable additional login security protocols, vs. a new user wizard.  I assume you were thinking about the latter?

**Comment by kbromer** [comment]
Yeah, I'm curious if it allows you to drop into any generic flow or if its 2-factor only

**Comment by kbromer** [comment]
**lurch: attach W-007358

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZgAAI" target="_blank">W-007358</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
