### ISSUE TITLE
As a user, changing an opportunity from a null amount to a positive amount should create a payment.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1285]
[Per this hub thread.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001nHu3r&fromEmail=1)
[Change here.](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/PMT_PaymentCreator.cls#L243)

**Comment by bermager** [comment]
Hi, I fixed it, but I can't create a pull request. The bot always closes it.
How should I name the pull request?

Regards

**Comment by njjc** [comment]
Awesome work, @bermager, thanks for the contribution. I've been working on docs for external contributors, let me know if you had to do anything differently and we can update the document.

http://developer.salesforcefoundation.org/Cumulus/Contributor/
https://github.com/SalesforceFoundation/Cumulus/tree/gh-pages/Contributor

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
