### ISSUE TITLE
BUG: Google geocoding doesn't accept postal codes with a space.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1287]
Reported in [this hub thread](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001nINUe&emtm=1421867587833&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
