### ISSUE TITLE
Field Mapping not working for 'Open' Ended status on Recurring donation

### ISSUE THREAD

**Issue by AshwinPandole** [SalesforceFoundation/Cumulus#1291]
@njjc 
Hi Nicolas,
We have a field named 'Program Designation' on recurring donation and is mapped to similar field on Opportunity.
The values get copied to donation when the Open Ended Status='None' but they don't get mapped when Open Ended Status='Open'.
Is this for reason or is this an issue.

have provided login access to sandbox org (ID: 00DO0000000WPZc)

Thanks.

**Comment by njjc** [comment]
Hi @AshwinPandole, would you mind first posting about this issue in the Nonprofit Starter Pack group on the [power of us hub](http://powerofus.force.com/)? We prefer for issues to be posted there first in case others have encountered the issue, before I take time digging into the code for what could be a configuration issue.

Thanks!

**Comment by njjc** [comment]
https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007jSdW&tab=sfdc.ProfilePlatformFeed&fId=0D58000001oD3tK

**Comment by njjc** [comment]
I've got some time to look into this today, would you mind granting login access again? @AshwinPandole

**Comment by AshwinPandole** [comment]
I have granted you access @njjc  Org Id : 00DO0000000WPZc
Please use below steps to recreate the issue.
1) Create a recurring donation with Program Designation = ChildCare and Status = (any). The values of Program Designation will get populated on the donation records. Note : All donations are in Pledged stage
2) Update the Program Designation = Healthcare and status = Open. Click on Refresh Opportunity. The changed value of Program Designation does not get updated to associated pledged donations. **This is the main issue. This used to happen in 2.0 ** 
3) Change the Status = None (None is a picklist value). Click on Refresh Opportuntity The changed value of Program Designation will get updated on all associated pledged donation records

**Comment by njjc** [comment]
So the system handles open and non-open recurring donations differently. For non-open recurring donations, when you refresh opportunities, it deletes already created opportunities that aren't in a closed stage.

For open ended recurring donations, it simply creates new opportunities into the future.

The problem here is switching from non open ended RD to open ended RD, the system assumes the already created opportunities were for an open schedule, and leaves them be.

Is there a reason to switch between the two schedule types in this case?

**Comment by AshwinPandole** [comment]
There is no reason for switch between the schedule. We just observed that what we wanted to achieve (that is copy program designation from RD to donation) is not happening for status as Open.

So while creating a new RD in open status - if the user forgot to specify Program Designation there is no way to update Program Designation on Donation. Other than delete RD and create a fresh one.

Shouldn't the behavior be same for Open and None ?

**Comment by njjc** [comment]
Could you just require the program designation field so that it has to be filled in when the recurring donation is created? We've never deleted and recreated opportunities for open RDs.

**Comment by AshwinPandole** [comment]
Yes in this release we have made it mandatory on both RD and Donation.
Hence its failing for all past records.

**Comment by njjc** [comment]
I'd suggest doing a quick data migration to update them. I've put another issue for if and when we decide to re-architect the recurring donations functionality #1374, closing this ticket.

**Comment by njjc** [comment]
@AshwinPandole FYI this issue has been fixed and will be included in the next release, a week from tomorrow!

**Comment by AshwinPandole** [comment]
@njjc Thanks for the update.

**Comment by AshwinPandole** [comment]
@njjc Is this fix released? I tried testing this in sandbox but it didn't work.
Thanks

**Comment by njjc** [comment]
Release should happen later today to sandboxes!
