### ISSUE TITLE
As a developer, I'd like errors coming from batch jobs to be logged in the error log and error notifications to be posted

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1294]
Our jobs that implement UTIL_MasterSchedulableHelper.UTIL_IRecurring do error handling in the __executeReturnStatus__ method, but this will only catch if there are issues launching the batch. Each batch of records processed by the batch runs in its own transaction, so the error handling done in executeReturnStatus doesn't catch errors in the batch itself. We cannot catch exceptions in the __execute__ method of the batch, because then the platform will not know the job failed, and the batch widget will not show the user it failed.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft3AAA" target="_blank">W-008291</a>

**Comment by mpusto** [comment]
Resolved in 3.83
