### ISSUE TITLE
BUG: As a developer, I want to understand why tests are failing in Spring '15

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1295]
Test methods from 4 test classes are failing in my spring '15 managed package test org.

**Comment by kbromer** [comment]
Which 4?

**Comment by njjc** [comment]
ACCT_HHAccounts_TEST: changeContactOwners  
ERR_Handler_TEST: errorHandlingDisabled, errorsStoredInDbTdtmCustomConfigEmailErrors, testInactiveUserEmailBehavior 
RLLP_OppRollup_TEST: testGivingRollupBatchHHAccount testGivingRollupBatchOne2One testOrgSoftCreditsHHAccount, testOrgSoftCreditsOne2One, testSoftCreditsHHAccount, testSoftCreditsOne2One
STG_SettingsManager_TEST (testPanelOppBatch)

**Comment by ceiroa** [comment]
I verified that the change that decreases the limit has been removed, for now:

![screen shot 2015-01-28 at 3 20 56 pm](https://cloud.githubusercontent.com/assets/1894238/5947273/5be69396-a701-11e4-9561-afaefff09d95.png)

**Comment by ceiroa** [comment]
@davidhabib ~ regarding the hardcoded value of 5, I must have done that because there was no other way to get this value from the platform, per https://salesforce.stackexchange.com/questions/62845/concurrent-batch-job-limit-of-2:

"[...]and hopefully there will be someway to identify this limit in Apex as there is not today."

**Comment by davidhabib** [comment]
wait, so are you saying that all test pass now in spring '15 without us doing any code change?

**Comment by jlantz** [comment]
The jenkins build I kicked off yesterday against our gs0 test org to test the beta package failed with the same error:

http://ci.salesforcefoundation.org/view/uat/job/Cumulus_uat_managed_test_gs0/76/consoleFull#151252163474022756-574a-4673-bd0d-e114a2a1fd70

**Comment by davidhabib** [comment]
@ceiroa what org did you test in?

**Comment by ceiroa** [comment]
This is with a brand new dev org I created from https://www.salesforce.com/form/signup/prerelease-spring15.jsp. 

This would match the stackoverflow post, where they said the limit change would be reverted.

**Comment by ceiroa** [comment]
To clarify, I'm investigating flex queue anyway, since we'll need it shortly. We might as well move to it in advance.
