### ISSUE TITLE
BUG: help text on Account's Primary Contact field needs updating.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1297]
It currently says "The primary contact for a Household Account, or the One2One contact for a One2One account.", but you can certainly use it on Organizational Accounts as well.

https://powerofus.force.com/0D58000001mccZQ

**Comment by jvarese** [comment]
Does this suffice then?

"The primary contact for a Household Account, an Organization Account. or the 1-to-1 contact for a 1-to-1 Account."

**Comment by kbromer** [comment]
**lurch: attach W-007449

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cbuAAA" target="_blank">W-007449</a>

**Comment by njjc** [comment]
This was fixed in 97f65eb0c90a53978a8bed3ea19bd03449f05119
