### ISSUE TITLE
As a user, I do not want an address record to be created if no address information is entered in an account, but State and Country picklists are enabled and a default Country value is selected

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1318]
With state and country picklists enabled and a default country value selected, the tests newAddrForOrgAccounts and updateOrgAccounts in ADDR_Addresses_TEST currently fail.

Taking the example of updateOrgAccounts, if picklists are enabled it fails because address records are created when the accounts are created. This happens because of the default value automatically given to the account country. 

Setting ADDR_Addresses_TDTM.hasRunAddrTrigger to false before doing the account update should not be necessary, because no address records should have been created on insert. If we to set it, then we get an error because twice the number of address records get created (1 per account insert, and 1 per account update).

We should consider whether a new address record should actually be created if the only address information in the existing record is the country. Maybe we should update the existing record instead, specially if the country does not change.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.35 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.35
