### ISSUE TITLE
As a developer, I do not want tests in HH_ManageHHAccount_TEST to fail if Country and State picklist are enabled, and a default Country is selected

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1319]
The following tests in HH_ManageHHAccount_TEST fail in that case:

	testRemoveContactActiveAddress -- System.JSONException: Cannot deserialize instance of ShippingAddress from FIELD_NAME value city at [line:1, column:15386]
		Stack trace: (System Code)
		Class.HH_ManageHousehold_EXT.unpackState: line 319, column 1
		Class.HH_ManageHousehold_EXT.remoteRemoveMember: line 361, column 1
		Class.HH_ManageHHAccount_TEST.testRemoveContactActiveAddress: line 223, column 1

	testRemoveReAdd -- System.JSONException: Cannot deserialize instance of ShippingAddress from FIELD_NAME value city at [line:1, column:12189]
		Stack trace: (System Code)
		Class.HH_ManageHousehold_EXT.unpackState: line 319, column 1
		Class.HH_ManageHousehold_EXT.remoteRemoveMember: line 361, column 1
		Class.HH_ManageHHAccount_TEST.testRemoveReAdd: line 601, column 1

**Comment by davidhabib** [comment]
Seems like there are issues with the JSONParser and address objects.  Stackexchange thread here with workaround by Andrew Fawcett: http://salesforce.stackexchange.com/questions/29304/with-json-how-to-serialize-the-accounts-shipping-and-billing-address

What is weird is our code is not explicitly even touching the Shipping fields which are generating the error.

**Comment by davidhabib** [comment]
found that we were explicitly removing the BillingAddress compound field from our soql, but needed to also remove ShippingAddress.  These two compound fields are not supported by the JSON parser, and we don't need them.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.35 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.35
