### ISSUE TITLE
As an integrator, I'd like the importData call to be available in the API

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1324]
The Data Import object (table) can be directly written to through the standard REST API. If we expose the "importData" call (method currently resides in the BDI_DataImport_CTRL class) it would make integrations, such as online-payment apps, a lot easier.

This allows things like:
- Create multiple Contacts at once for a Household
- Create multiple Donations for a Contact
- Create a Contact with a Donation

**Comment by mrbelvedere** [comment]
Included in beta release version 3.35 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.35
