### ISSUE TITLE
"Gender Field" help text revision for clarity

### ISSUE THREAD

**Issue by shannonsans** [SalesforceFoundation/Cumulus#1325]
Suggestion from the NPSP community sprint:

Please revise the help text on the "Gender Field"  to make it clear that if it's not set, the gender-neutral label is used. For example, "Set this field to use gendered relationship labels, or leave it blank to use the neutral label for all relationships."

(Assigning to @jvarese for label review.)

**Comment by kbromer** [comment]
**lurch: attach W-007284

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYUAAY" target="_blank">W-007284</a>

**Comment by mpusto** [comment]
Resolved with the complete review of all Settings strings and page updates in spring 2016.
