### ISSUE TITLE
Change all instances of Writeoff to Write off in the NPSP UI

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1326]
This single word is appearing inappropriately in all of the payments UI. Because it is a command/verb, "Hey you, WRITE OFF payments!" it should be two words.

It is only one word when it is a noun. "My writeoff."

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fnDAAQ" target="_blank">W-008244</a>

**Comment by mrbelvedere** [comment]
Included in production release version 3.73
