### ISSUE TITLE
As a user, multicurrency orgs should not improperly round currency conversion so that my converted values are accurately portrayed when aggregated to Contacts or Households

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1329]
I think its here: 
https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup_UTIL.cls#L305

Original thread: 
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001grohV&fromEmail=1

**Comment by mrbelvedere** [comment]
Included in beta release version 3.33 (Beta 4) and higher
