### ISSUE TITLE
As a contributor, I'd like to see the same style (same font specially) in the Contributor and ApexDocs pages

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1335]
http://developer.salesforcefoundation.org/Cumulus/Contributor/ and http://developer.salesforcefoundation.org/Cumulus/ApexDocumentation/ use different font, which makes it weird going from one to another. It doesn't feel like they are part of the same site. I think we should aim to make them feel like they are different areas of the same site.

**Comment by njjc** [comment]
Fixed in [this commit](https://github.com/SalesforceFoundation/Cumulus/commit/6e3c062a1c2f72bf8fbbd0b8082129af7266b6be). Closing manually since we don't merge pull requests from gh-pages.

**Comment by njjc** [comment]
@davidhabib Can I modify the ApexDocs css file directly, or will it be overwritten when new docs are generated?

Also, we should move all our CSS files to /assets/css/, which might require tweaking the ApexDocs build system. Let's chat about it sometime, I've made an issue for it. #1343
