### ISSUE TITLE
As a developer on the gh-pages branch, all css and other assets should be under the /assets/ folder.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1343]
ApexDocs css and NPSP logo should be moved to /assets/ and files updated appropriately.

**Comment by kbromer** [comment]
**lurch: attach W-007319

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ3AAI" target="_blank">W-007319</a>

**Comment by davisagli** [comment]
Seems to be the case now.
