### ISSUE TITLE
BUG: Refresh Household Names hits error

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1349]
with managed version 3.32:

When trying to refresh all household names, I'm getting the error: Error in null: Invalid object name 'Household_Naming_Settings__c'

You also get the same error just clicking Save in the Settings page.

This is NOT happening in unmanaged NPSP synced as 2/5/2015 4pm'ish PST.

**Comment by kbromer** [comment]
We may need to push a fix on this tomorrow-

**Comment by davidhabib** [comment]
I'm guessing it's from this commit I did back on 1/21.
https://github.com/SalesforceFoundation/Cumulus/commit/5d9812208c54d8136af5c1baf6bf544d0a9fc714
I didn't wrap our object name with UTIL_Namespace.StrTokenNSPrefix().  THus it fails in the managed code.  not sure how our tests pass in the managed code!

**Comment by davidhabib** [comment]
OK, I've created a pull request with the fix.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.33 (Beta 4) and higher
