### ISSUE TITLE
Google and Cicero address verification strip apartment number

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1353]
From https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001qKr8p

Amanda Byrne says:

Regarding Google Address verification: Now that we have address verification, we've noticed some less than ideal behavior:

1. Many of our addresses have the 9 digit zip-code. Google address verification is stripping the extra digits off and leaving only the 5 digit version.

2. Apartment and unit numbers are usually removed during verification. This is a big problem.

We've noticed that the API returns the apartment number as a 'subpremise' like so:
{ 
"long_name" : "117", 
"short_name" : "117", 
"types" : [ "subpremise" ] 
}, 

But I don't know if it would be reliable to make any 'subpremise' an apartment number- it sounds like a pretty generic field name- like a 'scrap left over' field.

There is an NPSP field for Mailing Address 2, which we've never used- we enter the street and Apt or unit # in the Mailing Street. However, the verification process did not add the 'subpremise' there.

Sadly, we've decided to turn off address verification. So promising.

**Comment by njjc** [comment]
It's hard do know if the subpremise should be Apartment, Suite, etc. I've often seen it presented as #subpremise, e.g. The Landmark @ One Market #300, San Francisco, CA 94105, so maybe that would be generic enough for us to include it that way.

**Comment by ceiroa** [comment]
From https://developers.google.com/maps/documentation/geocoding/#GeocodingResponses: 

* premise: indicates a named location, usually a building or collection of buildings with a common name
* subpremise: indicates a first-order entity below a named location, usually a singular building within a collection of buildings with a common name

**Comment by ceiroa** [comment]
I have verified that Cicero always strips it. Google does as well, but sometimes it returns it in the premise field, which we are now appending to the Mailing_Street field.

**Comment by ceiroa** [comment]
Resource on international address formats: http://www.bitboost.com/ref/international-address-formats.html

**Comment by ceiroa** [comment]
We should consider storing the original address in a new field (or in the "API Response" field) in the Address object. We don't need to have additional fields in either contact or account, but adding one to our custom address object shouldn't be an issue.

If we implement this, we should do it for all 3 address verification services.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36

**Comment by kshvetz** [comment]
Can anyone tell me if Google/SFDC has fixed this issue, specifically in the latest NPSP 3.0?  I still see no apt # fields, also nothing in the workflow rules or triggers to copy such a field between Household/Contact using either 1:1 or Household Account model.  How can Salesforce be lacking something so basic and fundamental to address management?

Also am I the only one here who knows that "premise" refers to a book, film, movie, etc?  Apparently even Google doesn't know that "premises" is singluar for a location!

**Comment by judisohn** [comment]
@kshvetz We don't offer support/troubleshooting here in Github. Please feel free to start a topic in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) in the Hub. Unfortunately, we have little control over the data provided by the 3rd party services in address verification.
