### ISSUE TITLE
As an admin, I don't need to see the Address Verification Endpoint for each service

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1355]
We can just remove the textbox that we auto-populate, and get the validator to pull the endpoint directly from each class.

We can also deprecate the settings (endpoint and zipcode endpoint).

Also, we shouldn't show in view mode the auth credentials (ID or Token) that don't need to have a value. For example, when in in edit mode, if a user selects Google Geocoding, we hide the Auth Token field. However, we show in in View mode, and also when the user clicks edit (before making any changes to the drop-down).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
