### ISSUE TITLE
Household Name Specifications only support LastName in LastName part of namespec

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1357]
Thanks for exchanging emails with me about the latest NPSP packages.  I now have the NPSP package version 3.33 installed to my 2 orgs, and they work fine.

I did find one new minor issue:

1) Using Blacktab, turn on the perm "Customizable Name Settings", so that an admin has access to the Middle Name and Suffix fields.
2) Go to Setup->User Interface and enable Middle Name and Suffix.
3) Go to NPSP Settings
4) Go to the Household Name Settings.
5) In Household Name Format, use this format: {!MiddleName} {!LastName} Household
6) In Formal Greeting Format, use this format: {!{!FirstName} {!MiddleName}} {!LastName}
7) Create a new contact named "Maria von Trapp", where 'von' is the middle name.
8) The Household name will be "MiddleName Trapp Household", meaning that the variable wasn't substituted correctly.
9) The Formal Greeting Name is "Maria von Trapp", which is correct.

For Step #8, is this something you'd like to log in your backlog?  A customer reached out to me specifically about Step #8, and I could reproduce it using the latest NPSP packages.

Thanks!
Dave Louie

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsiAAA" target="_blank">W-008279</a>

**Comment by davidhabib** [comment]
another thread that talks specifically about middle name and Suffix.  https://powerofus.force.com/0D58000001Ht5b8

**Comment by judisohn** [comment]
another thread on this subject: https://powerofus.force.com/0D58000002XN6X9

**Comment by judisohn** [comment]
another thread: https://powerofus.force.com/0D58000002xPZkr

**Comment by judisohn** [comment]
*lurch: detach

**Comment by judisohn** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x800000001fsiAAA" target="_blank">W-008279</a>

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000049k4zAAA" target="_blank">W-011689</a>
