### ISSUE TITLE
BUG: Recurring Donations with -none- for the Open Ended Status exhibit weird behavior.

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1359]
Here is the original hub thread related to this: https://powerofus.force.com/0D58000001YDhPV
Here is the original bug we fixed related to this: bug #1114. https://github.com/SalesforceFoundation/Cumulus/issues/1114
Also related to bug #1246 https://github.com/SalesforceFoundation/Cumulus/issues/1264
Here are updated reproduceable instructions (from the post): 
Jeff Issenberg (Exponent Partners)
I've just run into this again so I did some more systematic testing. I seem to be getting this result when I choose "--None--" which is different than choosing "None" for the Open Ended Status. Do others get the same result? I've got Donations listed in the Recurring Donation's Donations related list. When I open any of these donations I get "Record deleted". Then 4 minutes later when I open the records they are there!! Strange.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.35 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.35
