### ISSUE TITLE
As a user, I want to include my own custom fields in Household Name specifications, and have updates to those fields on the contact automatically update the household names.

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1360]

**Comment by kbromer** [comment]
**lurch: attach W-007262

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cY8AAI" target="_blank">W-007262</a>

**Comment by cdcarter** [comment]
Chris McCullough from Percolator and I are working on this issue together.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
