### ISSUE TITLE
As a developer, investigate Permission Sets to consider inclusion in our package

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1366]
We have many help topics that have to describe setting field level security on new fields we add.  Would the use of Permission Sets help us with this problem?  this task is to investigate Permission Sets to see what they can or cannot do for us, and to make a recommendation.

**Comment by kbromer** [comment]
**lurch: attach W-007356

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZeAAI" target="_blank">W-007356</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
