### ISSUE TITLE
Average Gift calculating a zero incorrectly

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Cumulus#1370]
For some but not all Accounts the Average Gift field on Accounts is showing a $0 when multiple gifts have been given and tallied in the other rollup fields.

For example a record will show:
Total Gifts	
$252,650.00
First Gift Date	
1/1/1992
Largest Gift	
$250,000.00
Last Gift Date	
12/15/1997
Smallest Gift	
$25.00
Best Gift Year	
1997
Average Gift	
$0.00

I have confirmed this issue in two separate instances both running NPSP 3.34.
In one account this affects 17k records out of 33K that should have an average gift >0
In the other account this affects 1k records of 2.5k that should have an average gift>0

**Comment by njjc** [comment]
Thanks for reporting this. Are your orgs multicurrency, or any other config we should be aware of?

**Comment by kbromer** [comment]
Just tested it in my demo org running 3.34, looks to be running okay in a clean org.  Any additional info @brianpickett around what else is running in the org would be helpful.  Thx!

**Comment by njjc** [comment]
I wonder if it has anything to do with the age of the opportunities. The example given has a last gift date of 18 years ago.

**Comment by brianpickett** [comment]
No multi-currency and its affecting donors that gave up-to very recently.  I'm asking the client if I can give you access to their account but in the meantime here's a CSV of summary information so you see the span of time and variance on number of gifts. https://app.box.com/s/0ptszmd3yeayt0fqfcrlonya31ztptw9

**Comment by brianpickett** [comment]
The client is fine with you logging in to review their instance. Org ID 00Di0000000HMOL
Login access has been granted to the Salesforce foundation for a month. If it helps I can request access to another org that I can verify is experiencing this issue.

**Comment by njjc** [comment]
Hi @brianpickett, sorry for the delay, I'll look into this shortly.

**Comment by njjc** [comment]
Hello @brianpickett, one of the batches of contact rollups is failing due to a custom validation rule. Could you fix this failure and run the batch again to see if it fixes the three contacts that are out of sync?

**Comment by brianpickett** [comment]
Thanks @njjc. We were looking at the Account field and didn't think to look at Contacts.  Using the Apex Logs I tracked an error back to a dupe management app with a rule on Contacts.  Turned off the rule, turned off the validation rules and ran the Rollups again ~ still two contacts with Avg Gift discrepancies. 

Same result with Accounts. Under Apex Jobs, the RLLP_OppAccRollup_BATCH shows 534 batches with no failures. There is no dupe management rule on Accounts and I turned off the single validation rule before running the batch.  It could be there is another app interfering with the rollup but wouldn't we see a failed batch?

**Comment by njjc** [comment]
Hey @brianpickett, I tried to log in again but access expired. Could the last two that are out of sync be owned by an inactive user? Try changing the owner on the two records, saving them, and running the rollups again.

**Comment by jeniferbbc** [comment]
@brianpickett, @njjc   - I also have a client with the same problem in a sandbox (00Dn0000000Du2I).  If you would like access just let me know and I'll check with the client.  I do not see any  pattern with the  Accounts that have an incorrect Average Gift vs those with a correct Average Gift.

If I edit a donation to set it to pledged then back to closed, the trigger fires and the correct value is populated.

A refresh of the rollups does not result in any failed batches, but it also does not calculate the correct amount.  The records do not appear to be touched.

**Comment by njjc** [comment]
@jeniferbbc SUPER helpful info. I've found the problem in the code and it will be included in next week's release.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.37 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.37
