### ISSUE TITLE
As a developer, I want to be able to flag a record in Data Import to immediately trigger the import

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1375]
Currently, all entries in the Data Import object are queued up until someone manually kicks off the import of the items in the import queue.  There is only one import queue.

The recommended implementation is a checkbox field on Data Import which if checked will trigger an immediate import of the record rather than adding the record to the import queue to be manually triggered.

The use case for this would be an external fundraising tool which wants to send donation information to be immediately loaded into Salesforce.  At the same time, the org has offline fundraising data they want to queue up for batch import at the end of the week.

**Comment by njjc** [comment]
This would be super useful for simple API integrations or web forms. Creating correctly linked data depending on NPSP account type settings is such a headache that this would solve.

**Comment by davidhabib** [comment]
i'm uncomfortable with this.  BDI is currently build around importing a full set of records.  We've just exposed an API to kick off this process.  Having someone run BDI on each singular record at a time will be very inefficient in cpu and number of queries, and will certainly run into limits quickly.  So I don't think we should encourage this type of usage.

**Comment by njjc** [comment]
Can the API be used to convert a single record if wanted?

**Comment by davidhabib** [comment]
the API just kicks off the process, which always works on all records not
marked as imported.


David Habib | Senior Force.com Developer | salesforcefoundation.org

**Comment by njjc** [comment]
I can definitely see cases where someone would want it to run on a single record without messing with what's currently in the table. We should discuss during standup tomorrow.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fuBAAQ" target="_blank">W-008294</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
