### ISSUE TITLE
Auto Creating Payment Causes AfterInsert & AfterUpdate Triggers to Fire

### ISSUE THREAD

**Issue by collinsjmj** [SalesforceFoundation/Cumulus#1376]
I've created a Trigger on Opportunities with AfterInsert and AfterUpdate. The purpose is to create Assets (eg. Benefits granted to different membership levels that need to be tracked by the organization) based on the Membership Level. A custom object (Membership Benefits) maps the Membership Level to one or more Membership Benefits as appropriate for the org. When the Oppty (only for Record Type 'Membership') Stage is 'Posted', the trigger determines the Benefits based on the Membership Level and inserts them to the Accounts Assets. 

The trigger is pretty straightforward and works in all scenarios save 1:
If during the initial creation of the Membership Opportunity the Amount is specified and a payment is set to be automatically created (the default behavior), my trigger fires both for AfterUpdate and for AfterInsert. Two sets of Membership Benefits/Assets are then created.

I can probably add a field to Assets to track the Oppty ID to prevent a duplication, but because the opportunity is being created/inserted (hence, no update possible), I'm not sure why the AfterUpdate is firing at all.

Any thoughts?

Much thanks:)

**Comment by njjc** [comment]
Hi @collinsjmj, inserting of a payment causes an automatic master-detail rollup to fire which updates the opportunity. You should be able to solve this by adding a static flag to ensure that your code only runs once for a single transaction. [Here's an example](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_Addresses_TDTM.cls#L42).

Based on your description, I'm not sure what would prevent a second set of Membership Benefits/Assets for any other type of update. In that case, I'd probably query for the related records to see if they exist already or not.

**Comment by njjc** [comment]
Also, for future reference, you're better of posting this type of question on the [powerofus hub](powerofus.force.com), we try to keep github issues related to actual work items for NPSP.

**Comment by collinsjmj** [comment]
Thank you for taking the time to share and guide. Much appreciated.

On Wednesday, February 11, 2015, Nicolas Campbell <notifications@github.com>
wrote:

> Also, for future reference, you're better of posting this type of question
> on the powerofus hub <http://powerofus.force.com>, we try to keep github
> issues related to actual work items for NPSP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1376#issuecomment-73971809>
> .
>


-- 
John Collins
o +1.720.588.2432
m. +1.970.688.0659
john@contexturetechnology.com

**Comment by njjc** [comment]
My pleasure!
