### ISSUE TITLE
Add a sum of the amount all donations in a batch on the bulk data entry screen

### ISSUE THREAD

**Issue by pherzogchc** [SalesforceFoundation/Cumulus#1377]
When we enter numerous donations in the system via the bulk data entry it would be very helpful to see a sum of the total batch for reconciliation purposes.

**Comment by kbromer** [comment]
**lurch: attach W-007243

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXpAAI" target="_blank">W-007243</a>

**Comment by melissabarber** [comment]
This has been marked as "Never" internally.
