### ISSUE TITLE
As a user, I want to be able to import multiselect picklist data with the NPSP Data Importer

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1378]
user reporting that multiselect picklists don't copy their data to the object.  https://powerofus.force.com/_ui/core/chatter/topics/TopicPage?id=0TO800000000Tp4&ref=feed_item_topic&entityId=0D58000001rFMK2

**Comment by davidhabib** [comment]
turns out it was user mistake.  the mapping wasn't specified in the Help text field.

**Comment by mrbelvedere** [comment]
Story deleted from ScrumDo
