### ISSUE TITLE
As a user, warn me in Health Check if both One-to-One and Household Account models specify the same recordtype in settings.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1379]
This is the 2nd time this week this has come up. What do you think about adding some text to the NPSP Settings > People page to tell folks that both Household and One to One shouldn't use the same record type? And maybe having Health Check look for this?

**Comment by jstokesconsulting** [comment]
I am also having this same issue.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.37 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.37
