### ISSUE TITLE
Manage Households page UI improvements

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1385]
The Manage HH VF page's UI could be less time-consuming to use with several small changes:

* Put a Save button at the top of the page so scrolling is not necessary to save on a laptiop-sized screen.
* When a field value is changed, change the "Changes Not Saved" warning so it does not move the position of the Save button.  This allows Save to be clicked quickly, before the change "moves" it on the page.
* When a new COntact is added on the page, prefill their last name field from the existing Contact's last name, since most multi-person HHs are husand and wife sharing a name.

**Comment by kbromer** [comment]
**lurch: attach W-007317

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ1AAI" target="_blank">W-007317</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
