### ISSUE TITLE
As a developer, I would like to have an NPSP release status page which shows release status, build status, infrastructure status, and known issues for the current production and beta releases of the NPSP.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1387]
Inspired by https://status.heroku.com/

Consider including in base package.

**Comment by kbromer** [comment]
**lurch: attach W-007323

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ7AAI" target="_blank">W-007323</a>

**Comment by davisagli** [comment]
We at least have a dashboard for build status now: https://mrbelvedereci.herokuapp.com/repos/
