### ISSUE TITLE
BUG: As an affiliations user, duplicate affiliations shouldn't be created when adding an org's Primary Contact.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1389]
https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007h2oi&tab=sfdc.ProfilePlatformFeed&fId=0D58000001s2P8Z&emtm=1424066421220&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
