### ISSUE TITLE
Research defining a NPSP REST API

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1394]
With the payments integration Manelsky said he wanted to work on during the DC sprint.

**Comment by ceiroa** [comment]
During the NY Engineering Summit, we discussed implementing the REST API defined by OSDI (http://opensupporter.org/). It seems like both NPSP and NGOC teams agree adhering to an existing standard already used by other companies would be advantageous. Then every third party company that wishes to integrate with either of our applications only needs to target one API.

The specification can be found at https://github.com/opensupporter/osdi-docs.

**Comment by ceiroa** [comment]
OSDI notes (to list all possible concerns with the spec in one comment):

- Only given_name and family_name available for person name. It doesn't support foreign last names, that might be composed of multiple last name parts.
- The options for postal_addresses.address_type are only "Home", "Work", or "Mailing". Would "Mailing" be enough to support vacation addresses?

**Comment by kbromer** [comment]
**lurch: attach W-007297

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYhAAI" target="_blank">W-007297</a>

**Comment by njjc** [comment]
Lots of global classes ending in _API are available in our codebase.
