### ISSUE TITLE
As an employee, complete performance self summary.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1398]
Step 1: Complete Your Self-Summary, due on March 2nd. You'll receive an email today from Work.com with a link to your Self-Summary or you can select the performance tab from Work.com in Org62 to get going.

If you collected feedback from your colleagues throughout the year, include it in your Self-Summary. If you need help, find instructions here. And, make sure to factor in your accomplishments from your FY15 V2MOM. (note: your FY15 V2MOM will be back online for editing after 4PM PST today. Go to your Chatter profile in Org62, select the 'More' tab and click on 'Goals' to view it).

**Comment by davidhabib** [comment]
really?  I think it's a bit of overkill to put personal tasks in gitHub/Scrumdo.  This dilutes us focusing at the product related work.  anyone disagree?

**Comment by ceiroa** [comment]
I agree. Also, fyi, I have deleted the go-cumulusci task from scrumdo.

**Comment by njjc** [comment]
OK, I just didn't want to forget it and use scrum stories as my todo list.
I've removed it.

**Comment by mrbelvedere** [comment]
Story deleted from ScrumDo
