### ISSUE TITLE
As a user, on the contact null the Account name.  Current address does not change and new household account does not get an address record.

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Cumulus#1403]
As a user, in the Household account model, on a contact record with a default address (no address override), I null the Account Name and hit Save.  A new Household Account is created as expected but 
1) the contact retains its connection to the old address on the old household
2) the new household account does not create a new custom address record.

I was expecting that a new custom address record would be created on the new account with the contact being update so the "current address" field points to the new address.

Verified this behavior in two accounts.

**Comment by brianpickett** [comment]
Same result when taking an existing contact and changing households (moving from one household to another).  Even occurs when the existing contact did not have a current address assigned.

**Comment by davidhabib** [comment]
fixed with contact merge work in version 3.39
