### ISSUE TITLE
As a user, I would like to specify the record type when using the Batch Data Entry tool

### ISSUE THREAD

**Issue by ehrenfoss** [SalesforceFoundation/Cumulus#1404]
From this PowerOfUs Hub post: http://goo.gl/f55BRm

Check if all available picklist values are being displayed. We should display all values as apex doesn't support finding which values to show per record type.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fuFAAQ" target="_blank">W-008295</a>

**Comment by melissabarber** [comment]
This has been marked as "Never" internally.
