### ISSUE TITLE
Data Importer: when creating a Campaign, Active=False

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1405]
Issue: When Data Importer creates a Campaign, it sets Campaign.Active=False.  This makes the Campaign and other data invisible in SF.

Proposed solution: DI should set Active=True for created Campaigns.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.37 (Beta 5) and higher

**Comment by johnfine** [comment]
Hey Nick, I see that you are working on Data Importer issues, so here's
another one (I haven't entered this into github yet):

In the csv input data, If Contact1.FirstName = {blank} and
Contact1.LastName <> {blank}, and if the matching rule is FirstName and
LastName, then instead of matching to records where FName = {blank} and
LName is a match, no matching occurs.  The first unmatched record causes a
new Contact to be created with FName = "null" (really the actual word
"null") and LName = COntact1.LastName.  Then every subsequent record
matches this newly created one.

I'd say that, while this is not exactly a bug, no nonprofit wants a Contact
record whose Fname = "null".

Instead, I would vote for having a match occur on a record where LName
matches and FName is blank.  Lots of orgs handle email-only contacts in
this manner, sometimes putting the email address in the LName field in SF,
sometimes putting a placeholder field like "Supporter".

Another use case is the placeholder Contact for anonymous and cash
donations, which I have seen called Fname = {blank} and LName = "Anonymous".

Thx for listening!  And great to see DI getting buffed out - it is such an
awesome tool.

-John

**Comment by mrbelvedere** [comment]
Included in production release version 3.37
