### ISSUE TITLE
As an admin, I'd like error messages to include the user and org ids

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1406]
For those admins that manage more than one org, it is useful to know which org the error is coming from.

We can have a message similar to the one Salesforce adds at the beginning of an error message:

Apex script unhandled exception by user/organization: xxxxxxxxxxxxxxxx/xxxxxxxxxxxxx

**Comment by mrbelvedere** [comment]
Included in beta release version 3.38 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.38
