### ISSUE TITLE
Address Verification Settings page is hiding the textbox where user needs to enter Google Geocoding Token

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1408]
The field our Google validator is pulling the token from is not the one linked to the textbox that is displayed when Google is selected from the dropdown. Thus user gets the "MISSING AUTHID OR ENDPOINT" message.

We need to test if the same is happening to Cicero.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
