### ISSUE TITLE
As a user, I would like to batch data entry of parent and child objects at the same time (BDE)

### ISSUE THREAD

**Issue by ehrenfoss** [SalesforceFoundation/Cumulus#1413]
Allow batch entry of child objects
-- Standard objects like Account Cases, or Opportunity Activities
-- Custom objects like Contact Volunteer Engagement or Opportunity Match Detail

Split from here: https://github.com/SalesforceFoundation/Cumulus/issues/1354

**Comment by ehrenfoss** [comment]
1.  What about objects with multiple batchable parents? 

Let's say we have an object called "Affiliation" that has a lookup to Account and Contact.  All three objects also have a Batch__c lookup as well, so they can now be added to the same batch.  

If we are displaying a list of objects in this batch, where should Affiliations appear?  Under Accounts, next to Contacts?  Or under Contacts?  I would summarize the two approaches as "Child of highest parent" or "Child of lowest parent".  Doing either approach in a non-accidental way might be a big task.

Gets more complicated:  what if the Contact's parent isn't the same Account that is the Affiliation's parent?  Sure, there might be business logic to prevent this for Affiliations in NPSP, but it's possible for Custom objects.

2.  General approach for child/parents

Here's how I would plan to implement the parent/child support:

- Refactor itemList and BatchItem concepts to store metadata around "my parent Id", "my children", and "nesting level".  
- Update the VF page to group parents/children and indent nested items.  Remember, it might be hard to use Maps here because of a VF limitation in repeat tags.
- Add a "New [Child]" button under a parent item for each type of batchable child
- Rerender item list when an item is saved, in case the parent of an item changed.
- Investigate whether or not we can handle "remembered" (pinned) values per object type
- Update BatchItem to have a string value corresponding to list fields, if we have to work around the VF/Map/repeat issue.

**Comment by kbromer** [comment]
**lurch: attach W-007295

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYfAAI" target="_blank">W-007295</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
