### ISSUE TITLE
Fatal error should not occur when the size of the address verification response is larger than the max size of the API Response field

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1415]
This happens when Google thinks the address is ambiguous. When should trim the response to make it fit.

![screen shot 2015-02-24 at 11 20 04 am](https://cloud.githubusercontent.com/assets/1894238/6451100/d312df38-c0f1-11e4-8d9a-dedee704a2a2.png)

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
