### ISSUE TITLE
As a developer, I want to include a set of contact KPI dashboard components for inclusion on page layouts.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1429]

**Comment by kbromer** [comment]
**lurch: attach W-007312

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYwAAI" target="_blank">W-007312</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
