### ISSUE TITLE
Google address verification strips last 4 digits from a 9-digit zipcode

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1435]
From https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001qKr8p

Amanda Byrne says:

Regarding Google Address verification: Now that we have address verification, we've noticed some less than ideal behavior. Many of our addresses have the 9 digit zip-code. Google address verification is stripping the extra digits off and leaving only the 5 digit version.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
