### ISSUE TITLE
Typo for Schedulable__c plural form

### ISSUE THREAD

**Issue by Zosoled** [SalesforceFoundation/Cumulus#1437]
Cumulus/src/objects/Schedulable__c.object, line 126
Says "Schedulabls", should say "Schedulables"

**Comment by kbromer** [comment]
**lurch: attach W-007364

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZnAAI" target="_blank">W-007364</a>

**Comment by mpusto** [comment]
Included in 3.83
