### ISSUE TITLE
As a user on Spring 15, the Household Model converter shouldn't ask me to verify inactive user records are transferred since its no longer a requirement.

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1438]
https://success.salesforce.com/ideaview?id=08730000000Br8MAAS

https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CONV_Account_Conversion_CTRL.cls#L234

**Comment by mrbelvedere** [comment]
Included in beta release version 3.37 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.37
