### ISSUE TITLE
When manually converting to the new Household Account model, addresses don't populate Address object

### ISSUE THREAD

**Issue by NorthPeakMelissa** [SalesforceFoundation/Cumulus#1443]
One of our clients wasn't using the Household object; so, the conversion utility for the new Household Account model didn't work. When we switched to the new Household Account model and manually created the new Household Accounts, the address on the contact didn't populate the Address object. Here's how we recreated the issue:

- Starting NPSP Settings:
  - Account Model = One-to-One
  - Household Account Record Type = Individual

- Created test contact with address and verified One-to-One Account created.

- Changed NPSP Settings:
  - Account Model = Household Account
  - Household Account Record Type = Household Account

- Ran Jitterbit query on the Contact object to extract:
  - AccountID
  - ID
- Cleared AccountID column in CSV & used Jitterbit to update the Contact with the null value in the AccountID field.
- This successfully created a new Household Account for the test Contact. The Contact's address was added to the new Household Account, but not to the Address object on the Account.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
