### ISSUE TITLE
BUG: Manage Household UI field set not consistent with Household Account page layout.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1444]
The default field set for Account Manage Household Custom includes the Household Phone field, but the Household Account layout displays the standard Phone field, and not the Household Phone field.  We should be consistent in both and just display the Household Phone field.   Need to update the Trial Template, as well as the managed package.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fuPAAQ" target="_blank">W-008297</a>
