### ISSUE TITLE
Manage Households VF pages throwing Contact Validation Rules erroneously

### ISSUE THREAD

**Issue by Zosoled** [SalesforceFoundation/Cumulus#1445]
HUB thread: https://powerofus.force.com/0D58000001vhiEa

**Comment by judisohn** [comment]
This appears to be a Salesforce platform issue: https://success.salesforce.com/issues_view?id=a1p30000000T2L3AAK

**Comment by Zosoled** [comment]
Bummer! Hope they fix it soon.
