### ISSUE TITLE
As a user, I would like new contacts with Address override set true, to not put their mailing address in the household account, since I have their work address.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1448]
hub discussion: https://powerofus.force.com/0D58000001spM5l

the discussion also raises other potential enhancements with how addresses interact based  on the primary address type, but this tasks is really just avoiding putting the contact address into the household account on creation, if address override is checked.

**Comment by kbromer** [comment]
**lurch: attach W-007359

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZhAAI" target="_blank">W-007359</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
