### ISSUE TITLE
As a user, I would like to have several GAU Fund Allocation reports & dashboard when I install the NPSP

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1449]
not sure if we make the reports part of our package, or the separate reports unmanaged package, but we need some reports and a dashboard to show off this feature.

**Comment by kbromer** [comment]
**lurch: attach W-007280

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYQAAY" target="_blank">W-007280</a>

**Comment by judisohn** [comment]
[Unmanaged installer. ](https://mrbelvedere.salesforcefoundation.org/mpinstaller/npsp_reports)
