### ISSUE TITLE
NPSP Data Import - Upsert failed

### ISSUE THREAD

**Issue by alphasys** [SalesforceFoundation/Cumulus#1457]
When using the NPSP Data Importer, the records have been uploaded successfully into my Salesforce instance. However when I select my records, press "Start Data Import", and on the next screen "Begin Data Import Process", I receive an error saying:
Upsert failed. First exception on row 0 with id a0a28000000Gy1HAAS; first error: INVALID_CROSS_REFERENCE_KEY, invalid cross reference id: []
Error is in expression '{!importData}' in component <apex:commandButton> in page npsp:bdi_dataimport: (npsp)

![image](https://cloud.githubusercontent.com/assets/10205071/6666439/83078af0-cc38-11e4-8ff2-39bb1abe9f41.png)

**Comment by judisohn** [comment]
Hi @alphasys This is something that needs to be worked in to the new Data Import guide, but it's not a bug or issue. It just means that a custom setting record hasn't been set in your instance for the Data Importer.

Go to Setup > Develop > Custom Settings. Click Manage to the right of Data Import Settings and then click New button at the top. Don't enter anything, and click Save.

Then you should find the Import tool will work without error.

More on the Hub on this here: https://powerofus.force.com/0D58000001wlXmG

**Comment by alphasys** [comment]
Hi that worked, thanks.

**Comment by davidhabib** [comment]
@ceiroa We need to understand why several users are running into this recently.  we are doing an upsert on the Settings, which should work whether they are being created for the first time or updated.  Why would this start causing problems now?  change in the platform?  change in our settings code?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.36 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.36
