### ISSUE TITLE
Automatic Affiliation Management does not work well with bulk data loading

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1463]
When loading Affiliation-related data in bulk using a tool like DemandTools, the automatic Affiiation management features show some issues that make bulk loading difficult:

If the Auto-Affiliation checkbox is unchecked:
* Inserting Affiliation records that have Primary=TRUE in mass sets some but not all corresponding Contact.PrimaryAffiliation fields.

If the Auto-Affiliation checkbox is checked:
* Updating Contact.PrimaryAffiiation in mass generates some but not all corresponding Affiliation records.
* Updating Account.PrimaryContact in mass generates some but not all corresponding Affiliation records.

**Comment by davidhabib** [comment]
What batch size where you using on your data import?  it could very well be that our triggers were hitting limits that we can do nothing about.  did you try reducing your batch size significantly?

**Comment by johnfine** [comment]
I didn't try reducing batch size from the default 5000.  I tried turning on
serial mode in bulk mode instead in DemandTools, thinking that would have
the same effect.  Is that incorrect?  Can you suggest a batch size?  Thx,
David.

**Comment by davidhabib** [comment]
Wow.  5000 is way too huge!  I'd try 50, and go down by 10's from there.  I don't know what serial vs bulk does in DemandTools.  But what you are trying to do is reduce the trigger from getting 200 records at a time to something smaller.  The 5000 gets broken into chunks of 200 by Salesforce I believe.  So you need to use something < 200 to actually change what size chunk our trigger gets.

**Comment by johnfine** [comment]
OK, I'll experiment when I have some time.  Consider the issue as closed
until I let you know the results of my tests.  Thx!

**Comment by davidhabib** [comment]
I just fixed an issue where Affiliations use of a re-entrancy prevention flag was causing affiliations to not get created when a household object was being created for a new 1:1 contact.  I've removed the re-entrancy flag, and changed it to something we only explicitly set in needed scenarios.  So I wonder if this flag was getting in the way of your data import.  @johnfine , after you get version 3.43, can you let me know if you are still seeing this issue?  thanks!

**Comment by johnfine** [comment]
Will do David.  Should this fix affect HH Account model Contacts as well,
or only 1:1 Contacts?  My issue was with HH Account model.  Thx, -John

**Comment by davidhabib** [comment]
the fix affects all account models.  I just found the issue when the 1:1 account model was creating a household object.  but the fix is agnostic about account models.

**Comment by RBLopez** [comment]
I may have an instance of this issue occurring for one of my clients. We have a custom integration set up that is upserting affiliations in batches. Affiliations are being created/updated with the primary checkbox = true, but the primary affiliation field on the related contact isn't being populated appropriately. Toggling the field manually seems to do it, but we need this to happen in bulk.

**Comment by kbromer** [comment]
**lurch: attach W-007379

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ca2AAA" target="_blank">W-007379</a>

**Comment by davidhabib** [comment]
I've created bulk tests for these insert and update Affiliation scenarios.  They all run successfully against our 1k LDV org.  Waiting for our tests to get run against our 100k LDV org to decide if we have a problem or not.

@RBLopez can you provide more details about your client's instance that has the issue.  How many contacts, accounts, and affiliations in the org?  which version of NPSP 3 is it on?  What batch size is your integration using?  Does it happen consistently or not, and can you reproduce it?  Do you have any custom triggers in this org dealing with Affiliations or Contacts?

**Comment by RBLopez** [comment]
@davidhabib I've been working in the sandbox to try and turn things on and off. There are approx 7500 accounts, 6300 affiliations and 6600 contacts and this is now happening consistently. I worked with Nicolas in the HUB (https://powerofus.force.com/0D58000002J1hiq) and initially found an order of operations issue with workflow setting primary to true, but that has been corrected and this is still happening consistently.

We're working with batches of up to 100. NPSP version 3.53.
I had a trigger and two workflow rules firing on affiliation, but after deactivating all of those I'm still seeing the same issue consistently. Everything is running successfully and not even close to hitting any system limits. There are no NPSP errors being generated, nor are there any of our sync error logs being generated either (they look for errors on the DML operations on all three objects).

Are there any other potential spots where I should be looking?

**Comment by njjc** [comment]
@RBLopez Sorry I missed that last HUB post! I'm happy to log in on the backend and get full NPSP debug logs to help pinpoint the issue. We'll need to coordinate a time when you can do the batch insert and I can monitor the logs simultaneously. First, grant login access in your sandbox to "Salesforce.com Foundation Support" and give me the Org Id. I'm free for the next two hours if that works for you.

**Comment by davidhabib** [comment]
@RBLopez at this point we've tested batch inserts of 200 Affilations at a time in an org with over 100k of Contacts, Accounts, Payments, Addresses, Opportunities, Affilations, GAU Allocations, CampaignMembers.  Our tests run successfully hitting no errors and hitting no more than 19% of system limits.  So we are closing this issue.  If you can reproduce your problem in a clean org with no customizations, we would certainly look further into this.

**Comment by RBLopez** [comment]
hi @davidhabib , This is being reproduced in a sandbox with all triggers, workflows, etc turned off. I've been through all of our debug logs and we successfully set up batches of affiliations with primary = true checked and they are successfully inserted. The only thing I can see from there is that something is happening in the npsp namespace. If you're unable to troubleshoot, I'd really appreciate some pointers on what we should be checking as I have no way to know what is preventing the NPSP code from working as expected.

**Comment by davidhabib** [comment]
What's common between the records that aren't being set?  Is it consistently the same records, or different records?  Code works in bulk operations, so it would be VERY abnormal that the affiliation behavior would work "some of the time".   Inactive users owning records maybe? Sharing oddities?
