### ISSUE TITLE
As a user, in the Household Naming specifications, support null/empty for Name Connector and Name Overrun properties, so I can get a name with just the primary contact in it.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1464]
Hub post: https://powerofus.force.com/0D58000001xpNdD

**Comment by kbromer** [comment]
This is an easily solvable use case already, per pre-SFDO Judi: 

"In the meantime, what about a workflow rule that checks "Exclude from Household Name" when the contact is not the Primary Contact on the Household?"
