### ISSUE TITLE
BUG: Contact Merge hits error is some scenarios.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1466]
Several Hub users are reporting a problem where they get a runtime error when trying to use Contact Merge.  The thread is here: https://powerofus.force.com/0D58000001pLmcx

I was able to find AMERICANS FOR PROSPERITY FOUNDATION's error in the Foundation org:

Apex script unhandled exception by user/organization: 005i0000004Bz4D/00Di0000000aUpe
Visualforce Page: /apex/npsp__CON_ContactMerge
caused by: System.NullPointerException: Attempt to de-reference a null object
Class.npsp.CON_ContactMerge_CTRL.loadMergeCandidates: line 299, column 1
Class.npsp.CON_ContactMerge_CTRL.nextStep: line 169, column 1

The lines have since changed since we ApexDoc'd this class, but the fault in LoadMergeCandidates is here:

https://github.com/SalesforceFoundation/Cumulus/blob/f7a41a1a8e2e8d39f30a806e3dc722208dc32845/src/classes/CON_ContactMerge_CTRL.cls#L299

which corresponds to this current code in loadMergeCandidates:

            lastModifiedByRow.values.add(new Cell(c.id, modifiedBy.get('name') + ' ' + c.get('LastModifiedDate'))); 

I have no idea how this line could be failing with a null object exception, and wonder if it might be org specific.

**Comment by NathanSpiwak** [comment]
David,

I've found two contacts that should be merged, but produce an error. The contact is Max Hess and he's a staff member so I'm not worried about messing up his record. I've also enabled login access so you should be able to sign in and search for "Max Hess". Let me know what else I can do to help.

**Comment by davidhabib** [comment]
OK, I figured out the problem.  One of the contacts (Mr. Max Hess) has a LastModifiedBy value of Rollup Helper, 2/4/2015 3:25 AM.  This isn't a real user.  I could not find any user account for them whether active or inactive.  The NPSP Contact Merge code was assuming this field would always contain a real user record, and it then tries to get the Users name with modifiedBy.get('name').  But in this case ModifiedBy is null, so we hit the runtime error.

I will be able to fix this in npsp code, but the fix won't be available for several weeks.  You can work around it by modifying the record so your own user is tagged in the Last Modified By field.

**Comment by NathanSpiwak** [comment]
Oh! That's a great find! I would have never thought that could be the
issue. Now that we know we can work around it. Thank you again for your
help.

**Comment by bethsaunders** [comment]
David and Nathan - Thanks for all this research and testing!  My customer also uses Rollup Helper so this is likely our problem as well.  However, they are on NPSP 2.x with plans to upgrade near end of April.  Will the fix be available to 2.0 as well? (I'm guessing not).  We can try the work around in the meantime.

**Comment by davidhabib** [comment]
Sorry Beth, we aren't doing updates to the 2.0 packages.

**Comment by NathanSpiwak** [comment]
Beth, you can upgrade to 3.0 without changing your householding model. It's
a good option if you don't have time to go through the entire conversion
process.

**Comment by bethsaunders** [comment]
Thanks for confirming... we are on the upgrade path!

Thanks,
Beth

**Comment by mrbelvedere** [comment]
Included in beta release version 3.37 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.37
