### ISSUE TITLE
BUG: Contact Merge creates two default addresses in Address object

### ISSUE THREAD

**Issue by NorthPeakMelissa** [SalesforceFoundation/Cumulus#1469]
Instructions to recreate:
- Start with duplicate Contacts with same address, each contact has their own Household Account.
- Use NPSP Contact Merge to merge the contacts.

Result: One Household Account with 2 addresses in the Address object; both addresses are marked as default.

**Comment by NorthPeakMelissa** [comment]
Just tested this out using the Merge Accounts link on the homepage for Accounts, and the same thing happened. After the Accounts were merged, two addresses were in the Address object of the remaining Household Account, and both were marked as default.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 2) and higher

**Comment by NorthPeakMelissa** [comment]
Great to hear! Thanks.

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
