### ISSUE TITLE
BUG: Lead Convert button doesn't allow for organization account matching anymore

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1471]
Hub post: https://powerofus.force.com/0D58000001xrX3K

I confirmed in an instance running NPSP 2 with Convert overrride. If a company is entered, the standard lead conversion comes up. If Self is entered the override comes up.

In NPSP 3 org, the override comes up regardless of what is in the Company name field (happens with both the npe01 version and the npsp version of the VF page).

However, upon conversion the Account is created as an organization account. But it's not giving the user the option to match to an existing Account as a standard lead conversion would do. I know there's plans for enhancement around Lead conversion, but this is a bit of a regression from NPSP 2.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
