### ISSUE TITLE
Developer gets a 'Package Visibility: Type is not visible: tdtm_config_api' error when trying to call API method

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1472]
This happens through the Force.com IDE and the dev console, but not if the class is edited directly in the web UI.

HUB thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001xqmXI

Code that produces the error:

```
@isTest
global class TEST_NPSP_API {
    public static void insertDefaultTDTM() {
        List<npsp__Trigger_Handler__c> obj = npsp.TDTM_Config_API.getDefaultRecords();
        insert obj;
    }

}
```

**Comment by mscholtz** [comment]
FWIW, I was able to get very similar code to compile fine in the latest version of MavensMate

**Comment by kbromer** [comment]
**lurch: attach W-007367

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZqAAI" target="_blank">W-007367</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
