### ISSUE TITLE
BUG: Primary Contact/Primary Organization if more than one organization is marked primary

### ISSUE THREAD

**Issue by ashimasaigal** [SalesforceFoundation/Cumulus#1473]
Some funkiness with primary organization. By chance I had already set a primary organization for my contact in my affiliated records, but I didn't realize it. So, I created a new Affiliated record, marked primary, that organization now showed as my primary organization on my contact record. However, when I saw my error and edited the other affiliation (so it was not primary), the organization went blank on the contact record. There is clearly an issue when more than one organization is marked primary in affiliations.

**Comment by judisohn** [comment]
Thread on the Hub that's possibly related to this: https://powerofus.force.com/0D580000021uhh0

**Comment by ashimasaigal** [comment]
Thank you for including me Judi. You are the best!!

Peace,

Ashima
Database Sherpa
http://www.databasesherpa.com
The wisdom of a Sherpa.
The reward of your practice. 

Please excuse the typos and brevity of the msg

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
