### ISSUE TITLE
BUG: Google geocoding completely deleting street portion of address

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1488]
With this address:

1203 Kenray Loop
Springfield, OR 97477

[Per this hub thread.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001zsPjC&emtm=1427757534469&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4)

**Comment by njjc** [comment]
Ran a test, google's response doesn't include the street portion of the address, nor does it mark the address as ambiguous. @ceiroa do you have any idea why we would see this kind of response from google?


![screen shot 2015-04-07 at 10 12 38 am](https://cloud.githubusercontent.com/assets/1018198/7028980/b1190eb4-dd0e-11e4-8620-b0b792b55598.png)

**Comment by ceiroa** [comment]
No idea. It seems like it's only returning one result, so it's not that it considers it ambiguous.

**Comment by kbromer** [comment]
I think if it can't find the address, it just returns what it can geocode, in this case likely the city/town center

**Comment by njjc** [comment]
Unfortunately it just cut off the street portion, but didn't mark it as Ambiguous or anything. Seems like data loss from the user's perspective.

**Comment by ceiroa** [comment]
In issue https://github.com/SalesforceFoundation/Cumulus/issues/1353 we talked about storing the original address in the Address object. Did that get done as part of that ticket? I think it could be a reasonable solution for this.

**Comment by davidhabib** [comment]
it did mark location type as approximate. Maybe we should be special
casing that response?



On Apr 7, 2015, at 11:24 AM, Nicolas Campbell <notifications@github.com>
wrote:

Unfortunately it just cut off the street portion, but didn't mark it as
Ambiguous or anything. Seems like data loss from the user's perspective.

—
Reply to this email directly or view it on GitHub
<https://github.com/SalesforceFoundation/Cumulus/issues/1488#issuecomment-90689366>
.

**Comment by njjc** [comment]
Yep, you can see it in "Pre-Verification Address" in the screenshot I posted.

**Comment by njjc** [comment]
Google response needs additional parsing to mark address as ambiguous. This in conjunction with #1496 of adding an option to keep the original address when ambiguous is checked is a good solution to this issue.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.38 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.38
