### ISSUE TITLE
BUG: Turning off activities for the Household object prevents installation/upgrade of NPSP

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1490]
[Per this hub thread.](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006iHGb&tab=sfdc.ProfilePlatformFeed&fId=0D58000001vgaX2&emtm=1427907930152&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4)

Changing [this query](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CONV_Account_Conversion_BATCH.cls#L245) to dynamic soql, or to filter on a set of household ids instead of the household objects themselves, could fix this issue.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.38 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.38
