### ISSUE TITLE
BUG: Addresses sub-tab in NPSP Settings errors on save

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/Cumulus#1491]
On the People > Address Settings tab of NPSP settings, if you edit and then attempt to save, 
AND Enable Automatic Verification is FALSE
AND Verification Service is NULL
then the settings are not saved and a "Settings not saved: Attempt to de-reference a null object" error is shown under the Save/Cancel buttons.

Selecting Google or Cicero while leaving the Enable Automatic Verification = FALSE allows a save, even with a NULL Auth Token. Trying to save with SmartyStreets selected gives verification errors on Auth ID and Auth Token. Note also that selecting SmartyStreets doesn't cause the Auth ID field to appear until a save is attempted.

**Comment by davidhabib** [comment]
@njjc @ceiroa @jlantz So it sounds like recent work in address settings have introduced some problems.  Have these been fixed in 3.37 that went out to sandboxes last night?  If not, should we consider getting them in before we push 3.37 to production next Tuesday.

**Comment by davidhabib** [comment]
I think we should also consider improving the test suites for this settings page, as we've had problems with it before.

**Comment by ceiroa** [comment]
Yeah, this was my first candidate for a Cinnamon test...

**Comment by davidhabib** [comment]
just verified still happens in 3.37.  In reading the bug description, I see now that it requires auto-verify = 0ff and service = empty.  Which i'm guessing is the default that we the user gets if they manually install NPSP or get the trial template.  So new customers are going to hit this.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.38 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.38
