### ISSUE TITLE
Update contributor docs with instructions for Windows and clarifications for Eclipse

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1494]
[Per this hub thread.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D580000020o03X&emtm=1427955644339&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4)

**Comment by silne30** [comment]
Hi @njjc,

I took a look at the thread and it seems that there were a great many topics covered. Is there a specific line I should look at in the thread or comment by a specific person?

**Comment by kbromer** [comment]
duplicate #1253
