### ISSUE TITLE
Original address is removed from record if ambiguous, and ambiguous checkbox is checked

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1496]
From hub thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001jLTWQ (Issue was added to existing thread, so search for "Riju Jain").

The code is doing the right thing, but maybe what it should be doing is not check the "Validated" checkbox, check the "Ambiguous" one, and leave the original address in peace. Basically have a different option from either reject ambiguous or take the first result.

**Comment by njjc** [comment]
Sounds similar to #1488

**Comment by njjc** [comment]
The third option for ambiguous addresses sounds useful in relation to #1488.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.38 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.38
