### ISSUE TITLE
BUG: Changing Address Type on Contact does not save correctly

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1498]
If a contact in a household account has an address override, and you try to update the Contact's Primary Address Type field, and save the record, the value gets restored to the Address Type field on the Address object.  Ideally, this update would have updated the Address Type on the Address object.

**Comment by davidhabib** [comment]
Hub thread with similar scenarios to test when looking into this.  https://powerofus.force.com/_ui/core/chatter/topics/TopicPage?id=0TO8000000001QP&ref=feed_item_topic&entityId=0D58000001s3JXh

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
