### ISSUE TITLE
BUG: Saving a multiline address through a tool load (DemandTools, Data Loader) into a Household Contact's mailing street field refreshes with the crlf replaced with a space.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1499]
hub thread: https://powerofus.force.com/0D580000020oURn

**Comment by bradstruss** [comment]
I'm seeing this issue as well when updating/upserting multiline mailing address fields into a v3 HH Account Model system.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
