### ISSUE TITLE
Issue for Affiliations pack, Affiliations.cls

### ISSUE THREAD

**Issue by zzj8810** [SalesforceFoundation/Cumulus#1500]
1.It don't use Affiliations_Settings__c for profile level nor user level, it will always use org default.
quote line 197-199:
        if (affiliationsSettings == null) {
            //first see if we already have settings
            affiliationsSettings = Affiliations_Settings__c.getOrgDefaults();

2. Not unnecessary to concatenate unique string, a.Contact__c should be enough.
quote line 163-164:
                String unique = a.Contact__c;
                unique += a.Organization__c;

**Comment by davidhabib** [comment]
settings have been redesigned in NPSP 3.0 to do the correct thing.

**Comment by zzj8810** [comment]
But the old version with this bug is still out there at AppExchange:
https://appexchange.salesforce.com/listingDetail?listingId=a0N30000003GLGFEA4
Would you please update that as well? 
Other user might install that old package.

**Comment by davidhabib** [comment]
sorry, but we are not updating the old packages.  We have made 100's of fixes since NPSP 2.0 in NPSP 3.0, and that is our only supported platform moving forward.
