### ISSUE TITLE
As a user, I'd like the lat and long address info to be pushed from the address record to the Account.BillingLatitude  and Account.BillingLongitude

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1501]
These fields may have been added together with the new geolocation-related functionality included in Spring 15. 

Looks like you can create Account/Contact list views based on geolocation (e.g. within X miles of ____" but that requires the geocoding to be included on the Account/Contact record.

**Comment by staceyeileen** [comment]
There are lat/long fields for each of the standard address fields, so:
Account.BillingLatitude
Account.BillingLongitude
Account.ShippingLatitude
Account.ShippingLongitude
Contact.MailingLatitude
Contact.MailingLongitude

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
