### ISSUE TITLE
BUG: Changing an opportunity from 0 or null creates a payment regardless of npe01__Do_Not_Automatically_Create_Payment__c field.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1504]
[Per comment on this hub thread.](https://powerofus.force.com/0D58000001nHu3r)

**Comment by larahoke** [comment]
I have experienced this problem and it occurs with new Opportunity records as well. For new Opportunities, if the amount is $0, then no Payment is created. If the amount is null or more than $0, then a Payment is created.

**Comment by judisohn** [comment]
Going through this thread https://powerofus.force.com/0D580000026RzQp with @larahoke and it appears to be an issue with one org. Trying to isolate exactly what is causing it and then will update if it's related.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
