### ISSUE TITLE
BUG: Changed Primary Address Type on contact overwritten by type in current address

### ISSUE THREAD

**Issue by RBLopez** [SalesforceFoundation/Cumulus#1509]
Steps to reproduce:
1) Create a contact record with a current address that has a type specified.
2) Change the Primary Address Type on the contact but no other address fields.
3) Address management code sets the Primary Address Type field to equal the type on the address record.

This one could be particularly annoying for users because it looks/behaves as though changes they made are just not being saved. There should either be a new address record created, or the address type on contacts should not be controlled by the related address record.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41

**Comment by davidhabib** [comment]
possible regression?  https://powerofus.force.com/0D58000002FGWoo

**Comment by kevsnell** [comment]
Hi David,

So we are experiencing a similar issue.

I've tried to explain the process so you can replicate it.

Create a Contact with an address and the primary address type field set - the household account is created and the related address history record is created against the household.  However, this sets the address history to the address type "main" based on it being the default address type value and overwrites the primary address type on the contact to "main".  I have also change it so there is no default address type on the address history but this then just sets the primary address type to blank on the contact.  So on insert the contact primary address type is overwritten by whatever is set as the default on the address history record.  I expected the functionality to set the address type on the address history of that set on the contact in the primary address type field.

Interestingly the functionality works correct when you are editing the contact record and the address history record takes the primary address type from the contact.  So the problem only seems to exist on insert of a contact.

I've tried this in a couple of different orgs and experience the same problem in all of them.  I guess the main question is how can we stop this from happening and how long would it take for a fix to be put in place.

Thanks

Kev

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fueAAA" target="_blank">W-008299</a>
