### ISSUE TITLE
BUG: Formula on Address.Mailing Street Address is always inserting comma on end

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1517]
The formula is currently:

npsp__MailingStreet__c + IF(ISNULL(npsp__MailingStreet2__c), '', ', ' + TRIM(npsp__MailingStreet2__c))

This is adding a comma to the end no matter what is in the Mailing Street 2 field. It should be:

npsp__MailingStreet__c + IF(ISBLANK(npsp__MailingStreet2__c), null, ', ' + TRIM(npsp__MailingStreet2__c))

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
