### ISSUE TITLE
Recurring Donation Custom Field Mapping doesn't support lookup/master-detail fields.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1524]
[Per this hub thread.](https://powerofus.force.com/0D580000025JfAS)

**Comment by njjc** [comment]
Lookup fields are in fact supported. Need to get to the bottom of why they were rejected in this specific case.

**Comment by jlantz** [comment]
The issue turned out to be due to missing field level security in profiles

**Comment by mrbelvedere** [comment]
Story deleted from ScrumDo
