### ISSUE TITLE
Add new HUB Logo to NPSP Resources page

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1526]
![power-of-us-hub_rgb](https://cloud.githubusercontent.com/assets/908119/7404740/ad0b2420-ee9c-11e4-9a31-74f362cf8319.png)

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
