### ISSUE TITLE
As a developer, I want to have a suite of browser based tests for the UI functionality of Manage Households on Households and Household Accounts so I can test functionality which cannot be tested by Apex tests alone.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#153]
Tests should use the specification http://github.com/SalesforceFoundation/CumulusTesting/specs/ManageHouseholds.feature

**Comment by davidhabib** [comment]
**lurch: attach W-007964

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001eY7AAI" target="_blank">W-007964</a>
