### ISSUE TITLE
Primary address deletion behavior is not handled.

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1531]
It appears that when deleting a primary address directly from the related list, the address is still retained as the Billing Address on the Account post-deletion, even though the address record itself has been removed. 

Consider one of the following deletion behaviors: 
1.  Select the most recently available previous address (if one exists) from the list of addresses on the Account
2.  Remove the address values from the Shipping address fields and any associated Contacts

**Comment by davidhabib** [comment]
without the user specifying another default address, not sure what we should use.  are you suggesting we just clear the account and contact address fields and leave them blank?  or do we choose some random address to be the new default?

**Comment by kbromer** [comment]
Right now we do nothing, which wouldn't be the expected behavior for me, but I'm open to thoughts.  I think the best bet would be to clear the affected Contact/Account address fields and leave them blank until another address is set... ?  We should discuss

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
