### ISSUE TITLE
As a user, I'd like to be able to set filters when I create a User Defined Rollup

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1541]
Hub thread: https://powerofus.force.com/0D580000026TE5e

**Comment by kbromer** [comment]
**lurch: attach W-007309

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYtAAI" target="_blank">W-007309</a>

**Comment by davidhabib** [comment]
related post that refines the request: https://powerofus.force.com/0D58000002Twkw8

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)
