### ISSUE TITLE
Hide Refresh Opportunities Name panel when the batch is running

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1543]
On all of our other NPSP Settings pages that invoke batches, once the user clicks to invoke the batch, the page refreshes to display the progress widget and the panel/button that invoked the batch is hidden.  The new Refresh Opportunity Names section doesn't follow this standard.

**Comment by njjc** [comment]
Thanks for catching this!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
