### ISSUE TITLE
As a user, I'd like to be able to see Affiliations and Relationships in global search result

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1548]
When someone searches on an account or contact, they expect to see Affiliation (and Relationship) records returned in global search results. There have been a few threads on the Hub on this, including this one https://powerofus.force.com/0D580000027EpZU

The reason this doesn't work is due to the fact that relationship field names are not indexed. https://success.salesforce.com/ideaView?id=08730000000iaAnAAI

The workaround is to have text fields that sync with the name of the related record. While users can create workflow rules to update values it's inefficient because if the Account or Contact name changes then the value on the Affiliation is out of sync and wrong. Should we bake these text fields in to the object and update on related record name changes?

**Comment by davidhabib** [comment]
I'm not a big fan of doing hacks like this to workaround the platform.  Given the idea is in the "considered" stage, I think we should defer to Salesforce core on this one.

**Comment by ceiroa** [comment]
I kind of agree with Dave. The workaround seems too hacky...
