### ISSUE TITLE
As a user, I'd like to have an automatically populated 'Primary Donor' lookup field on Opportunity to Contact

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1550]
This field should be the contact who is checked as the Primary Opportunity Contact Role. If the Contact Role is change to another contact, a job should check for that and update the lookup field.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
