### ISSUE TITLE
Update the Trialforce template (.dot) custom profiles to include all needed objects/security

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1552]
Using spec document developed at a prior sprint.

**Comment by davidhabib** [comment]
please include turning on perms and field level visibility for Volunteers for Salesforce, since it is included in the trial template.

**Comment by judisohn** [comment]
@davidhabib Will do

**Comment by judisohn** [comment]
@kbromer There's an 'Office Manager' profile in the template that's not in the spec document at all from the sprint. Any idea what makes it different from Office Staff? Perhaps remove it? (not packaged so shouldn't break anything)

**Comment by kbromer** [comment]
Find by me, provided we have the use-case covered.  Since its template-only, shouldn't be an issue for anybody currently using it.

**Comment by judisohn** [comment]
I guess I'm trying to figure out the use case - what perms should an Office Manager have that staff wouldn't (that would be profile-based and not role hierarchy) and that isn't System Administrator?

**Comment by judisohn** [comment]
@davidhabib Custom profiles updated (with the exception of the Office Manager profile mentioned above). Would you like to review and if okay, update as the latest or is that something @jlantz should do?

**Comment by davidhabib** [comment]
I defer to @jlantz.  I don't know how he  makes the DOT!

**Comment by jlantz** [comment]
The DOT is made from the org.  I'll work on pulling the changes into the
CumulusTemplate repo for storage later.

**Comment by davidhabib** [comment]
I am doing a few additional fixups in the template org.  these include:
- putting the correct phone field in the ManageHouseholdUI field set

**Comment by judisohn** [comment]
Great - I also went ahead and removed Conference as the default in the Type field on Campaign. In addition to the custom profiles I also updated the Permission Sets, which had great descriptions but didn't actually have any of the configuration they said they did.

**Comment by davidhabib** [comment]
anyone think we should update the list of Account Type values to something more meaningful for nonprofits?

**Comment by davidhabib** [comment]
we still need to add the Manage Household button on the Household Account page layout, once the template org has npsp 3.40

**Comment by judisohn** [comment]
Re: Account Type - yes, but do you have a generic idea ready or should we get some input on the Hub as to what would be a good set? I've commonly seen/used in its simplest form:

* Corporate
* Government
* Nonprofit
* Foundation
* Household

Others?

**Comment by davidhabib** [comment]
I like your simple list for Account Type.

Should we be deleting the deprecated BDE Entry FS and BDE List FS field sets from Opps, since Opps replaced them with V2 versions?

**Comment by davidhabib** [comment]
Should we delete the unmanaged NPSP Default Sales Process?  it is currently only holding two stages (Prospecting and Closed/Lost), and the DOT has a Donation Sales Process which is more reasonable.

**Comment by davidhabib** [comment]
Under Search Settings, do we want to enable Enhanced Lookups or Lookup Auto-Completion for any of our objects?  (I didn't even know about these settings!)

**Comment by davidhabib** [comment]
UI Settings.  should we Enable Separate Loading of Related Lists?  Enable Collapsible Sidebar?  (I always do in my orgs)

**Comment by davidhabib** [comment]
i'm finding that most of the profiles are missing visibility on the fields we've recently added to Payments and Opportunities

**Comment by judisohn** [comment]
> Should we be deleting the deprecated BDE Entry FS and BDE List FS field sets from Opps, since Opps replaced them with V2 versions?

Yes. I think so to avoid confusion.

> Under Search Settings, do we want to enable Enhanced Lookups or Lookup Auto-Completion for any of our objects? (I didn't even know about these settings!)

I believe I've read that these can cause a hit on performance. I think it's best to leave them for the org to enable if they want.

> UI Settings. should we Enable Separate Loading of Related Lists? Enable Collapsible Sidebar? (I always do in my orgs)

Sure, why not? 

> i'm finding that most of the profiles are missing visibility on the fields we've recently added to Payments and Opportunities

I thought I specifically caught those. I'll take another pass through. It was a bit mind-numbing.

**Comment by judisohn** [comment]
I should add that I specifically didn't edit FLS for Program Staff or Volunteer since they don't have at least Read access to the Payment and Opportunity objects so it didn't matter to edit them. But I'll check the others.

**Comment by judisohn** [comment]
So there's some history to look back on:

* Added the new Account Types to Organization record type (didn't delete the standard ones, but they're not enabled for any record types)
* Deleted Office Manager profile
* Deleted the NPSP Default Sales Process
* Deleted deprecated BDE Entry FS and BDE List FS field sets on Opportunity
* Enabled Separate Loading of Related Lists
* Disabled Show Quick Create
* Enabled Collapsible Sidebar
* Enabled Enhanced Profile User Interface (so it's more consistent with documentation and Permission Sets for new users)

@jlantz just need 3.40 in there so page layout on Account can be adjusted for new Manage Household button, and should be all set.
