### ISSUE TITLE
Add Account Merge UI to NPSP Contact Merge

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1553]
Brian Pickett (North Peak)
@Katie McFadden (Swift River Consulting) and @Anne Crawford (KELL Partners) thanks for spelling out your process. This is definitely a challenging process in the Household account model. 

I like how in your process when doing a Contact merge with DemandTools users are always looking for contacts within the same account. This should prevent orphaned accounts.

The main scenario that creates the lion's share of challenges using DemandTools is merging accounts when the duplicate is a secondary contact. In these cases its very difficult to find the right accounts to merge first. In your process presumably this is done within Wave 3 (i.e. - eyeball it).

@David Habib the main remaining challenge (not an issue) with the native Contact Merge is the user has no access to select how the Households should be merged. For example, if we're storing important profile/donor-qualification information on the Household record, when merging contacts you can't tell the system which household fields should "win" and you risk losing important information. It seems to cover this the Merge Contacts process would need an interim step where the Households of the selected contacts are displayed in the merge-wizard. So in essence Merge Contacts becomes a Merge-Accounts-then-Merge-Contacts wizard.
Like
   ·   Today at 8:37 AM   ·  
David Habib
David Habib
In the scenario where the household has interesting data that needs merging and control by the user to decide what to do, the solution is to have them use the standard Salesforce Account Merge tool first. 

The trigger work I've put into the NPSP to handle this scenario should then do the right thing about removing duplicate addresses and affiliations, as well as moving Opportunities to the winning household account, recalculating rollups, etc.

After merging the household accounts, the user can then either use the standard Salesforce Contact Merge (within an account) functionality, or use NPSP's Contact Merge. Having the NPSP also provide the functionality of Account Merge while in our Contact Merge seems like too heavy a lift given there is a solution provided by Salesforce.
Like
   ·   Today at 8:44 AM   ·  
Brian Pickett (North Peak)
Brian Pickett (North Peak)
Yes, that is do-able but the workflow is ...ahem... "not ideal" in that scenario. So if I find Sally Smith needs merging, I have to click through somewhere else to merge her Account first. Generally account names are generic so finding the right "Smith Household" takes extra steps and is risky (since virtually no identifiable information is provided). 
Then I have to repeat the steps using the Contact Merge.

Do-able yes. Tight and simple ~ no.

**Comment by kbromer** [comment]
**lurch: attach W-007294

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYeAAI" target="_blank">W-007294</a>

**Comment by judisohn** [comment]
Related Idea on Hub [here](https://powerofus.force.com/hub-ideas/1136).

**Comment by njjc** [comment]
This has been marked as "Never" internally.
