### ISSUE TITLE
Address Validation Error during Contact Merge

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1554]
user reporting that they are hitting address validation errors during contact merge even though address validation is off.  https://powerofus.force.com/0D580000027Fxdu

Sounds like there is two issues:

1. if validation is off, this should not happen.

2. if validation is on, contact merge will be doing its fixups in a future, and thus cannot call validation.

**Comment by davidhabib** [comment]
@ceiroa In looking at ADDR_Validator_TDTM, we no longer log an error if the Address is being inserted/updated during a batch operation.  I propose the same thing if the Address is inserted/updated  during a Future operation.

The change would be on line 76 to no longer process an error.  It could just spit out debug for this scenario, just like the batch scenario.

comments?

**Comment by ceiroa** [comment]
@davidhabib Yes, let's do that.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
