### ISSUE TITLE
Cicero Address Validation errors should be treated differently

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1555]
Currently, let's say you are converting a lead or saving a contact with a partial address.  NPSP still creates the address object with the partial address and tries to validate it.  If you are using Cicero, and have an address with just City and State, you will get an error email sent and logged that says:

Error Type: ADDR_Cicero_Validator.CiceroException
Error Date: 2015-05-14 20:23:51
Message: "400: BAD REQUEST
{"response": {"errors": ["If not supplying an address, you must supply a full postal code and a valid country code"], "messages": [], "results": {}}}"

Stack Trace:
 Stacktrace available at the time of saving the record - Class.ADDR_Cicero_Validator.verifyAddress: line 168, column 1
Class.ADDR_Cicero_Validator: line 100, column 1
Class.ADDR_Validator: line 90, column 1
Class.ADDR_Validator: line 64, column 1
Class.ADDR_Validator: line 48, column 1

I think this is too disconcerting to the user.  Seems like it would be much better to have the validator just save the error in the Verification Status (which it does), and not log and email an error.  Not sure if we have this same error with Google and Smarty Streets.

It really boils down to treating address related problems as just something to record on the address, vs. unexpected problems with the service that should generate the error email and error log.

**Comment by kbromer** [comment]
**lurch: attach W-007382

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ca5AAA" target="_blank">W-007382</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
