### ISSUE TITLE
If the account model is set to One to One, Organization Affiliation record not created based on Primary Affiliation

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1557]
Replicated this in 3.38 org - POU thread https://powerofus.force.com/0D580000027Fx0n

**Comment by judisohn** [comment]
I think I found a clue - I think it's related to Household record creation - If Households creation is set (All New or Edited) then Organization Affiliation creation fails even with Household Account model (when I switched back to Household model, but forgot to turn off Household creation it failed - as soon as I set Households to No Contacts, it was fine again)

**Comment by judisohn** [comment]
Might also be related - https://powerofus.force.com/0D580000029TapP - appears to be challenges with auto-affiliation creation when not using the Household Account model.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43
