### ISSUE TITLE
BUG: Relationships - set to List Setting - when Status changes to Former from Current, Type is set to Neutral value of row

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1564]
Hub thread: https://powerofus.force.com/0D580000027HLFb

Replicated in test org. When changing status, on Save the Type is updated to the row's Neutral value.

**Comment by kbromer** [comment]
Still can't replicate.   What is the gender set to?

**Comment by judisohn** [comment]
Interesting... 

Here's what I also put in the thread:

Gender field blank. Created 2 new Relationship rows, one duplicating Beth's use case (Public Health Nurse, Client, Client, Client). Updating Status changed the Type from Public Health Nurse to Client.

So I created a second relationship row with Original Name, Original Male, Original Female and Original Neutral to make it easier to see exactly what was happening. Confirmed that the type changed to Original Neutral on save.

All created values were added to the Relationship Type picklist.

Both contacts are Household contacts - NPSP 3.39 as vanilla as I can make it.

Account Model is Household Account.

**Comment by kbromer** [comment]
Weird.  I have 3.39 vanilla.  Gender and salutation defined.  It works fine.  

Tried just the gender per Beth's comment, and it still works as expected.  Lets get someone else from the dev team to try it out.

**Comment by kbromer** [comment]
Okay, think we have it now: 

If an update fires and the base relationship gender is unknown, the current behavior will update the type based on the new 'Neutral' gender.  

Fix here is to simply ignore a change only to the status instead of reevaluating the relationships.

**Comment by bethbbc** [comment]
Hi guys! Glad this got figured out! Any ETA on the change/fix?

**Comment by njjc** [comment]
@bethbbc next release!

**Comment by bethbbc** [comment]
Awesome!!! Thanks!

**Comment by njjc** [comment]
Hi @bethbbc, this actually didn't make it in today as the fix I implemented didn't work correctly. Digging further it looks like quite a bit more of the relationships code isn't working as expected, which I'll be working on this release.

**Comment by bethbbc** [comment]
Thanks for the update, Nicolas!! Greatly appreciated. Let me know if you
want/need any help testing.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.48 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.48
