### ISSUE TITLE
Acknowledgement Date and Acknowledgement Status opportunity fields should be available in field sets.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1570]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D580000028NNri&emtm=1432227724890&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
