### ISSUE TITLE
Warn users in lead conversion if profile default account record type is same as Household/One to One

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1571]
If default is set to same record type as is used for Household or One to One, then Affiliate accounts created in lead conversion will have that record type be treated as individual account in reporting and naming.

Could be in Health Check too, but then would have to check against all profiles?

**Comment by kbromer** [comment]
**lurch: attach W-007313

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYxAAI" target="_blank">W-007313</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 5)
