### ISSUE TITLE
If the only member of a household/primary contact is marked as deceased, Exclude from Household Name should be unchecked

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1572]
This is to avoid an "Anonymous Household." Exclude from Greetings should still be checked, opt outs should still be checked.

POU thread: https://powerofus.force.com/0D580000020pFeI

**Comment by kbromer** [comment]
**lurch: attach W-007459

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cc4AAA" target="_blank">W-007459</a>

**Comment by davidhabib** [comment]
another hub thread: https://powerofus.force.com/0D58000002Mw1Ul

note that ideally we might do lastname household (deceased) rather than just lastname household.

**Comment by davidhabib** [comment]
one user requests that the deceased format by customizable, not hard coded to lastname household (deceased).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.61 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.61
