### ISSUE TITLE
As a user I want to record relationships with non-contacts

### ISSUE THREAD

**Issue by Filikin** [SalesforceFoundation/Cumulus#1574]
Working with a domestic abuse charity.
They wanted to record relationships between clients and their children and their alleged abusers.
But they didn't want to create contact records for the alleged abusers (legal reasons).
So I modified the page layout of the relationship to make the related contact optional and added a text field for the name of the alleged abuser.
Everything was fine, until they updated a relationship and it was deleted because of this line in the after update handler of REL_Relationships_TDTM.cls
     
 if (r.npe4__RelatedContact__c == null) {
                    relationshipsToDelete.add(r);
} 

for the moment I have disabled the after update handler - but how about a custom setting to optionally disable the deletion of the relationship?

**Comment by njjc** [comment]
Could you potentially make an "anonymous" contact for this case and even auto fill it when that contact field is left blank? Unfortunately I don't see this as a big enough use case for us to implement a setting.

**Comment by njjc** [comment]
A new custom object for this type of "relationship" is another possibility.

**Comment by jlantz** [comment]
Closing as this change will not be made to the package.  The workaround is to use custom objects.

**Comment by Filikin** [comment]
?thanks Nicolas,

the custom object is out as that would require duplicating all the features of the relationship object, but I will try the anonymous contact idea

Eamon

Eamon Kelly
ENCLUDE - Technology Donations and Solutions for Irish Charities
Drumcondra Business Centre
120 Drumcondra Road Upper
Dublin 9
Main Phone:      (01) 6535099
Support Phone: (01) 4853435
Mobile: 085 7130794
Web: http://www.enclude.ie<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.enclude.ie>

ENCLUDEit - technology donation website http://www.encludeit.org<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.encludeit.org%2f>

________________________________
