### ISSUE TITLE
As a developer, I would like to have a checklist to use when reviewing a change

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1577]
For example:
- If fields are added, were they added to the right fieldsets, layouts, profiles in template, etc

**Comment by davidhabib** [comment]
https://developer.salesforce.com/blogs/engineering/2015/05/developer-practices-checklist.html

good developer checklist we might want to use or incorporate.

**Comment by kbromer** [comment]
**lurch: attach W-007264

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYAAAY" target="_blank">W-007264</a>
