### ISSUE TITLE
False positive from Health Check

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1582]
From https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D580000028OzMD

User is getting error message with contents of label healthSolutionScheduleJobs.

The functionality that notifies of this issue has not changed since almost a year ago (see line 503 in https://github.com/SalesforceFoundation/Cumulus/blame/104dbfac7bcc4aad4b35030edd98039dcdf9fe36/src/classes/STG_PanelHealthCheck_CTRL.cls). However, recent commit added one more class to be scheduled (https://github.com/SalesforceFoundation/Cumulus/commit/ce18095683b88894df7ac6c1e0d6342c08f6276e), which is causing to miscount. @njjc

**Comment by njjc** [comment]
Thanks @ceiroa, good catch. I'll fix it!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
