### ISSUE TITLE
Update Batch Data Entry UI to use new Opportunity Primary Contact field.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1585]
Currently a hacky workaround is in place.

**Comment by kbromer** [comment]
And by "hacky" I assume you mean "brilliant".

**Comment by kbromer** [comment]
**lurch: attach W-007452

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cbxAAA" target="_blank">W-007452</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
