### ISSUE TITLE
As a user, I can have Household Naming specification that will produce Mr. & Mrs. John Doe.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1586]
Hub thread: https://powerofus.force.com/0D580000028QKE5

Currently, household naming doesn't support is only showing the firstname for the primary contact, but not showing firstname for other contacts. {!{!Salutation} {!FirstName}} {!LastName} will get you Mr. John & Mrs. Jane Doe. I will put in a feature request for what you are asking, but I'm not sure how feasible it will be to implement given our naming formula rules.

**Comment by judisohn** [comment]
Another request for this: https://powerofus.force.com/0D58000002AFHxM

**Comment by davidhabib** [comment]
another similar request for this: https://powerofus.force.com/0D58000002CG5da

**Comment by kbromer** [comment]
**lurch: attach W-007282

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYSAAY" target="_blank">W-007282</a>

**Comment by judisohn** [comment]
Another use case: https://powerofus.force.com/0D58000002Mykem

**Comment by cdcarter** [comment]
A similar but not quite the same request: https://powerofus.force.com/0D58000002XN6X9

**Comment by judisohn** [comment]
Another use case: https://powerofus.force.com/0D58000002lLqaC

**Comment by dianemichaelis** [comment]
Any word on this! We would love it too. It'd be ideal if it had the ability to pull the primary contact first name or the male first name. Both options would be awesome!
