### ISSUE TITLE
Divide By(Schedule Type) not working for Open Recurring Donation

### ISSUE THREAD

**Issue by poonamkeswani** [SalesforceFoundation/Cumulus#1587]
When we create a new Recurring Donations and populate following fields. 
1) Name, Amount, No of Instalments
2) Schedule Type = Divide By, Open Ended Status = Open, Instalment Period = Monthly
The divide by function does not work. It does not populate the Instalment Amount and Donation Amounts correctly.

Note : It works fine when we select Open Ended Status as None.
I have granted Salesforce Foundation access to my Sandbox Org - 00DO0000000WPZc

**Comment by poonamkeswani** [comment]
@njjc - Your help will be highly appreciated.

**Comment by davidhabib** [comment]
divide by is only for NON open-ended RD's.  open-ended RD's always assume multiply by, since there is no way to do divide by with no end point!
