### ISSUE TITLE
If the Household primary Contact is marked deceased, another Household member should be automatically elevated to be the primary Contact

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1588]

**Comment by kbromer** [comment]
**lurch: attach W-007459

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cc4AAA" target="_blank">W-007459</a>

**Comment by bmcguirk** [comment]
Sorry guys, but is this projected to be in a future release?

**Comment by njjc** [comment]
Yep, though hard to say when.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.61 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.61
