### ISSUE TITLE
Account Converter should copy contact's primary address type to address objects and not make work address the default

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1590]
hub thread here:  https://powerofus.force.com/0D580000027H65N

relevant part:

Caroline Renard (Technology Interpreter for Arts Groups)
It would be useful if the Primary Address Type on Contact was applied during conversion. Have just converted an org with several contacts that had been directly related to organizations (so the address on their Contact record was "Work") and the HH address was blank. Now that they are converted, in the new Household Accounts, the same address appears as "Home" and Default in the Address object. I've used Apsona to update the Address Type on the Address object back to "Work" and to uncheck the Default, but it would be nice not to have to do this bit of post-processing - and it would have completely confused my client if they had noticed (or NOT noticed!) before I did. Thanks!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43
