### ISSUE TITLE
Contact Merge query can hit limits if org has > 100k Opportunities

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1591]
Cascase Aids Alliance hits a runtime soql error when trying to merge contacts.  Here is the hub post: https://powerofus.force.com/0D580000028RIkb

the problem is due to the following query in CON_ContactMerge_TDTM.run()

list<Opportunity> listOpp = [select Id, npe01__Contact_Id_For_Role__c from Opportunity 
                where npe01__Contact_Id_For_Role__c in :listConId];

Unfortunately, npe01__Contact_Id_For_Role__c is just a text field and not a real lookup, so it doesn't get indexed.  not sure what our workaround is.

**Comment by davidhabib** [comment]
maybe we first query for all OCR's based on the contactId, and then we will have a set of opps to look at that we can filter on.  it won't catch opps that have npe01__Contact_Id_For_Role__c set, but no OCR, but I'm not sure that should happen.  @njjc any thoughts, and how this might need to change with your primary contact code you are working on?

**Comment by kbromer** [comment]
That's what we do in rollups (drive everything off the OCR).  It gives us a clean reference to the Con and Opp, which we can then use to instantiate the object in memory and set the fields on it and update it without ever actually retrieving it from the DB.

**Comment by davidhabib** [comment]
the whole point of this code was to actually find any opps who had npe01__Contact_Id_For_Role__c filled in for a contact being deleted or merged.  so it was doing what we'd normally get if the field had been a lookup!  that's why i raise the issue that we still might miss some.  but oh well!

**Comment by njjc** [comment]
Now that we have a lookup we can just blank out the text version of the field when the lookup is blanked out. I'm not positive an update happens when a lookup is blanked out, I'll have to do some testing.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.41 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.41
