### ISSUE TITLE
Recurring Donations - UI string and help bubble updates

### ISSUE THREAD

**Issue by jvarese** [SalesforceFoundation/Cumulus#1592]
SETTINGS | RECURRING DONATIONS | RECURRING DONATIONS

Intro Sentence: These settings control how Recurring Donations behave in the Nonprofit Starter Pack. See the NPSP Documentation for more information. [Link "NPSP Documentation" with /NPSP_Recurring_Donations. @njjc  -- I always forget, does Dave need to add anything else to the link besides this slash + identifier?]

Opportunity Forecast Months
Number of months’ worth of open opportunities created for Open-Ended Recurring Donations. The default is 12, so after every month, Salesforce creates another month’s worth of open opportunities (i.e., the total months’ worth of open opportunities is always 12). 

Open Opportunity Behavior on RD Close
Tells Salesforce what to do with any remaining open opportunities when you mark the status of a Recurring Donation as Closed. 

Maximum Donations
Restricts the total number of donations (installments) for Fixed-Length Recurring Donations. Default is 50.

Add Campaign to All Opportunities
If selected, adds the campaign that you’ve specified for the Recurring Donation to all related (i.e. “child”) opportunities. If this option is not selected, the campaign appears on the Recurring Donation’s first opportunity only.

Opportunity Record Type
The opportunity record type assigned to the Recurring Donation’s child opportunities.

Disable Scheduling of Nightly Job
Prevents the scheduling of the nightly update to Recurring Donations. You’ll need to remove any existing scheduled jobs through Setup | Monitoring | Scheduled Jobs.

SETTINGS | RECURRING DONATIONS | RECURRING DONATION CUSTOM FIELD MAPPINGS

Intro sentence: This setting lets you map fields from the Recurring Donation record to the Recurring Donation's child Opportunities.

Then, in the edit screen, intro sentence . . . 

First, select the Recurring Donation field you want to map. Then select the Opportunity field you want to map to. The Recurring Donation field you select will appear on all child opportunities for the Recurring Donation.

IMPORTANT: Both of these fields must have the same data type.

Delete the two description strings for the field choices that are currently there.

NEW RD PAGE - UI TEXT AND HELP BUBBLES

Open Ended Status
Change to: Status

Status picklist values:
Open-Ended: Open
Fixed-Length: Open
Closed

Next Donation Date
The date on which you want the next donation to occur. This date also determines the date of all future donations.

Last Donation Date
Do Not Enter. The NPSP calculates this value automatically based on the last time a child donation was marked Posted.

Installment Period
How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.

Installments
Number of installments (donations) you expect to receive. For Fixed-Length Recurring Donations only. 

Schedule Type
Tells Salesforce how to compute the amount for each child opportunity, based on what you've entered in the Amount field. For Fixed-Length Recurring Donations only. 

Paid Amount
Do Not Enter. The NPSP calculates this value automatically as donations are made and marked Posted.

Total Paid Installments
Do Not Enter. The NPSP calculates this value automatically as donations are made and marked Posted.

**Comment by njjc** [comment]
Prefix is http://powerofus.force.com/, so http://powerofus.force.com/NPSP_Recurring_Donations

**Comment by davidhabib** [comment]
@jvarese I cannot change the picklist values for the Recurring Donation Open Ended Status field to what you suggest.  Our values cannot change since they have already been released.  Given this, do you still want me to rename the field Open Ended Status to just Status, or leave as is?  FYI, the picklist values we are stuck with are Open, Closed, and None, with the picklist also showing --None-- for empty.

**Comment by davidhabib** [comment]
@jvarese can you hear me now?

**Comment by njjc** [comment]
@jvarese HELLOOOO

**Comment by jvarese** [comment]
@njjc -- I can hear you! But I can't hear Dave!

:-(

**Comment by jvarese** [comment]
For the record, we have not updated the Status string or the picklist values, but instead added a help bubble describing the values that we're locked into.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43

**Comment by jvarese** [comment]
New help bubble for Open Ended Status: Choose Open for an Open-Ended Recurring Donation. Choose None for a Fixed Length Recurring Donation. Choose Closed to close a Recurring Donation.
