### ISSUE TITLE
Recurring Donation child opportunities should roll up Paid Amount when inserted as Closed/Won, not just on update to Closed/Won

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1595]
Hub thread: https://powerofus.force.com/0D580000029U9Ui

**Comment by judisohn** [comment]
Also from the thread for more investigation when opportunities are not planned in advance, may be related:

>I had read somewhere to set the installments to 0 to prevent the entering of new pledged opps. Your plan resets the installments to however many closed/won opps exist. I don't have a problem with that, but hitting the Refresh Opps button with that number of installments generates a Divide by 0 error. Should I just take the Refresh Opps button off the layout?

>And sorry - apparently I have 2 questions. Rollups get batch updated overnight for consistency. (I believe - I'm still new to SF.) But it doesn't look like the recurring donation Paid Amount would be included in those. Is that a consideration?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43
