### ISSUE TITLE
In some cases, changing an Opportunity to Closed/Lost causes infinite recursion

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1600]
https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000005WuCJ&tab=sfdc.ProfilePlatformFeed&fId=0D580000028Qlbg&emtm=1433784041080&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43
