### ISSUE TITLE
Missing Rollups.html from ApexDoc

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1602]
Getting a 404 when hitting this: http://developer.salesforcefoundation.org/Cumulus/ApexDocumentation/Rollups.html

**Comment by kbromer** [comment]
Ah, its empty content, needs at least a couple of <html> tags I think

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fw1AAA" target="_blank">W-008305</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
