### ISSUE TITLE
When converting a Lead, if the Account has an apostrophe in its name the Lead can't be matched to existing account

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1604]
POU thread: https://powerofus.force.com/0D580000029Vui7

The reason why this took a while to reproduce is that it only happens in an instance that has the managed packages. It's not reproducible in a Dev org with unmanaged code.

This issue happens regardless of whether using Visualforce override or standard Lead Convert button. In an org without NPSP 3, the Lead can be matched to the existing account.

**Comment by davidhabib** [comment]
User (and myself) can only replicate on the Standard Lead Convert page from Salesforce.  The NPSP Lead Convert Override page does not have this problem.
