### ISSUE TITLE
Address Verification Service drop down not giving choice of services

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1605]
POU thread: https://powerofus.force.com/0D580000029W6KB

Reproduced in org with 3.42 and when editing Address Settings, the Services drop down does not show any services to select.

**Comment by judisohn** [comment]
Another report https://powerofus.force.com/0D58000002ADDD1

**Comment by davidhabib** [comment]
wow.  how did we introduce this one?

**Comment by njjc** [comment]
I'm not sure. I fixed another bug and it was working a month or so ago. I'll look into it, probably my fault :(

**Comment by njjc** [comment]
Good news everyone! It wasn't my fault! Summer '15 bug! Whew. :+1:

**Comment by mrbelvedere** [comment]
Included in beta release version 3.43 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.43
