### ISSUE TITLE
Cannot Make edits to STG_SettingsManager VF Pg

### ISSUE THREAD

**Issue by KalmanS** [SalesforceFoundation/Cumulus#1606]
When I select EDIT > any changes that are made are not getting saved. Err but or Message is "Settings not saved: Attempt to de-reference a null object"

Verification Service attribute only showing a check and no other options. Current service selected is SmartyStreets but it's not configured correctly.

**Comment by judisohn** [comment]
See #1605 for same/related issue.

**Comment by davidhabib** [comment]
fixed by #1605 in release 3.43

**Comment by KalmanS** [comment]
Thanks David!
