### ISSUE TITLE
Relationship Viewer not displaying in IE10

### ISSUE THREAD

**Issue by GeoffPidcock** [SalesforceFoundation/Cumulus#1607]
Details are provided below;

When relationship viewer is booted in the NPSP, a blank screen is presented. 
IE10 details can be found here:

![image001 1](https://cloud.githubusercontent.com/assets/12888728/8152327/1acc2900-135f-11e5-8362-23fc44d3e428.png)

Kindest regards - Geoff Pidcock - geoff@geoffpidcock.com

**Comment by kbromer** [comment]
This is tied to the library we use.  Newer IE versions work, and we'll be looking at revising the viewer with a new library shortly. I'm going to close this issue based on that information.  Thanks for logging it @GeoffPidcock!
