### ISSUE TITLE
Add Salutation fields to Manage Household VF page contact cards

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1610]
Thread: https://powerofus.force.com/0D58000002ADGTC

**Comment by davidhabib** [comment]
Note that we have a separate github issue for supporting a field set for the contact cards, so the user could specify any fields.  might be a better solution than just hard-coding salutation.

**Comment by judisohn** [comment]
I thought so and I did a search and couldn't find it - was probably putting in the wrong search term - feel free to close and add the thread mentioned here so it's part of the same issue. I agree that the more general one is better overall.

**Comment by davidhabib** [comment]
we agreed to close this and keep issue #1480 open.
