### ISSUE TITLE
Add "Type" field as part of included Grant Management Object fields

### ISSUE THREAD

**Issue by BrightStepTracy** [SalesforceFoundation/Cumulus#1618]
Suggested initial picklist values: LOI, Application, Interim Report, Final Report

**Comment by judisohn** [comment]
@BrightStepTracy Thanks!! I'm assuming you mean this for the Deadline object?

**Comment by BrightStepTracy** [comment]
Yep! As a springboard for rollup summaries :)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwCAAQ" target="_blank">W-008308</a>
