### ISSUE TITLE
Auto-Populate Grant Deadline Name field on Create from Opportunity

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/Cumulus#1619]
Can this be auto-populated with some kind of Text, even if it's just the Opportunity name and "Grant Deliverable"? It would save a step of data entry, as well as allow for workflow-driven renaming once the Grant Deadline record is saved.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwDAAQ" target="_blank">W-008309</a>

**Comment by BrightStepTracy** [comment]
Can this somehow leverage the now-GA customizable Opportunity naming as applied to this Object?

**Comment by judisohn** [comment]
@TracyKronzak I added a new Action to the trial template that creates a Deliverable from Opportunity and populates the Deliverable Name with "{Opportunity Name} Deliverable" We don't want to package as packaged Actions are not editable. We won't be creating a custom button that populates the value at this time as they are not Lightning-compatible.
