### ISSUE TITLE
Create Selenium test to exercise New Contact Donation button

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1620]
Include both primary and nonprimary household members.

**Comment by kbromer** [comment]
**lurch: attach W-007983

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001eZeAAI" target="_blank">W-007983</a>

**Comment by chrismcmahon** [comment]
I moved this to the top of the backlog, I should be able to tackle it next sprint.

**Comment by mpusto** [comment]
Completed November 2015.
