### ISSUE TITLE
New Opportunity for household's non primary contact: record is read only

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1621]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002AFily&fromEmail=1

**Comment by mrbelvedere** [comment]
Included in beta release version 3.44 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.44
