### ISSUE TITLE
As an Administrator, I would like more standard Account fields available in the Manage_Household_Custom field set

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/Cumulus#1623]
Per [this Hub thread](https://powerofus.force.com/0D58000002AFuAh) someone would like to have the `ParentAccount` field available to the `Manage_Household_Custom` field set. I can see a definite use case for using Parent Account to reflect religious congregation membership, or perhaps an assignment to a social service Org Account. 

There are some other standard Account fields excluded from the field set. They are the B2B-centric fields, but creative reuse of standard fields rather than creating custom fields might make it worth making the following available in the field set as well:
* AnnualRevenue
* NumberOfEmployees
* Industry

**Comment by kbromer** [comment]
**lurch: attach W-008297

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fuPAAQ" target="_blank">W-008297</a>
