### ISSUE TITLE
Household Conversion Script Disregards Account Address Setting

### ISSUE THREAD

**Issue by zacherytapp** [SalesforceFoundation/Cumulus#1626]
When performing a Household Account migration using the Conversion Script (npsp__CONV_Account_Conversion) - currently, the Address settings are not taken into account and an Address record is created always. The conversion process should take the Address settings into account.

**Comment by bethsaunders** [comment]
This would be extremely helpful.  Customers could choose Address Management just as they choose an Account Model BEFORE the conversion takes place.  (The address clean up is a lot of work otherwise).

**Comment by ericacox** [comment]
I agree.  Often Address Management is disabled because a large number of contacts/Households creates a storage concern.  This makes the cleanup even more tedious, and the extra records created may even cause an org to hit space limitations.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.46 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.46
