### ISSUE TITLE
Make Opportunity Contact Roles creation happen for both Contact Id for Role and Primary Contact

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1627]
Use either one here: https://github.com/SalesforceFoundation/Cumulus/blob/rel/3.42/src/classes/OPP_OpportunityContactRoles_TDTM.cls#L220

**Comment by mrbelvedere** [comment]
Included in beta release version 3.48 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.48
