### ISSUE TITLE
Health Check must gracefully handle creating an Account failing

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1629]
a user reported they have a validation rule on Accounts that causes Health Check to fail to run (rather than logging an error).  Hub post here: https://powerofus.force.com/0D58000002AGcF2

the culprit is STG_PanelRDCustomInstallment_CTRL.verifyRDSaving(this) which creates a temp account assuming it will always succeed.  this needs to be in a try/catch and handled gracefully with an error log entry.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwHAAQ" target="_blank">W-008311</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.57 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.57
