### ISSUE TITLE
NPSP Data Import should give Error if not in Household Account model, or matches existing 1:1 contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1630]
The data importer should detect whether the accounts that come back from new and matched contacts are Household or other, and give an error if other.  Currently, if you have existing 1:1 contacts that get matched on data import, then the failure will occur when we try to save an address to the 1:1 account.  The error is something like "Addresses can only be saved to HOusehold and Org accoutns (if enabled)".  But the real issue is that the contact's account is a 1:1 account!  we should test for this, to give a better error message.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwLAAQ" target="_blank">W-008312</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
