### ISSUE TITLE
Manage Household page-- dragging card pops card to top of screen

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1633]
On a Manage Household UI screen
Search for Add Member
Add several members
Click and drag a Member card
Click card a second time and card pops to top of Manage Household area.
Seen in latest Firefox 38.0
See screen shot
![screen shot 2015-06-29 at 2 10 13 pm](https://cloud.githubusercontent.com/assets/204643/8418530/a682abfe-1e68-11e5-8356-1e92e2c7007a.png)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwQAAQ" target="_blank">W-008315</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
