### ISSUE TITLE
Validation on Opportunity Name Settings throwing error 'Variable does not exist: oppList'

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1636]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002BNtS7&fromEmail=1

**Comment by mrbelvedere** [comment]
Included in beta release version 3.46 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.46
