### ISSUE TITLE
Create and make available an unmanaged package that contains all NPSP related reports

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1638]
Example request - https://powerofus.force.com/0D58000002BNbUV

Also related to #1449

**Comment by davidhabib** [comment]
oh shoot.  i entered this one yesterday but I put it directly into AA, not gitHub!  Since it was a work item, not a bug, i thought going first to AA made sense!

**Comment by judisohn** [comment]
I just updated the title here to match exactly what you have in AA so it shouldn't dupe. :-)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZcAAI" target="_blank">W-008170</a>

**Comment by judisohn** [comment]
[This is done. ](https://mrbelvedere.salesforcefoundation.org/mpinstaller/npsp_reports)
