### ISSUE TITLE
make sure Mailing Street 2 is on Address page layout

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1640]
make sure in both the managed package and the DOT that Mailing Street 2 is on the Address page layout.  this should help avoid confusion that this user has: https://powerofus.force.com/0D58000002BNy47

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZbAAI" target="_blank">W-008169</a>
