### ISSUE TITLE
Manage household page: Chrome scrolls to focus element, Firefox does not

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1641]
Seen in Chrome v.43, not in Firefox: 

Click Accounts->Household Accounts->Go
Click first account->Manage Household

Account record immediately scrolls to the bottom of the account page, hiding Add Member and other controls at the top of the page.

**Comment by chrismcmahon** [comment]
Note that this causes the automated browser test to fail in a way that cannot be worked around. The page is in place long enough to enter a character in the Add Members search box, but the buggy scroll to the bottom

**Comment by davidhabib** [comment]
why closed Chris?

**Comment by chrismcmahon** [comment]
Update: so actually what's happening is that the Household Details/Primary Contact field at the bottom of the page automatically gets focus upon loading the page. 

In Chrome, this causes the browser to scroll to the bottom of the page in a small(ish) window, while Firefox does not scroll to make that element visible.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwSAAQ" target="_blank">W-008317</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
