### ISSUE TITLE
Display currency symbols based on ISO code

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1642]
Per [this discussion](https://powerofus.force.com/0D58000002ADqYw) on the manage allocations page, a list of ISO codes to currency symbols is [here](http://www.xe.com/symbols.php).

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwTAAQ" target="_blank">W-008318</a>

**Comment by njjc** [comment]
This was fixed by #2136
