### ISSUE TITLE
People/Address Settings: silent save failure

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1643]
In People/Addresses/Address Settings, edit the settings

Click the checkbox for Enable Automatic Verification. 
Do not pick a Verification Service. (Or, if already logged in with values saved in the browser) pick the blank value in the selectbox and re-check the Enable checkbox)
Click Save

On save, enabled setting checkbox is now not enabled. No error message is shown.

Note that whether Auth Token is set or not has no effect on this behavior.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft1AAA" target="_blank">W-008289</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
