### ISSUE TITLE
Lead Conversion Error when merging with Existing 1-1 Contact

### ISSUE THREAD

**Issue by pankaj90** [SalesforceFoundation/Cumulus#1647]
Hello,

  Account model is set as One-to-One and we have overridden standard lead convert button using NPSP lead override page. On converting a lead and trying to merge with an existing Contact, below error is occurring. 

The OWD for Account, Contact & Opportunities is Public Read/Write and this error occurs only when merging lead with an existing Contact and creating a new Opportunity upon conversion. Also viewing debug logs shows that some error occurs when NPSP code tries to create Opportunity Contact Role for the newly created Opportunity but fails to do so and throws below error message as shown in snapshot.

Our Sandbox Org. Id is: 00DN0000000UKyl

![leadconversionerror](https://cloud.githubusercontent.com/assets/3071956/8570548/b4f0222e-259e-11e5-82d9-fe7689b99b47.png)
@njjc Can you please assist.

Many Thanks.

**Comment by njjc** [comment]
Hi @pankaj90, we don't offer support through github, issues in github are exclusively for our work items on this project. We will enter bugs as appropriate when issues are reported on the hub. Please post your question to the [Power of Us Hub](https://powerofus.force.com/).
