### ISSUE TITLE
Add missing NPSP Data Import fields to the page layout and DOT

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1648]

**Comment by judisohn** [comment]
Landing Page for NPSP Resources - double check

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZaAAI" target="_blank">W-008168</a>
