### ISSUE TITLE
As a user, I'd like to use the NPSP Data Import to add/import custom fields to Household account records

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1654]
Power of Us thread: https://powerofus.force.com/0D58000002CGVw2

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ft0AAA" target="_blank">W-008288</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
