### ISSUE TITLE
Health Check should test for Trigger Handler entry problems

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1656]
We had one a group with a ton of duplicate TDTM entries, because they had set Sharing Rules to Private for the Trigger Handler object.

If Health Check can detect Sharing Rules via Apex, it should make sure Trigger Handler isn't private.  If there is no way to do this from Apex, then Health Check could at least detect duplicate entries, which would be indicative of the problem.

**Comment by kbromer** [comment]
I think we need to check for dupes, but I'm wondering if we shouldn't just be enforcing sharing on the actual runtime firing.  It would potentially allow orgs to setup different configurations for different users if necessary.

**Comment by davidhabib** [comment]
I think having different TDTM configs per user would be a disaster.  Very hard to debug and keep in order.  I think it would lead to lots of confusion, data issues, and bug reports.  I would very strongly dissuade us from this direction.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fszAAA" target="_blank">W-008287</a>

**Comment by mpusto** [comment]
Released in November 2015.
