### ISSUE TITLE
All NPSP Settings checkboxes display wrong unchecked state after Cancel

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1658]
For example:

Under NPSP Settings/People/Leads, click Edit
Change the checkbox state from unchecked to checked
Click Cancel

Page displays the checkbox as checked even though it is actually unchecked. 

In order to show the correct (unchecked) state, user has to once again click through NPSP Settings/People/Leads. 

This seems to be true for all checkboxes in NPSP Settings

Note that the opposite is not true; start with a checked state and make the checkbox unchecked, then Cancel: user correctly sees the checkbox checked.

**Comment by kbromer** [comment]
@ceiroa fixed this in HEDA w/ W-008088

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwUAAQ" target="_blank">W-008319</a>

**Comment by kbromer** [comment]
@ceiroa fixed this in HEDA w/ W-008088
