### ISSUE TITLE
Badges!

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/Cumulus#1662]
We've had two potential clients ask for "badges" in the NPSP in the past month, and this is clearly a feature of NGO Connect that is getting traction as a means for creating conditional "alerts" on records inside of Salesforce.  Some form of "pop-up" is also a frequently-requested feature from organizations moving from Raiser's Edge, which has a stronger on-record-based alert system than the NPSP provides or is available through simple Validation Rules and email notifications.

While the NGO Connect implementation of this feature somewhat violates the general rule that the NPSP isn't dependent on Visualforce, it does bring up the conversation on how to better generate conditional visual notifications using per-record data.  So, for future consideration as a new feature and enhancement, here's a rough outline of where these may be helpful:
- Accounts, Contacts, Opportunities, Campaigns as base records for "badges"
- Able to allow predefined (if then) and multiple criteria to produce an image - one or more conditions produces a specific badge
- Can access information on related Object records as part of criteria (e.g. Contact field, Campaign Member Status of a specific type of Campaign Record)
- Able to use custom images from public Documents folder
- Display in platform and Salesforce1 device access

**Comment by cdcarter** [comment]
The folks at PatronTech have implemented badges for a lot of their clients with a simple formula field that displays a custom image stored in Documents and it works great. You can use a Process to trigger a checkbox on the record and have the image display conditionally based on that, or you can build logic right into the image formula. Caroline Renard and I realized recently that they display just fine on Salesforce1 too.

**Comment by BrightStepTracy** [comment]
@cdcarter - thanks! Does that mean that the display is locked in to the standard two-column format on a non-VF Page Layout?  Or have they done something clever with display as well?  It's good to hear that they display on Salesforce1, though -- image-based formulas were my original thinking, but I'm kind of hoping for something more elegant, that could potentially have it's own tab in the NPSP Settings.

**Comment by cdcarter** [comment]
@BrightStepTracy -- Their solution is indeed just using the 2-column Aloha layout, but if you put the badges at the top of the page, it works fine. You can also have them in your compact layouts and mini layouts, which look kinda smooth.

<img width="388" alt="screen shot 2015-07-26 at 11 16 57 am" src="https://cloud.githubusercontent.com/assets/164/8895264/dea9bd22-3387-11e5-93db-fe8c20fe1a5e.png">

A settings based solution could be nice, especially if it could be as flexible as a formula can be.

**Comment by kbromer** [comment]
**lurch: add

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwXAAQ" target="_blank">W-008322</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwaAAA" target="_blank">W-008324</a>

**Comment by mpusto** [comment]
Check out this app from @cdcarter and Beth for badges! http://www.bigthinks.cloud/weathervane

**Comment by kbromer** [comment]
Very cool app, but what really makes the site are the action shots of Beth and Christian here: http://www.bigthinks.cloud/about/  

;)

**Comment by bethbrains** [comment]
Hey @mpusto I have a github account too, yo.... 😝

**Comment by mpusto** [comment]
It wasn't coming up when I tried to mention you. Now it does. @bethbrains

**Comment by dextermilo** [comment]
**lurch: attach W-008322

**Comment by dextermilo** [comment]
Lurch?

**Comment by njjc** [comment]
This has been marked as "Never" internally.
