### ISSUE TITLE
As a newish to Salesforce data import implementer, I'd like additional information on how to access the Configure Data Importer Options

### ISSUE THREAD

**Issue by donners77** [SalesforceFoundation/Cumulus#1665]
In the "NPSP Administrator's Guide to Importing Donor Data" is says on page 22 "Access these configuration options on the NPSP Data Import summary page" but I could not easily locate such a page (I was expecting it to be located under the "NPSP Settings" tab).

I eventually found it (or something like it) under Settings\Develop\Custom Settings\Data Import Settings

It would be helpful to add a comment to the document saying where these settings are located, or if they are on a page that may be hidden due to security permission issues then what to do about it.

**Comment by judisohn** [comment]
Hi @donners77 this comment is better for the Hub. Issues here in GitHub should only be for those things that are directly in the application. Thanks for understanding!

P.S. The Data Import summary page is found when you go to the NPSP Data Import tab and click on a view such as 'To Be Imported' and then the 'Start Data Import' button.
