### ISSUE TITLE
As a newish to Salesforce data import implementer, I'd like a clearer statement of how contact1/2 and account1/2 relate

### ISSUE THREAD

**Issue by donners77** [SalesforceFoundation/Cumulus#1666]
Reading the "NSP Administrator's Guide to Importing Donor Data" it is not entirely clear to me how contact1, account1, contact2 and account2 all relate together.

My understanding is that:
1. contact1 is affiliated with account1
2. contact2 is affiliated with account2
3. contact2 is in contact1's household
4. there is no connection between account1 and account2
5. there is no connection between contact1 and account2
6. there is no connection between contact2 and account1 

Is that correct? 

It might be good to spell this out more clearly in the guide and even provide a diagram.

Kind regards,
Craig.

PS. That's for all your great work on the documentation. I hope these comments are helpful.

**Comment by judisohn** [comment]
Hi @donners77 Please post questions/issues like this on the Power of Us Hub. We reserve GitHub issues for bugs and feature requests that require changes directly to the NPSP code base. Thanks for understanding!

**Comment by donners77** [comment]
Sure. No worries.
