### ISSUE TITLE
BUG: Deleting contact address data generates a blank Address record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1667]
Hub thread: https://powerofus.force.com/0D58000002DMFU3

Reproduced in clean org. Steps to reproduce: 

1. Contact with Address record, no override
2. Edit contact, remove data from Mailing address fields
3. Save

Result is that prior address is set to non-default. New blank record is created as the default record.

Question is whether we should assume that if a contact address is removed without making it an override, does that assume that the account should not have an address as well? And if so, then there should be no default record.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsyAAA" target="_blank">W-008286</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
