### ISSUE TITLE
Upon installation, Opportunity Record Type Exclusion for Rollup fields pull from Contact RT instead of Opportunity

### ISSUE THREAD

**Issue by buzzbold** [SalesforceFoundation/Cumulus#1670]
Hello,
I didn't see an existing case, and this might actually be a Mr. Belvedere issue instead. Might also be lower priority, because it can be worked around by simply editing the settings and choosing valid values.

Just after installation (in an existing org), Health Check shows a Failure for Opp Record Types that are "Invalid". This makes sense, because the Record Type that is invalid is a Contact Record Type, and not an Opp RT at all.

Somewhere, the initial values being set on these Donor Statistics settings is describing the schema for Contact when it intends to describe Opportunity.

![image](https://cloud.githubusercontent.com/assets/5488153/8991188/99941934-36bc-11e5-8a2a-6c8fc94e32f4.png)

Thanks,
Steve

**Comment by davidhabib** [comment]
sounds like our code for initializing empty settings is doing the wrong thing!  thanks for reporting this.

**Comment by njjc** [comment]
Hi Steve, those values pull from old NPSP settings objects, in order to keep settings intact on upgrade. If you had a previous installation of NPSP before upgrading to NPSP 3, then those values were already present in those settings.

**Comment by buzzbold** [comment]
I see. I seem to remember seeing this issue in older versions of NPSP, now that I think about it.

I created a new Sandbox with the old NPSP installed to create a checklist for myself before performing an upgrade for Production. No data was brought over; but if this was a Custom Settings object, I think those values DO come over with the deployment. Does that still sound consistent with your thinking? If you would like me to try anything, I'm happy to. Otherwise, thanks for the response.

**Comment by njjc** [comment]
Custom settings values seem to be copied over to sandboxes as of Summer '13, so you can check in your sandbox under Setup > Develop > Custom Settings > click 'Manage' next to Households Settings. 

I'm fairly certain that this settings value was an issue before the upgrade, it just never manifested itself since the opportunity record type didn't exist, so there was nothing to filter. Issues like this are raison d'etre for Health Check, so it's great that it caught it!
