### ISSUE TITLE
Unpredictable error reporting in NPSP Data Import

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1672]
When Data Import encounters an error from Salesforce in updating Account after it's created (such as after Address record is inserted due to a field that the Account address fields can't accept) the error is reported as a failure on the first record in the batch, rather than on the record where the error is actually located.

**Comment by davidhabib** [comment]
@judisohn here's the issue we hit again at Dreamforce.  glad we didn't forget to put it in gitHub.  we just hadn't pulled it into AA!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
