### ISSUE TITLE
Household Address record is not created when converting a lead

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1673]
thread: https://powerofus.force.com/0D58000002EHe9L

Reproduced when converting a lead with an address and using 'Self' as the Company. NPSP Settings set at defaults.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
