### ISSUE TITLE
"Enable Automatic Verification" disabled by default

### ISSUE THREAD

**Issue by Zosoled** [SalesforceFoundation/Cumulus#1674]
Since this feature engages other services that may cost money, might it be helpful to NOT enable automatic verification calls by default? In my case, I was testing the verification service while someone else was importing contact records, and we went through a large number of SmartyStreets API calls before I was able to uncheck the "Automatic" box.

**Comment by davidhabib** [comment]
I just looked at our code and we do initialize it to disabled on install.  The user has to enable it in order to enter their service credentials.  Not sure what you would have us do here!

**Comment by Zosoled** [comment]
Ah, I should look closer first. Never mind.
