### ISSUE TITLE
API to detect NPSP version number.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1675]
A simple reimplementation of [these methods](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_version.htm) in a global class.
[Per this hub thread.](https://powerofus.force.com/0D58000002EIWTJ)

**Comment by davidhabib** [comment]
that doesn't fully solve the issue picnet asked about.  having the api is good, but that only works for those who have code that are extensions to NPSP (or unmanaged code), who can call the api.  Ryan was asking for a foolproof way to figure out if 3.0 is installed just by querying for a field.  V4S and A4S do this same thing.  I think he can query for any npsp added field on Account. there are a bunch of them.  I'll comment on the hub thread.

**Comment by kbromer** [comment]
You can SOQL the ApexClass table, there's a 'Prefix' column, just do a [select count() from ApexClass where Prefix = 'npsp'];

It should work regardless of perms, etc.

**Comment by cozimek** [comment]
Third-party apps that do deep integrations with the NPSP would find it beneficial to quickly and confidently know which specific version of the NPSP an organization is using.  While querying for the appearance of certain fingerprints like fields and Apex classes is okay, it requires varying queries to determine which version of the NPSP you're integrating.  A potential solution that allowed for a simple query to a custom setting or other applicable fingerprint would be fantastic.

**Comment by kbromer** [comment]
Fair enough - FWIW though, that 'npsp' prefix query will only return a count if the 3.x+ version is installed

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZZAAY" target="_blank">W-008167</a>

**Comment by cozimek** [comment]
Many thanks everyone!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.53 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.53
