### ISSUE TITLE
Make action labels in Relationship window translatable.

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1677]
From owiener:

I see now the relationship viewer working in french in my NPSP 3 sandbox ! Thanks again to everyone. As a last touch for the non-english users, would it be possible to make the roll-over links translatable as well, ie "View Contact Record", "Create New Relationship" and "Re-Center on This Contact" ?

![image](https://cloud.githubusercontent.com/assets/908119/9174508/1f4ceecc-3f35-11e5-9d37-6bd750c9c6b0.png)

if you can't see the image, it is in issue #968

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwdAAA" target="_blank">W-008327</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 12) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
