### ISSUE TITLE
Spanish translations need correction & updating

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1679]
Hub thread: https://powerofus.force.com/0D58000002EHfgV

- Affiliation package almost all translated, missing new fields and a bug needs to be fixed
- Households is partially translated. 
- Recurring Donations is partially translated. 
- Contacts & Organizations is partially translated. Payment fields, payment related fields in opportunities and other opportunity fields are not translated. 
- Nonprofit Starter Pack is not translated (No translations for Batch, Addresses, Settings, etc)
- Relationship Package is not translated

In this document you will see the fields that are missing for the first packages (and the Bug I mention in the Affiliation package)
https://docs.google.com/spreadsheets/d/1gbeRyUF1xFLwmdg3l1PAN-hfL37CoX2dmpEgZ9uCMV4/edit?usp=sharing

**Comment by judisohn** [comment]
**lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fgvAAA" target="_blank">W-008201</a>

**Comment by mrbelvedere** [comment]
Included in production release version 3.73
