### ISSUE TITLE
Account Primary Contact field is missing from French in Translation Workbench

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1681]
Hub thread: https://powerofus.force.com/0D58000002EKCTP

**Comment by kbromer** [comment]
Its there - it even has a translation already: 


![image](https://cloud.githubusercontent.com/assets/926530/9224702/85973ac2-40d2-11e5-823d-69db6d020b3b.png)

**Comment by owiener** [comment]
@kbromer Hi Kevin, how do you get the Package field ? I can't see it on my org:
![translate problem](https://cloud.githubusercontent.com/assets/8507011/9224790/6a21dfee-4105-11e5-83b9-68d858d06a46.JPG)

**Comment by kbromer** [comment]
'Override', not 'Translate'

**Comment by judisohn** [comment]
@kbromer Right, but it's not there in Translate (when that field appears for other languages). If it's overridden, wouldn't it be that way for everyone and not just those who have their language set for French?

**Comment by kbromer** [comment]
If its already translated and available for the language (which it is for French), you can only override the existing translation.  

Its there for anybody who is assigned that language.

**Comment by owiener** [comment]
@kbromer thanks for your help, I never pay attention to that Override translation element
