### ISSUE TITLE
Option to exclude an Address record from verification

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1686]
Hub thread: https://powerofus.force.com/0D58000002FFDL3

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fwgAAA" target="_blank">W-008330</a>

**Comment by cdcarter** [comment]
+1

**Comment by mrbelvedere** [comment]
Included in beta release 3.114 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.114

**Comment by cpolcyn** [comment]
Reverted from master. See https://github.com/SalesforceFoundation/Cumulus/pull/2855
