### ISSUE TITLE
Opportunity Naming Settings validation shouldn't rely on contact/opp data existing

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1687]
From the hub: https://powerofus.force.com/0D58000002F96ew

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZYAAY" target="_blank">W-008166</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 11) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
