### ISSUE TITLE
Enable 'Require CSRF protection on GET requests' for CON_DeleteContactOverride

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1688]
This setting is specifically for this purpose per the 8th point of [this doc](https://help.salesforce.com/apex/HTViewHelpDoc?id=pages_creating.htm&language=en)

**Comment by mrbelvedere** [comment]
Included in beta release version 3.49 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.50
