### ISSUE TITLE
Support multi-language orgs in Opp Record Type settings & rollups

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1693]
From owiener as a comment on issue #968 

from your post dated October 2014, 2, you said: "As for the the record type issue, the current settings are storing the record type's name (not devname), which can get translated. The code then tests against name. So if you save your membership record type setting in French, then the rollups will work correctly in a French instance. You get problems, as reported above, when the setting is saved in one language, and then the code is run from another language. The fix for this would be to save all picklist and recordtype settings by their underlying value (for picklists) and DevName (for recordtypes), and always that those in the code. Unfortunately, this would break current user's settings where the saved setting doesn't match."

Did you progress on this one ? The solution you proposed last year (ie translate the record type in french on the english translation) won't work when we use a second language. I though I could create a new record type (which would be the equivalent of the english one), then in NPSP Settings > Donations > Donor Statistics >Opp Rec Types Excluded for Contact Rollup add that new record type, and re run the rollup donations batch. But that produce a very strange result: the donation linked to the english record type are back in the contact donation total (but should be in Memberships total), and the one using the newly created record type only appears in the Household donation totals (it doesn't appear in the contact donation totals and not in the membership totals) ?

I'm sorry to bother you with this subject again but I really need a solution to work with 2 or more languages.

**Comment by davidhabib** [comment]
See my early comment on issue #968 for an outline of the work this fix would entail.

**Comment by owiener** [comment]
@davidhabib Your follow-up is greatly appreciated ! Thanks !

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsxAAA" target="_blank">W-008285</a>

**Comment by owiener** [comment]
Hi there,
thanks for the follow-up. Any idea when this will be in place ?
All the best,

O. Wiener

PS if i click on the link W-008285, i'm having the following msg: "Your IP address is not trusted. Verify your network / VPN connection."

**Comment by judisohn** [comment]
@owiener The tracking links in issues are to our internal project management system.

**Comment by owiener** [comment]
Thanks Judi for that answer !

**Comment by davidhabib** [comment]
Here's the outline of a potential solution, taken from the discussion in #968.  Note that this is a large amount of work that covers many settings, and the approach described here has not been tested.

I investigated changing the record type settings to change from storing the recordtype Name, to store the recordtype Id. The thought being we could have the settings facade detect when loading old settings that weren't Id's, and we could try to query for the correct Id. I do believe we could make this work, but it will be a non-trivial change. here are the things that would have to be done:

1. the facade would need to map non Id's to Ids.
2. code using the properties (rollup code) would need to change to expect these as Id's and use them accordingly.
3. the Settings pages that display these would need to handle displaying in readonly mode the record type name from the Id.
4. the settings pages would need to change to use Id's in the multiselect listboxes, not Names.
5. the installation script would need to change to setting the defaults for these properties to Id's, not Names.
6. several test cases would need to be modified to either store Id's, unless they are going through a wrapper we could change to handle the mapping.
7. The same steps for the picklist value settings apply as in #3 above. We'd need the settings facade to verify each item against the list of picklist values, and see if it matched either the name or label, and then save the label. Similarly, we'd have to modify code to test against labels, and settings pages to display labels when they hold the value instead.

**Comment by mpusto** [comment]
Thanks @davidhabib for the clear steps. I am a bit concerned about item 4 though. I can imagine that being a poor user experience as users won't know which Id to use (for example in exclusions for roll ups) and telling them to go find it would be a much worse experience than it is now.  Do you have any ideas for a good workaround for that?

**Comment by davidhabib** [comment]
The multiselect listboxes would still display localized names.  it's just that internally they would be storing the recordtype Id's, not names.  sorry if that wasn't clear!

**Comment by mrbelvedere** [comment]
Included in beta release 3.79 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.79
