### ISSUE TITLE
Household naming settings don't exist on fresh install.

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1694]
To reproduce: 

* Do a fresh install or uninstall/install in the manner of this Jenkins build: http://ci.salesforcefoundation.org/view/uat/job/Cumulus_uat_browsertests_deploy/
* Navigate to a Managed Household URL, for example https://npsp.n34.visual.force.com/apex/HH_ManageHHAccount?scontrolCaching=1&id=account_id

* See error "npsp:DML currently not allowed" as a result of the call to

13:58:16.099 (99969874)|DML_BEGIN|[419]|Op:Upsert|Type:npsp__Household_Naming_Settings__c|Rows:1

* Go to NPSP Settings/People/Households/Household Settings, click Edit and click Save
* Navigate to the Manage Household URL again. 

* No DML error appears

**Comment by njjc** [comment]
Household_Naming_Settings__c need to be added to the post [install script](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/STG_InstallScript.cls#L84).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.50 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.50
