### ISSUE TITLE
UTIL_Namespace.StrTokenRemoveNSPrefix incorrectly removing npsp__ from other parts of field names

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1695]
[This replace](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_Namespace.cls#L92) should only be happening if the string starts with npsp__, otherwise fields named "foo_bar_npsp__c" will be incorrectly modified.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.50 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.50
