### ISSUE TITLE
Honor/Memorial Fields for Recurring Donations/Opportunities

### ISSUE THREAD

**Issue by BrightStepTracy** [SalesforceFoundation/Cumulus#1696]
This is a simple customization request, but working with Luminate again reminds me that they actually have thought this through a bit.  This same set of fields existing on both the Recurring Donation and Opportunity Objects (with pre-existing custom mapping, if this is even possible) would enable this quickly for folks without consulting partners needing to spend time building them.
![honor memorial](https://cloud.githubusercontent.com/assets/13025357/9619850/bf08fbe6-50c8-11e5-9ce6-07a3f77c158c.jpg)

**Comment by judisohn** [comment]
**lurch: attach W-007190

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cTjAAI" target="_blank">W-007190</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.61 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.61
