### ISSUE TITLE
If a WFR field update updates the Open Ended Status field on a Recurring Donation to Closed, triggers do not fire to clean up opps 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1699]
https://powerofus.force.com/0D58000002FGsPq

theory to investigate from @njjc: triggers still fire a second time after workflow field updates could be in the same context and our code has a static flag set to prevent recursion so it runs it the first time, then thinks it's done and doesn't try the second time around. firing order does triggers first, then workflow rules then if the workflow has a field update, it fires triggers a second time so if those are all in the first context, first run of triggers sets static flag second run of triggers doesn't fire since the static flag is set.

**Comment by njjc** [comment]
Edited from chat stream of consciousness for clarity ;)

Firing order does triggers first, then workflow rules, then if the workflow has a field update, it fires triggers a second time. They could be firing in the same context; our code has a static flag set to prevent recursion. When runs it the first time, it sets the flag, then doesn't try the second time around as the flag has already been set.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fswAAA" target="_blank">W-008284</a>

**Comment by judisohn** [comment]
See related #2591

**Comment by mrbelvedere** [comment]
Included in beta release 3.104 (Beta 3)
