### ISSUE TITLE
getPackageVersion and updatePackageVersion

### ISSUE THREAD

**Issue by arangari** [SalesforceFoundation/Cumulus#1706]
hi,
i came across the link below. 
http://salesforce.stackexchange.com/questions/13561/how-to-get-a-list-of-the-managed-packages-including-version-numbers-installed.

it is referring to getPackageVersion and updatePackageVersion in answer by Jason Lantz. 

However I couldnt find 
https://github.com/SalesforceFoundation/Cumulus/blob/dev/lib/ant-salesforce.xml . 

I also searched for it in the repository. 

Is it moved? Could I have pointers to it?

Regards,
Amit

**Comment by jlantz** [comment]
The build scripts that used to be part of this repository have been separated out into CumulusCI:

https://github.com/SalesforceFoundation/CumulusCI

The previous contents of ant-salesforce.xml have been moved to here:

https://github.com/SalesforceFoundation/CumulusCI/blob/master/build/cumulusci.xml
