### ISSUE TITLE
In the Relationship Viewer, clicking 'Create New Relationship' does not carry the Contact to the new Relationship record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1709]
Household Model, click on a contact's 'create new relationship' link in the viewer and the new relationship record is completely blank. Should carry the Contact's name across to the Contact field.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsrAAA" target="_blank">W-008282</a>

**Comment by coriobriensfdo** [comment]
New Issue created for Lightning only issue.
