### ISSUE TITLE
As an admin, I want to set Open-Ended Recurring Donations to a schedule other than Monthly

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Cumulus#1710]
Not all open-ended commitments are monthly. In fact for membership scenarios it is common that the commitment be annual (yearly). It would be great to have a setting for Open-Ended style recurring donations to create future pending donations a year out rather than solely monthly as is today

**Comment by judisohn** [comment]
Hi Brian, You can already do this: https://powerofus.force.com/articles/Resource/NPSP-Create-Custom-Installment-Periods-for-Recurring-Donations - is that what you mean?

**Comment by brianpickett** [comment]
Hi Judi,
The use-case I am trying to enable is where a new Opportunity is created as-needed on an annual basis.  Are you saying the following set-up will create just 1 opportunity now, followed by a new opportunity in 1 years time?:
Open Ended Status = Open
Installment Period = Yearly
Installments = 1

I'm having a tough time testing this. Thanks.

**Comment by judisohn** [comment]
If you are creating an Open Ended Recurring Donation, you should not be entering anything for the Installments. That is generated automatically. If you set the Installment Period to Yearly, then the future opportunities should be automatically generated based on the Forecast Months setting in NPSP Settings. See https://powerofus.force.com/articles/Resource/NPSP-Create-a-Recurring-Donation

**Comment by brianpickett** [comment]
Ok, thanks for clarifying. I'm familiar with that functionality and its not the user-experience I had in mind.  I'm on the fence about whether to take this any further as it seems using Recurring Donations for annual renewals is a bit of a hack anyway.
