### ISSUE TITLE
Affiliations should be re-parentable

### ISSUE THREAD

**Issue by JimBTek** [SalesforceFoundation/Cumulus#1711]
Hello! 

I am at a crossroads with NPSP and importing web form submissions. I help several nonprofits that do a lot of resume and job application collecting, and we are pushing this data through Formstack straight into NPSP3. 

My Issue is that if a person freeforms in the account name of the Organization they are affiliated with and it doesn't match an existing it errors out, and if I manually override the Account name and put it in a holding name, then the Organization can never be corrected in NPSP3. It would be ideal to allow Affiliation to be re-parentable and not a lot of work to check that box. 

If you are thinking "Well you should do web-to-lead" my other issue is that you cannot map lead fields to the Affiliation object, because we have custom fields on Affiliations like School, major, graduation date, GPA, that should be part of a person's affiliation with a university, vs. on their contact record. I am opening another issue to request this.  Thanks!!!

**Comment by judisohn** [comment]
Hi @JimBTek Unfortunately, this isn't something that will be possible as it will require us to change field definition in a way which we currently can't do in a managed package. I'll leave this open as we can consider it once the platform would allow us to make the change, but I wanted to set the expectation that it won't be something we can do in the near term.

**Comment by JimBTek** [comment]
Hi @judisohn ok, since it's managed this can never be changed?

**Comment by judisohn** [comment]
Never is a strong word. For right now and honestly for the foreseeable future, we can't do anything with that field.

**Comment by JimBTek** [comment]
@judisohn thanks, i totally understand. Is there a way people are getting around all this though? To do web to salesforce with custom affiliation fields? web to lead won't let me convert custom affiliation fields and going straight to affiliations the end user would have to type in the exact org name to not error out. 

Perhaps with building a form using salesforce sites?  

I really appreciate the help. Like i said both small nonprofits i am helping get a lot of job/internship applications and help place people so they have a constant need for this.  

I think the most appropriate fallback is web-to-lead and moving the affiliation custom fields to the contact or opp.

**Comment by cdcarter** [comment]
@JimBTek -- a few thoughts that might help your use case (though I agree with this issue):
* as you mentioned, a Force.com Site with a custom form could do a lot, but you should also consider the various 3rd-party form tools that give steep NPO discounts.
* depending on how sad this is for you, a clone, edit, and delete procedure might just be the trick.

This may be worth discussing further over on the Hub!

**Comment by JimBTek** [comment]
I'm using Formstack, but it's not going to autocomplete the Org name from Salesforce to my knowledge to make sure the Org name is correct. 

It seems like the only fix is a custom lead conversion page or to not have custom fields on affiliations.
