### ISSUE TITLE
Make contact email addresses external IDs again

### ISSUE THREAD

**Issue by JimBTek** [SalesforceFoundation/Cumulus#1713]
The standard contact email field in salesforce is an external id, but with NPSP it is replaced. Is there a reason why the new email fields cannot be external ids for easy importing of data? This makes using data loader problematic, but still works with dataloader.io.  I understand there is a NPSP importer, but we have a lot of custom fields we are importing as well. 

I don't quite know enough yet to find this in the code and submit a pull request.

Thanks!!!

**Comment by davidhabib** [comment]
I just verified that we cannot change the Email fields in the npe01 package to mark them ExternalID.  Even if we could, I don't think we'd do it for the following reasons:
1. each object is limited to 7 external id's
2. each external id creates an index, and each object is limited to 13 indexes.
3. some organization's constituents share email addresses, and marking the as external id's would prevent this information from being tracked.
