### ISSUE TITLE
Payment should be auto-created if no existing Payment record and Opportunity Amount changes to > 0 from 0 or null

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1714]
This would allow compatibility with Opportunity Line Items (Products).

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZQAAY" target="_blank">W-008162</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
