### ISSUE TITLE
Updating Relationship Status field should update the reciprocal relationships' status.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1715]
Fixing #1564 introduced this issue: updating the status no longer updates the reciprocal status.

[Per this hub thread.](https://powerofus.force.com/0D58000002GMIWT)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZWAAY" target="_blank">W-008164</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 11) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52

**Comment by keithmancuso** [comment]
Hey ya’ll I know this issue is Long closed but I am seeing this behavior again.  Any ideas what might be causing it?

**Comment by judisohn** [comment]
@keithmancuso Best bet is to post in the [NPSP Group in the Hub](https://powerofus.force.com/0F980000000CjRe) for further troubleshooting. Thanks!
