### ISSUE TITLE
Sharing settings prevent query of account, causes null object error

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1717]
At [this line](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ACCT_IndividualAccounts_TDTM.cls#L195) and in related areas, the account query returns now rows despite having valid account IDs due to sharing settings. Make sure map.containsKey(c.accountid) before referencing map.get(c.accountid).

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZVAAY" target="_blank">W-008163</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 11) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
