### ISSUE TITLE
Possible upgrade problem in Winter '16 with Enhanced Notes enabled

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1724]
FYI @jlantz - I don't have a way to replicate/test this in another org until Winter '16 is released to production, but wanted to note it (no pun intended) just in case we get reports from others.

Winter '16 includes the GA release of enhanced Notes http://docs.releasenotes.salesforce.com/en-us/winter16/release-notes/notes_admin_setup.htm

In a gs0 org with Winter '16 with Enhanced Notes enabled (Setup > Build > Customize > Notes > Notes Settings) NPSP could not be upgraded from 3.48 to 3.51 due to this error (System Administrator profile):

(NewNote) Insufficient Privileges
You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.

After disabling Notes, the upgrade worked without error.

**Comment by kbromer** [comment]
I think its one (or both) of these two known issues (probably the first): 
https://success.salesforce.com/issues_view?id=a1p30000000eMpcAAE
https://success.salesforce.com/issues_view?id=a1p30000000E17HAAS

**Comment by judisohn** [comment]
Yup sounds like it's this one https://success.salesforce.com/issues_view?id=a1p30000000eMpcAAE thanks - once confirmed in next release I'll close issue.
