### ISSUE TITLE
Blanking out a household account naming field doesn't recalculate name

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1727]
e.g. [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/HH_HouseholdNaming.cls#L342) it only calculates if it's nulled AND auto naming is enabled.

**Comment by kbromer** [comment]
That's WAD I think, you need to use the replacement text value (IIRC 'REPLACE') to clear the custom name override- otherwise it'll overwrite user created names

**Comment by njjc** [comment]
Behavior seems strange and Judi agrees. Here's how I think it's working:

Scenario 1: I set a household's setting to "Don't auto calculate informal greeting." Then, I blank out that informal greeting.
Result: the code changes my setting to "DO auto calculate informal greeting", then auto calculates it.

Scenario 2: I want informal greeting to be always calculated. I blank out informal greeting. 
Result: It stays blank.

**Comment by kbromer** [comment]
Hmm.... did we generate checkboxes for that at some point? I wonder if its related to that.  Otherwise scenario 2 is a regression that should've been caught at some point

**Comment by njjc** [comment]
We didn't do checkboxes yet, that was related to contact naming exclusions, but Judi and I discussed implementing that here as well. I think this "works as designed" but that the design was weird.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fVJAAY" target="_blank">W-008159</a>

**Comment by judisohn** [comment]
Probably related: https://powerofus.force.com/0D58000002TvVr6

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
