### ISSUE TITLE
bug: affiliation mass upsert with primary checked not updating primary affiliation on contacts

### ISSUE THREAD

**Issue by RBLopez** [SalesforceFoundation/Cumulus#1728]
We have set up an integration that is upserting affiliations in batches of up to 100 records. Most of these affiliations have the primary checkbox set to true, but the contacts associated with them do not have the primary affiliation field filled in with the appropriate account. I haven't gotten any error notifications from NPSP nor seen any errors logged.

If I manually toggle the primary checkbox on one of these affiliations then the primary affiliation field on the contact is updated appropriately.

**Comment by davidhabib** [comment]
please post stuff like this on the Hub.  we then will put an issue into gitHub if we feel it is something in our code that needs attention.
