### ISSUE TITLE
When creating a monthly recurring donation on the 30th or 31st of the month - only 11 opportunities get created

### ISSUE THREAD

**Issue by merishashim** [SalesforceFoundation/Cumulus#1729]
When creating a monthly recurring donation on the 30th - only 11 opportunities get created - Opportunity for February doesn't get created.
ie, I created a recurring donation on September 30th for the above issue to occur.

When creating a monthly recurring donation on the 31st - only 11 opportunities get created.
ie, I created a recurring donation on August 31st, the August 31st opportunity was created, then September opportunity was missed, then October 1st and sequentially til July 1st was created.
  
Currently in version 3.51

**Comment by merishashim** [comment]
Just to add more info, the opp creation logic is failing to identify end-of-month dates for February. So I if I donate today (Sept 30), it creates opps for the 30th of each month until it gets to February.  It fails to validate February 30th, and instead of going backwards, bumps the opp date to March 1.  It then uses the 1st as the recurring date for the remainder of the opportunities that need to be created.  However, it fails to compensate for the skipped February by adding one more opportunity at the end, so we end up with 11 instead of 12 donations.

**Comment by njjc** [comment]
Thanks for the detective work @merishashim! I'll look into it.

**Comment by njjc** [comment]
@merishashim what's your open ended status set to?

**Comment by jlangelaan** [comment]
@njjc Its set to open.

**Comment by davidhabib** [comment]
related to fix for closed issue #1589 ?

**Comment by davidhabib** [comment]
related thread on hub: https://powerofus.force.com/0D58000002J1Upw

**Comment by jlangelaan** [comment]
Can someone help me understand how a custom open stage might affect the RD functionality?

I am reviewing existing RD documentation and this section stands out to me.  

We have a flow that goes like this:
- PayPal custom integration finds a Pledged record with a Payment Token record
- Attempts to process the donation, but it fails (for what ever reason)
- The payment record is marked as "Failed"
- A workflow changes the Opp stage from "Pledged" to "Declined" (an open stage, 0%, omitted from forecasting).


![image](https://cloud.githubusercontent.com/assets/14916309/10227923/0f573356-6825-11e5-8ac3-191ee04760b7.png)

**Comment by davidhabib** [comment]
since you are setting it to an open stage (declined), any change to the RD where NPSP needs to recreate the opps will blow away open Opps and recreate them.  So there is some risk with this.  If Declined was a closed stage, NPSP would leave it alone.

**Comment by jlangelaan** [comment]
Adding one other piece of information - the "Next Donation Date" is not updating as expected. Just completing some analysis to confirm if this is consistent. This likely relates to the Decline open stage.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
