### ISSUE TITLE
cleanupContactRelationships method in REL_Relationships_TDTM not used?

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1744]
I have not found any references to this method. Should we remove it?

And if we delete that one, we can also delete getRelKey right below.

**Comment by kbromer** [comment]
Contact Merge? 

https://github.com/SalesforceFoundation/Cumulus/search?utf8=%E2%9C%93&q=cleanupContactRelationships

**Comment by ceiroa** [comment]
Funny, Eclipse didn't find that reference. But yeah, it's there.
