### ISSUE TITLE
DI records with Contact and Campaign info should insert a CampMem record

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1748]
It would be awesome if Data Importer would add a new CampaignMember record if Contact1 fields are filled in and Campaign is also filled in - whether or not Opp fields are also filled in.

Two common use cases would be satisfied:

1. When an Opp is inserted whose Campaign field is filed in, then the Contact associated with the Opp should be added as a CampMem.  This case is so common that the code to do it was presented at last year's DF.

2. When a list of Contacts that are collected from an Campaign event (like a house party or seminar) need to be added as Campaign Members, even though they are not (yet) donors.

**Comment by judisohn** [comment]
This has come from time to time, and we do have a story in our internal tracking for this and I'm adding this issue there to combine it (below doesn't make sense, but trust me - that's what it does)

**lurch: attach W-007255

@johnfine Question - is there a reason why you wouldn't want the Primary Contact of any Opportunity to be added (or updated to responded state if they're already there) as a Campaign Member of the Primary Campaign? Why should it just be as part of the Data Import tool?

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cY1AAI" target="_blank">W-007255</a>

**Comment by johnfine** [comment]
@judisohn No reason, just the opposite - any Opp added or updated in the SF UI that has a non-blank Campaign field should cause an insert of the Primary Contact as a CampMem.  Ah, I see what you are getting at - if NPSP had this functionality, then DI doesn't have to do the CampMem insert if Opp fields are present in the import data - importing the Opp will cause a CampMem insert.  Absolutely, that's the better solution.  But I would still request that DI add CampMems if Contact fields and Campaign are present, but Opp fields are not present.

**Comment by judisohn** [comment]
@johnfine I see the difference you mean now. You're talking about for marketing or event purposes only having nothing to do with opportunities. Interesting. Not sure how much of a lift it will be to separate Campaigns and Opportunities in the Data Import process, but I can see that it's a different issue so I'll separate it.

** lurch: detach W-007255

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g0yAAA" target="_blank">W-008356</a>

**Comment by cdcarter** [comment]
Is this closed from the latest campaign / data importer stuff?

**Comment by judisohn** [comment]
Thanks, @cdcarter!
