### ISSUE TITLE
id values not unique on page /apex/npsp__CONV_Account_Conversion

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1752]
Two checkboxes on this page have the same value for id, 'check-required-fields'. This violates the W3C standard that says that id values should be unique per page. (And it makes automated UI testing inconvenient. )

![screen shot 2015-10-16 at 11 36 52 am](https://cloud.githubusercontent.com/assets/204643/10550212/80777c2c-73fa-11e5-8fa6-7b5f6395138c.png)

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g2zAAA" target="_blank">W-008373</a>
