### ISSUE TITLE
Error editing NPSP Settings: GAU Allocations

### ISSUE THREAD

**Issue by brianpickett** [SalesforceFoundation/Cumulus#1753]
I am at the NPSP Settings tab, attempting to edit the GAU Allocations section.
The response I get is "Collection size 1,256 exceeds maximum size of 1,000."

**Comment by davidhabib** [comment]
do you get the error when you click the Edit button on the GAU Allocations page, or just when you first click on NPSP Settings tab?

does the GAU Allocations page display in edit mode with Cancel and Save buttons at the bottom?

How many General Accounting Units do you have in this org?

**Comment by njjc** [comment]
Sounds like you could have over 1k active GAUs, and the page is trying to generate a list of all active GAUs to add to a select list to choose a default. If you do indeed have the need for that many GAUs, maybe you can mark some legacy ones as inactive?

**Comment by brianpickett** [comment]
Its on the page when I hit Edit under GAU Allocations.  Bingo on the 'over 1,000 active GAUs.' There are 1,200 active GAUs. We'll try to pare them down.  Thx.

**Comment by njjc** [comment]
That must be a limitation of picklists. I never considered anyone would have over 1k GAUs, but those are obviously famous last words. I'll add a 1k limit to the query so the page loads. Thanks for reporting!

**Comment by judisohn** [comment]
@njjc Would it be possible to have a lookup/search field instead?

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g5KAAQ" target="_blank">W-008403</a>

**Comment by njjc** [comment]
That would be possible, and probably preferable. I'll create another story.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.53 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.53
