### ISSUE TITLE
Deleting a relationship without a reciprocal causes null id error.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1755]
[This query](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/REL_Relationships_Con_TDTM.cls#L147) can return relationships with no npe4__ReciprocalRelationship__c, which creates an object with a null id. Check for null here.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g4XAAQ" target="_blank">W-008393</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.53 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.53
