### ISSUE TITLE
Contact Merge with unique fields does not work

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1759]
https://powerofus.force.com/0D58000002Kuvxo

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g6IAAQ" target="_blank">W-008415</a>

**Comment by judisohn** [comment]
https://powerofus.force.com/0D58000003KF25z

**Comment by mpusto** [comment]
Based on testing by @mbeaty-sf we have confirmed this issue is resolved.
