### ISSUE TITLE
Manage Household UI page gets error on load in Lightning Experience

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1760]
you get a too many redirects error, and nothing displays.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g8JAAQ" target="_blank">W-008440</a>

**Comment by kbromer** [comment]
Interesting. For me it loads, but certain features don't work like type ahead for Contact search...

**Comment by davidhabib** [comment]
didn't load on Nic's system either.  And what's weird is I thought Judi tested this last month, and either worked, or we did a minor fix.

**Comment by kbromer** [comment]
![image](https://cloud.githubusercontent.com/assets/926530/10623928/931f57b8-7761-11e5-957b-d970c31278c4.png)

**Comment by judisohn** [comment]
@davidhabib @kbromer 

That is strange. Yes, I tested last month and found nothing out of the ordinary. Just tested again, this time in my DE org (before was on gs0) and not only does the page load, but type ahead search works as well. After the sprint let's try and figure out what's different here.

![2015-10-21_05-52-52](https://cloud.githubusercontent.com/assets/4614343/10633417/843b6334-77b8-11e5-906c-f58f056f3768.png)

**Comment by davidhabib** [comment]
just tried and could not reproduce this in 4 separate orgs.
