### ISSUE TITLE
Donor Profile One-Pager

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1763]
As an NPSP user, I want to click a button from a contact or account record to automatically create a one-page PDF donor profile.

**Comment by judisohn** [comment]
Group project from Seattle 2015 Sprint - led by Beth Breisnes.

**Comment by mpusto** [comment]
Stalled due to obscure platform bugs. Also VF page render as PDF is not supported in Lightning and would require complete redesign.
