### ISSUE TITLE
NPSP 2 Contact Delete Override doesn't redirect to NPSP 3 version

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1766]
old visualforce page has <apex:page standardController="Contact" action="{!urlFor($Action.Contact.Delete, contact.id, null, true)}" />

when we recently added a new contact delete override in NPSP 3.0, we should have also updated the old npe01 package to redirect to the new page.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gd2AAA" target="_blank">W-008558</a>
