### ISSUE TITLE
NPSP Data Importer creating duplicate addresses?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1767]
one user reporting this problem.  haven't heard of it before, but in looking at tests, not sure we cover this scenario.  worth adding a test to ensure we don't have an issue.
https://powerofus.force.com/0D58000002KwQ6j

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gr7AAA" target="_blank">W-008592</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
