### ISSUE TITLE
CONV_Account_Conversion has a lot of english language

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1771]
the Household Account Conversion page has a LOT of hardcoded english language that is untranslatable/overridable.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hA5AAI" target="_blank">W-008713</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 12) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
