### ISSUE TITLE
Contact Merge doesn't work if Contact has a lookup to Case

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1778]
The merge controller https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CON_ContactMerge_CTRL.cls#L283 expects lookup relationships to have a `Name` APIname field, but Case has `CaseNumber`

**Comment by judisohn** [comment]
lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gYHAAY" target="_blank">W-008521</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
