### ISSUE TITLE
Manage Allocations page doesn't accept decimals on percent fields

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1779]
Entering 1.1% and 98.9% rounds them down to 1% and 98%. A use case for allowing this is credit card transaction fees.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gZFAAY" target="_blank">W-008532</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.63 (Beta 17) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.63
