### ISSUE TITLE
Manage Household Page has Issues with Large Data Volumes and CPU Usage.

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1780]
A lot of people chiming in here: https://powerofus.force.com/0D58000002BLwVb 

I took a stroll through the code and didn't see anything OBVIOUS but that page has a nice mix of remote and VF actions so I didn't get too far down the well.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gr3AAA" target="_blank">W-008591</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
