### ISSUE TITLE
Non Selective Query Error on Addresses Object in LDV org using REST

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1781]
hub thread: https://powerofus.force.com/0D58000002KwbYE

We started getting the error when the number of records in the Address object reached 99,000+. Operations after that started throwing the Non Selective Query error. There was no issue prior to that.

We have an external integration running a script which is updating/inserting Address records. It is not using the Bulk API. We are using the rest api through the force.com toolkit for .net (https://github.com/developerforce/Force.com-Toolkit-for-NET). 

Inserting and address manually did not cause an issue. Interesting. Please reach out to Tim Whitbeck twhitbeck@bthreesolutions.com at B3 Solutions and set up a time to review the specifics of the API / SDK scripting they are using to push (insert/update) records to SF using the Rest API.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gZyAAI" target="_blank">W-008539</a>

**Comment by twhitbeck** [comment]
David,

We encountered this when issuing an update command with the [Force.com-Toolkit-for-NET](https://github.com/developerforce/Force.com-Toolkit-for-NET). In particular, we called the `UpdateAsync` method with following parameters:
`npsp__Address__c` for object name
the Id of the address
and an object including the follow fields as the record

`Id`
`npsp__Household_Account__c`
`Contact__c`
`npsp__MailingStreet__c`
`npsp__MailingCity__c`
`npsp__MailingState__c`
`npsp__MailingPostalCode__c`
`npsp__MailingCountry__c`
`npsp__Default_Address__c`
`npsp__Address_Type__c`
`Personify_Record_Id__c`
`Personify_Contact_Id__c`
`Personify_Company_Id__c`
`Personify_Added_On__c`
`Personify_Changed_On__c`

That's all the information we have at this time.

**Comment by TGMarcovecchio** [comment]
David:

Is there any progress on this issue?

**Comment by davidhabib** [comment]
So we have now tested in a large data organization with over 155,000 addresses, and we do not get any errors when inserting and updating as many as 200 addresses at a time.  

Unfortunately, we don't use the Force.com Toolkit for .NET and it is out scope for the NPSP team to start trying to debug what this library is doing that issues the non-selective query.  I'd recommend having your developers step into the code for this toolkit, and pinpointing what actual call is being made to Salesforce that hits the error.
