### ISSUE TITLE
Enhance Health Check to provide links to reports showing suspect data

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1782]
At the community sprint we went through all the health check errors, and identified which we could provide a report to.  We need to have a way of providing a link to something that opens a report (and will work in Lightning).

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001ga3AAA" target="_blank">W-008540</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.57 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.57
