### ISSUE TITLE
In LDV Org, non-selective query error from REL_Relationships_Con_TDTM.deleteEmptyRelationships()

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1787]

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gdvAAA" target="_blank">W-008568</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
