### ISSUE TITLE
Store Two Character State Code in Address Verification

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#1788]
I have a client that would prefer to use the two character state code for the verified state instead of the full state name. They're using Cicero, though I believe this is true for Google and SmartyStreets as well. I have to think there are others who would like to do the same.

I see two possible solutions:
1. Build a custom "before update" trigger on the npsp\_\_Address\_\_c object that converts the State value to the two character version. This gets a bit complicated, but the trigger will need to prevent the npsp address verification triggers from running again to re-validate and change the state back. The _change_ here would be to find a way to prevent the trigger recursion (unless there is one in the code base already).
2. Update the ADDR_Cicero_Validator class to pull out the two character state code from one of the candidate response items (since the match_addr response returns the full state name). There would need to be a setting for this as well. Some research is needed to determine if this is possible for SmartyStreets and Google.

Of course, I'm open to other solutions for this as well; and I'm willing to build one of the above to contribute to the starter pack.

**Comment by kbromer** [comment]
Could you just re-implement the validator to convert the state abbreviation to the full name, then back again before writing it?

**Comment by force2b** [comment]
I don't think we'd need to convert it to the full name to send it for validation (Cicero seems to accept with the 2 character version). It's just the writing to the State field that would need conversion. Three questions though:
1. Are you thinking of using a table of State Code to State Name values for the conversion, or try to pull  it out of the candidate response (assuming it's there)?
2. Is this a change you'd want me to make for all the verification services, or can I just make it for Cicero?
3. What's the best approach to handle this as an NPSP Setting?

**Comment by kbromer** [comment]
1.  That would be up to your implementation
2.  You can just swap out the existing validator with one of your own that would be custom for your client, I don't think its a change we'd want to make across the entire install base
3.  See above :)

**Comment by force2b** [comment]
Good point. I completely forgot that the implementation supports a custom verification service. That will definitely be my approach. Thanks.
