### ISSUE TITLE
BUG: Deleting a single contact in a household deletes entire household/all contacts in HH

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1790]
POU thread: https://powerofus.force.com/0D58000002M0DI8

Can't replicate in a dev org with 3.53, but was able to reliably reproduce behavior in new trial org with 3.51 - not sure why trial doesn't have latest production release?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gp6AAA" target="_blank">W-008569</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.54 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.54
