### ISSUE TITLE
Manage Household "New Contact" function needs to implement duplicate management features

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1792]
[Per this hub thread.](https://powerofus.force.com/0D58000002M0Lwk) We need to implement the "warn but allow save" functionality [outlined here](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_Datacloud_DuplicateResult.htm).

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gpGAAQ" target="_blank">W-008571</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
