### ISSUE TITLE
As a user, I want to use the Primary Contact field on Opportunity for non-Household Account gifts

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1793]
POU thread: https://powerofus.force.com/0D58000002M0Os2

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gpkAAA" target="_blank">W-008578</a>
