### ISSUE TITLE
Contact Merge Parameter Support

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1796]
Partner/Customer request: 

Ideally what we want is to be able to call the Page like this:
/apex/CON_ContactMerge?cid1= 0039000001i32ZyAAI&cid2= 0039000001kyd7CAAQ&step=2
Where the cid1, cid2, cid3 are the contacts to merge, and step=2 indicates that we shodul skip the search step on the standard screen.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gq9AAA" target="_blank">W-008582</a>

**Comment by cdcarter** [comment]
So this actually already exists! You can pass in a `mergeIds` comma separated list. 

```/apex/CON_ContactMerge?mergeIds=0031500001b35hI,0031500001b35hN```

Was the partner/customer requesting that cid1/cid2 syntax for a specific reason that would make more sense?

**Comment by kbromer** [comment]
<facepalm> Totally. https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CON_ContactMerge_CTRL.cls#L204

</facepalm>
