### ISSUE TITLE
BUG: If NPSP Data Import has custom checkbox field on Opportunity, an Opportunity will be created even if false/unchecked and no other Opp data mapped

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1797]
POU thread: https://powerofus.force.com/0D58000002M1JfO (replicated in clean org)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gqTAAQ" target="_blank">W-008586</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
