### ISSUE TITLE
Allocations Settings: Replace GAU picklist with lookup

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1799]
When large numbers of GAUs exist, the picklist is unwieldy, and is also limited to 1000 values.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gwqAAA" target="_blank">W-008632</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
