### ISSUE TITLE
If an Account External ID is selected in Data Import Settings, that should control the Account Matching behavior rather than name alone

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1802]
Hub thread: https://powerofus.force.com/0D58000002MwUzK

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gzuAAA" target="_blank">W-008638</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
