### ISSUE TITLE
Test fails if org does not have 'COO' UserRole record

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#1806]
The test data utility method UTIL_UnitTestData_TEST.CreateNewUserForTests() references the UserRole 'COO'.  In orgs where there is no such UserRole record, any tests that use this test data method fail.

This method should not assume the existence of the 'COO' UserRole.

**Comment by dospromptman** [comment]
**lurch: attach W-008360

**Comment by dospromptman** [comment]
sudo **lurch: attach W-008360

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001g1NAAQ" target="_blank">W-008360</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
