### ISSUE TITLE
When deleting list of relationships, deleting of reciprocal relationships fail if list contains mutually referential relationships

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#1812]
When deleting relationships, it is expected that the reciprocal relationship will also be deleted.

However, when deleting a list of relationships where at least two of the relationships in the list are reciprocals of each other, none of the remaining reciprocal relationships will be deleted.

This seems to be caused by an issue in REL_Relationship_TDTM where trying to delete records that are already deleted in an after delete trigger causes an ENTITY_IS_DELETED error for each of those mutually reciprocal rows when processing the delete DML in TDTM_TriggerHandler.

Since this trigger is run with rollback, the transaction is rolled back and none of the reciprocal relationships are deleted (except for those that were deleted as part of the original delete dml).

There is a unit test that demonstrates this issue here: https://github.com/SalesforceFoundation/Cumulus/blob/test-for-delete-reciprocal-relationship-bug/src/classes/REL_Relationships_TEST.cls#L864

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004powrAAA" target="_blank">W-017631</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
