### ISSUE TITLE
Household Merge from Manage Household UI page should have full functionality

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1816]
The Manage Household UI page currently just reparents the contact's to the new Household Account or Household Object.  While this should cause in the Household Account model for fixups to be done from the AfterUpdate in ACCT_IndividualAccounts_TDTM, several users have reported that addresses aren't always copied to the contacts, and that sometimes the losing HH Account is left with opportunities.

https://powerofus.force.com/0D58000002MxTop
https://powerofus.force.com/0D58000002MyOdj

We need to investigate why this is happening, and decide if we can enhance our triggers to cover these scenarios, or whether the Manage Household UI page needs to do some explicit Account Merge work.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001h4kAAA" target="_blank">W-008686</a>

**Comment by johnfine** [comment]
Common user scenario that causes possibly the same bug: when merging together a husband and wife who are each in their own separate single-Contact HH Accounts, the "recipient" Contact has its Contact.CurrentAddress field nulled out:

1. From HH Account record for a single-Contact HH that has an address, click Manage Household.
2. In Add Members, choose a Contact from a different single-Contact HH Account that has an address.
3. Click Add then choose Add and merge Households (I believe this issue also occurs if you choose Delete from Old Household).
4. Click Save on the manage HH page.

Issue: for the Contact whose HH Account is being added to, on their Contact record, the field Contact.CurrentAddress is nulled out.

**Comment by davidhabib** [comment]
thanks for adding the reproduceable case john.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
