### ISSUE TITLE
Settings page error when class from other package found starting with ADDR and without no-args constructor

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#1819]
See https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000009bi6N&tab=sfdc.ProfilePlatformFeed&fId=0D58000002MzHmu

We probably need to wrap the line that tries to instantiate the class with classType.newInstance() in a try-catch, in case the class doesn't have a no-args constructor.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001h8EAAQ" target="_blank">W-008690</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.57 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.57

**Comment by davidhabib** [comment]
turns out users are still seeing an error, and its coming from STG_PanelADDRVerification_CTRL's constructor, which isn't silently eating this error anymore.  When we redid our error handling in 2016, we added back code to add a page message for errors.
