### ISSUE TITLE
Adding a Payment to a Closed/Lost Opportunity lands user on "Record Deleted" error page

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#1824]
Steps to reproduce:

1) Create a new Opportunity with Amount = 1, Stage = Closed Lost.
2) From Opportunity detail page, scroll to Payments related list and click "New Payment"
3) Create new Payment with Amount = 1, Paid = unchecked.
4) Click Save

Expected result:

A new, related, unpaid payment will be created.

Actual result:

User is navigated to error page: "Record Deleted: The record you attempted to access has been deleted. The user who deleted this record may be able to recover it from the Recycle Bin. Deleted data is stored in the Recycle Bin for 15 days."

**Comment by kbromer** [comment]
We're too clever for our own good. I'll bet our code is seeing the closed oppty and deleting the payment in the after trigger, redirecting us back to the newly created, yet now deleted, payment record.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hCBAAY" target="_blank">W-008738</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.111 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.111
