### ISSUE TITLE
Scheduling payments on Closed/Lost Opportunity does not create any Payments

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#1825]
Steps to reproduce:

1) Create a new Opportunity with Amount = 1, Stage = Closed Lost
2) On Opportunity detail page, scroll to Payments related list and click "Schedule Payments" button
3) Click "Calculate Payments" to calculate 12, the default number, payments.
4) Click "Create Payments" to confirm creation of the 12 payments.

Expected result:

12 new, related, payments are created and are visible in the Payments related list on the Opportunity detail page

Actual result:

No payments are created and/or appear in the Payments related list on the Opportunity

Note: performing the above steps but with Stage = Closed Won *will* produce the expected result.

**Comment by dospromptman** [comment]
Related to #1824

**Comment by kbromer** [comment]
I think this is the correct behavior, but needs to be caught and a reasonable error message displayed. 

The idea was that once an Oppty is closed, you shouldn't ever add payments to it (data integrity, etc.), but clearly the quiet fail is not good.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hCCAAY" target="_blank">W-008739</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
