### ISSUE TITLE
Surface current version and "your version" to the end user

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1828]
Ideally a user would be able to see the current version and their version, and a visual notice if they're not in sync -  possibly on settings on Getting Started or the Settings Page

@judisohn 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hCQAAY" target="_blank">W-008742</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hCVAAY" target="_blank">W-008743</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hCaAAI" target="_blank">W-008744</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
