### ISSUE TITLE
Version 3.55 BUG: 'Cannot call test methods in non-test context' error in NPSP Data Import

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1830]
Version 3.55

* Create new NPSP Data Import record
* Populate Contact1 First Name, Contact1 Last Name
* Process

Failure message: Cannot call test methods in non-test context

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hFoAAI" target="_blank">W-008784</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.56 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.56
