### ISSUE TITLE
GAU Allocations based on Campaign for Closed Won Opportunities

### ISSUE THREAD

**Issue by alphasys** [SalesforceFoundation/Cumulus#1832]
When creating new Opportunities with a Campaign provided, GAU Allocations are correctly created based on the Campaign GAU Allocations when the Opportunity is not in a closed state. However when the Opportunity is created and saved immediately with a Closed Won state, the GAU Allocation will not be in line with the Campaign but instead take on the default GAU.

Not sure whether this is deliberate, however the challenge is when creating donation records to record historic donations, GAUs allocations need to be made manually.

**Comment by judisohn** [comment]
@alphasys We generally recommend that you post in the Power of Us Hub NPSP group first until we can determine exactly what is going on and that it requires code change, then we post it as an issue here if necessary.

Could you write out step by step what you are doing? I am unable to reproduce this and will close until we can see if it's really a bug/something needs to be changed. Then we can re-open it.

I have a campaign that is set for 100% to a 'Special Fund' while the default in NPSP Settings is 'Unrestricted'

I created a new opportunity off a Contact, set Primary Campaign source to that Campaign and the stage to a Closed/Won value. When I saved, the GAU Allocation shows 100% of the Amount to the 'Special Fund' as set by the Campaign, not the default 'Unrestricted' GAU. Did I capture your use case correctly?

I don't believe what happens with the GAU Allocation has anything to do with the Stage of the Opportunity - @njjc is that correct?

**Comment by njjc** [comment]
@judisohn That's correct. This is likely happening due to customizations in the org.
