### ISSUE TITLE
One-to-One model not behaving correctly

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/Cumulus#1835]
After installing and configuring NPSP 3.0 for One-to-One model in a developer edition org, the accounts and contacts are not behaving as they should. Accounts are behaving as Company accounts, being accessible through the Contact page,when you should be redirected again to the contact page.
NSP config as follows:
![image](https://cloud.githubusercontent.com/assets/8911757/11335768/99e2a968-91df-11e5-92f0-4b049db0641a.png)
 The Individual record type should behave as One-to-One but it is not behaving properly.
Any Solution or possible bug here in developer editions?
Thanks in advance,

**Comment by judisohn** [comment]
Hi @gonzalos4g - if you don't mind, please post first on the Power of Us Hub NPSP group https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe - that way the community can help you determine if what you're experiencing is a bug. Once we're sure that there's code changes needed, then we post here.

As for your issue, it sounds like you have not set the View button correctly on Account. Go to Setup > Build > Customize > Accounts > Buttons, Links and Actions. Click Edit to the left of View and change to the Visualforce page named ACCT_ViewOverride [npsp__ACCT_ViewOverride]. If that is not resolving this issue, please post on the Hub and I'm sure we can help you figure out what might be going on. Thanks!

**Comment by gonzalos4g** [comment]
Thanks Judison! That solved the issue! Great support!
