### ISSUE TITLE
Contact Merge Deletes Chatter History

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#1836]
**External Contribution Issue created by @cdcarter**

As noted here: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000002NupKB and related to Idea: https://success.salesforce.com/ideaView?id=08730000000Yu03AAC (which really should be a KI...) -- "losing" contacts on a contact merge lose their chatter history. Since the NPSP is already hijacking contact merge and adding additional features, perhaps until the issue is resolved NPSP can strong arm the behavior programatically.

**Comment by kbromer** [comment]
Not "hijack", but "enhance".  

;)

**Comment by cdcarter** [comment]
The amount of ish that you have to do to merge Chatter history without losing data (fun fact: you'll always lose data) is so high that I really don't think this should be part of the NPSP contact merge. Perhaps someone wants to write an independent app to handle it, but really Chatter doesn't make this easy and it'd really quickly turn the fairly simple override into absolute hell.

**Comment by davidhabib** [comment]
this really feels like a core issue to me.  we ultimately call Salesforce's merge api, and they should own this type of functionality.  Or Contact Merge override is more to deal with the issues that are unique to NPSP given our account model and other custom objects.

**Comment by cdcarter** [comment]
I agree. Since mrbelvedere owns the issue, I can't close it myself, but as the "original reporter" I believe that this shouldn't be an NPSP fix.

**Comment by kbromer** [comment]
Every time I add a "cantfix-wontfix" label to an issue, i think of Dave Chapelle doing Puff Daddy...

https://www.youtube.com/watch?v=Zf0hjLJZFng
