### ISSUE TITLE
As a user, I'd like a setting to disable the automatic creation of Campaign Member records from Opportunities

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1838]
See conversation here: https://powerofus.force.com/0D58000002Nuq8Q

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hObAAI" target="_blank">W-008800</a>

**Comment by njjc** [comment]
Also consider a setting to choose which status is default "non-responded" and which status is default "responded".

**Comment by mrbelvedere** [comment]
Included in beta release version 3.60 (Beta 2) and higher
