### ISSUE TITLE
Lead conversion creating an opportunity should populate opportunity's primary contact field

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1839]
[Per this hub thread.](https://powerofus.force.com/0D58000002Nuq8Q)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hkMAAQ" target="_blank">W-008947</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
