### ISSUE TITLE
Some Test Classes Not Suffixed as '_TEST'

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#1841]
These classes have the suffix '_TEST2' instead of '_TEST', and these are both test classes:

* [RLLP_OppRollup_TEST2.cls](https://github.com/SalesforceFoundation/Cumulus/blob/001db1d/src/classes/RLLP_OppRollup_TEST2.cls)
* [STG_InstallScript_TEST2.cls](https://github.com/SalesforceFoundation/Cumulus/blob/001db1d/src/classes/STG_InstallScript_TEST2.cls)

The issue with this is that the default matching pattern used in CumulusCI to figure out what tests to run is '%_TEST'.  These classes don't match that pattern.

As far as I can tell, this matching pattern is only used when the tests are being run using the python script test running, which is used when running records with parallel running disabled.

We may want to consider renaming these classes to match the '_TEST' suffix, or changing the matching pattern used in our CumulusCI properties to run these tests.

**Comment by njjc** [comment]
See the discussion on W-008787

**Comment by mrbelvedere** [comment]
Included in beta release version 3.57 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.57
