### ISSUE TITLE
Does this verify with SmartyStreets API

### ISSUE THREAD

**Issue by antwonlee** [SalesforceFoundation/Cumulus#1844]
Does current version of Non Profit Starter pack works with SmartyStreets?  On SmartyStreets site, https://smartystreets.com/docs/salesforce/install it states it is not fully compatible.

**Comment by njjc** [comment]
Hi @antwonlee, we prefer that people ask questions about NPSP on the [power of us hub](powerofus.force.com), and reserve github issues for actual work items for NPSP.

NPSP [supports smartystreets](https://powerofus.force.com/articles/Resource/NPSP-Verify-Addresses) in our address verification framework. The smartystreets documentation is referring to their salesforce integration, which provides inline address verification as data is being entered. I'm not sure why they say it isn't supported by NPSP, as we use standard address fields on Contacts and Accounts, but you'll have to take up the issue with their support.
