### ISSUE TITLE
When deleting a donation created w/ a Campaign and auto-campaign member, the member remains with a responded status

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1850]
With the NPSP 3.56 I notice that if I record a donation with a primary campaign and donor designated, and then delete the donation, I still have a campaign member record with the status of Responded that I have to delete manually. Is that the intended functionality?

https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000005QWVJ

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hTSAAY" target="_blank">W-008826</a>
