### ISSUE TITLE
As a developer, I'd like to understand the process needed to contribute to the NPSP

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1851]
Specifically, guidance in writing issues, guidance in what issue labels are (`community-ready`)?, an understanding of the CLA process, etc... Not the technical steps, but the open source stuff!

**Comment by kbromer** [comment]
@judisohn is working on a site for this right now!

**Comment by judisohn** [comment]
Hang tight @cdcarter - coming soon, I promise. This actually came out of the conversation you and I had at the sprint about increasing the transparency of the work we're doing.

**Comment by cdcarter** [comment]
You all rock!

**Comment by judisohn** [comment]
Glad you did. :-)

**lurch: attach W-008829

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hThAAI" target="_blank">W-008829</a>

**Comment by cdcarter** [comment]
Just popping questions into here: is it preferred that we create issues with the contrib tool that are owned by mrbelvedere, or should we create issues with our github creds and then link contributions to them?

**Comment by judisohn** [comment]
Others may have opinions, but I think it would be better to create the issue first, then link to it in the tool. @jlantz do you have a preference?

**Comment by judisohn** [comment]
@cdcarter Safe to close this one yet? Especially now that we have the great new docs?
