### ISSUE TITLE
Provide NPSP Setting to turn off Empty Address Object deletion

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1857]
hub thread: https://powerofus.force.com/0D58000002NvXjD

basically, some users might have extended the address object, and so our code that looks to see if it is empty might not catch other fields they care about.

so we should provide a setting to turn off this behavior.  Or we should change our empty detection code to look at all fields on the object, including custom fields.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hc3AAA" target="_blank">W-008889</a>

**Comment by judisohn** [comment]
Another [thread](https://powerofus.force.com/0D58000003NKzRs) on this.

**Comment by mpusto** [comment]
Doing some cleanup. I tested this to see what happens when there is a custom field that is populated but no other address fields (street, city, state). As long as a custom field is populated at all, the address is not deleted if all standard address fields are blank.
