### ISSUE TITLE
Create new Last Soft Credit Gift Date & Last Soft Credit Gift Amount field

### ISSUE THREAD

**Issue by mhiman** [SalesforceFoundation/Cumulus#1859]
Create a new field so that users can pull reports on Last Soft Credit Gift Date & Last Soft Credit Gift Amount. Thanks!

**Comment by judisohn** [comment]
**lurch: attach W-008862

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hWRAAY" target="_blank">W-008862</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.63 (Beta 15) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.63
