### ISSUE TITLE
BUG: Payments are not being auto-created in push upgraded 3.57 orgs until Payment Settings are loaded

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1860]
Threads where this has been reported: 

https://powerofus.force.com/0D58000002Q3EVl
https://powerofus.force.com/0D58000002Q30az

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hcSAAQ" target="_blank">W-008892</a>

**Comment by njjc** [comment]
Fixed in #1861
