### ISSUE TITLE
If Audit Fields are enabled through Permission Set, NPSP Data Import should allow edit as custom field

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1864]
Steps to repeat:
- Create Permission Set enabling Audit Field creation after allowing in User Interface settings
- Add to Admin User
- Custom Date/Time field for Contact 1 Created Date in NPSP Data Import w/help text Contact1.CreatedDate
- Create test record and process. Error:    You do not have permissions to modify Contact.CreatedDate

Power of Us thread: https://powerofus.force.com/0D58000002Q46yv

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hesAAA" target="_blank">W-008895</a>

**Comment by judisohn** [comment]
Closing as this was fixed already.

**Comment by davidhabib** [comment]
turns out we need to also special case CreatedById, not just CreatedDate.

**Comment by judisohn** [comment]
@davidhabib LastModifiedID too.

**Comment by mrbelvedere** [comment]
Included in beta release 3.109 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.109
