### ISSUE TITLE
If a Contact is marked as Deceased, they should no longer get soft credit for Household gifts

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1870]
POU thread: https://powerofus.force.com/0D58000002Q4c7x

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hfvAAA" target="_blank">W-008907</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.61 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.61
