### ISSUE TITLE
Unable to disable Households Trigger

### ISSUE THREAD

**Issue by SUMO-Steve** [SalesforceFoundation/Cumulus#1877]
Hello,

I have a use case where a Customer Portal user is indirectly updating a contact.  In doing so the FiscalYearSettings object is being queried.  I have tried to create/update the custom settings for npo02 to "disable" the triggers.  However even disabling the trigger AND ensuring the Fiscal Year box is unchecked the query is still being ran, and the error is still showing up.

Also, it's stating that there is a dependent class which is invalid and needs to be compiled.  Problem with this error message is that each of the classes have the IsValid box ticked when queried.

Any help would be greatly appreciated!

**Comment by judisohn** [comment]
Hi @SUMO-Steve Do you have access to the Power of Us Hub? If so, would you mind posting this in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe)? It's easier for our team to discuss and troubleshoot with you there, and that way the resolution is more accessible to our community for future reference. Thanks!

**Comment by SUMO-Steve** [comment]
Thank you.

On Mon, Jan 4, 2016 at 1:31 PM, Kevin Bromer <notifications@github.com>
wrote:

> Closed #1877 <https://github.com/SalesforceFoundation/Cumulus/issues/1877>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1877#event-505067067>
> .
>



-- 

Best Regards,

Stephen Sprague
Product Engineer
SumoScheduler.com
(510)-969-0698 (o)
(510)-246-1800 (c)
