### ISSUE TITLE
How to contribute to this project?

### ISSUE THREAD

**Issue by aleramesh** [SalesforceFoundation/Cumulus#1886]
Apologies for asking this kind of question in the issues section but I am helpless so wanted other developers to know what I am trying.

Can I contribute to this project with Salesforce Developer Edition? 

I followed steps mentioned in this [step!](http://developer.salesforce.org/Cumulus/Contributor/Developer-Edition-Salesforce-Instance.html) but not able to log into power of hub and then emailed "community@salesforcefoundation.org" and below is the response I received:

>My apologies. Are you working on a pro bono project? I am only able to grant access to the Power of Us Hub to nonprofit and higher ed users and approved partners. 

If we cannot contribute to this project with salesforce developer edition then how can I contribute? I am just wondering how the other developers are contributing? Do i need to be Employee of Salesforce??

Thanks

**Comment by judisohn** [comment]
Hi @aleramesh - thank you so much for your interest in contributing to NPSP. I'm the Open Source Manager at Salesforce.org who works with contributors to our open source projects. May I ask specifically what you're interested in contributing? There is no requirement for Power of Us Hub access to contribute, and you can indeed use a standard Developer org. But I'd love to hear about what you're working on so we can be sure that you're connected with the right resources to guide and review even before your pull request. Thanks!
