### ISSUE TITLE
When Account Record Type is changed from Household Account, update _SYSTEM: fields

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1887]
thread: https://powerofus.force.com/0D58000001YDFov

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001iC1AAI" target="_blank">W-008988</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 9)
