### ISSUE TITLE
In NPSP Settings > Donations > Campaign Members, on Save, the value in CM Responded Status matches CM Non Responded Status

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1889]
@njjc The correct data is visible on Edit and is correct in Custom Settings and behavior is normal, it just displays incorrectly. Tip of the hat to Tracy Kronzak for reporting this issue.

Steps to repeat:

* Enable Automatic Campaign Member Management
* Set Campaign Member Responded Status to 'Value 1'
* Set Campaign Member Non Responded Status to 'Value 2'
* Save

Campaign Member Responded Status will be 'Value 2' - when Edit again, it shows correct value.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001iOqAAI" target="_blank">W-009047</a>
