### ISSUE TITLE
As a user, I would like an Affiliated Contact to receive automatic soft credit on Organization Opportunity

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1893]
Thread here: https://powerofus.force.com/0D58000002S0LVl

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k20AAA" target="_blank">W-009097</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
