### ISSUE TITLE
Enable platform encryption for Account Name

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#1894]
Currently the new SFDC Platform Encryption feature will not work on certain fields in the NPSP b/c they're used as filter criteria in SOQL.  Account.Name is a key one and this line blocks enablement: 
https://github.com/SalesforceFoundation/Contacts_and_Organizations/blob/master/src/classes/Constants.cls#L164

It may be possible to make that dynamic SOQL, and then warn users of the Individual Account model that they are unable to use at-rest encryption on Account.Name unless they convert models.  

Mailing address fields are also blocked due to presence in formula field. That should be evaluated separately 

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k2AAAQ" target="_blank">W-009099</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k2FAAQ" target="_blank">W-009100</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k2KAAQ" target="_blank">W-009101</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k2PAAQ" target="_blank">W-009102</a>

**Comment by davidhabib** [comment]
Platform encryption
- must create a Tenant key first
- create permissions set with manage encryption keys / manage tenant secrets
- assign this to yourself
- read platform encryption deployment guide
- wouldn’t allow with NPSP to encrypt Account.Name and Contact.Mailing Address
- question about household name when contact name encrypted
- question about household custom naming.  what happens?
- Kevin has sent dhabib a login
- fix the Account.Name issue, test, writeup any other caveats

**Comment by mpusto** [comment]
Released May 2016.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWsnAAG" target="_blank">W-016734</a>
