### ISSUE TITLE
Allocations: Donation of $0 allows allocation of arbitrarily large dollar amount.

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1896]
Create a Donation
Navigate to Manage Allocations for that Opportunity.
Add any dollar amount to be allocated, e.g. $100.00
Save the record. 

This should not be allowed but it is. See screen shot.
![screen shot 2016-01-14 at 10 40 04 am](https://cloud.githubusercontent.com/assets/204643/12332413/8f0116e8-baab-11e5-8d2e-159a5d88f107.png)

Note: it is also possible to save legal values for percentage. This is weird but not actually wrong.

**Comment by chrismcmahon** [comment]
Forgot to add the 'bug' label

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k3mAAA" target="_blank">W-009107</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.62 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.62
