### ISSUE TITLE
Update all custom settings getAll() methods to use UTIL_CustomSettingsFacade

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1897]
Found about two dozen references to custom settings getAll() which could impact running tests in parallel.

**Comment by davidhabib** [comment]
@njjc does this issue represent incorporating all the fixes/changes made in HEDAP by @ceiroa in pull request https://github.com/SalesforceFoundation/HEDAP/pull/145

for example, I see the pull request includes a fix in the facade to set npe4__Reciprocal_Method__c to 'List Setting' not 'List Settings'.  I've made that one fix on my system, but I'm not sure if some of the other changes in this pull request also need to get in NPSP, like caching some of the settings.

**Comment by njjc** [comment]
I did that fix in the org that I'm working on this issue in, but if it makes it in one of your pull requests earlier then that's fine.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k8DAAQ" target="_blank">W-009123</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
