### ISSUE TITLE
ADDR_Addresses_TEST2.clearConAddrExisting test method fails with state and country picklists enabled

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1901]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k8hAAA" target="_blank">W-009129</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001k8mAAA" target="_blank">W-009130</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001rb2AAA" target="_blank">W-009332</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.64 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
