### ISSUE TITLE
A single opportunity record type set as default causes test failures in OPP_OpportunityNaming_TEST

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1906]

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kGHAAY" target="_blank">W-009183</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kGMAAY" target="_blank">W-009184</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kGRAAY" target="_blank">W-009185</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBXeAAO" target="_blank">W-017355</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBXjAAO" target="_blank">W-017356</a>

**Comment by mpusto** [comment]
@force2b has confirmed that we have default record types in our test code and do not have failing tests. This is no longer an issue.
