### ISSUE TITLE
NPSP Data Import with person in c1 and later c2 hits runtime error

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1907]
https://powerofus.force.com/0D58000002SvxYp

If you import the following 2 record csv, neither record will import and both will have the error 
[NPSP_Data_Import_Template.xlsx](https://github.com/SalesforceFoundation/Cumulus/files/101660/NPSP_Data_Import_Template.xlsx
	
Update failed. First exception on row 1 with id a0Tj0000004AltzEAC; first error: ENTITY_IS_DELETED, entity is deleted: []

note that I had to rename the file from .csv to .xlsx to allow gitHub to attach it.  If it gets lost, the first sample csv file on the hub thread is the one to use.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kI8AAI" target="_blank">W-009193</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
