### ISSUE TITLE
Replace Verify Address onclick javascript button with visualforce page for LEX compatibility

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1909]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kN8AAI" target="_blank">W-009200</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kNDAAY" target="_blank">W-009201</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kNhAAI" target="_blank">W-009202</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kNmAAI" target="_blank">W-009203</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kcDAAQ" target="_blank">W-009260</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.63 (Beta 17) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.63
