### ISSUE TITLE
Exclude all NPSP rollups & auto-calculated fields from User Defined Rollups

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1912]
In at least two orgs, when setting up a User Defined Rollup, `Contact.npsp__Soft_Credit_Last_N_Days__c` and `Account.npsp__Number_of_Household_Members__c` have presented themselves as available Target Fields when setting up a new UDR. 
![screen shot 2016-02-01 at 10 48 28 am](https://cloud.githubusercontent.com/assets/164/12727390/b1c38b50-c8d1-11e5-8b13-47c7e19d6696.png)
![screen shot 2016-02-01 at 10 48 40 am](https://cloud.githubusercontent.com/assets/164/12727391/b2815a36-c8d1-11e5-94c4-f7f71df83189.png)

I would expect that these fields would be excluded, since they are standard package rollups.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kduAAA" target="_blank">W-009269</a>

**Comment by judisohn** [comment]
Thanks @cdcarter - I marked this as a bug, because it appears that we did exclude the hard credit rollups but have missed specifically some soft credit and other auto-calculated fields. Good catch.

**Comment by cdcarter** [comment]
Due to the custom label ID in new dev orgs bug, I'm unable to work on this issue. I have yet to be able to create a new dev org that doesn't face this issue, and it makes it impossible to work on anything in NPSP Settings. It's frustrating to have an entire large portion of the NPSP that outside contribs cannot work on. Have we seen any movement from core on the bug?

**Comment by tet3** [comment]
This will happen with all fields in the `npsp` namespace - this is the code that's trying to exclude them in the setting panel controller:

**Comment by tet3** [comment]
@judisohn or @njjc So, how does one go about testing something like this that will only look different in the managed package context?

**Comment by mpusto** [comment]
@cdcarter and @tet3 the label bug has been fixed just fyi. :)

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128
