### ISSUE TITLE
Add "Date of Largest Gift" for Contact and Account/Household

### ISSUE THREAD

**Issue by mhiman** [SalesforceFoundation/Cumulus#1913]
Common request for folks leaving Raiser's Edge. Partially mitigated already by Best Gift Year field.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kYLAAY" target="_blank">W-009224</a>

**Comment by judisohn** [comment]
another request: https://powerofus.force.com/0D58000002mBngl

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
