### ISSUE TITLE
BUG: Lead Conversion page does not respect Lead Process Status selected values

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1922]
Thread: https://powerofus.force.com/0D58000002UgML0

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001lA3AAI" target="_blank">W-009287</a>

**Comment by cdcarter** [comment]
http://salesforce.stackexchange.com/questions/103837/how-do-i-get-the-intersection-of-recordtype-and-picklist-values-inside-apex is a great explanation of why this is really hard to do.

**Comment by davidchengIC** [comment]
Currently working on this during the 2016 NPSP Sprint.

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 5)
