### ISSUE TITLE
Malformed relationships causing null object exception

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1923]
Relationships without a contact lookup populated throw a null exception at [this line](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/REL_Relationships_TDTM.cls#L273).
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001m2JAAQ" target="_blank">W-009291</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001m2OAAQ" target="_blank">W-009292</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001m2TAAQ" target="_blank">W-009293</a>

**Comment by davidhabib** [comment]
@kbromer why did we get three Lurch tracking comments (and I assume 3 items added to AA)?

**Comment by kbromer** [comment]
I've seen it happen once before. I think it might be a bug when lurch is called from within the body of the issue instead of in the comments.

**Comment by kbromer** [comment]
I closed the second two as dupes, I'm going to delete the comments for brevity sake

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV3uAAE" target="_blank">W-011178</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.105 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.105
