### ISSUE TITLE
NPSP Data Import Tool - Add Phone Number Field(s) to Matching Rules

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/Cumulus#1926]
The Contact/Account level phone number fields can't be included in the NPSP Data Imports Matching Rules - they aren't available in the Custom Unique ID field.  Can these be included for Contacts with no email addresses/access?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001nZJAAY" target="_blank">W-009299</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
