### ISSUE TITLE
TDTM_Account AfterDelete Trigger calls future method which fails if running in Batchable context

### ISSUE THREAD

**Issue by sfdcmatt** [SalesforceFoundation/Cumulus#1927]
The TDTM_Account trigger, in AfterDelete context, calls a future method called handleAccountMergeFixupsFuture within the ACCT_AccountMerge_TDTM class. If you execute an Account Merge in a Batch class, this call to the future method will fail, with the error message "Future method cannot be called from a future or batch method."

**Comment by judisohn** [comment]
Thanks again, Matt!!

Pull request in #1928 

Putting this through to generate a Work item for review.

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001onBAAQ" target="_blank">W-009300</a>
