### ISSUE TITLE
Manage Allocation: Save button no longer disabled automatically when allocated amount exceeds opp amount

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1930]
**lurch: attach W-009301

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001p87AAA" target="_blank">W-009301</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.65 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.65
