### ISSUE TITLE
Use consistent terminology and ordering on NPSP SLDS custom pages

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1935]
Manage Soft Credits, Find Matched Gifts - have a Save and a Cancel button on the top right.
Manage Allocations - has a Save & Close and a Cancel button on the top right.

We should be consistent.  What is the correct UI to use?  I chose Save and Cancel buttons because that is what LEX seemed to use, but to be fair, those were on popup dialogs.  I can't think of a similar full page view that we can model off of in LEX.

Also, what is the correct ordering of buttons?  Seems like LEX popups go with Cancel, and then Save.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qDCAAY" target="_blank">W-009313</a>

**Comment by jjbennett** [comment]
Completed in Spring 3a 2016.
