### ISSUE TITLE
Formula Field in Relationship Object throwing an error because of Suffix enable on Names

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/Cumulus#1936]
Trying to emulate the Formula field of Relationship Explanation for the translation to Spanish, when saving the field it fails with error: Error: Invalid Data. 
Review all error messages below to correct your data.
Field $Label.1012400000IcEZv is inaccessible. Please review all fields referenced by the formula. Context: common.formula.EntityFormulaContext (Related field: Formula)

This Org has the Name Suffix activated. The same formula with orgs that do not have this functionallity activated works correctly.
The error comes out with any RelatedContact__r.FirstName, lastName or Suffix

**Comment by judisohn** [comment]
@mpusto @davidhabib Is this related to that Platform Label ID issue identified a while ago?

**Comment by gonzalos4g** [comment]
Don´t really know it...
I finally get rid of the Label (Relationship Explanation Connector) in the
formula field and that works for me (Hardcoding the value), but unable to
use the label for dynamic update on that formula.
Thanks for the quick response!

2016-02-11 13:09 GMT+01:00 Judi Sohn <notifications@github.com>:

> @mpusto <https://github.com/mpusto> @davidhabib
> <https://github.com/davidhabib> Is this related to that Platform Label ID
> issue identified a while ago?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1936#issuecomment-182830077>
> .
>



-- 
Gonzalo Gómez de la Cal
*Consultor **S4G Consulting*
www.s4g.es

*Tel*: +34 911530379 (Madrid) / +34 932304137 (Barcelona)
*Mov*: *+34 654512548*

**Comment by davidhabib** [comment]
Yes, this very much sounds like the same platform issue where custom labels would get converted to their internal id on visualforce pages.  There is nothing we can do about this, but I would encourage @gonzalos4g to enter a Salesforce support case with a reproducible example.

**Comment by gonzalos4g** [comment]
Ok, Thanks David!

2016-02-11 16:48 GMT+01:00 David Habib <notifications@github.com>:

> Closed #1936 <https://github.com/SalesforceFoundation/Cumulus/issues/1936>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/1936#event-547326291>
> .
>



-- 
Gonzalo Gómez de la Cal
*Consultor **S4G Consulting*
www.s4g.es

*Tel*: +34 911530379 (Madrid) / +34 932304137 (Barcelona)
*Mov*: *+34 654512548*
