### ISSUE TITLE
Update manage allocations page to better handle multiple currencies

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1941]
Currently we rely on the user replacing a custom label to change a currency symbol. Instead, we should rely on salesforce to display the currency using an outputfield and a dummy opportunity with currencyisocode set.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qwiAAA" target="_blank">W-009327</a>

**Comment by kbromer** [comment]
Clever!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 16) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
