### ISSUE TITLE
Update opportunity naming to better handle currency fields

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1942]
Currently a custom label is applied to the currency, which is OK for single currency orgs but not ideal for multicurrency.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qwjAAA" target="_blank">W-009328</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
