### ISSUE TITLE
NPSP Data Import: Support Unique ID Matching for Household Accounts as well as Organization Accounts

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1943]
Currently, if a user selects the option to match Account Unique ID on the NPSP Data Import setting page, it only functions for rows where the Account Name is populated (Organization Accounts). There have been a number of requests to support household-level unique IDs fields to help in migration from Account-centered fundraising databases where the Household was the primary record without separate contacts.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001r0kAAA" target="_blank">W-009329</a>

**Comment by judisohn** [comment]
Fixed in #2446
