### ISSUE TITLE
NPSP Settings for Address: Settings not saved: Attempt to de-reference a null object.

### ISSUE THREAD

**Issue by NorthPeakMelissa** [SalesforceFoundation/Cumulus#1950]
After checking the box to set minor changes as updates and trying to save, receive the error "Settings not saved: Attempt to de-reference a null object." Here are the steps to reproduce:

- In the Addresses section of NPSP Settings click Edit
- Check the box for "Simple Address Change Treated as Update"
- Click Save
- Settings not saved, remain in Edit screen, and have "Settings not saved: Attempt to de-reference a null object" error in red below Save button.

If I then, check the box for "Enable Automatic Verification" and select "The Google Geocoding API" or "Cicero" for the verification service, I'm able to save without error. I can't select "SmartyStreets" and save without providing an Auth Token. @njjc

**Comment by judisohn** [comment]
Thanks for reporting @NorthPeakMelissa! I replicated this in my own org as well. We'll hopefully get this in to a sprint very soon.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001sx6AAA" target="_blank">W-009336</a>

**Comment by streetyouth** [comment]
I got this bug having never used the address page settings to my knowledge after upgrading about a year ago but having done the HA model conversion yesterday. I also note that having gotten the error message once (I personally clicked both enable organization addresses and simple address processing to stimulate the error), I cannot select and save one, the other, or both without getting the error. I have not tried clicked the third option.

**Comment by streetyouth** [comment]
So... I think there is no way to enable organization addresses with this bug. And no way to set simple update option, either. Someone said on the HUB that they got around this by first configuring address verification. Unconfirmed.

**Comment by njjc** [comment]
The bug here has to do with leaving the "Verification Service" setting blank. It will be fixed in the next release, but in the meantime the settings will save as long as you've selected a service, even if "Enable Automatic Verification" is unchecked.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.66 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.66
