### ISSUE TITLE
Health check report filters for zero but not null

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#1951]
When using the Empty Household Accounts report in the Health Check Reports folder, the report filter it starts with says "Total Household Members" equals "0". When there are empty household members, the rollup does not populate this value with zero, it has a value of NULL. The report should not be filtering on zero but rather on null.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001sxGAAQ" target="_blank">W-009338</a>
