### ISSUE TITLE
Recalculate rollups for a single account

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#1952]
As an administrator or SI partner, I want to re-calculate rollups for a specific account, so that I can quickly debug some bad behavior without waiting for an entire batch job to run.

Example use case: I'm currently integrating NPSP with another system and working in a full sandbox, and I'm running into trigger order of execution errors between NPSP and non-NPSP managed packages. While working out those problems, I'm regularly having to re-run the batch job to bring sanity to my rollup fields. However, batch jobs take a long time (and tend to be slower in sandboxes anyway). Being able to run the batch for just the record I care about would reduce cycle time.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001sxkAAA" target="_blank">W-009342</a>

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128
