### ISSUE TITLE
Buttons for Batch Data Import need to trap and display error messages

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1955]
the shared page has apex:pageMessages, but the button handlers need to try/catch and add to pagemessages the exception.  Also worth considering making new pages for these buttons since lightning doesn't allow us to fix the namespace prefix with c in the address bar in DE orgs.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001vvvAAA" target="_blank">W-009367</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.100 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.100

**Comment by judisohn** [comment]
@RadSFDeveloper @davidhabib - @smarovich realized that we didn't document this in the data guidebook, in case someone runs in to the issue and didn't fix the button. Can you give us an example of what the user might see or not see that would indicate that their profile doesn't have access to the button so we can document it? Thanks!

**Comment by RadSFDeveloper** [comment]
@judisohn , @smarovich , @davidhabib - If a user's profile is not enabled for a Visualforce page, a page containing the following generic "Insufficient Privileges" error message will be displayed:

Insufficient Privileges
You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary. For more information, see Insufficient Privileges Errors. 

Click here to return to the previous page.

**Comment by judisohn** [comment]
@RadSFDeveloper Always? In my org with managed 3.100, I removed the System Administrator Profile from the page. Then I created NPSP Data Import records and both buttons appeared to delete the records without any error message. Is there more to it than that? Perhaps it's only on non-Admin Profiles?

**Comment by RadSFDeveloper** [comment]
@judisohn , System Administrators have permissions regardless if they are assigned to the page at the Setup > Develop > Visualforce Page > Security. Non-admin profiles must have permission for the Visualforce page in order to view it.

**Comment by judisohn** [comment]
That makes sense, thanks!

**Comment by smarovich** [comment]
Thanks, @RadSFDeveloper and @judisohn! So, would it work to add this note to the doc (where we talk about deleting import records):  "If you see an Insufficient Privileges error when trying to delete import records, your Admin needs to add your profile to the Enabled profiles for the BDI_DataImportDeleteBTN Visualforce page.  Access the list of Enabled Profiles in Setup by searching for Visualforce Pages. Next to BDI_DataImportDeleteBTN, click Security."

**Comment by RadSFDeveloper** [comment]
@smarovich , that sounds good. I believe it is better not to specify a special case for the System Administrator (or a profile used create the page at the org) with regards to enabled profiles by default.

**Comment by judisohn** [comment]
Perfect @smarovich! Thanks, all!
