### ISSUE TITLE
Bug when excluding record types from Householding code

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/Cumulus#1962]
I think I've found an error in `HH_Households_TDTM#insertHousehold` starting at line [371](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/HH_Households_TDTM.cls#L371) that is evidenced when you insert multiple Contacts of different RecordTypes (some excluded, some not).

I don't have a test case for this (I found it when trying to debug a different issue), but I think you can easily generate one.

Let's say we don't Household Contacts of RecordType X, and we do household Contacts of RecordType Y, and we insert two Contacts (one of each type).  For convenience, let's call them "Noel" (No Household) and "Yasmin" (Yes Household).

If you pass in an array of `[Noel, Yasmin]` to the `insertHousehold` method, you'll end up with one entry for Yasmin's Household in `householdInserts`.  `lsr` will then have one record.  The `for` loop on line 371 will run twice.  On the first run, Noel will be assigned to Yasmin's Household.  On the second run, it will error on line 373 when we try to access `lsr[1]`.

**Comment by judisohn** [comment]
Thanks for reporting @ckoppelman - we'll investigate and get this in to a sprint as soon as we can.

**Comment by njjc** [comment]
That does indeed look like a bug, since we're looping over the entire contacts list despite only inserting a subset of them for households.
Thanks for reporting @ckoppelman.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001yWsAAI" target="_blank">W-009411</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
