### ISSUE TITLE
Test failures in new dev orgs with duplicate rules enabled by default

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#1964]
*********** DEPLOYMENT FAILED ***********
Request ID: 0Af3600000AJcQ2CAL

All Test Failures:
1.  HH_ManageHHAccount_TEST.testRemoveContactActiveAddress -- System.DmlException: Insert failed. First exception on row 0; first error: DUPLICATES_DETECTED, Duplicate Alert: []
    Stack trace: Class.HH_ManageHHAccount_TEST.testRemoveContactActiveAddress: line 207, column 1
2.  HH_ManageHousehold_TEST.testRemoveContactActiveAddress -- System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, TDTM_Contact: execution of BeforeInsert
    
    caused by: System.AssertException: Assertion Failed: Class.ACCT_IndividualAccounts_TDTM.insertContactAccount: line 568, column 1
    Class.ACCT_IndividualAccounts_TDTM.run: line 288, column 1
    Class.TDTM_TriggerHandler.runClass: line 169, column 1
    Class.TDTM_TriggerHandler.run: line 101, column 1
    Trigger.TDTM_Contact: line 34, column 1: Expected: null, Actual: Insert failed. First exception on row 0; first error: DUPLICATES_DETECTED, Duplicate Alert: []
    
    Class.TDTM_TriggerHandler.run: line 139, column 1
    Trigger.TDTM_Contact: line 34, column 1: []
    Stack trace: Class.HH_ManageHousehold_TEST.testRemoveContactActiveAddress: line 201, column 1
*********** DEPLOYMENT FAILED ***********

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001yZXAAY" target="_blank">W-009434</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
