### ISSUE TITLE
payment mapping can cause error in Payment Wizard and Opportunity creation

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1966]
If you have a payment mapping that contains a field the payment wizard normally uses, then you will get an error when you try to bring up the payment wizard.  Example: have a payment mapping from Opportunity.Number of Payments to some custom field on the payment.  Now bring up the payment wizard and you will get the error:

duplicate field selected: npe01__Number_of_Payments__c

obviously our dynamic soql code is adding the fields from the payment mapping without making sure they are already part of the select clause.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000002Hb1AAE" target="_blank">W-009457</a>

**Comment by judisohn** [comment]
Updated title as this can also cause issues with Opportunity creation. For example, if a date field is mapped to Scheduled Date. 

![image](https://user-images.githubusercontent.com/4614343/34059936-666db8d0-e1af-11e7-9b11-f01065042ecb.png)

Payment Mapping should exclude any target field that is used in NPSP code specifically.

**Comment by oagostinho** [comment]
Hi @judisohn 

I will try to resolve this. ;-)

Best Regards!

**Comment by oagostinho** [comment]
> Updated title as this can also cause issues with Opportunity creation. For example, if a date field is mapped to Scheduled Date.
> 
> ![image](https://user-images.githubusercontent.com/4614343/34059936-666db8d0-e1af-11e7-9b11-f01065042ecb.png)
> 
> Payment Mapping should exclude any target field that is used in NPSP code specifically.

HI @judisohn, @davidhabib 

Is this situation still valid?

I went to the NPSP Settings -> Donations - Payment Mappings,
I tried to map  npe01__Number_of_Payments__c to a custom field in Payment Object but it seems that the code has already some validations to not show that "special fields" in the Opportunity Field - selected list.

In that way, I explore the VisualForce Page and the Apex Class STG_PanelPaymentMapping_CTRL and it has already some kind validation for fields belongs to NPSP Succes Pack.

Could you please give some clarification here? Thanks

Best Regards,
Orlando

**Comment by mbeaty-sf** [comment]
This Issue has since updated to address one of the two issues listed. This Issue is going to be closed, and will provide a link to the refined, updated Issue.
