### ISSUE TITLE
Add field set support to the Payment Wizard

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#1967]
Hub request: https://powerofus.force.com/0D58000002WX0ii

User would like to add some of their custom fields to the payments section of the wizard.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000002W2FAAU" target="_blank">W-009476</a>

**Comment by tet3** [comment]
We're looking at this at the Baltimore Community Sprint. @force2b and I might flip or arm wrestle for it.

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110
