### ISSUE TITLE
Data Importer does not ignore case when matching First Name, Last Name, and Emails 

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1968]
When matching is set to "First Name and Last Name", DI does not match when FName and LName match exactly except for the case of letters in the strings.  DI should ignore case when matching - i.e., "John Smith" and "john smith" should match.

To dup this issue:
- Create a Contact in SF with Firstname="John" and Lastname="Smith" (propercasing the names is important here).
- Create a DI record with Contact.FIrstName = "john" and Contact1.LastName="smith" (all lowercase for these values).

Run DI matching on "FirstName and LastName".

Expected a match, got a create.

RUn same steps with case matching and DI matches.

**Comment by judisohn** [comment]
@davidhabib Is it possible to make the match case-insensitive?

**Comment by davidhabib** [comment]
yes, the code currently is creating its matching keys based on the exact text, rather than always converting to lowercase.  this can be fixed.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000033WzAAI" target="_blank">W-009494</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.142 (Beta 5)
