### ISSUE TITLE
Data Importer does not ignore case when matching Fname and LName 

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1969]
When matching is set to "First Name and Last Name", DI does not match when FName and LName match exactly except for the case of letters in the strings.  DI should ignore case when matching - i.e., "John Smith" and "john smith" should match.

To dup this issue:

* Create a Contact in SF with Firstname="John" and Lastname="Smith" (propercasing the names is important here).

* Create a DI record with Contact.FIrstName = "john" and Contact1.LastName="smith" (all lowercase for these values).

Run DI matching on "FirstName and LastName".

Expected a match, got a create.

RUn same steps with case matching and DI matches.

**Comment by judisohn** [comment]
Same as #1968
