### ISSUE TITLE
Data Importer does not fill Campaign field on "Account1" Opp creation

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#1970]
If 

Account1.Name is filled in AND
* Donation.Donor is set to "Account1" (meaning the Opp.Account should be set to the Account1 value in the DI record rather than the Contact1 value - this is a "company" donation)
AND
* Donation.CampaignName is present
AND
* Contact1.FirstName and Contact1.LastName are null

THEN the created Opp does not have its Campaign field filled with the corresponding Campaign.

Opp.Campaign should be set to the campaign corresponding to Donation.CampaignName.  The reason is that Opp.Campaign is used in reports and rollups to track all donations to a Campaign, both "company" and "personal", even when the "company" donation is not associated with any Contact.

**Comment by judisohn** [comment]
@johnfine I attempted to reproduce this in my test org:

1. New NPSP Data Import record
2. Account1: New Company Name; Donor: Account1; Amount: 50; Close Date: 2-28-2016; Campaign: New 2-28-2016
3. Processed the record
4. Result: Account created, Donation created, Campaign created and linked to Opp.

A second NPSP Data Import record linked to the same Account/Campaign matched and correctly populated the Campaign on the opportunity.

Please try and recreate in another instance and if you can give specific steps to reproduce, feel free to reopen the issue.

**Comment by johnfine** [comment]
My apologies - it was a process that ran after DI that removed the value in Opp.Campaign.

I'm sorry to cost you the time to try to repro - from now on I'll always test with a clean instance before reporting issues.
