### ISSUE TITLE
If Contact's Account is Organization Account, Campaign Member functionality does not work

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1975]
Even though our best practice model is that all Contacts have a Household Account and Organizations are through Affiliation, the Campaign Member functionality should still work regardless of Account Record Type (if not, we should explicitly say this in documentation).

Steps to reproduce:

1. Create Organization Account. Create Contact directly in that Account.
1. NPSP Settings set to defaults with Campaign Member functionality enabled
2. Add Contact to Campaign, Status = Sent
3. Create Opportunity from Contact, Associate to same Campaign
4. Result: Campaign Member Status remains at Sent instead of updating to Responded as expected

If Contact not already member of Campaign, they are not added.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000003b4gAAA" target="_blank">W-009536</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
