### ISSUE TITLE
BUG: 'Find Matching Gifts' & 'Manage Soft Credits' button - Attempt to de-reference a null object 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#1977]
If the Amount is null, both buttons will product 'Attempt to de-reference a null object' Visualforce error. Regardless of type of Account or any other factor. Does not happen if Amount = 0

Hub thread: https://powerofus.force.com/0D58000002XPJPL

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000003b5PAAQ" target="_blank">W-009545</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.70 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.70
