### ISSUE TITLE
Calculate NPSP donation rollups based on custom amount field on Opportunity

### ISSUE THREAD

**Issue by ghost** [SalesforceFoundation/Cumulus#1978]
Use case: We have a client using Products and Pricebooks for donations, memberships, registrations, and merchandise. The Opportunity is the order which captures all of the items purchased, including donations as Opportunity Products. We're able to tag the donation Opportunity Products as donations and rollup the total of all the donation Opportunity Products into a custom rollup field on the Opportunity called Total Donations.

This enhancement suggestion is to make it possible to point the NPSP to look at a custom amount field on Opportunities for the donation rollups rather than only the standard Amount field. In the example of our client, we'd like to be able to have the NPSP donation rollups calculate based on the Total Donations field.

@njjc

**Comment by davidhabib** [comment]
Our User Defined Rollups should allow you to do this and rollup to your own custom field on contact.  I don't think we'd try to add more settings to allow you to change what our current rollup fields work on.  @njjc @judisohn agreed?

**Comment by judisohn** [comment]
Agreed. You can also create custom formula fields on Opportunity to create user defined rollups against and get nearly identical fields as the standard rollups.

**Comment by cdcarter** [comment]
UDRs are "all time" only, correct? 

I'm gonna mention #1541 so that this issue shows up on that ticket too, since the ability to add date filters would be necessary to actually match NPSP rollup functionality.

Similarly, UDRs would not allow this type of functionality to work for (non-partial) soft credit rollups.

**Comment by judisohn** [comment]
@cdcarter It's pretty straight forward to create a formula field on Opportunity that returns Amount (or other currency field) if the date range is met and 0 if not, and then roll that up.

I would imagine that doing soft credit rollups (partial or not) against a configurable Opportunity field other than Amount would be a rather tremendous lift, but I can let @davidhabib speak to that.

**Comment by cdcarter** [comment]
I agree that it's probably not worth the effort to make a change around the stock soft credit rollups. But in the ideal world where somebody searches for this ticket before posting this question again, I think it's good to be clear about the limitations of UDRs. 

Very clever idea around timefiltering UDRs. That should probably make its way to a Best Practice Nugget, I hadn't thought of doing it that way!

**Comment by mscholtz** [comment]
@judisohn @davidhabib FWIW, we would wholeheartedly support the original request of @NorthPeakMelissa here.  We have had the exact same scneario with a few clients, and are having it again with another right now.  While it's true that UDRs exist, and they're a great tool, it's a pretty drastic change to have to consider hiding all of the native rollups, and recreating all of them with UDRs.  Melissa's suggestion would be so much easier, and I think would get used (and appreciated) a lot.

So I vote to reopen this issue. 

Thanks!

**Comment by davidhabib** [comment]
@njjc food for thought when we look at rollups.

**Comment by mscholtz** [comment]
Hey @davidhabib just curious if you guys are still reconsidering this, or if there's been any movement toward this approach.  Thanks!

**Comment by davidhabib** [comment]
@njjc correct me if I'm wrong, but no I don't think we are planning on providing an option to change our standard rollups to use a different field.  but we are increasing the flexibility of our User Defined Rollups as part of our rollup redesign work we are undertaking.

**Comment by njjc** [comment]
I am planning on including the ability to choose a custom amount field for standard rollups.

**Comment by mscholtz** [comment]
@njjc @davidhabib awesome!
Any sense of when this might be done/released?  (Safe harbor etc. understood)

**Comment by njjc** [comment]
No :) but it's just about the only thing I'm working on until it's done; about 3-6 months probably.

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128
