### ISSUE TITLE
Find Matching Gifts could potentially match itself

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#1995]
Depending on how the Opportunity was created, a donation could match itself as a result of running Find Matching Gifts. I suggest excluding the original donation from any search results on the Find Matching Gifts page
![screen shot 2016-03-17 at 4 15 58 pm](https://cloud.githubusercontent.com/assets/204643/13864063/d59511fe-ec5b-11e5-9e1b-f0ca0775ac6e.png)

**Comment by chrismcmahon** [comment]
Note that when one chooses to match an opp record to itself, this error occurs upon clicking Save: 

	
Matching Gift: attempt to violate hierarchy constraints
Update failed. First exception on row 0 with id 006610000093QD5AAM; first error: CIRCULAR_DEPENDENCY, attempt to violate hierarchy constraints: [npsp__Matching_Gift__c]

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
