### ISSUE TITLE
Add a custom setting to allow users to specify our batch size for Opp related Rollups

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2000]
currently, all of our batches for opp rollups (household, contact, soft credit) use the default 200 batch size.  In some extreme instances, such as contacts with _lots_ of soft credits, one can hit limit errors when using such a large batch size. 

We should provide a new setting that we display on the Donor Statistics settings page to allow the user to specify a batch size to use.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Ovn6AAC" target="_blank">W-009669</a>
