### ISSUE TITLE
Rename NPSP2 Batch Entry Tab

### ISSUE THREAD

**Issue by BrightStepTracy** [SalesforceFoundation/Cumulus#2004]
*If possible* in a similar fashion as the NPSP2 Contact Merge Tab, to help differentiate from newer Batch Entry tool.

**Comment by davidhabib** [comment]
that would require us rev'ing and push upgrading the separate BDE package that lives on the AppExchange.  Since we still make it available to customers, and we can't just push to those on NPSP 3.0, we can't do this.

**Comment by BrightStepTracy** [comment]
True, but can you rename it even something more descriptive? It's becoming a PITA for doing label-sorting in upgraded instances, and would really benefit customers trying to sort out old components from new.  If not "OLD" something like "Batch Entry 2"
