### ISSUE TITLE
intermittent: unexpected final address for 3-way Contact Merge

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2012]
Seen rarely when done manually; seen most often in automated browser tests.; seen more often in Firefox than in Chrome:

Create 3 Contacts via the API with three addresses 1, 2, and 3 such that each Contact automatically gets a Household Account created for them. 

On the Contact Merge page, select a variety of values from among the three accounts: 

![screen shot 2016-03-21 at 4 06 41 pm](https://cloud.githubusercontent.com/assets/204643/13937097/95b23f5e-ef7f-11e5-98aa-b832052b2395.png)

Upon clicking the Merge Contact button and the Merge button in the subsequent modal dialog, the Contact detail page presented immediately after merging seems to have the correct address. Note however, the absence of Address records under Recent Items. 

![screen shot 2016-03-21 at 4 07 14 pm](https://cloud.githubusercontent.com/assets/204643/13937098/95b83ad0-ef7f-11e5-8b91-f697729e55fe.png)

Upon navigating to All Contacts and picking the record for our aaa2 Contact, however, we find that the address has incorrectly been changed to all values of '1', which corresponds to the address for the first Contact '1' created via the API.

![screen shot 2016-03-21 at 4 07 46 pm](https://cloud.githubusercontent.com/assets/204643/13937099/95bd8698-ef7f-11e5-9507-859162201699.png)

Note that now we have two Address records under Recent Items. Both of those address records are assigned to the proper Household; one of the address records contains all "3" values, and this record is never ultimately assigned to our Contact. The other address record contains our chosen variety of post-merge address fields, but has mistakenly not been assigned to the Contact record at the conclusion of Contact Merge.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvvAAAS" target="_blank">W-009704</a>

**Comment by njjc** [comment]
https://github.com/SFDO-Tooling/CumulusCI/issues/438#issuecomment-358669352
