### ISSUE TITLE
If Opportunity RecTypes/Types are excluded from Account/Contact Rollups, soft credits should not roll up either

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2015]
This was reported by Anne Crawford at KELL Partners and confirmed in a test org.

If Opportunity Record Types or Types are excluded from Account or Contact rollups, this works as expected for hard credit rollups. However, any Opportunity Contact Role soft credit (including partial soft credit) added to the Opportunity rollup to the Contact regardless. Ideally, soft credit rollups should respect the same exclusions as hard credits for the same opportunity.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvsVAAS" target="_blank">W-009684</a>

**Comment by kbromer** [comment]
I think this is a regression from teh partial soft credits, though I'm surprised we don't have a test for this:  

The original soft credit query constructor is here:  https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup_UTIL.cls#L729

It looks like @davidhabib might've rolled his own constructor here https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppPartialSoftCreditRollup.cls#L69 and left out the code that handles the record type collection - am I reading that right DH? 

Is the older query only used when PCSs are turned off now? Seems like we should just move that query into the UTIL class to keep it neater

**Comment by davidhabib** [comment]
yep, I missed excluding by rectypes and opp types.  I didn't put the querying construction into the util class because I was trying to leave the KELL code as it was, with the minimal changes needed.  that said, once we finally put to rest the LDV rollup tests, I will then remove our old soft credit rollup code, and it makes sense to move the query construction into the utility class for consistency.

**Comment by judisohn** [comment]
Another thread reporting this issue: https://powerofus.force.com/0D58000002btjk1

**Comment by kbromer** [comment]
The original design of soft credits was inclusive (of roles), not exclusive (of record types).  That's why you have to explicitly select certain roles to be treated as soft credits, and why soft credits are only added for donation oppty types.  I'm not sure this isn't WAD.  Changing this behavior also means you'll never be able to soft credit something that isn't also hard-credited at the same time. I'm not sure that's the correct answer either.

**Comment by judisohn** [comment]
@kbromer Hmmmm.... I can see that being true for general soft credit, absolutely. You'll want to add a soft credit and have it roll up even if the donor isn't being counted. However, I disagree this is WAD for automatic soft credit - such as in the case of Household Members. If one member of the Household (the donor) is not credited for a gift on their contact record, it doesn't make sense to me that other members of the Household do receive soft credit on their contacts without a clear and easy way to exclude that behavior from happening.

**Comment by kbromer** [comment]
Well that's my point - they shouldn't if the roles are set properly. if anything, I'd argue the incorrect behavior is automatically generating soft credits for non-donation Oppty rectypes.

**Comment by judisohn** [comment]
But it's perfectly reasonable to select Household Member as a Role that calculates soft credit. It's desired behavior in many instances where the donor is hard credited. It shouldn't be excluded across the board - just excluded if the Donor in the same Household is not also getting hard credit.

**Comment by judisohn** [comment]
And if it's possible to not have the OCR automatically created if the Record Type/Type is excluded, I'm all for it. I just thought that was more challenging to implement.

**Comment by kbromer** [comment]
Yes, agreed- i just wouldn't want to try and change the current behavior mid-stream, it is WAD, its just we probably haven't captured enough of the other use-cases

**Comment by davidhabib** [comment]
I'm confused by your discussion.  Isn't the issue that the original soft crediting code honored the Exclude by Record Type and Type, and the new Partial Soft Crediting rollup code does not?

**Comment by kbromer** [comment]
Yup, you're right @davidhabib https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup_UTIL.cls#L717 For some reason I thought it didn't. I stand corrected. I'll go back to my cave again. :tophat: :bow: :footprints:

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
