### ISSUE TITLE
Address w/ Country only in State & Country picklists org lost

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2018]
hub thread: https://powerofus.force.com/0D58000002auDl1

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Q59gAAC" target="_blank">W-009737</a>

**Comment by jjbennett** [comment]
Closing - resolved with issue #2111
