### ISSUE TITLE
Case change of Contact name does not update Household Naming fields

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2021]
hub thread: https://powerofus.force.com/0D58000002avhTF

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Qem5AAC" target="_blank">W-009749</a>

**Comment by judisohn** [comment]
another request: https://powerofus.force.com/0D58000002mC6a2

**Comment by judisohn** [comment]
Idea posted: https://powerofus.force.com/hub-ideas/1111
