### ISSUE TITLE
Change Related List Label on Opportunity.npsp__Matching_Gift_Account__c from 'Opportunities' to 'Matched Gifts'

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2023]
Hub thread: https://powerofus.force.com/0D58000002bsrcp

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QeoBAAS" target="_blank">W-009768</a>

**Comment by davidhabib** [comment]
fixed with pull request #2028

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
