### ISSUE TITLE
If Account Record Type is changed from the one set as the Household or One to One, update _SYSTEM fields so no longer acts as Household/One to One

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2030]
Thread: https://powerofus.force.com/0D58000002bunro

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QevRAAS" target="_blank">W-009840</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 9)
