### ISSUE TITLE
Test failures caused by UTIL_Describe in API 36

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/Cumulus#2032]
When deploying to the packaging org, we get a bunch of test failures that seem to point back to UTIL_Describe:

http://ci.salesforcefoundation.org/view/uat/job/Cumulus_uat/1043/console

It seems the way fields are looked up when namespaced has changed from 35 to 36.  I was able to get the tests to pass by changing UTIL_Describe back to API 35 but subsequent deployments reset it to API 36.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RExrAAG" target="_blank">W-009881</a>
