### ISSUE TITLE
Account 'New Account Donation' button error in LEX

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2033]
https://powerofus.force.com/0D58000002chqPF

Confirmed that if one uses the custom button in LEX, error is 'Record Type ID: this ID value isn't valid for the user.' (and the Account doesn't auto populate). The standard Opportunity related list New button works without an issue - Account name is auto populated and record saves correctly (and NPSP creates OCR for Primary Contact). Given that the desired behavior is achieved with standard functionality, my recommendation is to deprecate the custom button rather than fix the error within the button.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqZIAA0" target="_blank">W-009906</a>

**Comment by njjc** [comment]
Closed as this has been marked as "Never" internally.
