### ISSUE TITLE
Any Open Recurring Donation with Next Donation Date after the 28th is assumed to be last day of month

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2034]
thread: https://powerofus.force.com/0D58000002ci7gK

repro steps: New open ended RD connected to a contact, Monthly Installment Period. Next Donation date on 4/28/2017. Default settings. 

First Opp is set for correct Close Date. Other 11 Opps are set to close on the last of the month. Should be 4/28, 5/28, 6/28, 7/28, etc. Instead it's 4/28, 5/31, 6/30, 7/31, etc.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003REy1AAG" target="_blank">W-009883</a>

**Comment by davidhabib** [comment]
related to #313

**Comment by davidhabib** [comment]
also  #1729 and its pull request #1731

**Comment by judisohn** [comment]
@davidhabib @mpusto would this be possible/solve this?

* If 31st - No change. Close Dates on all opportunities are assumed to be the last day of each month
* If 30th - Close Date is the 30th of each month for all opportunities, except if February. If February, then it's 28 or 29 depending on Leap Year.
* If 29th - Close Date is the 29th of each month for all opportunities, except if February in a non-Leap Year in which case it would be the 28th
* If 28th - Close Date is the 28th for all opportunities

**Comment by cdcarter** [comment]
I am unable to reproduce in a 3.75 org with standard settings.

**Comment by mrbelvedere** [comment]
Included in beta release 3.104 (Beta 2)
