### ISSUE TITLE
Find Matched Gifts page's header doesn't resize with window

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2036]
Bring up the Find Matched Gifts page that we've styled with SLDS.  change the width of the browser window.  Note that the header doesn't grow or shrink to fit.  I suspect this was introduced when we added some of the summary fields into the headers (since this issue does not occur on the Manage Soft Credits page).

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003REyfAAG" target="_blank">W-009891</a>
