### ISSUE TITLE
Timeout set during HTTP requests for address verification

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#2038]
We appear to be setting the timeout in some of our validators (SmartyStreets chief amongst them) manually to 5000 milliseconds (https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_SmartyStreets_Gateway.cls#L193).  If SmartyStreets is delayed in its return, a read timeout can occur as reported here: https://powerofus.force.com/0D58000002XOG4q

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RF10AAG" target="_blank">W-009893</a>
