### ISSUE TITLE
Bulk Data Process - "Refresh Opportunity Names" has wrong header text. 

### ISSUE THREAD

**Issue by jlangelaan** [SalesforceFoundation/Cumulus#2044]
The header text on the visual force page reads "Bulk Data Processes - Rollup Donations Batch"

![image](https://cloud.githubusercontent.com/assets/14916309/14449359/ef71c732-0026-11e6-9c16-232c8ac47e6c.png)

**Comment by mpusto** [comment]
**lurch: add

**Comment by mpusto** [comment]
Thanks for reporting it Jessica! Should be a quick fix.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqZbAAK" target="_blank">W-009911</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.71 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.71
