### ISSUE TITLE
TDTM cannot currently call a local class

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#2047]
I don't believe we can currently extend TDTM with a local class based on this (resolved) issue 

Per this KB known issue: https://success.salesforce.com/issues_view?id=a1p30000000SVY3AAO

We currently use a the Type.forName call with the single parameter, which does not allow us to extend it outside of the managed package context with a local class: 

https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/TDTM_TriggerHandler.cls#L149

Ideally, we should try it both ways, once with the local namespace, once without. Per the two different forName method implementations found here: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_type.htm 

You can see the 2 param version should be used when inside a managed package context

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqdEAAS" target="_blank">W-009932</a>

**Comment by kbromer** [comment]
Chalk it up to user error, global v public.
