### ISSUE TITLE
Contact Roles should not change on an Opportunity despite changes in Household makeup

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2051]
Thread: https://powerofus.force.com/0D58000002d5HBy

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003VoVsAAK" target="_blank">W-009966</a>

**Comment by kbromer** [comment]
Duplicates https://github.com/SalesforceFoundation/Cumulus/issues/2050
