### ISSUE TITLE
Relationships auto create settings page no longer showing Campaign Types field for Campaign Members

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2053]
[Per this hub thread](https://powerofus.force.com/0D58000002e8y5O).

Rerender of panelNewAc on update of object picklist isn't happening here: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/pages/STG_PanelRelAuto.page#L23

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abJrAAI" target="_blank">W-010001</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.72 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.72
