### ISSUE TITLE
Health Check Information Incorrect

### ISSUE THREAD

**Issue by jlangelaan** [SalesforceFoundation/Cumulus#2055]
After the data model change - 

The "Account Model Data" Health check fails and indicates the Account Model is set to Household Account but there are a mixture of Accounts.

The Health Check says there are 1691 One-to-One Accounts, 1673 Household Accounts.

A report for contacts by "Organization Record Type" has 1671 Household Accounts, 0 other account record types.

There are only 1671 contacts in Salesforce.

Can provide specific org details if needed.

**Comment by judisohn** [comment]
Hi @jlangelaan - the error is referring to Accounts, not Contacts so I suspect using a Contact report would not be accurate. Looking in Setup > Data Storage, how many total Accounts are in the instance? Regardless, it might be better if we continued this conversation in a Hub post and we can re-open this if/when we determine that there is in an error in the Health Check report that needs attention. It sounds like it's something that may be more unique to that particular org. Thanks!
