### ISSUE TITLE
BUG: If a contact custom field with Name that matches NPSP field (after namespace) exists, error in Contact Merge and Manage Household

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2056]
Thread: https://powerofus.force.com/0D58000002eAJYw

Steps to reproduce. 

Create custom Contact field - label Deceased, Name - Deceased (Deceased__c) 
Clone a contact, and then merge in Contact Merge tab

Error: Failed to query contact information. Error: System.QueryException: duplicate field selected: npsp__Deceased__c

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abLTAAY" target="_blank">W-010021</a>

**Comment by judisohn** [comment]
This also appears to be an issue with the Manage Household page. Any custom field with the same name as a NPSP field after the namespace prefix.

**Comment by tet3** [comment]
We encounter this issue with some regularity with NGOC. I wrote about it here: https://powerofus.force.com/0D58000002HCTYA

Our approach has been to treat it as a platform shortcoming and have customers give different API names to their custom fields.

The only approach that I know of for an ISV to take is to "faux-namespace" fields, and all the references to them, eg, inside one's NPSP dev org, call a field npsp_Deceased__c, so that when packaged, the field's API name is npsp__npsp_Deceased__c. Kind of ugly. And not foolproof - if someone created a field called npsp_Deceased__c in their org you'd still have a conflict. 

I'll be interested to see if you have a better alternative!

**Comment by judisohn** [comment]
@tet3 thanks for the feedback! What's interesting here is that it's a new issue introduced in the push of 3.71 on Tuesday night/Wednesday morning. These orgs had these competing custom fields before and didn't have this problem. Something new is setting it off.

**Comment by davidhabib** [comment]
we recently updated our API version, so that may have exposed the issue.
Dave


David Habib | Lead Member of Technical Staff | salesforce.org

**Comment by JodiNA** [comment]
Hi Team,

Just tried to merge a contact and ran into the issue you're describing.  Never had before (going to what  Judi just said).   Our custom field is Deceased__c. 

Any workaround you suggest in the meantime as you're looking into this further?

Thanks!
Jodi

**Comment by judisohn** [comment]
@JodiNA - rename your custom field's Name (not Label) to something else, such as Deceased_Custom (which would give it the API name of Deceased_Custom__c)

**Comment by JodiNA** [comment]
Thanks, I'll try that.

On Fri, Apr 22, 2016 at 3:26 PM, Judi Sohn <notifications@github.com> wrote:

> @JodiNA <https://github.com/JodiNA> - rename your custom field's Name
> (not Label) to something else, such as Deceased_Custom (which would give it
> the API name of Deceased_Custom__c)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SalesforceFoundation/Cumulus/issues/2056#issuecomment-213561087>
>



-- 
*Jodi Nemser-Abrahams*
Information & Data Manager
Keshet
284 Amory Street
Jamaica Plain, MA 02130
617.524.9227x111

Web: www.keshetonline.org
Facebook: www.facebook.com/KeshetGLBTJews
Twitter: @KeshetGLBTJews <https://twitter.com/KeshetGLBTJews>
Blog: www.myjewishlearning.com/category/keshet/

*Subscribe for LGBT* Jewish news, resources and inspiration in your inbox
<http://bit.ly/1E6oJYK>.

*Registration <http://www.keshetonline.org/teenshabbaton/> for our first
ever West Coast Shabbaton for LGBTQ and ally teens is open! *Find more
information *here* <http://www.keshetonline.org/teenshabbaton/>.

*Stand up for transgender rights.* Sign Keshet's petition
<https://www.keshetonline.org/work/petition-in-support-of-full-transgender-rights-in-massachusetts/support-transgender-rights-in-ma/>
calling
Massachusetts legislators to support “An Act Relative to Transgender
Anti-Discrimination."

A teen. A mom. A straight rabbi and a queer rabbi.
See how we are transforming the Jewish community together
<https://youtu.be/3b8NL5jwt4o>.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.72 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.72

**Comment by judisohn** [comment]
Re-opening as this issue is back (due to the API change?). See https://powerofus.force.com/0D58000002wIoed

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l8AAAQ" target="_blank">W-011266</a>

**Comment by sjurgis** [comment]
Here's some code to help identify all clashing field names in your org
```

private static Set<String> getInstalledPackageNamespaces() {
    Set<String> namespaces = new Set<String>();
    for (AggregateResult ar : [SELECT NamespacePrefix FROM ApexClass WHERE NamespacePrefix != null GROUP BY NamespacePrefix]) {
        String namespace = (String) ar.get('NamespacePrefix');
        namespaces.add(namespace.toLowerCase() + '__');
    }
    return namespaces;
}

Set<String> installedNamespaces = getInstalledPackageNamespaces();
Map<String,SObjectType> describe = Schema.getGlobalDescribe();
public static Map<String, List<String>> findConflictingFields(String objectApiName) {
    Map<String, List<String>> conflictingFields = new Map<String, List<String>>();

    Map<String, Schema.SObjectField> fieldMap = describe.get(objectApiName).getDescribe().fields.getMap();

    Map<String, List<String>> potentialConflicts = new Map<String, List<String>>();

    for (String fieldName : fieldMap.keySet()) {
        String namespacedFieldName = '';
        String unnamespacedFieldName = fieldName;

        for (String namespace : installedNamespaces) {
            if (fieldName.startsWith(namespace)) {
                namespacedFieldName = fieldName;
                unnamespacedFieldName = fieldName.substringAfter(namespace);
                break;
            }
        }

        if (!potentialConflicts.containsKey(unnamespacedFieldName)) {
            potentialConflicts.put(unnamespacedFieldName, new List<String>());
        }
        potentialConflicts.get(unnamespacedFieldName).add(fieldName);
    }

    for (String unnamespacedFieldName : potentialConflicts.keySet()) {
        List<String> fields = potentialConflicts.get(unnamespacedFieldName);
        if (fields.size() > 1) {
            conflictingFields.put(unnamespacedFieldName, fields);
        }
    }

    return conflictingFields;
}

public static void printConflicts(String objectApiName) {
    Map<String, List<String>> conflicts = findConflictingFields(objectApiName);

    if (conflicts.isEmpty()) {
//        System.debug('No conflicting fields found for ' + objectApiName);
    } else {
        System.debug('Conflicting fields found for ' + objectApiName + ':');
        for (String fieldName : conflicts.keySet()) {
            System.debug('  Field name: ' + fieldName);
            System.debug('    Conflicting fields: ' + String.join(conflicts.get(fieldName), ', '));
        }
    }
}

for (String sObjectName : describe.keySet()) {
//    System.debug('Checking conflicts for object: ' + sObjectName);
    printConflicts(sObjectName);
}
```
