### ISSUE TITLE
BDE settings not working as expected?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2057]
BDE has two settings dealing with opportunity naming.  These no longer seem to work as intended, and also it is not clear how these interact with NPSP's new custom Opp naming code.  Dev needs to investigate how these settings are used, whether they work, and what should happen.  Then we need to update the Settings help strings to make sense!

**Comment by davidhabib** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abO8AAI" target="_blank">W-010053</a>

**Comment by njjc** [comment]
Closed as this has been marked as "Never" internally.
