### ISSUE TITLE
Undelete a Contact must update Household Name and Greetings

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2071]
If you delete a contact from a household (account or object), we correctly update the household's name and greetings.  If you then undelete the contact, thus restoring them to their household, the name and greetings don't get updated.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000GEwwAAG" target="_blank">W-010244</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.79 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.79
