### ISSUE TITLE
Lead conversion results in Household account named "REPLACE"

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/Cumulus#2072]
When using Household Account model and disabling Household Account Addresses, a Lead conversion to an individual (i.e. Company = Self) results in a household account named "REPLACE".  The Contact name is unaffected.  Enabling Household Account Addresses fixes the issue.

The lead conversion is using LD_LeadConvertOverride Visualforce page.  The HH account record type in use is the NPSP record type.  Automatic household naming is enabled with the default settings.

**Comment by davidhabib** [comment]
@davidchengIC thanks so much for narrowing this down for us!

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000GF0tAAG" target="_blank">W-010250</a>

**Comment by judisohn** [comment]
Yes, indeed I think it has! Thanks for checking @cdcarter!
