### ISSUE TITLE
Health Check limit errors on verifyNoMissingOppPayments

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2081]
Apex script unhandled exception by user/organization: 0051A00000A83D4/00D80000000dXy4

Visualforce Page: /apex/npsp__STG_SettingsManager
caused by: System.LimitException: npsp:Too many query rows: 50001
Class.npsp.STG_PanelHealthCheck_CTRL.verifyNoMissingOppPayments: line 655, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runAllDetections: line 184, column 1
Class.npsp.STG_PanelHealthCheck_CTRL.runDetector: line 101, column 1

we need to fix its soql to limit appropriately.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003n4NeAAI" target="_blank">W-010291</a>

**Comment by davidhabib** [comment]
duplicate of #2022
