### ISSUE TITLE
Add Health Check test to detect duplicate contact roles

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2082]
to allow users to identify opps that might be double counted in rollups and soft credit rollups.  after we release this, we can then fix the double counting issue.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003n4yUAAQ" target="_blank">W-010292</a>

**Comment by davidhabib** [comment]
dupe of #2022

**Comment by dospromptman** [comment]
@davidhabib, I don't think this is a dupe of #2022.  Was there a different ticket that contains additional details?

**Comment by davidhabib** [comment]
Oops!  I think i mixed up bugs.  I believe #2081 and #2022 are the dupes of eachother!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 16) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
