### ISSUE TITLE
Health Check icons need some spacing on their top

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2087]
with the new SLDS'ing of the NPSP Settings pages, the icons displayed in Health Check are up against the very top of their error box and look bad.  They should be down a bit, or maybe centered vertically.  Obviously, not a big deal, but it just looks unpolished.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhnhAAA" target="_blank">W-010361</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
