### ISSUE TITLE
Manage Household UI need to consider user's security permissions

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2091]
both the old and new page don't have specific FLS checks in place, which should be added.
hub thread: https://powerofus.force.com/0D58000002hT517

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oKlvAAE" target="_blank">W-010465</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
