### ISSUE TITLE
Add all NPSP opportunity fields to opportunity field sets

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2098]
https://powerofus.force.com/0D58000002jHrqb

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxwdAAA" target="_blank">W-010529</a>

**Comment by mrbelvedere** [comment]
Included in production release version 3.75
