### ISSUE TITLE
Data Import: Contact True checkbox fields are updated to False in import

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2101]
hub thread: https://powerofus.force.com/0D58000002jsKto

Reproduce:
1. Custom checkbox on Contact, check as True
2. Create custom NPSP Data Import field for checkbox, mapped in help to contact field
3. Create NPSP Data Import record, First/Last Name only, with a donation (donation probably not necessary)
4. Process, matching on First and Last Name
5. Result: Contact's custom checkbox is now False, shouldn't have been updated

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxzhAAA" target="_blank">W-010556</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
