### ISSUE TITLE
Investigate intermittent issue where Address record changes are not saving to Account/Contact as expected

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2108]
Reported multiple times, difficult to reproduce, example here: https://powerofus.force.com/0D58000002ckxAQ

**Comment by judisohn** [comment]
**lurch: add

**Comment by davidhabib** [comment]
Any chance @chrismcmahon could spend some time trying to get a repro case in a clean NPSP org, rather than asking dev to try to track down in this customer's org, where so many other factors can come into play?

**Comment by kbromer** [comment]
Or better yet, log a ticket and work with support to repro

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003pbfKAAQ" target="_blank">W-010606</a>

**Comment by judisohn** [comment]
Okay @kbromer I'll close and go that route for this one to see if we can get a use case. This was just one of a few reports. Seems to happen more often when inserting via API.
