### ISSUE TITLE
Unable to change household account to org account

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2110]
Changing the record type switches it back, nulling out the npe01__SYSTEM_AccountType__c and setting npe01__SYSTEMISINDIVIDUAL__c to false gets switched back, and the user can't do both at once.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003pbhBAAQ" target="_blank">W-010627</a>

**Comment by njjc** [comment]
Unable to reproduce.
