### ISSUE TITLE
moving contact to new household account should preserve their mailing address

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2111]
hub thread: https://powerofus.force.com/0D58000002kgcIb

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003pbhkAAA" target="_blank">W-010634</a>

**Comment by davidhabib** [comment]
also hub post: https://powerofus.force.com/0D58000002lI2Eo

slightly different scenario (new account vs move to existing account).  same desired behavior.  preserve the contact's address.

**Comment by mhiman** [comment]
This issue affects a client. Tried to mass convert to household accounts (successfully) and address was moved to HH Account, but deleted from Contact's mailing address.

**Comment by mhiman** [comment]
Amendment - in about half? the cases the address was moved to the Household account (and deleted from the contact mailing), and in about half, was never moved to Household Account record (we have field tracking on Billing Address as well as Mailing Address on Contact).

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
