### ISSUE TITLE
public class ADDR_Addresses_TDTM extends npsp.TDTM_Runnable Class is not defined as global

### ISSUE THREAD

**Issue by dschueler** [SalesforceFoundation/Cumulus#2115]
HELP!! I have a package that requires NPSP....all has been well but with 3.74 now when I go in to update the package, I get a bunch(maybe 25 or so) errors that will not let me open the package for update. The error message all look basically the same..for example:
public class ADDR_Addresses_TDTM extends npsp.TDTM_Runnable
Class is not defined as global
SF is saying "Please Edit and Resave the following items" obviously I can not on a managed package. 

I am needing to release this package so this has me dead in the water...help!

**Comment by judisohn** [comment]
Hi @dschueler Do you have access to the Power of Us Hub? If so, please post your question in the [Nonprofit Starter Pack group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) so the community can best help you troubleshoot.
