### ISSUE TITLE
Apex Doc combine groups Opportunity and Opportunities

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2117]
On the NPSP code base documentation site there are two groups one for Opportunity and another for Opportunities.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qw2oAAA" target="_blank">W-010702</a>

**Comment by njjc** [comment]
@kbromer is there a reason the lurch command didn't work for @jjbennett? Does she need to be added to a list of integration users?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
