### ISSUE TITLE
Add 'Disable Duplicate Management Rules' to Account Converter checklist

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2121]
https://powerofus.force.com/0D58000002lJRWb

In the 'Important Information' column we should add a checkbox for 'All Data.com Duplication Management Rules have been disabled.'

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qFTPAA2" target="_blank">W-010680</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
