### ISSUE TITLE
Manage Soft Credit page lookup icon partially hidden

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2127]
https://powerofus.force.com/0D58000002mBmcJ

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qxQFAAY" target="_blank">W-010713</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
