### ISSUE TITLE
fix workflow rule Opportunity Copy FMV to Amount 

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2128]
https://powerofus.force.com/0D58000002lIe9h

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qxQjAAI" target="_blank">W-010719</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
