### ISSUE TITLE
Correct Health Check reports so they accurately pull up results

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2130]
This https://powerofus.force.com/0D58000002mCg9G is coming up quite a bit. We should have made this report using the Accounts report type, not the Contacts & Accounts report type. There are Accounts that are properly linked to the correct Primary Contact so they're not coming up in the Health Check sweep for Accounts without Contacts, but their Contacts don't have the Account as their direct Account so they're not coming up in the Account Type report.

Recommendations:

* Add a report for 'Accounts by AccountType' using Accounts report type with same _SYSTEM:AccountType not equal to (blank) filter and reference that in the error about mix of account types
* Add a report for 'Individual Accounts without Linked Contact' using the Accounts report type with filters of _SYSTEM:AccountType not equal to (blank) and Primary Contact equals (blank) and reference that in the error about orphaned Accounts, which is what it's really looking for.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qxR3AAI" target="_blank">W-010723</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 7) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
