### ISSUE TITLE
No Save Button on NPSP Address Settings

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#2134]
In Google Chrome, after hitting edit on the NPSP Settings - People - Address Settings page, there is no ability to save the setting.

Gif of clickpath attached. Current work around is to manage the custom setting object directly.

![npsp-stgs](https://cloud.githubusercontent.com/assets/164/16536686/c24eae38-3fa9-11e6-94a9-7433f11906d3.gif)

**Comment by judisohn** [comment]
@cdcarter I'm not able to duplicate this error in my test org - there, I can disable/enable Household/Organization address and save in the section below the verification services (that are all unchecked in that org) without an issue. Might be related to you disabling verification in that demo while 'reject ambiguous' is still checked?

**Comment by cdcarter** [comment]
Yup.
