### ISSUE TITLE
Address Settings - verification service defaulting to SmartyStreets when nothing is set

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2138]
Occasionally, when no verification service is selected on the Address Settings Page and the user clicks Edit, SmartyStreets is auto selected.

**Comment by jjbennett** [comment]
**lurch: attach w-010266

**Comment by njjc** [comment]
@kbromer @LurchTheButler isn't working for @jjbennett, does she need to be added somewhere?

**Comment by kbromer** [comment]
Yup, just added her, should be set now

**Comment by njjc** [comment]
thanks!

**Comment by jjbennett** [comment]
**lurch: attach w-010266

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003n3aFAAQ" target="_blank">W-010266</a>

**Comment by njjc** [comment]
Yay!

**Comment by mrbelvedere** [comment]
Included in beta release version 3.76 (Beta 13) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.76
