### ISSUE TITLE
Relationship Viewer: 'Center on this Contact' link says 'Create New Relationship'

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2141]
Thread: https://powerofus.force.com/0D58000002njlX3

Replicated in Chrome.

![image](https://cloud.githubusercontent.com/assets/4614343/16617136/ec0d8718-434f-11e6-9eb0-fd9ce290f838.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003wRpbAAE" target="_blank">W-010780</a>
