### ISSUE TITLE
'Always Rollup to Primary Contact' should roll up to Household Account in Household Account model

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2149]
With both the One-to-One and Individual Bucket model, and Household creation set to 'All New or Edited Contacts' when 'Always Rollup to Primary Contact' is checked in NPSP Settings, the Opportunity is rolled up to the Contact, the Account on the Opportunity and the Contact's Household object record.

With the Household Account model, the Opportunity is not rolled up to the Household (the Contact's Account).

This behavior should be changed so it is consistent across all the 3 account models, without regression.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003wRrwAAE" target="_blank">W-010804</a>

**Comment by shawnholt** [comment]
Hi - so to be clear, If I'm using the household model, an opportunity that is linked to a non-household account and a primary contact is a a household member, the credit should roll up to the household - correct?

**Comment by judisohn** [comment]
It should (IMO), but that is not the behavior that is currently happening.

**Comment by shawnholt** [comment]
Just wanted to make sure we are on the same page. Also, if both users are linked to non household accounts but they are also household members (like affiliation rollup) I would expect the household rollup to work.  So wondering for suggestions to prioritize this bug fix or workaround.  I could create a completely custom declarative rollup. Any other approaches or suggestions to expedite remediation?  Thanks for the help!

**Comment by judisohn** [comment]
The issue here is *only* if their direct account on their contact record is a Household account, there is an Opportunity Contact Role record on a different Organization/business gift for the contact that is checked as 'Primary' and 'Always Rollup to Primary' is checked in Settings. In this scenario, the gift will appear on the Contact and the Organization/business account. It will not appear on the Household account record.

I'm not clear what you mean by "like affiliation rollup."

You'll need to use a 3rd party tool like Declarative Lookup Rollup Summaries or Rollup Helper. Standard Rollup Summaries won't work in this case.

**Comment by shecandoit** [comment]
any indication that this issue will make it through the upcoming sprint process?

**Comment by mpusto** [comment]
Our developers took a look at it and it requires completely re-architecting all of our rollups. This will require a lot of effort, and is very high on our priority list! However, because there will be such a big change to our entire codebase, it will take a bit longer than a few weeks. Thanks for your patience.

**Comment by tet3** [comment]
I want to put a vote in for making this optional. I get wanting to have the behavior consistent across Account models, but I also think that having the same Opportunity roll-up to more than one Account is kind of a terrible idea. IMO, the total for say, Account.npo02__OppAmountThisYear__c across all Accounts should be the same as a sum of Opportunity.Amount for the same period (and relevant RTs). I can see wanting to make this behavior available, though.

**Comment by judisohn** [comment]
I agree, Thomas. I don't like rolling up to two accounts either and advise unchecking the 'Always roll up...' box as a best practice. I think it was meant as an awkward hack for Contacts that were directly related to Organizations and then gave personally and there was no 1:1 account to associate to the opportunity. But it really should work consistently across models.

**Comment by shawnholt** [comment]
For a few clients an important use case is that a person gives a personal donation through their business.  This is different than a foundation, where the contact does not matter.  While soft-credit could apply, it has many different meanings and for at least two clients this is a true hard-credit to the household.

**Comment by judisohn** [comment]
But @shawnholt - in that case would the business also get hard credit? Even if the company passed the check through, if the gift is hard credited to the Household, shouldn't the Household account (or 1:1) be the Opportunity Account (and rolled up) and the payment be indicated as coming from the business's check in some other way (custom field on Payment or Opportunity is the most common way I've seen)?

**Comment by shawnholt** [comment]
HI @judisohn - good point.  We could create a custom field or other method to capture this.  The main challenge is that it is not an easy question to ask directly - especially using iats/form assembly.  For "donations" that come via an org, which is really coming from an individual, you can't really ask.  It is implied (based on campaign / opportunity type.)  On the other hand for accounting, the org is really making the donation.  Perhaps we could call it "soft credit" but it is a technically a hard donation. -including billing address, tax letter, etc.  If we ask the user for details - they will be about the org (like using a company credit card,) however we need to calculate (pledges, reporting, thank you letter, etc.) on the household.  I know it is not ideal to have hard credit in multiple places but in our case, that is easy to see by opportunity record type (ie. grants are really from orgs, donations are really from contacts/households).  If we were more judicious about soft-credit (eg, not using for influencer, and other ways) we could use it, but here it is really a more of a hard donation.  Also, this came up when the client had a mixed model.  It is less of an issue with pure HH model but I think having more control (like adding rolloup household similar to rollup to contact setting) and specify record type would solve a lot of this directly....

**Comment by njjc** [comment]
There isn't a feasible fix for this issue, unfortunately. People using this setting with the Household Account model will have to take into account that Orgnizational donations will roll up to the Contact, won't be reflected in their Household Account. We'll be updating our documentation about this setting as we release Customizable Rollups; I'm closing this issue as it will never be fixed.
