### ISSUE TITLE
Primary Opportunity Role Deleted when Default Role matches Household Role and HH changes

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2150]
On the Contact Role Settings Page, if the Opportunity Contact Role Default Role is the same as the Household Member Contact Role and the Opportunity is moved to a new Household, the trigger to create the Household Member Contact Roles is deleting the Primary Contact before adding in the members of the Current Household.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003wRsBAAU" target="_blank">W-010807</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.77 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.77
