### ISSUE TITLE
Prevent the Default Contact Role from being used for Soft Credit or Household Contact Roles

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2151]
Need to prevent the Opportunity Contact Role Default Role being the same Role as the Household or Soft Credit Contact Roles on the Contact Role Settings Page.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003wRsCAAU" target="_blank">W-010808</a>

**Comment by kbromer** [comment]
Probably can't be a validation rule (OCRs) but could be a healthcheck option

**Comment by jjbennett** [comment]
I updated the description, this is for the settings page.

**Comment by kbromer** [comment]
👍

**Comment by jlantz** [comment]
Included in beta release 3.85 (Beta 8)
