### ISSUE TITLE
NPSP Data Importer: When reporting a missing field error, would be nice to see the object name

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#2156]
![image](https://cloud.githubusercontent.com/assets/5971774/16749807/df401f2e-4781-11e6-8e52-da2aa33d7eaf.png)

In the attached image link, the error occurred because a custom field on Opportunity had been renamed in SF, but the reference to that custom field in the help text on the Data Imports object had not been changed.

It would be convenient for that error message to show the name of the object rather than just the field name: instead of 'General_Accounting_Unit__c', 'Opportunity.General_Accounting_Unit__c'.  That would make it easier to figure out which object to look in for the new field name.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6KQAAY" target="_blank">W-010813</a>

**Comment by njjc** [comment]
Closed, as the product development team has decided not to address this item.
