### ISSUE TITLE
new MHUI: don't allow adding the same contact more than once

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2160]
Search for a Contact and add them as Member to the Household
Search again and add the same Contact to the Household
Save
Get errors

![screen shot 2016-07-13 at 3 57 50 pm](https://cloud.githubusercontent.com/assets/204643/16822756/8bce77e4-4913-11e6-8d79-7073e6491577.png)

Suggest removing Contacts already added to the Household from search results; alternately, produce an error when attempting to add the same Contact a second time.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6LdAAI" target="_blank">W-010827</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.78 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release rel/3.78
