### ISSUE TITLE
expose Relationships package logic to external developers

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2161]
the Polaris project has provided a pull request here to the relationships package.  https://github.com/SalesforceFoundation/Relationships/pull/31

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6LxAAI" target="_blank">W-010830</a>

**Comment by ckoppelman** [comment]
I also added a boolean to make the method idempotent (updates duplicate names instead of adding new values each time).

**Comment by judisohn** [comment]
See comment on https://github.com/SalesforceFoundation/Relationships/pull/31
