### ISSUE TITLE
NPSP Deletes Non-Empty Accounts

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/Cumulus#2163]
The cleanup code at https://github.com/SalesforceFoundation/Cumulus/blob/rel/3.76/src/classes/ACCT_IndividualAccounts_TDTM.cls#L628 deletes HH accounts if they have no more contacts or opportunities.

However, an account is not necessarily empty at that point, it may have other custom related objects still in it.

I am running into this issue during an overnight integration that sometimes shuffles contacts between households (in a weird but meaningful way). Sometimes, that can cross the batch boundary, and leave a household "empty", even though it still has lots of related information. This behavior should be able to be turned off.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x7ipAAA" target="_blank">W-010834</a>

**Comment by kbromer** [comment]
Interesting, never considered the use case.  Feels like it should probably just be split out into its own trigger handler as a separate function.

**Comment by njjc** [comment]
I've removed the line that deletes the account as it causes unrecoverable data loss for the contact as well.

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
