### ISSUE TITLE
Update Opportunity Naming to correctly support multiple currencies

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2164]
**lurch: add

**Comment by njjc** [comment]
https://powerofus.force.com/0D58000002oWcWR

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xnqHAAQ" target="_blank">W-010837</a>

**Comment by njjc** [comment]
Duplicate of #1942

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xnqMAAQ" target="_blank">W-010838</a>
