### ISSUE TITLE
Improve display of health check solution message when it contains a SOQL query

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/Cumulus#2166]
As per this hub thread: https://powerofus.force.com/0D58000002oVW9G

When displaying a SOQL query in a Health Check solution message, the query should be made easier to copy by removing wrapping quotes and offsetting the SOQL query text.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xnqgAAA" target="_blank">W-010840</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
