### ISSUE TITLE
New Manage Household: Adding new contact to Household Account does not update Number of Household field

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2171]
STR:

* Household record with one member
* Launch Manage Household and add new Contact through field in upper right
* Save
* Result: Number of Household Members remains at 1

Repeat by adding a new Contact directly from the Contact related list on the Account and the Number of Household Members value increases as expected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xntfAAA" target="_blank">W-010875</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.78 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release rel/3.78
