### ISSUE TITLE
Icons not displaying in ManageHHUI and other SLDS pages under IE and Edge

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2173]
due to SVG icons not supported on these browsers.  there are some workarounds we need to implement.  we are not yet sure on which of our SLDS themed visualforce pages have this issue, but assume some do.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xnuYAAQ" target="_blank">W-010884</a>

**Comment by davidhabib** [comment]
note this thread mentions svg4everybody and locker service compatibility.
https://org62.lightning.force.com/one/one.app#/sObject/0D50M00002n6bcGSAQ/view

**Comment by jlantz** [comment]
Included in beta release 3.84 (Beta 1)
