### ISSUE TITLE
ManageHHUI hits save errors if NPSP error logging disabled

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2174]
Many of our save scenarios are hitting record lock issues on the account, as so many pieces of the save hit the account (merging, updating contacts, updating the hh from the LC component, updating the hh from the visualforce page fieldset).  Seems like UpdateNames() is usually the call that fails with the record lock.  With NPSP Error logging enabled, this error isn't treated as fatal, and just gets logged.  But with error logging disabled, this error gets propagated up to the page, and the save fails.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xnusAAA" target="_blank">W-010888</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.78 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.78
