### ISSUE TITLE
Household Merge No Longer Available

### ISSUE THREAD

**Issue by chrisgarland9** [SalesforceFoundation/Cumulus#2175]
The ability to merge a household as per the following article is no longer present since the UI changes I noticed.

https://powerofus.force.com/articles/Resource/NPSP-Merge-or-Split-Households

**Comment by davidhabib** [comment]
the new Manage Household UI works exactly the same.  If the Contact you choose is part of a multiperson household, you get prompted whether to add them all or just the single contact.  Can you provide more details on your scenario to clarify whether we have a bug vs. a misunderstanding.

**Comment by chrisgarland9** [comment]
Ahhh I see.  You are no longer prompted if adding a contact when they were the only contact in the household.

**Comment by chrisgarland9** [comment]
Thank you.
