### ISSUE TITLE
If OCR Role is one for soft credit rollup and marked as Primary, Contact gets both hard & soft credit

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2180]
thread: https://powerofus.force.com/0D58000002pcg8N

As discussed with @mpusto, desired behavior should be that if Primary is checked, Contact should receive hard credit only regardless of soft credit role selected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003yStHAAU" target="_blank">W-010904</a>

**Comment by jlantz** [comment]
Included in beta release 3.82 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.82
