### ISSUE TITLE
ability to "deep clone" grant deadlines

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2181]
Based on the this Idea: https://powerofus.force.com/hub-ideas/1062

Users should be able to "deep clone" grant opportunities to get all the associated items in one clone, rather than just copying the record without its associated deadlines.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySueAAE" target="_blank">W-010919</a>

**Comment by njjc** [comment]
Closed, as the product development team has decided not to address this item.
