### ISSUE TITLE
If Household object is hidden in security, new Manage Household will not work

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2186]
thread: https://powerofus.force.com/0D58000002qr06e

Pretty common to disable Household object in Household Account model to avoid confusion. Manage Household should still work on a Household Account in Household Account model.

![image](https://cloud.githubusercontent.com/assets/4614343/17189533/d8e6eea6-540f-11e6-81cb-f0874eedd3e9.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySvrAAE" target="_blank">W-010922</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.78 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.78
