### ISSUE TITLE
remove activity fields from Field Set in Household package

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2187]
hub thread: https://powerofus.force.com/0D58000002qr3rO?fromEmail=1&s1oid=00D00000000hWLM&s1nid=0DB800000004Fa7&s1uid=00580000005f4XR&s1ext=0&emkind=chatterCommentNotification&emtm=1469659807861&OpenCommentForEdit=1

since some of our users will disable activities on the Household object, we should remove the LastActivityDate field from the Manage Household UI field set on the Household object, or else users aren't able to install the package.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySwuAAE" target="_blank">W-010923</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.79 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.79
