### ISSUE TITLE
ManageHousehold load cursor obscured on Firefox, IE11, and Edge

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2188]
hub thread with picture: https://powerofus.force.com/0D58000002qrUhj

replicates on my Firefox 47.0.0 on Mac.  The cursor is beneath the visualforce elements, and the visualforce elements don't get disabled.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySyHAAU" target="_blank">W-010928</a>

**Comment by davidhabib** [comment]
I can also reproduce this on IE11 (Mac w/ Parallels) and Microsoft Edge (Mac w/ Parallels)

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
