### ISSUE TITLE
If Opp Naming date format is MMYY then an Opp on last day of year not in 2016 names in following year

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2191]
thread: https://powerofus.force.com/0D58000002qsrEk

Only happens with opportunities not in this year. 12/31/2016 works fine but 12/31/2015 shows as 1216 and 12/31/2017 shows as 1218. 

Tested and this only happens with MMYY and MMYYYY. All the same date formats work as expected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003z81uAAA" target="_blank">W-010937</a>

**Comment by njjc** [comment]
Resolution is to use lowercase y for year: http://stackoverflow.com/a/8686347
