### ISSUE TITLE
Lightning Experience stale cache when using a custom edit page.

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2193]
When using a custom edit page for modifying the record being viewed or related records is used, and redirects back to the same view page, the outdated cached version is shown.

**Comment by jjbennett** [comment]
**lurch: attach w-010363

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhnrAAA" target="_blank">W-010363</a>
