### ISSUE TITLE
NPSP installs no longer including Relationship Reciprocal data

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2194]
until recently, installs of NPSP from mrbelvedere included the 27 records in Relationship Lookup custom settings. Now those list settings are not included in the install, even after clicking NPSP Settings tab.

https://powerofus.force.com/0D58000002peSZn
https://powerofus.force.com/0D58000002qtRSt

If it helps, a Developer Edition created in late April 2016 includes the Relationship records:

![image](https://cloud.githubusercontent.com/assets/4614343/17309990/adf676f4-580f-11e6-94c1-e996449ad4fc.png)

One created today does not:

![image](https://cloud.githubusercontent.com/assets/4614343/17310047/f2cdc5ac-580f-11e6-9774-83c732b0555c.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003z81zAAA" target="_blank">W-010938</a>
