### ISSUE TITLE
If a formula field is used in Household Naming, Manage Household does not update correctly

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2198]
thread: https://powerofus.force.com/0D58000002qsUEn

likely related: https://powerofus.force.com/0D58000002reuLW

Steps to repeat:
1. Create Nickname custom field on Contact
2. Create Greeting custom formula field on Contact with formula: BLANKVALUE(Nickname__c, FirstName)
3. Use custom Greeting field as Informal Greeting value in NPSP Settings
4. Create Contact and update Nickname, have another Contact in the same Household
5. Confirm Informal Greeting on Account is correct
6. Use Manage Household to Exclude 2nd Contact from Informal Greeting

Result: Informal Greeting blank (if 3 members in household and one excluded, it will just say ' and ') This persists on Save.

Editing the Account does not fix, however running the Household Name batch job does fix the value.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003fQttAAE" target="_blank">W-010951</a>

**Comment by kbromer** [comment]
Is that true if you edit it in the standard UI as well?

**Comment by judisohn** [comment]
@kbromer Nope. Something is going on in the Manage Household save. When I repeat the steps but exclude a Contact by just editing the record and checking the field, on save the Informal Greeting on Account updates correctly immediately.

**Comment by kbromer** [comment]
Interesting!

**Comment by allisonletts** [comment]
I think this is related--I just have {!{!Nickname__c}} in the informal greeting field (a text field, not a formula) and I'm experiencing the same problem. Note that the preview in NPSP Settings looks funny as well.

![image](https://cloud.githubusercontent.com/assets/17914696/17366660/5c02890e-595a-11e6-9f2b-b965af1f5119.png)

**Comment by judisohn** [comment]
When you use a custom field, the preview won't ever show it so that's expected. Are you seeing the text field correctly in Manage Household and/or the record when you save it?

**Comment by allisonletts** [comment]
Not seeing it correctly either in Manage Household or when I save it.

**Comment by carlpaulsen** [comment]
A related thread found a similar problem using a workflow to update the informal greeting (https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000009gqymAAA&tab=sfdc.ProfilePlatformFeed).

Is this issue intended to cover that problem too, or is there another issue for that?

**Comment by davidhabib** [comment]
duplicate with #2341
