### ISSUE TITLE
Updating Address on Account sets 'Primary Address Type' to Home, but new contacts in HH do not have field populated

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2199]
reported by Donna Whittig

Steps to repeat:
1. Household Account with members without any data in Billing Address fields.
2. Edit account to populate Address. Save.
3. Note that the 'Primary Address Type' field on Contacts are populated with 'Home' automatically.
4. Now add a new Contact to the Household (either directly in UI or Manage Household).
5. Note that the new Contact does not have the same Primary Address Type as the other members (it's blank)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003fQtyAAE" target="_blank">W-010952</a>

**Comment by judisohn** [comment]
This may be related: https://powerofus.force.com/0D58000003O2j0K

**Comment by mrbelvedere** [comment]
Included in beta release 3.102 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.102
