### ISSUE TITLE
Account Converter not populating Household ID on Account custom field

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2202]
thread: https://powerofus.force.com/0D58000002rh4FT

@kbromer I duplicated in my test instance as well. Field didn't copy - length 255, definitely wouldn't have been an ID conflict issue. Perhaps worth a deeper look?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003fQzmAAE" target="_blank">W-010997</a>

**Comment by kbromer** [comment]
Coooooool, I love stuff that randomly breaks.

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
