### ISSUE TITLE
ManageHHUI Name & Greeting checkboxes not working correctly

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2203]
if you override the hh name, formal and informal greetings (all unchecked), then if you check one of them, the hh name and greetings get updated to the name spec.  This is obviously wrong.

Same thing happens if you uncheck any of the checkboxes.  All of the fields get refilled with the namespec version.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003fQzwAAE" target="_blank">W-010999</a>

**Comment by davidhabib** [comment]
not reproducable
