### ISSUE TITLE
ManageHouseholdUI does not work on Internet Explorer

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2205]
the page loads incompletely, and you see a runtime error object or method not supported 'startsWith'.

basically, some of our javascript code is using String.startsWith() which isn't supported in IE.  Note that it does not have this problem on Microsoft Edge.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g61WAAQ" target="_blank">W-011000</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
