### ISSUE TITLE
Manage Household: fail to add Contact to HH from search results Firefox/Windows

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2207]
Reported by three users in the Hub, I was able to reproduce the problem often enough to report the issue in detail. 

In the Manage Household UI, search for Contacts and get results. Normal behavior is to click the circle-plus button for a Contact from the search results in order to add the Contact to the Household page as a "card" on the page. In normal behavior, we see the search results disappear immediately, then the page briefly goes grey as code formulates the Contact card and adds it to the page.  The 'processing' pulsing circle of dots may or not appear as this happens. 

At least some of the time in later versions of Firefox on multiple versions of Windows, we see a problem.  Search for Contacts, get results. Click the circle-plus button to add one Contact to the Household. We see the search results disappear immediately as normal, but nothing else happens. The page does not go grey, no contact card is created, the contents of the Manage Household page do not change after attempting to add the Contact, and no changes to the page appearance or behavior are apparent.

No screenshot because there is nothing useful to show, unfortunately. 

NOTE: upon first loading the MHUI page, one sees in the Console a javascript error "unreachable code after return statement". This error does not seem to be a result of any operations of the page. It seems to be traceable to a piece of localization software unrelated to MHUI code.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g62tAAA" target="_blank">W-011015</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
