### ISSUE TITLE
contactDeleteOverride - not available in Lightning

### ISSUE THREAD

**Issue by lyndsayneer** [SalesforceFoundation/Cumulus#2208]
The Contact Delete Override visualforce page is not available for lightning pages. If the instance is on Lightning then they must update the Delete button to the Standard Salesforce.com Page in order for the Delete quick action to be available to add to the Salesforce 1 and Lightning Experience Actions section of the page layout.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV3VAAU" target="_blank">W-011173</a>

**Comment by jlantz** [comment]
Included in beta release 3.84 (Beta 2)
