### ISSUE TITLE
Compilation errors in HH_ManageHousehold_TEST and HH_ManageHHAccount_TEST

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2211]
Class	HH_ManageHousehold_TEST
Pass/Fail	CompileFail
Error Message	line 430, column 14: Invalid type: HH_ManageHousehold_EXT.viableAddress

Class	HH_ManageHHAccount_TEST
Pass/Fail	CompileFail
Error Message	line 439, column 14: Invalid type: HH_ManageHousehold_EXT.viableAddress

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g638AAA" target="_blank">W-011017</a>

**Comment by njjc** [comment]
Never mind, the issue was that my dev org didn't delete deprecated test classes.
