### ISSUE TITLE
Households package still referencing deprecated fields?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2212]
based on the errors reported by some users trying to install Households 3.4 with the installer, I believe our French and Spanish translation fields may still have references to the fields we recently deleted out of Contacts and Orgs 3.3

Households - 3.4
 
Managed Package
Install Failed
(Households_and_Donations) In field: field - no CustomField named Contact.npe01__Last_Donation_Date__c found, Details: Households_and_Donations: In field: field - no CustomField named Contact.npe01__Last_Donation_Date__c found (Household_Reports/Households_and_Donations) invalid report type, Details: Household_Reports/Households_and_Donations: invalid report type (es) In field: name - no ReportType named Households_and_Donations found, Details: es: In field: name - no ReportType named Households_and_Donations found (fr) In field: name - no ReportType named Households_and_Donations found, Details: fr: In field: name - no ReportType named Households_and_Donations found

**Comment by davidhabib** [comment]
**lurch: add

**Comment by davidhabib** [comment]
@njjc Hey Nic, are you in a position where you could look into this today or tomorrow?

**Comment by njjc** [comment]
Sure.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g63NAAQ" target="_blank">W-011019</a>

**Comment by njjc** [comment]
This was fixed in SalesforceFoundation/Households#53
