### ISSUE TITLE
Manage Household page doesn't work for New household object

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2222]
hub thread: https://powerofus.force.com/0D58000002tINz9

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003gn1bAAA" target="_blank">W-011056</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.88 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
