### ISSUE TITLE
Manage Household page doesn't put Primary Contact first in names & greetings

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2225]
hub thread: https://powerofus.force.com/0D58000002tIuNL

info from david: OK, so the naming code orders the contacts this way:
Primary_Contact__c, npo02__Household_Naming_Order__c ASC NULLS LAST, CreatedDate '

But I realize that the Manage Household page is only using npo02__Household_Naming_Order__c when you drag contacts around and the name gets updated.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003gn3SAAQ" target="_blank">W-011070</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
