### ISSUE TITLE
BUG: Adding Contact in Manage Household w/Household Object adds Contact to its own Household

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2232]
Thread: https://powerofus.force.com/0D58000002uMbOA

Duplicated issue following described STR:

Set Account model to 1:1 and Household creation to 'All New or Edited Contacts'

1) From Jane Smith contact record, access household by clicking "Smith Household"
2) Click "Edit" button on household record
3) Use search box that reads "Find a contact or add a new contact to the household" to search for "John Smith"
4) John Smith is not found, so click "+ New Contact"
5) New Contact box appears with John Smith's name already populated. Click blue "New Contact" button
6) John Smith now appears to be included as a household member. Click blue "Save" button in upper right-hand corner.
Results: Back on the household page, there is still only one household member (Jane Smith). There is a new record for John Smith, but he's a member of a new Smith Household.

Note: The Household is named correctly if First Names are in naming formula - example 'Jane and John Smith Household' but the contacts are in separate households, so the issue is happening at some point later in the process.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tp9fAAA" target="_blank">W-011098</a>

**Comment by jlantz** [comment]
Included in beta release 3.81 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.81
