### ISSUE TITLE
update Manage Allocations page UI to be consistent with Manage Soft Credits UI

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2233]
Related to [Issue 2227](https://github.com/SalesforceFoundation/Cumulus/issues/2227), the presentation of error messages in the Manage Allocations UI should be evaluated and modified to provide a consistent experience. This would include modifying the error message presentation to match styling of the Manage Soft Credits UI as well as having the doc team review the messages for consistency.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tpA4AAI" target="_blank">W-011102</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvUIAA0" target="_blank">W-017038</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110
