### ISSUE TITLE
Having more than 10k error records causes NPSP Settings delete method to fail

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2238]
https://powerofus.force.com/0D58000002uPVYc

**lurch: add

**Comment by kbromer** [comment]
Check the version. This was a problem in v2 i thought we fixed.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tpEQAAY" target="_blank">W-011151</a>

**Comment by njjc** [comment]
@kbromer [it doesn't look like it was fixed.](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/STG_PanelErrorLog_CTRL.cls#L123)

**Comment by kbromer** [comment]
Go us.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tpEVAAY" target="_blank">W-011152</a>

**Comment by njjc** [comment]
@kbromer lurch seems confused...

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV2SAAU" target="_blank">W-011160</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.80 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.80
