### ISSUE TITLE
npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by AnkurJaiswal619** [SalesforceFoundation/Cumulus#2240]
We are doing bulk donation upload for contacts using CSV file upload from a VF page. When contacts in CSV go beyond 180, we get this error: npsp:Too

[Logs.txt](https://github.com/SalesforceFoundation/Cumulus/files/442470/Logs.txt)

 many query rows: 50001

Currently there are lot of donations records against every contact in production and hence the package is throwing this error as some where the query is not filtered. Can you please help us by analyzing the log file attached below.

Also below are few lines from debug logs:
19:33:11.723 (93222233461)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93223215439)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93223428115)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93223508745)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93223552436)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93224010586)|SOQL_EXECUTE_BEGIN|[222]|Aggregations:0|select id from FiscalYearSettings  where IsStandardYear = false
19:33:11.723 (93226661191)|SOQL_EXECUTE_END|[222]|Rows:0
19:33:11.723 (93226851926)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93226898112)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93227132756)|ENTERING_MANAGED_PKG|npsp
19:33:11.723 (93228176429)|SOQL_EXECUTE_BEGIN|[449]|Aggregations:0|SELECT ContactId, Fiscal_Year(Opportunity.CloseDate) CalendarYr, SUM(Opportunity.Amount) TotalOppAmount, AVG(Opportunity.Amount) AverageAmount, MIN(Opportunity.Amount) SmallestAmount, MAX(Opportunity.Amount) LargestAmount, MIN(Opportunity.CloseDate) FirstCloseDate, MAX(Opportunity.CloseDate) LastCloseDate, COUNT_DISTINCT(Opportunity.Id) NumberOfClosedOpps, MAX(Opportunity.npo02__CombinedRollupFieldset__c) RollupFieldset FROM OpportunityContactRole WHERE isPrimary=true AND Opportunity.isWon=true AND Opportunity.Amount != null AND Opportunity.RecordTypeId NOT IN :rectypeset AND Opportunity.Type NOT IN :typeset AND ContactId IN :cset GROUP BY ROLLUP(ContactId, Fiscal_Year(Opportunity.CloseDate)) 
19:33:15.212 (96212454604)|SOQL_EXECUTE_END|[449]|Rows:1363
19:33:15.212 (96212917697)|CUMULATIVE_LIMIT_USAGE
19:33:15.212 (96212917697)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 43 out of 200
  Number of query rows: 2114 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 10 out of 150
  Number of DML rows: 1459 out of 10000
  Maximum CPU time: 20512 out of 60000
  Maximum heap size: 0 out of 12000000
  Number of callouts: 0 out of 0
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 0
  Number of queueable jobs added to the queue: 0 out of 1
  Number of Mobile Apex push calls: 0 out of 10

19:33:15.212 (96212917697)|LIMIT_USAGE_FOR_NS|MC4SF|
  Number of SOQL queries: 3 out of 200
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 25 out of 10000
  Maximum CPU time: 0 out of 60000
  Maximum heap size: 0 out of 12000000
  Number of callouts: 0 out of 0
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 0
  Number of queueable jobs added to the queue: 0 out of 1
  Number of Mobile Apex push calls: 0 out of 10

19:33:15.212 (96212917697)|LIMIT_USAGE_FOR_NS|npsp|
  Number of SOQL queries: 47 out of 200
  Number of query rows: 58547 out of 50000 ******* CLOSE TO LIMIT
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 61 out of 150
  Number of DML rows: 1159 out of 10000
  Maximum CPU time: 0 out of 60000
  Maximum heap size: 0 out of 12000000
  Number of callouts: 0 out of 0
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 0
  Number of queueable jobs added to the queue: 0 out of 1
  Number of Mobile Apex push calls: 0 out of 10

19:33:15.212 (96212917697)|LIMIT_USAGE_FOR_NS|SurveyMonkey|
  Number of SOQL queries: 13 out of 200
  Number of query rows: 607 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 60000
  Maximum heap size: 0 out of 12000000
  Number of callouts: 0 out of 0
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 0
  Number of queueable jobs added to the queue: 0 out of 1
  Number of Mobile Apex push calls: 0 out of 10

19:33:15.212 (96212917697)|CUMULATIVE_LIMIT_USAGE_END

19:33:15.537 (96537030812)|DML_END|[510]
19:33:15.537 (96537233113)|FATAL_ERROR|System.LimitException: npsp:Too many query rows: 50001

(npsp)

**Comment by kbromer** [comment]
That's the donation aggregation function running - it has to aggregate donor stats for all hard and soft credits associated with the donation.  Generally speaking, when importing donations we recommend reducing batch size or deferring your calculations until all donations are added, then running the batch update job.

**Comment by AnkurJaiswal619** [comment]
@kbromer Thank you very much for your help. By reducing batch size do you suggest we reduce the Rollup Batch Size in NPSP settings? This is currently set as 200.

**Comment by kbromer** [comment]
Correct
