### ISSUE TITLE
Manage Soft Credits page does not allow delete of row

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2242]
Manage Allocations allows individual rows to be deleted, but Manage Soft Credits does not.  If a user adds a row by mistake, they are forced to start over creating Soft Credits rows from scratch. If for example they add a fourth or fifth or sixth row by mistake, having to start over could be a hardship.

**Comment by chrismcmahon** [comment]
**lurch: add

**Comment by judisohn** [comment]
@kbromer - It doesn't look like @chrismcmahon can Lurch?

**Comment by kbromer** [comment]
@chrismcmahon should be good to go now

**Comment by judisohn** [comment]
@chrismcmahon try lurch again on this one.

**Comment by chrismcmahon** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV5wAAE" target="_blank">W-011202</a>

**Comment by jlantz** [comment]
Included in beta release 3.84 (Beta 4)
