### ISSUE TITLE
In Household Naming, don't insert NULL if Name Connector or Name Overrun are empty

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2247]
hub thread: https://powerofus.force.com/0D58000002vOlPZ

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV5bAAE" target="_blank">W-011197</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
