### ISSUE TITLE
NPSP Settings for RecordTypes should be Text(255), not Text(100)

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2251]
we need to look at all of our packaged settings and increase any multiselect settings to text(255).  When we changed our record type exclusion settings from using record type names to id's, some users were no longer able to save all of their exclusions.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003vBZSAA2" target="_blank">W-011257</a>

**Comment by judisohn** [comment]
This also causes upgrades to NPSP 3.79 or later to fail as the post install script can't run successfully.

**Comment by jjbennett** [comment]
Fixed in Households repo.
