### ISSUE TITLE
Entering a new EP Task in UI removes data from previous task

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2253]
Steps to repeat:

1. Open an EP Template record
2. Click Manage Template
3. Add a Task (including Subject and details)
4. Add a 2nd Task

Note that the previous entered task is now blank.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003vBakAAE" target="_blank">W-011259</a>

**Comment by jlantz** [comment]
Included in beta release 3.81 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.81
