### ISSUE TITLE
Contact role settings do not display correctly

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2257]
Steps to reproduce:
1. Go to NPSP Settings-->Donations-->Contact Roles
2. Click edit.
3. Modify Soft Credit Roles to include various roles.
4. Click Save.  No roles look selected, although the data is saved.

This is found in Chrome, Safari, Firefox. 

![image](https://cloud.githubusercontent.com/assets/10934541/18355996/abcc7eb4-75b0-11e6-829f-6ecd0072efd5.png)

![image](https://cloud.githubusercontent.com/assets/10934541/18356006/b5c91a3a-75b0-11e6-9021-c08b18b07c59.png)

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l8PAAQ" target="_blank">W-011268</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l8UAAQ" target="_blank">W-011269</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l8ZAAQ" target="_blank">W-011270</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l8eAAA" target="_blank">W-011271</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002w26qAAA" target="_blank">W-011358</a>

**Comment by jlantz** [comment]
Included in beta release 3.82 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.82
