### ISSUE TITLE
Level custom field not selectable in interface

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2261]
Custom field on Account for 'Level' (tried picklist and text). 

Field is not selectable on Levels screen:

![image](https://cloud.githubusercontent.com/assets/4614343/18381361/d5f2c89e-7649-11e6-8b8c-029aad1960dd.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l9NAAQ" target="_blank">W-011277</a>
