### ISSUE TITLE
VF error on Level Edit

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2262]
With override on Edit, Level is not editable (all fields are populated on level, except for Engagement Plan).

Error text: SObject row was retrieved via SOQL without querying the requested field: npsp__Level__c.npsp__Description__c 

Note - this only happens in beta, not in unmanaged org so may be packaging related(?)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l9SAAQ" target="_blank">W-011278</a>

**Comment by jlantz** [comment]
Included in beta release 3.81 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.81
