### ISSUE TITLE
Level populates as Record ID instead of Record Name

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2263]
After batch run:

![image](https://cloud.githubusercontent.com/assets/4614343/18381991/fffeaf1a-764c-11e6-89ab-44a8a62fbfa8.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040l9XAAQ" target="_blank">W-011279</a>
