### ISSUE TITLE
Manage Household page does not load in Winter '17 instances

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2265]
Attempting to load the Manage Household page in Winter '17 (Classic or Lightning Experience) results in an error and the page does not load:

![image](https://cloud.githubusercontent.com/assets/4614343/18400656/dd03d866-76a4-11e6-9547-99df4a12205c.png)

Team is aware of the cause and is working on a solution.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040lA6AAI" target="_blank">W-011283</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tpB7AAI" target="_blank">W-011115</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040lAGAAY" target="_blank">W-011285</a>
