### ISSUE TITLE
EPs can't be added for objects that are detail in master/detail relationship

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2266]
STR: 

1. Add lookup on Engagement Plans to object that is detail to another object master, such as Address.
2. Create an Engagement Plan on that object.

Error in NPSP Error Log: "No such column 'OwnerId' on entity 'npsp__Address__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names."

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000040lALAAY" target="_blank">W-011286</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
