### ISSUE TITLE
Winter '17, Icon Buttons look wrong in Manage Household UI

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2287]
In the Manage Household page, many of the graphic buttons no longer render correctly.  They now seem to have a white background (vs. transparent), and also a visible outline.  Here are some examples.

![image](https://cloud.githubusercontent.com/assets/908119/18645362/b5d3a3c4-7e61-11e6-8a99-882324ff4250.png)

**Comment by davidhabib** [comment]
![image](https://cloud.githubusercontent.com/assets/908119/18645389/dc1096fa-7e61-11e6-9359-5fb0e495f77c.png)

**Comment by davidhabib** [comment]
![image](https://cloud.githubusercontent.com/assets/908119/18645418/f49a8410-7e61-11e6-983a-e6e32f9bf4ea.png)

**Comment by davidhabib** [comment]
inspecting the button element, I can see it is due to the following styles:

.sfdo203 .slds-button--neutral {
    padding-left: 1rem;
    padding-right: 1rem;
    text-align: center;
    vertical-align: middle;
    border: 1px solid #d8dde6;
    background-color: #fff;
}

If I disable border and background-color, then they look fine.  So the question is since we are using .sfdo203, why is this happening?

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjCnAAI" target="_blank">W-011364</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
