### ISSUE TITLE
Winter '17, Manage Household page hits error copying address to added contact

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2289]
in Winter '17, if you add an existing contact to the household with the autocomplete control, you will see the error "unable to read sobject" get displayed in the header, and the household's street will copy to the added contact, but not city, state, or zip.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjCsAAI" target="_blank">W-011365</a>
