### ISSUE TITLE
Engagement Plan Tasks assigned to record owner regardless of Default Assignee on Template

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2291]
thread: https://powerofus.force.com/0D58000002xSHBk

STR:

1. Create contact and set ownership to another user
2. Engagement Plan Template with Default Assignee 'User Creating Engagement Plan' and at least 1 task
3. Engagement Plan using that Template for that Contact

Result: Tasks assigned to owner of Contact when it should be your user.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjDWAAY" target="_blank">W-011373</a>

**Comment by njjc** [comment]
Whoops, thanks!

**Comment by jlantz** [comment]
Included in beta release 3.82 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.82
