### ISSUE TITLE
Deleting a blank Engagement Plan Task from within Engagement Plan Manage Template requires task subject

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2292]
reported in a comment here: https://powerofus.force.com/0D58000002wyimz

![image](https://cloud.githubusercontent.com/assets/4614343/18683869/0040e87a-7f40-11e6-9fff-3996901d9d7d.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjDlAAI" target="_blank">W-011375</a>

**Comment by jlantz** [comment]
Included in beta release 3.82 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.82
