### ISSUE TITLE
Winter '17, in LEX Account/Opportunity do not load if AccountViewOverride is on Account view button

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2293]

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjDqAAI" target="_blank">W-011376</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjDvAAI" target="_blank">W-011377</a>

**Comment by mpusto** [comment]
**lurch: attach W-011305

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000041TDzAAM" target="_blank">W-011305</a>

**Comment by cdcarter** [comment]
morbid curiosity here - what's the resolution/reason for closure here?

**Comment by davidhabib** [comment]
I believe it was a core bug that has been verified as fixed in 204.7
