### ISSUE TITLE
With Locker Service on, Manage Household page's drag/drop of contacts is broken

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2294]
With Locker Service on in Summer '16 or Winter '17, the drag/drop behavior for contact cards is broken.  The card being dragged gets displayed in the wrong location, and the drop has already gone thru and reordered the cards.

This is a LockerService bug that was reported in GUS, and has been marked fixed in release 206 which is Spring '17, which we can't yet verify.

Gus bug: W-3273335 
https://gus.lightning.force.com/one/one.app#/sObject/a07B0000002DaZJIA0/view

Gus bug: W-3346489
https://gus.lightning.force.com/one/one.app#/sObject/a07B0000002DaZJIA0/view

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjEZAAY" target="_blank">W-011385</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.88 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
