### ISSUE TITLE
Find Matching Gifts page, Selected and Unselected Totals are not updating

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2297]
When checking items in the list for potential matching gifts, the total selected and unselected amounts are not updating.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002wjEyAAI" target="_blank">W-011389</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 9)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
