### ISSUE TITLE
Hi, We are trying to run a batch in our Salesforce org, but the batch s failing and giving as exception as follows, NPSP: Too many DML Statements:151, this used to run perfectly in sandbox but after NPSP is updated, it is causing issue in sandbox also

### ISSUE THREAD

**Issue by abhimahajan50** [SalesforceFoundation/Cumulus#2303]
![npsp_error](https://cloud.githubusercontent.com/assets/15623627/18781589/18a9ee2c-81a0-11e6-8ffa-8384f23f7f44.png)

**Comment by judisohn** [comment]
Hi @abhimahajan50 It's a rather generic error and impossible to guess at this point. It depends entirely on the custom or app code in the batch and what it is doing, and it may or may not have anything to do with NPSP. If you are working with a developer, you'll need them to analyze the debug logs to see exactly where the error is being generated and what is happening around it that can be optimized.
