### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2306]
![rgb_npsp-full-color](https://cloud.githubusercontent.com/assets/450473/18836784/15e1774a-83c7-11e6-8434-0521d4fbebc0.png)

**Comment by johnranaudo** [comment]
I would like to participate with this update. Where exactly does the logo need to be updated?

**Comment by judisohn** [comment]
Thanks @johnranaudo - but I believe @jjbennett already self-assigned this and it's a bit of a placeholder. Maybe next time!

**Comment by jjbennett** [comment]
Yes, this is all set. I will close it now. Thank you!
