### ISSUE TITLE
Contact Merge breaks with Portal Users

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#232]
Portal users require an Account at the point of merge, but the current implementation of the NPSP Contact merge remove the Account just prior to the merge to avoid triggering the 1x1 trigger.   Workaround is explained in the code comments here:
https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CON_ContactMerge.cls#L109

**Comment by davidhabib** [comment]
I just tested this with HH contacts, one being a portal user.  merging the non-portal into the portal user contact succeeded fine.  Going the other way gave this error:

Errors

Merge failed. First exception on row 0 with id 001G000001o7FAUIA2; first error: MERGE_FAILED, When merging portal enabled accounts, the master record must be portal enabled.: []
Failed to merge the contacts. Error: System.DmlException: Merge failed. First exception on row 0 with id 001G000001o7FAUIA2; first error: MERGE_FAILED, When merging portal enabled accounts, the master record must be portal enabled.: []

I think this is completely acceptable to allow this error to display to the user, which it does nicely on our page.  I will now test OnetoOne accounts to see what we run into.

**Comment by davidhabib** [comment]
Actually, that test was done with single member household accounts, so our one2one handling is the same.  So I think this is ok behavior and there is nothing more to do.  @kbromer @judisohn do you two agree?

**Comment by davidhabib** [comment]
@judisohn this is the bug I want your feedback on.

**Comment by judisohn** [comment]
Yes, got it this time. Not sure what happened with the notification before. 

Anyway, yes, I think the error is fine as it clearly says what the problem is and points user in right direction to resolve it.
