### ISSUE TITLE
Enforce Required on Priority field on Engagement Plan Task

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2321]
thread: https://powerofus.force.com/0D580000030CD8v

The Visualforce page does not allow option to set Priority to None, but this can be done easily in standard edit. We should enforce that the Priority field on Engagement Plan Task is always populated, even if not editing from VF page.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000048DM0AAM" target="_blank">W-011498</a>

**Comment by jlantz** [comment]
Included in beta release 3.83 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.83
