### ISSUE TITLE
Household Mailing List button on Campaign does not function correctly in Lightning Experience

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2324]
The button correctly adds 'Household Duplicate' to the Campaign Member Status, however the report one lands on is filtered based on Campaign ID (which returns no results) rather than correctly selecting the Campaign. Workaround is to edit the report configuration to see results.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000048DchAAE" target="_blank">W-011618</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.112 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.112
