### ISSUE TITLE
"The record you attempted to access has been deleted" error when clearing Account field on Contact

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2329]
Error message: "The record you attempted to access has been deleted. The user who deleted this record may be able to recover it from the Recycle Bin. Deleted data is stored in the Recycle Bin for 15 days."

I'm seeing this error in the following scenario:
- Contact Record Type is originally something other than "Household Contact"
- Contact is attached to an Account with a record type other than "Household Account"
- Contact has blank address fields
- User changes the record type to "Household Contact" and clicks Save
- User edits the Contact again and clears the Account field (the goal is to allow the NPSP to create a new Household Account for the Contact)
- User clicks Save

It will work if the Contact has any values in the Address fields.

I've reproduced this in both Production and Sandbox with NPSP v3.82.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000048wmeAAA" target="_blank">W-011655</a>

**Comment by davidhabib** [comment]
@force2b I cannot reproduce this.  Are you still seeing this problem?  Are you sure it is not related to your contact record types (which NPSP does not have or use)?  Can you provide a debug log that includes the error?  Do you know what ID and object it is saying has been deleted?  What is in your recycle bin when you encounter this?

**Comment by davidhabib** [comment]
@force2b Hi Michael, any update on this?  thanks.

**Comment by force2b** [comment]
Sorry. I've been swamped. It's on my queue, but might be another week or so.

**Comment by davidhabib** [comment]
@force2b can you reproduce this still?  if not, we need to close this issue.  thanks.

**Comment by force2b** [comment]
@davidhabib Sorry for the delay. I set up a new org with NPSP3 installed, created the additional Contact record types to match the steps outlined above. Unfortunately I still could not reproduce this. It's really odd because the clients org doesn't have any customizations around the Address object, but clearly something is unique about that orgs config. I'll close this issue and dig around in their org more to see if I can find a true root cause. Sorry for adding any confusion.

**Comment by davidhabib** [comment]
Thanks for testing again @force2b
