### ISSUE TITLE
Engagement Plan Template: Subject field should be marked as required before Save

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2334]
It would be convenient to the user if Subject in EPTemplate had the small red star or other indication that it is a required field. As it is, user is notified of that only upon attempting to save with a task with no Subject 

![screen shot 2016-10-25 at 2 43 54 pm](https://cloud.githubusercontent.com/assets/204643/19705504/b0093a4a-9ac1-11e6-84f0-ed17e63bb629.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000049ihsAAA" target="_blank">W-011683</a>

**Comment by davidhabib** [comment]
caution that if there are any fields that are doing action callbacks/refresh, they won't work if subject isn't filled in.  I think I may have actually changed this to not be required up front due to this issue (or maybe that was in the Levels page?).

**Comment by jlantz** [comment]
Included in beta release 3.85 (Beta 9)
