### ISSUE TITLE
Engagement Plan Template allows infinite sub-tasks

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2335]
Users may create an arbitrarily large number of sub tasks for an Engagement Plan Template. This could potentially be harmful. 

![screen shot 2016-10-25 at 2 47 27 pm](https://cloud.githubusercontent.com/assets/204643/19705569/0de04c9e-9ac2-11e6-9ca2-3e6ffa91bf50.png)

**Comment by judisohn** [comment]
@chrismcmahon I don't know... what do you mean by 'harmful'? Not sure I agree that we should impose an arbitrary limit, and if so what that amount should be. I don't think it should be limited by the interface. @mpusto what do you think?

**Comment by mpusto** [comment]
Until this is reported as an issue for performance, I don't think we would consider this a problem.
