### ISSUE TITLE
Manage Household does not display greetings with custom formula fields 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2341]
thread: https://powerofus.force.com/0D580000032G2rQ

Duplicated in test org

1. Create formula on Contact to only display first initial of last name (left(FirstName))
2. Incorporate field in to Household naming rule (formal: {!{!Salutation} {!First_Initial_of_First_Name__c}} {!LastName})

Create Contact first - Household Formal Greeting is correct

However, if you create Account without Contacts, then use Manage Household to add contacts, the greetings are not displayed correctly with the custom field:

![image](https://cloud.githubusercontent.com/assets/4614343/19891289/d1f8324c-a015-11e6-9106-9a463b90e042.png)

If any attempt is made to manipulate the name within the Manage Household interface, the incorrect name remains and won't update correctly despite CUSTOM NAMING field remaining blank.

If the Manage Household page is not touched (auto name not togged), then on Save the record is updated correctly:

![image](https://cloud.githubusercontent.com/assets/4614343/19891399/5c031f38-a016-11e6-95fd-a8589de29ec2.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWsrAAG" target="_blank">W-016738</a>
