### ISSUE TITLE
In LEX, overriden Edit button on Engagement Plan Template does not appear if standard Salesforce1 button defaults are overriden

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2346]
In LEX, if the Engagement Plan Template page layout is using standard Salesforce1 & Lightning buttons:

![image](https://cloud.githubusercontent.com/assets/4614343/20004835/dfbc0b78-a264-11e6-9cdf-79f7a3b05e1b.png)

Then the Edit button appears and behaves as it should, but we are stuck with New Case, New Contact and New Lead buttons which makes no sense for our use cases:

![image](https://cloud.githubusercontent.com/assets/4614343/20004852/01f5f4c4-a265-11e6-938c-2b778e16e0d1.png)

If the predefined buttons are overriden so we can customize the buttons that appear, we are missing the Edit button!

![image](https://cloud.githubusercontent.com/assets/4614343/20004864/1ea33190-a265-11e6-8ad6-a2503fd83621.png)

This behavior was replicated in two different orgs. Not sure if the issue is platform or in the Edit button VF code.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWzFAAW" target="_blank">W-016787</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.85 (Beta 2)
