### ISSUE TITLE
NPSP Error Logs sent to inactive instances

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2348]
Report of NPSP Error Log sent to Administrator of an organization that was last active in 2014. Customer/Partner has no way to log in and resolve the error.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004BqxzAAC" target="_blank">W-016801</a>

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
