### ISSUE TITLE
As a developer, I want to increase the test coverage of HH_HouseholdNaming_BATCH

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#235]
The dev console says it's at 13% right now

**Comment by davidhabib** [comment]
**lurch: attach W-007353

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZbAAI" target="_blank">W-007353</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.

**Comment by codexmarcel** [comment]
Included in production release 3.188
