### ISSUE TITLE
Changes in NPSP Settings to Recurring Donations Settings do not save in Custom Settings

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2351]
Steps to repeat:

1. Open Recurring Donations custom settings in one tab, and NPSP Settings in another. 
2. Edit something on NPSP Settings > Recurring Donations > Recurring Donations (such as changing the max donations, the record type, etc) 
3. Reload the Recurring Donations Settings page and note that nothing has updated. 

Editing the Custom Setting directly does save and show correctly in NPSP Settings.

Updates to other areas, such as Payment or Donation settings are updated in Contact & Organizations Settings as expected, but further testing should make sure no other Settings are affected.

This was replicated in a customer org as well as a test org.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004BqzRAAS" target="_blank">W-016819</a>

**Comment by jlantz** [comment]
Included in beta release 3.84 (Beta 6)
