### ISSUE TITLE
Customer Community User not able to create contact

### ISSUE THREAD

**Issue by abhimahajan** [SalesforceFoundation/Cumulus#2354]
We are trying to insert contact from community portal, with Customer Community Login user as the logged in user. However we are unable to do so from 2nd Nov. (NPSP update).
We are getting following exception on our community VF page,

npsp.TDTM_Contact: execution of BeforeInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: OP_WITH_INVALID_USER_TYPE_EXCEPTION

We are using NPSP one-to-one account model.
[DebugLog.txt](https://github.com/SalesforceFoundation/Cumulus/files/580378/DebugLog.txt)

Any suggestions of what is the issue or is this has to do anything with Customer Community Login user license?

**Comment by judisohn** [comment]
Hi @abhimahajan There is a conversation about this topic [here](https://powerofus.force.com/0D5800000335FXl).

**Comment by abhimahajan** [comment]
Hi @judisohn the conversation link that you have provided, that question was asked by one of our company's employee. She is facing the same issue.
In my previous comment, I have added the debug file, as you can see in the debug log after contact is inserted, it is going in NPSP package and we have no clue what is happening inside. Can you please let us know after contact insertion what NPSP is doing and at what point this exception has occurred. So that we can have an idea what changes we need to do.

**Comment by judisohn** [comment]
Go ahead and [open a support case](https://powerofus.force.com/articles/Resource/How-to-log-a-tech-support-ticket-with-salesforce-com) so someone can pull a debug log that includes NPSP code.
