### ISSUE TITLE
Error Log Messages getting truncated

### ISSUE THREAD

**Issue by cgage-redf** [SalesforceFoundation/Cumulus#2355]
When NPSP logs an error, the text in the Full Message field is getting truncated to 255 characters. This happens despite the fact that this field is defined on the Error object as a Long Text Area with a capacity for 32,768 characters.

**Example:**
First error: Update failed. First exception on row 0 with id 0031500001byND9AAM; first error: CANNOT_EXECUTE_FLOW_TRIGGER, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 301...

**Comment by njjc** [comment]
@cgage-redf Can you check under Apex Jobs and see if this error originated there?

**Comment by cgage-redf** [comment]
Yes, it originated there. Does this mean there's nothing to be done on the NPSP side?

**Comment by njjc** [comment]
Yes, we're just reporting it and we're limited to the message reported in Apex Jobs. You can get the full message by enabling debug logs for the scheduling user of whatever job is failing, or by having the developer console open when it runs.
