### ISSUE TITLE
Rearranging contact cards in Manage Household does not update naming

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2357]
Per this [Hub thread](https://powerofus.force.com/0D580000033yZjS). 

Replicated in brand new org.

![image](https://cloud.githubusercontent.com/assets/4614343/20180270/d05af294-a727-11e6-8f0f-7e9666731129.png)

![image](https://cloud.githubusercontent.com/assets/4614343/20180278/d7f96cb0-a727-11e6-9087-6c50cb4b0ca2.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Br1hAAC" target="_blank">W-016846</a>

**Comment by judisohn** [comment]
Just adding [this thread](https://powerofus.force.com/0D580000034ZjCE) as there is an initial expectation from some users that rearranging the cards will update naming regardless of Primary Contact.

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 2)

**Comment by davidhabib** [comment]
turns out we fixed the code in our household naming trigger to have naming order take precedence over primary contact, but we did not fix (or forgot to commit?) the same change needed in the Manage Household UI to no longer put primary contact first.

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
