### ISSUE TITLE
Default address not resetting on Seasonal End Dates

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2358]
Seasonal addresses are not ending on scheduled end date.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Br1rAAC" target="_blank">W-016848</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 4)
