### ISSUE TITLE
As a developer, I want to increase the test coverage of REL_Utils

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#236]
The dev console says it's at 42% right now

**Comment by davidhabib** [comment]
**lurch: attach W-007354

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZcAAI" target="_blank">W-007354</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
