### ISSUE TITLE
Apex heap size too large, Context: npsp__RD_RecurringDonations_BATCH

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/Cumulus#2361]
Context: npsp__RD_RecurringDonations_BATCH
Eror Type: Batch Apex error

Error Message: First error: Apex heap size too large: 12003418

Why is this showing up?

**Comment by davidhabib** [comment]
Please post questions like these in the NPSP chatter group on the Power of Us Hub.  https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe
