### ISSUE TITLE
Deleted Contact in Household Account not in Recycle Bin

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/Cumulus#2362]
When you delete a Contact which is the only Contact in a Household Account (which also has no Opportunities), the Household Account is deleted.  That's fine.  However, the Contact then disappears from the recycle bin (`[SELECT Id FROM Contact WHERE IsDeleted = true AND Id = :c.Id].isEmpty() == true`) and cannot be undeleted.

**Comment by davidhabib** [comment]
NPSP provides a Contact Delete override that prevents this problem.  You need to set it up in your org.

**Comment by ckoppelman** [comment]
Oh, great!  It'd be great to use this in tests (which is where I saw the issue).  Any way of pulling that code out into a service class that I can use in test cases where I delete Contacts?

**Comment by davidhabib** [comment]
The code is in this controller class.  I don't see us exposing it, but you can certainly copy it for your use in your tests.  https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/CON_DeleteContactOverride_CTRL.cls

**Comment by ckoppelman** [comment]
Ok.  By the way, may I suggest that the Delete Override get added to the post-install checklist? https://powerofus.force.com/articles/Resource/NPSP-Post-Install-Checklist

**Comment by davidhabib** [comment]
Good catch.  @jvarese can you add this info to the post install checklist doc?
