### ISSUE TITLE
NullPointerException when try to create NPSP Addresses

### ISSUE THREAD

**Issue by Alex1703** [SalesforceFoundation/Cumulus#2365]
## Receive the null pointer exception when try to create NPSP Addresses

**How to reproduce:**
1. Create Household Account with related Contacts and one Household Account without Contacts.
2. Create NPSP Addresses for this Accounts in one DML operation.

**Result:**
[Class.npsp.ADDR_Addresses_TDTM.refreshCurrentHHAddress: line 339, column 1
Class.npsp.ADDR_Addresses_TDTM.run: line 174, column 1
Class.npsp.TDTM_TriggerHandler.runClass: line 173, column 1
Class.npsp.TDTM_TriggerHandler.run: line 98, column 1
Trigger.npsp.TDTM_Address: line 34, column 1](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ADDR_Addresses_TDTM.cls#L339)

**Suggestion to fix:**
`line 338: if (mapAccIdListCon != null && mapAccIdListCon.size() > 0) {`

replace to
`line 338: if (mapAccIdListCon != null && mapAccIdListCon.containsKey(accId)) {`

**Comment by davidhabib** [comment]
good catch.  thanks for the fix.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBLVAA4" target="_blank">W-016932</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 1)
