### ISSUE TITLE
As a developer, I want to increase the test coverage of UTIL_JobProgress_CTRL

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#237]
The dev console says it's at 53% right now

**Comment by davidhabib** [comment]
**lurch: attach W-007355

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZdAAI" target="_blank">W-007355</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
