### ISSUE TITLE
Validation Rule with same name as NPSP field is incorrectly triggered

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2370]
Thread: https://powerofus.force.com/0D580000034bNqe

Validation Rule in customer org is: 

(RecordType.Name="Membership Grant" || RecordType.Name="Non-Member Grant") 
&& 
IsWon=True && 
(ISBLANK(Grant_Period_Start_Date__c) || 
ISBLANK(Grant_Period_End_Date__c))

The customer has custom fields for Grant Period Start/End Date, and it's those fields that are on the layout and populated, however the debug log shows that the code is looking at NPSP versions of those fields instead:

![image](https://cloud.githubusercontent.com/assets/4614343/20434372/8159dc60-ad75-11e6-96dc-d71f1f52707d.png)

Error is not the actual Validation Rule firing (since it's not by the field - it's by NPSP).

Repeat by creating Date fields on Opportunity with Dev names of Grant_Period_Start_Date and Grant_Period_End_Date in clean test org using this validation rule:

(RecordType.Name="Grant") 
&& 
IsWon=True && 
(ISBLANK(Grant_Period_Start_Date__c) || 
ISBLANK(Grant_Period_End_Date__c))

Workaround: Change dev name of custom fields.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBLfAAO" target="_blank">W-016934</a>

**Comment by mpusto** [comment]
Because this is a core bug, we have closed the issue. If SFDC fixes it and it remains, we can re-open.
https://success.salesforce.com/issues_view?id=a1p30000000T2L3AAK
