### ISSUE TITLE
Entire contact insert batch fails with single bad address when state/country picks enabled

### ISSUE THREAD

**Issue by selfuntitled** [SalesforceFoundation/Cumulus#2371]
When state and country picklists are enabled, and a contact is inserted with a bad state or country (or any other data that generates an account level validation error) as part of a batch, the account insert fails, which causes the entire batch to fail.  

I know that with the change in 3.83 the idea is that the calling application is responsible for error handling, but I'm not sure how this looks with batches, or with a generic ETL tool that's creating or scheduling batches like DBAmp which couldn't possible anticipate NPSP.

Is this just an unfortunate consequence of the change in 3.83, or is there a more graceful way we could handle a DML error?

**Comment by judisohn** [comment]
Please post a message in the [Power of Us Hub NPSP group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) for further troubleshooting and discussion. Thanks!
