### ISSUE TITLE
Deleting an Affiliation that is checked as Primary should remove the Primary Affiliation from the Contact record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2375]
Thread here: https://powerofus.force.com/0D580000034bdBK

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004DBOtAAO" target="_blank">W-016962</a>
