### ISSUE TITLE
If Opp created in Lead Conversion, Opp Automatic Naming does not fire

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2378]
1. Set up NPSP Opp Naming for 'Both' and select a standard naming rule for profile's default Opp record type
2. Create Lead using 'Self' as Company
3. Convert using NPSP override - uncheck 'Do not create opportunity...' box

Result: Lead is converted correctly to Contact/Household, however Opportunity has name as set in Lead Conversion dialog and is not being updated to use naming rules as expected on Opportunity save. Admin must 'Refresh Name' to update.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXuNAAW" target="_blank">W-016969</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 5)
