### ISSUE TITLE
Return URL link broken for Email Acknowledgement multi-record in LEx

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2379]
Lightning Experience no longer sets the retURL parameter. After successfully sending multiple email acknowledgements, clicking the retURL keeps the user on the same page and adds an error message that the emails could not be sent.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXuhAAG" target="_blank">W-016975</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 3)
