### ISSUE TITLE
Deleting an opportunity with allocations should delete the allocation

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2382]

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxbAAG" target="_blank">W-017007</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxgAAG" target="_blank">W-017009</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxlAAG" target="_blank">W-017011</a>

**Comment by njjc** [comment]
@kbromer lurch is going wild...

**Comment by njjc** [comment]
Apparently it's a known issue with adding in the description.

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 7)
