### ISSUE TITLE
Enhance NPSP Data Imports to pass dml.DuplicateRuleHeader.AllowSave = true;

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2383]
Even if your rule says to just warn, but allow the save to go thru, any code doing inserts (apex, triggers) must explicitly pass in a flag to the Salesforce API to allow the save. (dml.DuplicateRuleHeader.AllowSave = true;) 

Unfortunately, NPSP does not pass in this flag in most scenarios. we should see if we can add in this flag when inserting contacts and accounts for data import.

hub thread: https://powerofus.force.com/0D580000035esUw

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXxcAAG" target="_blank">W-017008</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.115 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.115
