### ISSUE TITLE
If State & Country Picklists are enabled and Contact Address is Overridden, Mailing State  not updated on changed Address

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2385]
Thread: https://powerofus.force.com/0D580000034dUdS

Steps to reproduce:

1. Enable State & Country Picklists (standard settings are fine)
2. Create Contact with Mailing Address
3. Edit Contact - check 'Address Override' and change the address, making sure to change the State

Result: Contact has correct new Address:

![image](https://cloud.githubusercontent.com/assets/4614343/20538673/36545b20-b0c0-11e6-974f-1dd59e6aa2ab.png)

However Address Record still has Mailing State from previous address (Account).

![image](https://cloud.githubusercontent.com/assets/4614343/20538726/617df09a-b0c0-11e6-9fc0-cfb4c3cacd47.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by mrbelvedere** [comment]
Included in beta release 3.107 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
