### ISSUE TITLE
Engagement Plans with two lookups populated don't correctly display error

### ISSUE THREAD

**Issue by jessingrass** [SalesforceFoundation/Cumulus#2386]
When the user goes to Engagement Plan and incorrectly fills out too many objects in the engagement plan template, then an error message appears and is confusing and unfriendly. Please see screenshot for fields filled out, values, and error message.

![screen shot 2016-11-22 at 2 57 55 pm](https://cloud.githubusercontent.com/assets/1976801/20539965/11a8a736-b0c5-11e6-8dde-a3dc377598d8.png)

**Comment by jessingrass** [comment]
**lurch: add comment

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXyKAAW" target="_blank">W-017017</a>

**Comment by jlantz** [comment]
Included in beta release 3.86 (Beta 7)
