### ISSUE TITLE
Manage Soft Credits stopped working after enabling multi currency

### ISSUE THREAD

**Issue by nkarmi** [SalesforceFoundation/Cumulus#2394]
After enabling multi currency "Manage Soft Donation" stopped working, and I got the following error message: "Visual Force Error: Currency fields on entities with effective dated currency are not supported."

**Comment by judisohn** [comment]
Hi @nkarmi Please read our International FAQ [here](https://powerofus.force.com/articles/Resource/International-Nonprofits-FAQ). Unfortunately, Advanced Currency Management (dated exchange rates) is not supported in NPSP.
