### ISSUE TITLE
Custom Household Naming incorrect if Contact Overrun Count = 2

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2395]
If Contact Overrun Count is set to 2, we should a comma instead of & in 2 person names.

![image](https://cloud.githubusercontent.com/assets/908119/20803441/19221b06-b7a4-11e6-8ecb-39f842a988a2.png)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvdVAAS" target="_blank">W-017090</a>

**Comment by allisonletts** [comment]
It **shouldn't** be a comma, right? That's what's currently showing. It should be an **and.**

**Comment by davidhabib** [comment]
correct.  if only two names, no comma and just and and/&.  the workaround for now is to set your Contact Overrun Count to 3.

**Comment by allisonletts** [comment]
I'd been having this problem with Formal greetings where the last names
were the same for a while. It seems to have started including informal
greetings with the last release.

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 4)
