### ISSUE TITLE
Contact Role Health Check incorrectly reports error if Default Role is a part of a Soft Credit Role

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2401]
[Per this hub thread.](https://powerofus.force.com/0D580000036V2Pg)

I had just done softCreditRoles.contains(primaryRole), which is false positive for partial matches, e.g. softCreditRoles = 'Matched Donor' and primaryRole = 'Donor'

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004HJauAAG" target="_blank">W-017105</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 6)
