### ISSUE TITLE
Custom Household Name with multiple cross object references fails

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2403]
formal greeting format {!Account.npe01__One2OneContact__r.Primary_Affiliation__r.Name}

Apex trigger nictest.TDTM_Contact caused an unexpected exception, contact your administrator: nictest.TDTM_Contact: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object: Class.nictest.HH_NameSpec.strConFspec: line 319, column 1

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004HJb4AAG" target="_blank">W-017107</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 4)
