### ISSUE TITLE
User should receive an error message for Level with no min/max value

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2407]
Create a Level whose values for Minimum Amount and Maximum Amount are empty. 

Attempt  to 'Clone' this Level.

Regardless of the amount set in the cloned Level, attempting to save the new Level yields error message "Error: The Minimum Amount to Maximum Amount range on Level <Foo> overlaps with the Minimum Amount to Maximum Amount range on Level <Foo - Cloned>"

It may be that we should prevent creating Levels with no min/max values.

![screen shot 2016-12-06 at 2 23 25 pm](https://cloud.githubusercontent.com/assets/204643/20944153/9837c9b2-bbbf-11e6-8827-a2ed759980eb.png)

**Comment by judisohn** [comment]
@davidhabib @mpusto I can't think of a single plausible use case that a Level should not have a min or max (I was surprised I could save the level with the fields blank) and that feels to me like the true issue here. Should @chrismcmahon change the name before Lurching?

**Comment by mpusto** [comment]
Agreed

**Comment by judisohn** [comment]
*lurch: add

**Comment by judisohn** [comment]
nice catch @chrismcmahon!

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004HJdtAAG" target="_blank">W-017140</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 9)
