### ISSUE TITLE
Custom Opportunity Naming multiple cross object format with null reference fails

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2415]

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii3JAAS" target="_blank">W-017178</a>

**Comment by jlantz** [comment]
Included in beta release 3.87 (Beta 8)
