### ISSUE TITLE
Improve SLDS styling on all custom pages

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2419]
While doing our SLDS styling work, we haven't been consistent with how we handle field sets and various field types. known issues:

- Some pages with Date and DateTime field have the current Date/Time hyperlink after the field, some have the within the field. (and of course none offer a date picker since we don't want to build one!)

- some pages show multi-select picklists as a single listbox, others show two listboxes

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004Ii5oAAC" target="_blank">W-017210</a>
