### ISSUE TITLE
Matching Donation button from Contacts & Orgs on Opportunity should be deprecated

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2422]
Minor issue:
I have a Donation that creates an Opportunity for zero dollars like so: 

![screen shot 2016-12-20 at 3 27 47 pm](https://cloud.githubusercontent.com/assets/204643/21370490/29c231f6-c6c9-11e6-8130-d09d300867f6.png)

![screen shot 2016-12-20 at 3 27 55 pm](https://cloud.githubusercontent.com/assets/204643/21370505/332a668c-c6c9-11e6-9bb5-cd1f6189501f.png)

When I click the "Matching Donation" button the resulting screen says only "Error:
Attempt to de-reference a null object" 

![screen shot 2016-12-20 at 3 28 06 pm](https://cloud.githubusercontent.com/assets/204643/21370530/51f5d38a-c6c9-11e6-9890-882e4f22231d.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004K73HAAS" target="_blank">W-017267</a>
