### ISSUE TITLE
Spring '17: Manage Household New Contact error

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2423]
This may be gs0 issue.

STR:

1. Household Account with one Contact - Manage Household
2. Type Name of Contact in search box (that does not already exist)
3. Click + New Contact

Error: List has no rows for assignment to SObject

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004K73MAAS" target="_blank">W-017268</a>

**Comment by davidhabib** [comment]
this was fixed back in sprint 1b.
