### ISSUE TITLE
Cannot delete Contact in Account with >50k Contacts

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/Cumulus#2425]
I have several legacy accounts with huge numbers of contacts. When users try to delete those contacts using `CON_DeleteContactOverride`, they get an exception in the form:

> npsp:Too many query rows: 50001
> Error is in expression '{!processDelete}' in component apex:page in page npsp:con_deletecontactoverride: (npsp)

## Steps to reproduce:

1. Create an Account
1. Create 60k contacts all in that account.
1. Click delete on one of those contacts.

## Expected Result:
That contact is deleted.

## Actual result:
Exception: 

> npsp:Too many query rows: 50001
> Error is in expression '{!processDelete}' in component apex:page in page npsp:con_deletecontactoverride: (npsp)

## Workaround:
Use a different override.

**Comment by njjc** [comment]
Fixed in #2437
