### ISSUE TITLE
Recurring Donation non-selective query error in LDV orgs

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2430]
We have a customer with over 8 million opportunities.  They are unable to successfully create Recurring Donations, because one of the queries our trigger handler uses is being deemed non-selective in this environment.  

The NPSP query is doing 

....from Opportunity where  npe03__Recurring_Donation__r.id IN ... 

which fails to use the lookup index.  by making it the following, it will use the index.

....from Opportunity where  npe03__Recurring_Donation__c IN ...

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004PkDSAA0" target="_blank">W-017305</a>

**Comment by jlantz** [comment]
Included in beta release 3.88 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
