### ISSUE TITLE
Allow Refresh Opportunity Name batch job to be scheduleable

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2435]
thread: https://powerofus.force.com/0D580000039APkV

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBVsAAO" target="_blank">W-017334</a>

**Comment by njjc** [comment]
Fixed in #2454
