### ISSUE TITLE
Prevent exception when legacy accounts have >50k contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2436]
this is an issue found and fixed by @ckoppelman at the Polaris Project.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by davidhabib** [comment]
@judisohn I will be testing and merging the associated pull request with this fix during this sprint.  did you need to get anything signed by the contributor?

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBWbAAO" target="_blank">W-017343</a>

**Comment by jlantz** [comment]
Included in beta release 3.88 (Beta 2)

**Comment by judisohn** [comment]
@davidhabib Nope, all set - Charles signed the CLA shortly after he submitted the PR. :-) Thanks again!

**Comment by ckoppelman** [comment]
Just FYI, for the sake of any attribution if that's a thing, my org should be cited as Polaris, not Polaris Project.  The Project is a legacy name.

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
