### ISSUE TITLE
Cicero address verification dropping +4 zip codes

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2439]
#1353 included fix for Google dropping address data that it did not support, but does not seem to have been applied for Cicero. Message from Cicero developers:

"I wanted to reach out about a question a few of our customers have had about the Cicero address verification integration within the NPSP. Since our geocoding services do not use zip+4 (they use the full address instead), the +4 is being dropped from records once addresses are verified. I know this has been brought up before with the Google verification service, and I see a note from Carlos that it was fixed for them. Do you know if it would be possible to do the same for Cicero?"

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBXtAAO" target="_blank">W-017358</a>

**Comment by smthome** [comment]
@judisohn I was also just notified of an issue with the second part of Canadian zip codes being dropped in the verification process with Cicero. For example, a postal code that is "K6V 1M5" will become "K6V" when verified. Is this possibly related, and would it be fixed by this issue? Thanks!

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
