### ISSUE TITLE
When Contacts are merged with Recurring Donations, the losing Contact's Recurring Donation(s) are deleted

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2449]
Thread: https://powerofus.force.com/0D58000003AUWPg

Opportunities are retained, it's only the Recurring Donation that's deleted. It's recoverable from recycle bin.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004WCZjAAO" target="_blank">W-017449</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
