### ISSUE TITLE
verifyRecordsFuture throws a NullPointerException

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/Cumulus#2450]
Occasionally, I get the error below.

I've been doing a lot more geocoding on that API key lately and I wonder if it has to do with exceeding a limit either in Salesforce or Google.

> Failed to invoke future method 'public static void verifyRecordsFuture(Set<Id>)' on class 'npsp.ADDR_Validator' for job id '707.......'
> 
> caused by: System.NullPointerException: Attempt to de-reference a null object
> 
> Class.npsp.ADDR_GoogleGeoAPI_Validator.verifyAddress: line 168, column 1
> Class.npsp.ADDR_GoogleGeoAPI_Validator.verifyRecords: line 97, column 1
> Class.npsp.ADDR_Validator.verifyAddressRecords: line 103, column 1
> Class.npsp.ADDR_Validator.verifyRecords: line 77, column 1
> Class.npsp.ADDR_Validator.verifyRecordsFuture: line 61, column 1

I assume that `googresp.results[0].partial_match == null`, but it may be `googresp` or `googresp.results` since the line of code is:

    if (googresp.status == 'OK' && googresp.results.size() == 1 && !(settings.Reject_Ambiguous_Addresses__c && googresp.results[0].partial_match)){

Google has recently (Nov '16) changed their forward geocoding API. Perhaps that is the issue?

**Comment by davidhabib** [comment]
thanks for reporting the problem.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004WCaDAAW" target="_blank">W-017450</a>

**Comment by ckoppelman** [comment]
After dealing with this on my own geocoding, I believe that when `partial_match` is false, it is just not in the json response. Therefore, when Apex deserializes the JSON into an object, the `Boolean partial_match` field remains null.  Dereferencing a null boolean seems to work like in Java where null cannot be auto-unboxed and thus throws this exception.

**Comment by davidhabib** [comment]
yep, it was fixed in this pull request: https://github.com/SalesforceFoundation/Cumulus/pull/2462 which will be in our next sandbox release next week.
