### ISSUE TITLE
Recurring Donation Batch Error "List index out of bounds: 1"

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2455]
Create Household Contact
Add Recurring Donation (open)
Delete Contact (with override button)

Result:
In my org, I received 2 identical emails:

Errors:

Error #1:

Error Type: Other
Error Date: 2016-12-21 12:59:22
Message: "entity is deleted"
https://npsp.na35.visual.force.com/a0941000001mbvyAAA

Stack Trace:
null

Error #2:

Error Type: System.ListException
Error Date: 2016-12-21 12:59:22
Message: "List index out of bounds: 1"

Stack Trace:
Stacktrace available at the time of saving the record - (npsp)

**Comment by mrbelvedere** [comment]
Included in beta release 3.88 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.88
