### ISSUE TITLE
Google Address Validator hits exception on some addresses

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2461]
If you have google geocoding chosen for your address verification provider, the following address will generate a null pointer exception.

![image](https://cloud.githubusercontent.com/assets/908119/22077771/67d4b254-dd6a-11e6-90b0-e7f625e81d16.png)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGnZAAU" target="_blank">W-017541</a>

**Comment by davidhabib** [comment]
workaround is to uncheck "Reject Ambiguous Addresses" in NPSP Settings.

**Comment by mrbelvedere** [comment]
Included in beta release 3.89 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.89
