### ISSUE TITLE
Batch Data Entry page does not support picklist values controlled by the Record Type

### ISSUE THREAD

**Issue by matcadg** [SalesforceFoundation/Cumulus#2467]
Is anyone else having/had problems with picklists that have values limited by Record Type on the Batch Entry screen?
 
We have several record types defined for opportunities. We then have a picklist field which has different values available depending on the record type chosen by a user.
 
If we add the Record Type and a picklist field whose values are dependent on the Record Type to the fieldset that controls the fields visible on the batch entry screen (BDE Entry FS) both fields are displayed. Users can change the record type, but this does not trigger a refresh of the page section. The result is that the picklist now has wrong values in it (the values are those that were relevant for the default record type)
 
Interestingly the behavior seems to be if you hit save, you get an error message saying the save failed. This then does successfully reload the page with the correct picklist values, but has the effect of broadcasting an NPSP error email to everyone.
 
Is there a setting or something we should do differently to get record type dependent picklists working on the Batch Date Entry screen or is this a bug?

**Comment by judisohn** [comment]
Hi @matcadg Please post this in the [Power of Us Hub's NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) where we can help you with troubleshooting and determine whether it is indeed a bug or something that can be resolved in development. Once that's confirmed, we can come back here to open an issue. Thanks!
