### ISSUE TITLE
ApexDoc cleanup

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/Cumulus#2468]
A few things I noticed using the ApexDocs over the past couple days.:

- give everything a category; eliminate Miscellaneous 
- Move "Utils" category into "Utilities" 
- update classes using older XML-ish internal documentation to use ApexDoc
- Relationships.htm category page

I have a branch where I've started on this stuff - it's a great way to get familiar with the code base! Comment if there are other issues you've noticed and I'll try to get them addressed as well.

**Comment by davidhabib** [comment]
Thanks @tet3

**Comment by mrbelvedere** [comment]
Included in beta release 3.90 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.90
