### ISSUE TITLE
As an Admin, I want to designate custom fields on Relationship to be synced across reciprocal pairs

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/Cumulus#2469]
Hub Idea: https://powerofus.force.com/hub-ideas/1149

I thought this was an interesting and useful idea, and so I've got a version of this working pretty well.  A couple of questions that I'd love input on: 

1. Right now, I have a TextArea field on the npe4__Relationship_Settings__c CS object and am storing a semi-colon-delimited list of field API names. But 255 characters seems pretty limiting. Do you think it's enough? If not, recommended alternative? I've thought of a single-column List Setting or using an additional "overflow" TextArea field, neither of which I love.

2. Testing - I see that the Payment Mapping tests use a dummy packaged field: npe01__OppPayment__c.	npe01__Custom_Payment_Field__c, whose only role seems to be for testing. Is there a better pattern for that , or must I do a similar sort of thing for the Relationship object. The only thing that comes to mind is including the FF Apex MDAPI package to create and delete fields, but that doesn't sound a whole lot better.

**Comment by cdcarter** [comment]
I'd expect a separate setting for this. 

The linked idea is specifying a create-only behavior, is that the route you're approaching?

**Comment by judisohn** [comment]
Hi @tet3 - this is awesome, thank you! Can't wait to see your pull request.

But if you don't mind, could you start a thread in the Hub, maybe in the Contributor group and urge feedback/questions - @njjc and @davidhabib and @jjbennett will see and respond, promise. 

As you may have noticed, we have a bit of a workflow here in Github now, so we prefer that we leave issues just for those items that are on our backlog/actionable. You'll get much better engagement there to boot. :-) Once you have a pull ready, we can get an issue going to go with it.

Thanks again!
