### ISSUE TITLE
Investigate widely implementing DMLOptions.DuplicateRuleHeader.AllowSave

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2475]
Duplicate rules set to "allow save" are still blocked in DML operations unless the DMLOptions.DuplicateRuleHeader.AllowSave is specifically set for each DML operation.

Investigate applying this header to all processDML methods, and also to manual insert/update calls to Contact and Account objects that are likely to have this type of rule enabled.

[From the HUB.](https://powerofus.force.com/0D58000003Cjyxb)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004pp1IAAQ" target="_blank">W-017683</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.115 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.115
