### ISSUE TITLE
If Automatic Household Naming is disabled and existing naming rules have syntax error, exception is thrown

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2476]
Steps to repeat:

1. Household Naming Name rule with custom text that is invalid, such as {!{!FirstName}} {!LastName}} Household
2. Automatic Household Naming checked off
3. Edit any contact record

![image](https://cloud.githubusercontent.com/assets/4614343/22570563/f6365376-e969-11e6-80a0-00ac3f054346.png)

If Automatic Household Naming is disabled, any errors in the existing naming should be ignored.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004pp1SAAQ" target="_blank">W-017685</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.105 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.105
