### ISSUE TITLE
NPSP Data Importer (3.89) creates new Account for Contact2 even if Contact1 is matched on ID

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2479]
STR:

1. New NPSP Data Import record - Contact1 Imported (select existing Contact), Contact2 First Name/Contact2 Last Name (something that won't match)
2. Run utility with default matching

Expected: New Created Contact2 in same existing Household as Contact1

Result: Contact1 is Matched correctly. Contact2 is Created in its own Household.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004pp3YAAQ" target="_blank">W-017687</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.90 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.90
