### ISSUE TITLE
UTIL_RecordTypes.getRecordTypesForSelectList() returns master and inactive recordtypes

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2480]
[From the HUB.](https://powerofus.force.com/0D58000003Cl17O)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004v1a6AAA" target="_blank">W-017690</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.98 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.98
