### ISSUE TITLE
Unable to Match Gift to multiple opps from same account

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2486]
hub thread here: https://powerofus.force.com/0D58000003DQdfn

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004v1clAAA" target="_blank">W-017715</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.94 (Beta 14)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.94
