### ISSUE TITLE
Recurring Donations Batch

### ISSUE THREAD

**Issue by seanong** [SalesforceFoundation/Cumulus#2487]
I've done some extensions to the NPSP using Process Builder to apply some business logic. However, the Recurring Donations Batch nightly program is now running into governor limits. 
 
Happy to implement my own version of the Batch Program but I need the following method to be made global:
RD_RecurringDonations.evaluateRecurringDonationsForNewOppInsert
 
Would this be possible?

**Comment by judisohn** [comment]
Hi @seanong I saw you also [posted this](https://powerofus.force.com/0D58000003DQn5b) on the Power of Us Hub, as you should. Thank you. I'll make sure you get a reply from a developer there, as we prefer Github Issues only be used for actionable items. Thanks for understanding!
