### ISSUE TITLE
Trigger rollup not firing if date field gets cleared

### ISSUE THREAD

**Issue by sd5000** [SalesforceFoundation/Cumulus#2494]
We stumbled on an issue using the NPSP Rollups to roll up opportunity dates onto the contact. The specific use case is a "filtered" last gift date that shows the Last Gift Date from _only certain types_ of donations (similar to regular Last Gift Date but with certain types of donations filtered out). For example show me the last gift date excluding event ticket purchases. 

The way we figured to accomplish that was by creating a formula field on Opportunity called Filtered CloseDate, and set it to CloseDate for included donation types and NULL for excluded donation types (like event ticket purchases). Then roll up the MAX Filtered CloseDate to the Contact (thereby leaving nulls out of the rollup).

That mostly works fine. But when the Filtered CloseDate formula on an opportunity gets set to null, it doesn't seem to trigger the rollup code. Meaning if the most recent gift is changed from a regular donation to an event donation, the Filtered CloseDate formula goes to null on the opportunity record, but the rollup doesn't re-fire to readjust the Filtered Last Gift Date rollup on the Contact.

One crappy workaround would be to set the Filtered CloseDate formula to some ancient date like 1/1/1900. But then if it's the only opportunity on the contact, that ancient date would still roll up as the MAX on the contact. So it seems like it would be better to be able to trigger the rollup even from a nulled out field.

**Comment by davidhabib** [comment]
please post questions/issues like this on the hub in the NPSP group.  then folks can chime in, and we'll enter a gitHub issue if we have an actionable item.  thanks.

**Comment by judisohn** [comment]
**lurch: add

**Comment by judisohn** [comment]
Hub thread. https://powerofus.force.com/0D58000003F5a7O

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000059soOAAQ" target="_blank">W-017812</a>

**Comment by sd5000** [comment]
I stumbled on this problem again and it's possible I may have mis-identified the issue before. Is it possible this user-defined rollup code only runs when a child record is created and not when it's updated? 

That's how it seems to be behaving, at least when I'm rolling up these formula fields. Doesn't actually seem to have anything to do with whether the new value is null or not.

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128
