### ISSUE TITLE
Allocations Rollups misuse current Calendar year for Fiscal Year rollups

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2496]

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000050EprAAE" target="_blank">W-017799</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.91 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.91
