### ISSUE TITLE
When Levels are re-defined, Levels not cleared from objects

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2503]
When a user re-defines a level to be a different start and end value, the Level assignment batch goes through and assigns all records to the new levels. However, if a record has an old level field populated and it now meets *no* level definition, it retains the old information. This can cause confusion by mis-labeling records. The level field should be cleared for records which no longer meet any level criteria.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005FM6qAAG" target="_blank">W-017872</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.94 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.94
