### ISSUE TITLE
make NPSP compatible with modern DE orgs and unmanaged code

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Cumulus#2506]
New DE orgs now are created with LockerService enabled by default and with mydomain enabled by default. For now Lockerservice may be disabled but mydomain may not be disabled.  Using unmanaged code in DE orgs is very helpful for testing.

In NPSP the Relationships Viewer off the Contacts under page under mydomain yields an error "URL No Longer Exists"

The Manage Household button off the Account page under mydomain may or may not yield a "List has no rows for assignment to SObject" error. I saw the Manage Household button exhibit both behaviors. 

Other custom buttons are likely to have similar problems.

The Manage Households page when working also yields an error "Error
LockerService, a new Salesforce security service, is activated and is preventing this page from working correctly. To get this page to work correctly, search for Critical Updates under Salesforce Setup, and then deactivate the Enable Lightning LockerService Security critical update." I understand this is being tracked separately.

**Comment by njjc** [comment]
Nothing we can do to make our URL buttons resolve correctly in non-namespaced orgs as they have to be hard coded, this is a platform limitation unfortunately. The fix is to use scratch orgs with namespace enabled, not sure if that's possible yet, though.
