### ISSUE TITLE
Cicero Address-Cleaning Problems

### ISSUE THREAD

**Issue by NickSPowell** [SalesforceFoundation/Cumulus#2507]
Hi, we are a potential customer of Cicero (mainly because of the districts), but the address verification that leads to the district-adds has some serious problems out-of-the-box. I've tried this in our own sandbox and in an NPSP trial account and they both have the same problems. 

* It puts state and zip in the state field ('NY 10001') and 'USA' in the zip field.
* It removes the space between the asterisk and the apt number. This is not standard.
* It replaces 'Apt' and 'Unit' (and likely others) with an asterisk. There is no discernible reason for doing this and it hinders our ability to match against these addresses in other systems.
* It flat out removes some fringe apt elements. I've seen this problem mentioned elsewhere but that seemed to be a bug with 'apt' in general, I'm more talking about weirder ones like 'spc' and 'box'. And the removed elements are nowhere to be found in the API Response, so there doesn't even seem to be a way to subvert this behavior using code.
* If it's a bad address it removes all elements but 'Main St'. This is deeply unpreferable to just leaving the bad (possibly typo'd) address in there and just marking it as 'Ambigous' and not Verified.

The fact that I can't find anyone else mentioning these makes me feel as though we're doing something wrong, but ... we're using out-of-the-box settings, and there don't even appear to be declarative settings that would control this behavior, so other than using code that directly handle the extracts out of the API Response I'm not even sure how you'd subvert these things.

**Comment by judisohn** [comment]
Hi @NickSPowell Please post in the [NPSP group in the Power of Us Hub](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) (you can access thanks to your trial account) and if it's determined that a code change is needed in NPSP to address this, then an issue can be opened here. Thanks!
