### ISSUE TITLE
Cicero Address Verification malfunctioning

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2508]
An update to the Cicero API has caused our integration to put field some values in the wrong fields and to drop some fields altogether:

-state and zip field are both being put in the state field ('PA 19128') 
-country is being put in the zip field
-'Apt' and 'Unit' are being replaced with an asterisk

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005FMBvAAO" target="_blank">W-017935</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.92 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.92
