### ISSUE TITLE
EP: Error if non-Admin user completing task doesn't have ownership on child task

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2510]
[Hub thread](https://powerofus.force.com/0D58000003GDy1i).

This happens if non-Admins are assigned EP Tasks, but then on completion the dependent tasks can't be updated to move out of Waiting status. User has to have 'Modify All' on the parent object (or be above in role hierarchy) to update tasks they are not assigned.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005FMCZAA4" target="_blank">W-017942</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.93 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.93
