### ISSUE TITLE
Does Cumulus have anything to do with enabling upsert/lookup on Contact.Email ?

### ISSUE THREAD

**Issue by aaronbauman** [SalesforceFoundation/Cumulus#2511]
In my sandbox org I'm able to successfully upsert and read using Contact.Email - which is odd behavior since this field cannot be marked unique or external id.
I stumbled across this behavior by accident on an org with Cumulus / NPSP installed.

Is this some NPSP magic?
Does anyone know how or why this is working?

**Comment by judisohn** [comment]
I don't believe there is anything in NPSP code that would be changing how the field behaves, but please post this in the [NPSP Group in the Power of Us Hub](https://powerofus.force.com/0F980000000CjRe) for further conversation. We reserve Issues just for actionable items. Thanks!
