### ISSUE TITLE
Seasonal Address batch job may have non-selective query

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2513]
we are querying for all addresses where Seasonal_Start_month__c <> null, which won't use an index, and thus may be a problem for XL LDV orgs.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005FMDmAAO" target="_blank">W-017957</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.101 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.101
