### ISSUE TITLE
NPSP Data Import: if Contact Unique ID is number, fails with duplicate value error

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2517]
[Thread.](https://powerofus.force.com/0D58000003GHMk0) [Case.](https://org62.my.salesforce.com/5000M00000gX1ag)

Steps to repeat:

1. Create custom field on Contact, type Number (18,0). Mark as External Unique ID
2. Create corresponding NPSP Data Import fields for Contact1/Contact2 Unique ID, type Number (18,0), mapped to above field
3. Create NPSP Data Import record with First Name, Last Name, Contact1 Unique ID
4. Create Contact with same Unique ID (so it will have something to expect to match against)
4. Process with Contact Unique ID field selected

Error: duplicate value found: unknown duplicates value on record with id: 003...

5. Now change Contact and NPSP Data Import fields from Number to Text data types.
6. Process Data Import record with no error.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005KmXvAAK" target="_blank">W-017987</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.94 (Beta 9)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.94
