### ISSUE TITLE
Manage EP Template: CSS fix for narrow width

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2518]
From the Hub: https://powerofus.force.com/0D58000003H0OZa

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005KmZwAAK" target="_blank">W-018000</a>

**Comment by mpusto** [comment]
I tested this in Classic and Lightning and can no longer reproduce it.
