### ISSUE TITLE
Manage Allocations - Summary row malfunctions for numbers with commas

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2521]
Allocation amounts with commas in them, e.g. $2,500.00, are misinterpreted by Javascript as NaN, causing summary rows to not include those amounts.

[From the Hub.](https://powerofus.force.com/0D58000003H0RIl)

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QChEAAW" target="_blank">W-018044</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.99 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.99
