### ISSUE TITLE
Delete organization affiliation record on lead coversion

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2522]
[Thread.](https://powerofus.force.com/0D58000003GFj5B)

Since leads are converted using the default profile (Organization), the trigger is firing to create an Affiliation before the Account is converted to a Household (or 1:1). This record should be cleaned up following the switch to the Household/1:1.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QChYAAW" target="_blank">W-018046</a>

**Comment by force2b** [comment]
Taking this on

**Comment by judisohn** [comment]
After further investigation this is no longer an issue.
