### ISSUE TITLE
If recurring donation is None, and an opp is Closed Lost, any edit to other opps adds installments

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2523]
[Thread](https://powerofus.force.com/0D58000003HSNmj)

Steps to repeat:

1. None Recurring Donation (associate to Contact, but probably doesn't matter)
2. Allow to generate opps
3. Set first opp to Closed Lost
4. Refresh opps. New opp created, which is expected.
5. Edit anything on new Pledged opp (such as description - doesn't matter the field)
6. Refresh opps. New opp created and installment increases. Happens now on every edit.

If there is no Closed Lost opp, this behavior (opp creation on opp edit) does not occur.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QChnAAG" target="_blank">W-018048</a>

**Comment by julieloyd** [comment]
I think this issue occurs if you modify anything on the parent Recurring Donation, as well, and even if you haven't Refreshed Opps. We're seeing it when we modify the Name on Recurring Donation, for instance, as soon as we save the record.

**Comment by mrbelvedere** [comment]
Included in beta release 3.95 (Beta 4)

**Comment by Julia-Morales** [comment]
It's also occurring when opprtunities are Closed/Won. I've noticed that the new Opportunity is created and de installemnt updated when Paid Amount and Remaining balance fields are not updated correctly.

**Comment by judisohn** [comment]
@Julia-Morales Can you be a bit more specific by what you mean by "when Paid Amount and Remaining Balance fields are not updated correctly"?

**Comment by Julia-Morales** [comment]
Hi @judisohn, we've noticed that for the (None) Recurring donations, once a related Oportunitty is Closed/Won, the Paid Amount and Remaining Balance fields are not updated. That causes that in the future (after a month), a new Opportunity is created and the installments updated.

**Comment by judisohn** [comment]
@Julia-Morales Are you talking about fields on the Opportunity or Recurring Donation?

**Comment by Julia-Morales** [comment]
The field is in the Recurring Donation: npe03__Paid_Amount__c (the other one that is mentioned is a custom one based on the Paid Amount). Additional npe03__Total_Paid_Installments__c is not updated correctly

**Comment by judisohn** [comment]
Go ahead and post in the Hub or open a support case and someone can take a look. I suspect that there is an issue with how you have the Opportunity configured in that it's not being recognized as Closed/Won. This is not at all related to this issue here. Thanks!

**Comment by Julia-Morales** [comment]
I think this is related because, as the Donation has a wrong amount, a new opportunity is created.

**Comment by judisohn** [comment]
I am not able to reproduce what you are talking about. Please start a new thread in the [NPSP group](https://powerofus.force.com/0F980000000CjRe) with your steps to repeat and I can create a new issue for it. Thanks!

**Comment by mrbelvedere** [comment]
Included in production release rel/3.95
