### ISSUE TITLE
Provide transactional and user account way to disable all NPSP Triggers

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2525]
hub thread: https://powerofus.force.com/0D58000003HU7DH

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCnvAAG" target="_blank">W-018116</a>

**Comment by sefg** [comment]
Hi Nick, attached is the code and and some notes - I'd be happy for you to base a solution on this if it is useful. 
cheers
Stuart
[ProcessControl.zip](https://github.com/SalesforceFoundation/Cumulus/files/867893/ProcessControl.zip)

**Comment by davidhabib** [comment]
this issue was addressed and should be closed.

**Comment by mrbelvedere** [comment]
Included in production release rel/3.100
