### ISSUE TITLE
Async APEX error messages may not be sent at all

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/Cumulus#2526]
[Err_AsyncErrors.cls](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ERR_AsyncErrors.cls#L160) calls `ERR_Notifier.sendErrorNotifications('');`. Also Err_AsyncErrors implements Queueable interface.

Subsequently [`ERR_Notifier.sendErrorNotifications('');`](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/ERR_Notifier.cls#L93) does not take queueable APEX into consideration. Therefore the `if` statement does not have a condition that evaluates to true. This causes none of the Async email notifications to be sent.

This is a relatively simple fix, except the method `ERR_Notifier.sendErrorQueueEmailNotification()` looks for ALL errors that have not had an email send. So when this is fixed, be mindful that an email may be sent with a lot of errors since the emails may not have been sent for a while.

**Comment by davidjray** [comment]
Here is a commit on the HEDA side that addresses this: https://github.com/SalesforceFoundation/HEDAP/pull/399/commits/36ef3ca4b9947289f179fc5e5e002d433b673e2a

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCoKAAW" target="_blank">W-018121</a>

**Comment by davidhabib** [comment]
thanks for letting us know @davidjray

**Comment by davidhabib** [comment]
@davidjray looking at the code, i'm a little confused.  given we are in a queueble, not batch, then the first if condition will return true and we will call sendErrorQueueEmailNotificationFuture.  And we know empirically that lots of people are getting these emails, as they post in the hub about it.  Why do you think this code isn't functioning?  (Note that I looked at Apex documentation, and isBatch only returns true for being in a queueable in api 35 and earlier; we are on api 37)

**Comment by davidjray** [comment]
@davidhabib You are right, in HEDA we were still on Api version 35, which meant isBatch was returning true. I looked at the documentation too but didn't think to check the Api version you were on for this class.

Sorry for the false alarm!
