### ISSUE TITLE
Manage Household New Contact search does not support standard Middle Name

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2527]
https://powerofus.force.com/0D58000003IBdxL

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCqfAAG" target="_blank">W-018126</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.100 (Beta 17)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.100
