### ISSUE TITLE
ACCT_IndividualAccounts_TDTM.updateOwners causing System.ListException: Duplicate id in list

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2530]
The method needs to iterate over the DmlWrapper.objectsToUpdate and update any accounts already in the list with the new OwnerId instead of adding new account objects to the list directly, which is causing duplicates.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005ZpxrAAC" target="_blank">W-018140</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.95 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.95
