### ISSUE TITLE
ACCT_IndividualAccounts_TDTM Causing Failed to create Account for Contact first last. Required fields are missing: [Account Name]

### ISSUE THREAD

**Issue by NikunjDoshi** [SalesforceFoundation/Cumulus#2546]
Post NPSP upgrade with one to one model configured, when tried to create a contact with firstname and lastname populated it runs into "Failed to create Account for Contact first last. Required fields are missing: [Account Name]" (refer screenshot below)

![contact creation error](https://cloud.githubusercontent.com/assets/13551175/24459058/3f5f1ce4-14b8-11e7-8b24-41cd0ded5dc9.png)

Here`s the log og the same,

[apex-07L5E000001Xc8KUAS.txt](https://github.com/SalesforceFoundation/Cumulus/files/879308/apex-07L5E000001Xc8KUAS.txt)

When tried to create a contact with trigger handler for ACCT_IndividualAccounts_TDTM inactivated it contact creation goes smooth but with no account.

Can you please have a look at below npsp settings and Case Number: 16068879 and help us pinpoint what is that is causing the issue post upgrade (Please note we tried deactivating all the custom code and uninstalled other conflicting packages to see if it helps but it didn`t).

Let me know if any more info required

![npsp account model configuration](https://cloud.githubusercontent.com/assets/13551175/24459177/8751ad0a-14b8-11e7-9edc-2685bc358532.png)

**Comment by judisohn** [comment]
@NikunjDoshi I will take a look at the case. I'm going to close this issue as we prefer that you open a case (as you've done) or post in the Hub and we reserve Github issues only for items that are actionable by our team. I'll follow up with the support agent on your case if I find what is causing the issue.

**Comment by judisohn** [comment]
@NikunjDoshi I see the support agent has already replied. I hope the information he provided was helpful.

**Comment by NikunjDoshi** [comment]
That information is not helpful, and have replied to the same.

With all the specific information and access provided will need a specific
actionable reply.

Thanks!

**Comment by judisohn** [comment]
I can see that our support agent investigated further and found that it was due to a custom workflow rule. Glad to see the issue was resolved.
