### ISSUE TITLE
Review translations on RecurringDonationOpenStatus and Installment periods

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2548]
As RecurringDonationOpenStatus was overridden for some languages, it is causing issues with Recurring Donation forecast opportunities for orgs who are not updating/translating the Open Ended Status picklist. @jjbennett also noted some issues with installment period translations that may cause similar customer problems.

[Thread 1 - German](https://powerofus.force.com/0D58000003KDOGg). [Thread 2 - Spanish.](https://powerofus.force.com/0D58000003KDi8o)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005kjdyAAA" target="_blank">W-018257</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.95 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.95

**Comment by njjc** [comment]
@judisohn @jjbennett 
Since fixing this issue requires orgs to manually update translations, @smarovich and I think we need to include instructions of how to fix the issue for orgs with translations enabled in the release notes. Thoughts?
