### ISSUE TITLE
Household Naming does not group Last Names together unless they are sequential in order

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2554]
[Thread. ](https://powerofus.force.com/0D58000003Kog4E)

The STR in the post are accurate.

I'm guessing this was introduced in the update to no longer force the Primary Contact as the first name.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005kjn5AAA" target="_blank">W-018295</a>

**Comment by mrbelvedere** [comment]
Included in production release rel/3.101
