### ISSUE TITLE
Health Check error message for missing Payments points to wrong path

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2559]
Should be changed to:

You can create them using the Create Missing Payments button on NPSP Settings > Bulk Data Processes > Create Missing Payments.

**Comment by judisohn** [comment]
**lurch: attach W-011252

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003vBYyAAM" target="_blank">W-011252</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.98 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.98
