### ISSUE TITLE
Summer '17: with LockerService enabled, Manage Household drag & drop Contact cards does not work

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2561]
Tested in gs0 dev org in both Lightning Experience and Classic.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000065hpGAAQ" target="_blank">W-018434</a>
