### ISSUE TITLE
Summer '17: Manage Household - icons not rendering

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2562]
Does not seem to be influenced by Locker Service or whether in Classic or LEX.

Spring '17:

![image](https://cloud.githubusercontent.com/assets/4614343/25354420/e95769a2-2900-11e7-8efc-e6eb319085cc.png)

Summer '17:

![image](https://cloud.githubusercontent.com/assets/4614343/25354428/f1d063ea-2900-11e7-8815-7ed07073c410.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000065hpkAAA" target="_blank">W-018435</a>
