### ISSUE TITLE
Custom Lead Convert Issue

### ISSUE THREAD

**Issue by AnkurJaiswal619** [SalesforceFoundation/Cumulus#2565]
Hi Team, 

We are facing an issue in our dev sandbox on SF1 mobile app.

We have a javaScript Lead Convert button on the lead having some field validation on javascript which was working fine on desktop version but for SF1 we have created a new action and had written our javascript code on Visualforce page's javascript tag. Below is the code:

-----------------------------------------------------------------------
<apex:page standardController="Lead">
<apex:includeScript value="/soap/ajax/21.0/connection.js"/>
<apex:includeScript value="/soap/ajax/21.0/apex.js"/>
<script type='text/javascript' src='/canvas/sdk/js/publisher.js'/>
 
<script>
function myJavascriptFunc(){   
        var obj = '{!lead.id}';
        var leadType = '{!lead.Type__c}';
        
        sforce.connection.sessionId = '{!$Api.Session_ID}';
              if(leadType == 'ATF'){                       
                var CheckLeadActivityDetails = sforce.apex.execute("LeadConversionCheck","CheckLeadActivityDetails",{leadid : obj});
                
                if(CheckLeadActivityDetails == 'false'){
                 alert('Activity Name, Description of Activity, Activity Location and Funds Raised For should not be blank ');
                 Sfdc.canvas.publisher.publish({name: "publisher.close", payload:{refresh:"true"}});
                }
                 
                if(CheckLeadActivityDetails == 'true'){ 
                document.location.href = "/apex/npsp__LD_LeadConvertOverride?isdtp=p1&id="+obj;        
                }  
               }  
               else{ 
                var CheckLeadWWCCDetails = sforce.apex.execute("LeadConversionCheck","CheckLeadWWCCDetails",{leadid : obj});
                
                if(CheckLeadWWCCDetails == 'false'){    
                 alert("If WWCC Override is not checked, then WWCC Status should be \'Pass\'");
                 
                 Sfdc.canvas.publisher.publish({name: "publisher.close", payload:{refresh:"true"}});            
                }
                 
                if(CheckLeadWWCCDetails == 'true')
                 document.location.href = "/apex/npsp__LD_LeadConvertOverride?isdtp=p1&id="+obj; 
                 
                } 
                             
 }
 

 var previousOnload = window.onload; 
 window.onload = myJavascriptFunc();
 
</script>

</apex:page>

----------------------------------------------------------

We open above VF page using action on SF1 app but sometimes this custom "Convert" action open's the Contact drop-down picklist or other picklist and sometimes it does not open the picklist.

Also, Cancel and Convert button not redirected to the desired page. 

We have tested this on iPad as well as on Andriod phone.

Below is the screenshot:

![screenshot_2017-04-28-17-20-07-945_com salesforce chatter](https://cloud.githubusercontent.com/assets/21311075/25527784/efe229c6-2c37-11e7-94d7-c1d77a166ac1.png)

![screenshot_2017-04-28-17-20-16-721_com salesforce chatter](https://cloud.githubusercontent.com/assets/21311075/25527787/f5db9222-2c37-11e7-84c8-0d4901eaa54b.png)

Can we get help on this?

Thanks in advance!

**Comment by judisohn** [comment]
@AnkurJaiswal619 Please post this in the [Developers](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjxL) group on the Power of Us Hub for best results in troubleshooting your code. We prefer to leave Github for only items once they are actionable by our team. Thanks for understanding.
