### ISSUE TITLE
Manage Household: adding Contacts to same HH w/same Address creates multiple default addresses

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2566]
[Hub thread.](https://powerofus.force.com/0D58000003NLLLX)

Replicated in latest build, exactly as customer describes. This only happens in Manage Household. If the Contact is reparented to Household, or if standard SFDC Account Merge is used, the Address record is not duplicated.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000006VYbAAM" target="_blank">W-018512</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.103 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.103
