### ISSUE TITLE
Send Acknowledgment BTN not gracefully handling errors

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2567]
If an unhandled error occurs when sending an email acknowledgement from an Opportunity the cNotSent variable is not being set and is resulting in an error on the Visualforce page.
"The value 'null' is not valid for operator '>'
Error is in expression '{!cNotSent > 0}' in component <apex:outputPanel> in page npsp:opp_sendacknowledgmentbtn" since the cNotSent variable is never being set.

Steps to replicate:
Activate the Opportunity Email Acknowledgment
Create a Validation Rule on the Opportunity that will fire
Go to an Opportunity with a Primary Contact and click the Send Email Acknowledgement button

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006DbtXAAS" target="_blank">W-018517</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.99 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.99
