### ISSUE TITLE
In Multicurrency org, Best Gift Year Total not rolling up correct value if opp/account currency does not match user currency

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2570]
If the user's currency (may also be related to corporate currency) is a different value than the currency on the Opp & Account, then Best Gift Year Value appears to be using the converted value of the user's currency, rather than the value of the Opportunity (and then further converting it). 

Screen shot from customer org illustrates issue based on user currency in GBP, Account in USD and a single $75K Opp in USD. 

![image](https://cloud.githubusercontent.com/assets/4614343/25757989/c2b969d8-319a-11e7-9c5a-dfe08b2c430a.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006DjeGAAS" target="_blank">W-018567</a>

**Comment by njjc** [comment]
[Here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup.cls#L280) and [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup.cls#L435) is where we need to update the value with the correct currency for multicurrency orgs (example [here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/RLLP_OppRollup.cls#L818)).

**Comment by mrbelvedere** [comment]
Included in beta release 3.100 (Beta 15)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.100
