### ISSUE TITLE
Exclude Deceased from HH Names

### ISSUE THREAD

**Issue by benderguy** [SalesforceFoundation/Cumulus#2571]
There seems to already be a trigger that updates Contact fields _Do Not Call_, _Do Not Contact_, & _Email Opt Out_ when a _Deceased_ is checked. A client recently pointed out that the Contact should logically also be removed from Household names. I submit that if we are going to have a trigger that it should also check the boxes for _Exclude from Household Name_, _Exclude from Household Formal Greeting_, & _Exclude from Household Informal Greeting_.

**Comment by judisohn** [comment]
What you are requesting was the original behavior when the trigger was written around Deceased contacts. However, we got consistent feedback that users didn't like having the household renamed to 'Anonymous Household' in this scenario, and the only way to avoid this was to not exclude from Household Name. However, the code _does_ update Exclude from Household Formal Greeting and Informal Greeting. 

I just confirmed that this behavior is working as designed in the latest build. If your contacts are not being excluded from Greetings when marked Deceased, please check field visibility for _SYSTEM: Custom Naming on Account and the "Exclude from..." checkboxes on Contact. If you are still having issues, please post in the NPSP Group on the Hub as we prefer Github issues be just for actionable work items. Thanks!
