### ISSUE TITLE
Account Converter should create accounts with Contact's owner

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2577]
Current the Account converter does not explicitly set the owner of any Household Accounts that get created, so the running user defaults to the owner.  Customers have requested to use the Contact owner.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006JXGhAAO" target="_blank">W-018653</a>

**Comment by judisohn** [comment]
This is also an issue with the Data Importer. Basically, any time that NPSP creates the Account, which is a lot. I would recommend that we always set the Account owner to the Owner of the Primary Contact on Account creation, regardless of what code is creating the Account.

**Comment by vmarasow** [comment]
Just lurking around here.
Wondering, regardless if the Account is created through the Account Converter or the Data Importer, the logic to assign ownership of the Account would still need to be implemented in Account Converter, being that all triggers are disabled when the Account Converter is running. Amirite?

**Comment by judisohn** [comment]
Good point @vmarasow

**Comment by mrbelvedere** [comment]
Included in beta release 3.134 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 3.134
