### ISSUE TITLE
Multicurrency causes opp import failure when batch is larger than 100 records

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/Cumulus#2578]
When multiple currencies are enabled for an organization, opportunity imports will crash if batch is larger than 100 records due to the SOQL query limit being exceeded during OCR creation.  It appears that OPP_OpportunityNaming.getOppNamesAfterInsert() is causing a SELECT CurrencyIsoCode on every opp record and so the import crashes at 100 records.

A workaround is to disable OPP_OpportunityContactRole_TDTM and create OCRs via the data import itself.

Note: A custom opp name format is defined in this instance.  I don't know if that makes a difference.

10:23:21.912 (2912120342)|ENTERING_MANAGED_PKG|npsp
10:23:21.912 (2914463149)|SOQL_EXECUTE_BEGIN|[216]|Aggregations:0|SELECT OpportunityId, ContactId, Role, IsPrimary FROM OpportunityContactRole 
10:23:21.912 (2921901452)|SOQL_EXECUTE_END|[216]|Rows:0
10:23:23.302 (4302997148)|DML_BEGIN|[268]|Op:Insert|Type:OpportunityContactRole|Rows:200
10:23:24.928 (5928326160)|DML_END|[268]
10:23:24.928 (5968712528)|SOQL_EXECUTE_BEGIN|[119]|Aggregations:1|SELECT recordtype.name, amount, closedate, id, name, recordtypeid, account.npe01__systemisindividual__c, (SELECT opportunityid, contact.id FROM OpportunityContactRoles WHERE IsPrimary=TRUE LIMIT 1) FROM Opportunity WHERE Id IN :oppList
10:23:24.928 (6062318570)|SOQL_EXECUTE_END|[119]|Rows:200
10:23:24.928 (6146013184)|SOQL_EXECUTE_BEGIN|[140]|Aggregations:0|SELECT CurrencyIsoCode FROM Opportunity WHERE Id = '0063600000KR2OZAA1' LIMIT 1
10:23:24.928 (6151223101)|SOQL_EXECUTE_END|[140]|Rows:1
10:23:24.928 (6153363078)|SOQL_EXECUTE_BEGIN|[140]|Aggregations:0|SELECT CurrencyIsoCode FROM Opportunity WHERE Id = '0063600000KR2OaAAL' LIMIT 1
10:23:24.928 (6158422977)|SOQL_EXECUTE_END|[140]|Rows:1
10:23:24.928 (6159886219)|SOQL_EXECUTE_BEGIN|[140]|Aggregations:0|SELECT CurrencyIsoCode FROM Opportunity WHERE Id = '0063600000KR2ObAAL' LIMIT 1
10:23:24.928 (6164497330)|SOQL_EXECUTE_END|[140]|Rows:1
10:23:24.928 (6165870546)|SOQL_EXECUTE_BEGIN|[140]|Aggregations:0|SELECT CurrencyIsoCode FROM Opportunity WHERE Id = '0063600000KR2OcAAL' LIMIT 1
10:23:24.928 (6170290087)|SOQL_EXECUTE_END|[140]|Rows:1
etc etc ....

**Comment by judisohn** [comment]
Thanks for the report @davidchengIC - team is working on optimization around rollups/multicurrency now so timing for this is good. FYI @njjc

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006NfuLAAS" target="_blank">W-018654</a>

**Comment by davidhabib** [comment]
we should see about getting CurrencyIsoCode selected in the initial soql so that we don't keep requerying for it.

**Comment by njjc** [comment]
[Here](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_Currency.cls#L126) is where the issue is, [here is the caller](https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/OPP_OpportunityNaming.cls#L431). I think we'll have to change the design from passing the ID to passing the whole SObject and assuming the SObject has the CurrencyIsoCode field populated.

**Comment by mrbelvedere** [comment]
Included in beta release 3.107 (Beta 7)

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
