### ISSUE TITLE
Changing Opportunity from Open to Closed/Lost should Write Off the auto-created Payment, not delete it

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2579]
[Thread.](https://powerofus.force.com/0D58000003MlZQH)

Related to #1824 

If custom fields have been added to the Payment, or the Payment is related to other objects or processes, deleting the record can cause issues.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PD7wAAG" target="_blank">W-018655</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.111 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.111
