### ISSUE TITLE
If new Opp added to Open Recurring Donation, Paid Amount rollup is not calculated on edited Opportunities

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2581]
[Thread.](https://powerofus.force.com/0D58000003PMOPZ)

Verified in test org. It appears that the when the Opportunity is updated to include the RD, it's not firing the trigger on RD the way it does on insert. Then the batch is not seeing that Opp in its query either?

While it's our preferred process to update an auto-created Opp rather than create a new one, this still feels like a bug to investigate.

Steps to repeat:

1. Contact with RD, Open (I did quarterly but that doesn't matter)
2. Create new Opp for Contact and populate RD lookup
3. Verify that Paid amount is updated with new opp
4. Create new Opp for Contact and leave RD lookup blank. Save.
5. Edit and add RD.
6. RD Paid amount not updated. Running Batch does not update. Refresh does not update.

![image](https://cloud.githubusercontent.com/assets/4614343/26121052/f84794cc-3a40-11e7-8cf1-1f30ae08450f.png)

![image](https://cloud.githubusercontent.com/assets/4614343/26121088/14a28276-3a41-11e7-988e-ee3e84f3168a.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PFYOAA4" target="_blank">W-018665</a>

**Comment by FraidyStrauss** [comment]
Deleting a related opportunity should also trigger a recalculation. It doesn't do that now.

**Comment by mrbelvedere** [comment]
Included in beta release 3.100 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.100
