### ISSUE TITLE
Best Gift Year error

### ISSUE THREAD

**Issue by dguthmueller** [SalesforceFoundation/Cumulus#2582]
I have a custom date field called "Will Received" to mark when we provide a will to our clients.  It has a workflow that checks whether a date has been entered, and if so, it creates a task called "Will Provided".  For some reason, when we enter a date into the "Will Received" field, it prevents the record from saving and gives the error "Error: You must enter a value" for the Best Gift Year field.  We have not made the Best Gift Year field required and it even gives the error when the Best Gift Year field is removed from the page layout.  If I deactivate the workflow, it does not give the error.  However, the workflow and task creation have absolutely nothing to do with the Best Gift Year field.

**Comment by judisohn** [comment]
Hi @dguthmueller There is absolutely no validation on the Best Gift Year field in NPSP. In fact, none of our rollup fields should have any data entered in them at all. So there must be something else unique in your org that is causing this behavior. Did you check for a custom validation rule? If that wasn't it and you don't mind, please [post in the NPSP Group](https://powerofus.force.com/0F980000000CjRe) in the Hub or open a [support ticket](https://powerofus.force.com/articles/Resource/How-to-log-a-tech-support-ticket-with-salesforce-com) for further investigation, as we reserve Github issues only for items that are actionable changes in NPSP. Thanks!
