### ISSUE TITLE
If Relationship Type is changed, the reciprocal relationship should update to match new Type. 

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2586]
[Thread.](https://powerofus.force.com/0D58000003Pv14m)

Replicated. When Type is 'Mother' for example, reciprocal relationship is 'Daughter' as it should be. When Type on original record changed to a different value, the appropriate linked Type is not updated on the reciprocal and should be.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V91jAAC" target="_blank">W-018746</a>

**Comment by tet3** [comment]
Prob my fault. :-(

**Comment by judisohn** [comment]
Nope, it's ours in that we didn't catch the regression in our testing.
