### ISSUE TITLE
Payment Wizard interval frequency picklist values should be labels, not hard coded

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2588]
In the Payment Wizard, the interval drop down selection is hard-coded, which prevents non-English users from translating the values. 
![salesforce developer edition 1](https://cloud.githubusercontent.com/assets/10934541/26383712/1013314c-3ffa-11e7-82c4-5baf49b37592.png)

With API 39.0 we have the ability to reference picklist API names instead of labels in our code, so we may want to look into that as a solution that is integration proof and localization proof.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006V9YRAA0" target="_blank">W-018795</a>

**Comment by tet3** [comment]
@mpusto I'm pretty sure this isn't a picklist - just a set of `SelectOption`s in the code. If I'm wrong, what picklist field is this? I'm turning back to the work on #1967 I did at the Baltimore sprint, and can include this. Do you know offhand if there are existing labels for Week, Month, Year that could be used?

**Comment by mpusto** [comment]
You're correct @tet3 it is just SelectOptions in the code rather than a picklist. We need to update it to use labels instead.

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110
