### ISSUE TITLE
If Level is updated to blank value by criteria, Previous Level is not populated

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2590]
[Thread.](https://powerofus.force.com/0D58000003QG85q)

Replicated. Happens when record does not meet any criteria for a Level.

Steps to repeat:

1. Custom number field on account, plus Level & Previous Level fields
2. Level with minimum value of 5, max of 10
3. Populate number field with 6, run Level - Level is correct
4. Change number to 2, run Level

The Level should appear in Previous Level and Level should be blank, instead both fields are blank.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006VCONAA4" target="_blank">W-018816</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.103 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.103
