### ISSUE TITLE
DML errors in any of the batch jobs cause the batch of 200 to fail

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2592]
When a dml exception occurs in the batch rollups it will cause the whole batch of 200 records to fail. Instead use the `allOrNothing` flag to allow as many record as possible to successfully update and then log the failures in the NPSP Error Log. (Should that be one log entry per failed batch with a list of Id's, or one log entry per failed record?)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006f2GcAAI" target="_blank">W-018883</a>
