### ISSUE TITLE
Allow customers to provide their own household custom naming implementation

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2593]
We have an interface, but we haven't made it global yet.
hub thread: https://powerofus.force.com/0D58000003ROLX5

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006hjpQAAQ" target="_blank">W-018895</a>

**Comment by RBLopez** [comment]
Is this going to make it into the 3.101 release?

**Comment by judisohn** [comment]
@RBLopez Sorry, the work wasn't completed in time for the 3.101 release so it should make it for 3.102 in 2 weeks.

**Comment by mrbelvedere** [comment]
Included in beta release 3.102 (Beta 2)

**Comment by judisohn** [comment]
@RBLopez The work has been merged into our main development branch which means it will be in the next release for sure. Could you do me a favor and check out the pull request #2629 and let me know if the change is what you were expecting and if the notes (that will appear in the release notes) make sense? Note that your class has to include all the methods and not just the one(s) you wanted to handle differently.

**Comment by RBLopez** [comment]
Looks good to me. Thanks!

**Comment by mrbelvedere** [comment]
Included in production release rel/3.102
