### ISSUE TITLE
API version problem

### ISSUE THREAD

**Issue by TonyRenHK** [SalesforceFoundation/Cumulus#2602]
if I update the page 'ALLO_ManageAllocations' to version 40, the input field will be displayed like this in lightning  

 <apex:inputField value="{!Allo.npsp__General_Accounting_Unit__c}" styleClass="lookupInput"/>

![image](https://user-images.githubusercontent.com/9688136/26962982-81c80fc2-4d1c-11e7-986b-80232c6047d6.png)

**Comment by judisohn** [comment]
Thanks @TonyRenHK We regularly evaluate our API version and will update once necessary testing is done across the entire app. Given that this is something that should be covered as part of that bigger, regular effort I'm going to close this as a stand alone issue for now. 

But for future reference when we get to that point, what is the use case that you need to update this particular page right now?
