### ISSUE TITLE
Allow configurable batch size for RD_RecurringDonations_BATCH 

### ISSUE THREAD

**Issue by stopthesignal** [SalesforceFoundation/Cumulus#2610]
We receive errors ("Too many query rows: 50001") when the daily Recurring Donations batch (RD_RecurringDonations_BATCH) process runs to create/refresh opportunities in Recurring Donations. The batch size for RD_RecurringDonations_BATCH is set to 50 and cannot be changed. We've reduced the Opportunity forecast months and it partially alleviates the problem, but a configurable batch size would be great.  

Can we allow the RD_RecurringDonations_BATCH batch size to be configurable, similar to how the Donation Rollup processes are in the NPSP Settings tab? (like RLLP_OppContactRollup_BATCH, RLLP_OppAccRollup_BATCH etc).

**Comment by judisohn** [comment]
Thanks for the suggestion @stopthesignal - I see the size is indeed set to 50 [here](https://github.com/SalesforceFoundation/Cumulus/blob/916f7276796ffda7a0766ffce404ce140324fcc0/src/classes/STG_PanelRDBatch_CTRL.cls#L64). Not sure if this is something that can be controlled via setting the same way the other batch is, but I'll push this forward for future consideration.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006uODSAA2" target="_blank">W-019043</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.120 (Beta 6)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
