### ISSUE TITLE
Payment wizard error if Date of First Payment cleared

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2620]
bring up the Payment wizard.
clear out the date from the Date of First Payment field
click on the Calculate Payments button

Attempt to de-reference a null object
Error is in expression '{!calculate}' in component <apex:commandButton> in page pmt_paymentwizard: Class.djhcumulus2.PMT_PaymentWizard_CTRL.calculate: line 302, column 1

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000070H8RAAU" target="_blank">W-019132</a>

**Comment by tet3** [comment]
Will see if I can address this in other Payment Wizard work for which I will submit a pull request this week.

**Comment by tet3** [comment]
@davidhabib @judisohn This should give the user an error that the Date of First Payment is required, correct?

**Comment by tet3** [comment]
Eg: 
<img width="927" alt="blankdateerror" src="https://user-images.githubusercontent.com/1319826/29181507-72b55aca-7dc9-11e7-8af7-bb1b846a7a3f.png">

Using ```System.Label.exceptionRequiredField + ' ' + System.Label.pmtWizardFirstPaymentDate```

**Comment by davidhabib** [comment]
yes, that looks right to me @tet3

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110
