### ISSUE TITLE
Recurring Donations settings should not default to an inactive record type

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2633]
From @mattparlane on 06/11/2017:
> 
> I recently added some inactive record types to assist a migration from one org to another, and I found that my tests now fail. I traced it to this line, where an inactive record type is being used. Setting the record types to active solves the problem.
> 
> Please note that I haven't actually tested this, I don't even know how. I'm not actually proposing this change, I just want to start a conversation with someone more knowledgeable than myself.
>

**Comment by force2b** [comment]
**lurch: attach W-019089

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006uSK7AAM" target="_blank">W-019089</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.102 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.102
