### ISSUE TITLE
Campaign Allocations not used if a null Amount field is populated after the Opp was previously saved.

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2636]
To reproduce:
* Create a test campaign with one Allocation on it
* Ensure that Default Allocations are enabled in NPSP Settings with a different GAU than what is defined on the above Campaign
* Create a new Closed/Won Donation Opportunity populating the Primary Campaign field, but leaving the Amount field null. Save the record.
* Edit the Opportunity and enter a value into the Amount field. Save the record.
* Expected: The default allocation on the Opportunity matches the GAU on the linked Campaign.
* Actual: The allocation on the Opportunity is the GAU from the NPSP Default Allocation setting.

**Comment by force2b** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007ICV4AAO" target="_blank">W-019442</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.109 (Beta 6)

**Comment by cpolcyn** [comment]
Included in production release rel/3.109
