### ISSUE TITLE
User Defined Rollup: Must have a value in the amount field for roll up of other currency field

### ISSUE THREAD

**Issue by ashimasaigal** [SalesforceFoundation/Cumulus#2637]
While working to create a roll up of Fair Market Value from the Opportunity to the Account, I left the Amount field on the Opportunity empty (without a zero or any number, just blank). When I ran batch update, the roll up to the Account field was Zero. 

Once I changed the Amount field on the Opportunity to a Zero, then the field on the Account accurately reflected the Fair Market Values of the Opportunities attached to that Account.

It seems to only be affecting currency fields and not the number fields. I'm assuming this is a bug, but perhaps it is acting as it should.

This image shows that the NOTHING  in the Opportunity amount field gives no value in the Account:
![nothing in opp](https://user-images.githubusercontent.com/11590445/28186078-c4074e9e-67e7-11e7-8631-42a53b53a212.PNG)

Account information:
![nothing in acct](https://user-images.githubusercontent.com/11590445/28186079-c408c972-67e7-11e7-9941-609398bbb7a8.PNG)

This image shows that a Zero in the Opportunity amount field gives the value in the Account:
![zero in opp](https://user-images.githubusercontent.com/11590445/28186077-c407228e-67e7-11e7-9e98-c9a9072e9935.PNG)

Account information:
![100 in opp](https://user-images.githubusercontent.com/11590445/28186075-c401a49e-67e7-11e7-9834-205f90072950.PNG)

**Comment by judisohn** [comment]
Thanks, @ashimasaigal - I see what you mean. Not sure when anyone will have a chance to look at this, put I'll push it through to our backlog.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007IEdJAAW" target="_blank">W-019461</a>

**Comment by ashimasaigal** [comment]
Thank you @judisohn , I was perplexed when this simple roll up wasn't working, glad it was an helpful find.

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128
