### ISSUE TITLE
Links in Cascade Delete error messages don't display in lightning

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2641]
We'll likely have to remove the links altogether if there is no workaround.

**Comment by njjc** [comment]
**lurch: add

**Comment by force2b** [comment]
agreed. there is no way to know what the UI is from a trigger context. The delete overrides could still work though because it's possible to determine the UI from a page controller.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007O4fSAAS" target="_blank">W-019558</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.115 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.115
