### ISSUE TITLE
Manage Household: Remove Contact Address is not created when the former Household Address is being created

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/Cumulus#2647]
**How to Reproduce:**
1. Find/Create a Household with at least two Contact and a default Address.
2. View the Household > Manage Household > click X for a Contact to remove it > confirm the removal
3. Click Change Address > scroll down and click Enter A New Address > enter values for a new address > Set Address
4. Click Save

**Expected Result:**

- The Household and its Contacts' Address has been updated to the new default Address.
- The former default Address is still assigned to the Household but it is not default.
- The removed Contact is assigned to a new Household.
- The removed Contact has a new default Address which has the same values as the previous Household former default Address.
- The new Household has the default Address assigned.

**Actual Result:**

- The Household and its Contacts' default has been updated to the new default Address.
- The former default Address is still assigned to the Household but it is not default.
- The removed Contact is assigned to a new Household.
- (Error) The removed Contact Address is the same as the previous Household former default Address (the same Salesforce Id). 
- (Error) The new Household has no assigned Address.

**Comment by RadSFDeveloper** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007O7EBAA0" target="_blank">W-019591</a>

**Comment by mbeaty-sf** [comment]
Tested against most recent NPSP release to be displaying Expected Result.
