### ISSUE TITLE
Cascade Delete Non Selective Query Errors

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2650]
[Users have reported](https://powerofus.force.com/0D58000003FmTM9) non-selective query errors when bulk deleting accounts.

In testing query selectiveness for cascade delete queries that use multiple cross object lookups, (e.g. ```Recurring_Donation__r.npe03__Contact__r.AccountId```), it appears that only the last lookup can use the available index; the __r relationships use a table scan every time, which causes non-selectiveness.

The solution is redesign cascade deletion to split cross object lookups into multiple separate queries, allowing each one to use the index.

More information [here](https://salesforce.quip.com/pKYsAzptcsax), lines 225-230.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007OBA4AAO" target="_blank">W-019629</a>

**Comment by judisohn** [comment]
**lurch: attach W-021836

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009BFS5AAO" target="_blank">W-021836</a>

**Comment by cpolcyn** [comment]
Included in beta release 3.120 (Beta 11)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
