### ISSUE TITLE
Cascade Delete Static Flag Issue

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#2651]
Cascade Delete uses a "set and forget" static flag that doesn't work with batches over 200.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007OBAEAA4" target="_blank">W-019630</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.104 (Beta 3)
