### ISSUE TITLE
If standard Middle Name enabled and used in Household Naming, error in Manage Household

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2658]
Replicated in scratch org.

1. Enable Middle Names
2. Use this as Household Formal Greeting Formula: {!{!Salutation} {!FirstName} {!MiddleName}} {!LastName}
3. Go to Manage Household on any Account: duplicate field selected: MiddleName

![image](https://user-images.githubusercontent.com/4614343/28480765-35df872c-6e30-11e7-9eda-07bb5fd700bf.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007ODE7AAO" target="_blank">W-019653</a>

**Comment by force2b** [comment]
It's probably adding MiddleName to the query after it was previously added by another method that detects that MiddleName is enabled. Should be a very quick fix.

**Comment by mrbelvedere** [comment]
Included in beta release 3.103 (Beta 13)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.103
