### ISSUE TITLE
Batch Data Entry - INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY

### ISSUE THREAD

**Issue by dthowell** [SalesforceFoundation/Cumulus#2664]
I am getting a repeated issue across a few clients. 

It starts when an error is made on entry. Here is an example one:
Message: "Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Stage]: [Stage]"

Then if you try and enter the data again and save it correctly you get:
Message: "Insert failed. First exception on row 0; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: a0P7F0000012EnA: []"

My guess is that it doesn't realise that the first entry didn't save properly.

**Comment by judisohn** [comment]
Hi @dthowell Please see our statement regarding Batch Data Entry here: https://powerofus.force.com/articles/Resource/Statement-on-Batch-Data-Entry We are aware that there are errors and issues, but we have no plans to make any additional bug fixes or updates at this time.

Stay tuned for an announcement over the next few months regarding new batch data entry functionality. Thanks for your patience.
