### ISSUE TITLE
HH_AutoCompleteOptionController dont have helper js 

### ISSUE THREAD

**Issue by TonyRenHK** [SalesforceFoundation/Cumulus#2670]
In the path ' Cumulus/src/aura/HH_AutoCompleteOption/HH_AutoCompleteOptionController.js', there have following code:

({
    handleClick : function(component, event, helper) {
        helper.fireOptionSelectedEvent(component);
    },
})

Where can I find 'helper.fireOptionSelectedEvent'??

**Comment by jjbennett** [comment]
Hi @TonyRenHK,

If you take a look at the HH_AutoCompleteOption.cmp you will see that it extends="c:autocompleteOption". The autocompleteOptionHelper.js is where you will find that function.
