### ISSUE TITLE
Intermittent assertion failure in PSC_PartialSoftCredit_TEST unit test 

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/Cumulus#2674]
There is an intermittent unit test assertion failure in PSC_PartialSoftCredit_TEST.createDupePSCsNewOCRs() when Partial_Soft_Credit__c.Contact_Role_ID__c field is compared with an OpportunityContactRole.Id on sorted records.

Test failure details:
**PSC_PartialSoftCredit_TEST.createDupePSCsNewOCRs**
_Stack Trace:_ Class.PSC_PartialSoftCredit_TEST.createDupePSCsNewOCRs: line 408, column 1
_Message:_ System.AssertException: Assertion Failed: Expected: 00K0v000000KGoYEAW, Actual: 00K0v000000KGoaEAG

Notes:
- The issue seems to be related to retrieving records using Order By Contact_Role_Id__c field which is Text(18) (Unique Case Sensitive). As per @davidhabib research: "The following factors affect results returned with ORDER BY: Sorting is case insensitive."
- It is required to also investigate if other PSC unit tests verify Contact_Role_ID__c by comparing sorted records.

**Comment by RadSFDeveloper** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007U890AAC" target="_blank">W-019755</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.103 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.103
