### ISSUE TITLE
On sandbox refresh, NPSP Scheduled Jobs are not functional and leave error in NPSP Settings

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2684]
[Hub thread.](https://powerofus.force.com/0D58000003V7iyk)

[Known Issue](https://success.salesforce.com/issues_view?id=a1p300000008Ym6AAE) not targeted for a fix.

Error in NPSP Settings immediately upon sandbox refresh when clicking any sub tab:

![image](https://user-images.githubusercontent.com/4614343/28930200-3725a2fa-7840-11e7-8d53-9655f5ee8483.png)

Investigate whether we can detect these corrupted job records on refresh and delete/recreate them correctly.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000065rI4AAI" target="_blank">W-019885</a>

**Comment by judisohn** [comment]
This was determined to no longer be an issue so closing without any changes.
