### ISSUE TITLE
Custom Contact Roles do not receive full soft credits on Contact Record

### ISSUE THREAD

**Issue by jrpershall** [SalesforceFoundation/Cumulus#2687]
<img width="1243" alt="ocr problem - configured settings 1" src="https://user-images.githubusercontent.com/26254435/29132810-03a7a9ee-7cf7-11e7-9b0f-808d6d20060b.png">
<img width="1289" alt="ocr problem - role assignment" src="https://user-images.githubusercontent.com/26254435/29132756-dbb2c716-7cf6-11e7-9e19-0a946f738bd4.png">
<img width="671" alt="ocr problem - contact record no soft cred" src="https://user-images.githubusercontent.com/26254435/29132754-dbad55e2-7cf6-11e7-9bad-58b84019b3ac.png">

- double checked settings, the custom role is selected 
- report shows full soft credits working for non-custom contact roles
- Manage Soft Credits page shows the Contact as getting a full soft credit. 
- Switching the Contact Role to a default one and running the batch correctly populates the rollup.

**Comment by judisohn** [comment]
Hi @jrpershall Please post in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) in the Hub and we'll be able to help you with troubleshooting this issue. Should this turn out to be a bug that developers can address, we can reopen the issue. Thanks!
