### ISSUE TITLE
NPSP Settings > Household Naming Settings: Contact insert/update fails when Phone/Fax fields are included in Household Name Format

### ISSUE THREAD

**Issue by RadSFDeveloper** [SalesforceFoundation/Cumulus#2688]
How to reproduce:
1. View NPSP Settings > People > Households > Edit > Set Household Name Format field to include the Phone or Fax in the format > Save
2. Create or select a Contact > Edit a Contact > Save > an error is generated.

**Comment by RadSFDeveloper** [comment]
**lurch: attach w-019970

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007kK68AAE" target="_blank">W-019970</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.105 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.105
