### ISSUE TITLE
Recurring Donation installment Opp names created are not consistent with the Opportunity Naming pattern under NPSP Settings

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2689]
New Recurring Donation installment are always created with the following pattern regardless of what is defined under NPSP Settings: "{!Donor.Name} {!Label.npe03.RecurringDonationPrefix} (# of #Installments) {!CloseDate}". In addition, the available Opportunity Naming patterns under NPSP Settings do not support a pattern for "(# of #Installments)".

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007kK6rAAE" target="_blank">W-019971</a>

**Comment by judisohn** [comment]
Closing to align with internal discussion.
