### ISSUE TITLE
Contact Unique ID matching no longer working in NPSP Data Import

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2690]
Thread [here](https://powerofus.force.com/0D58000003ZhVBF), also reported in Partner forum and replicated in test org.

Correctly configured matching ID fields now display error message when selected as matching field in tool. These previously configured fields used to work correctly until 3.103 release. 

![image](https://user-images.githubusercontent.com/4614343/29192866-acf925a8-7de8-11e7-814c-07925ea7c74c.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by mrbelvedere** [comment]
Included in beta release 3.104 (Beta 1)

**Comment by Agroag** [comment]
Hi - I'm having this same issue.  When can we expect a fix? Thanks!

**Comment by njjc** [comment]
The fix for this is in 3.104 which will be pushed to production tomorrow. You can install it manually today with the link at the bottom of the [release information](https://github.com/SalesforceFoundation/Cumulus/releases/tag/rel%2F3.104).
