### ISSUE TITLE
Failed BDI Import - Error for missing ID on New and Exisiting Contact Imports

### ISSUE THREAD

**Issue by savvyjd** [SalesforceFoundation/Cumulus#2694]
Error: The Contact Custom Unique ID setting field Id_15__c must have matching fields in the NPSP Data Import object whose API Names are Contact1_Id_15__c and Contact2_Id_15__c.

Trigger 1: DemandTools BDI import of new donor contacts who wouldn't have an ID to map to
Trigger 2: DemandTools BDI import of existing donor contacts who do have an ID to map to

We do this BDI import once a week on Monday (8/8) mornings and it sounds like last release was pushed last Monday night. We have not changed any part of our process and I don't see anything in documentation to indicate a change that would effective about ability to do BDI imports.

I've attached a screenshot of our BDI settings page in case something there needs to be changed based on new update.
![screen shot 2017-08-14 at 11 10 30 am](https://user-images.githubusercontent.com/31014409/29284872-48028b48-80e1-11e7-8f8c-4fcea956d01c.png)

**Comment by davidhabib** [comment]
thanks for reporting.  we've already identified it in issue #2690 and will have a fix available this week for sandbox push, that you can manually install in production if you can't wait until the following week's production push.
