### ISSUE TITLE
BDI: custom Contact and Account Unique ID's don't support fields from other packages

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2700]
the optional Contact Custom Unique ID and Account Custom Unique ID settings allow the user to specify their own custom field for doing matching with.  These fields currently are assumed to always be in the org's non-namespaced code.  We don't support the fields living in another managed package, as well as a mixture of the Contact or Account field coming from another managed package, but the Data Import field being added by the customer without a namespace.  

Note that no customer has yet asked for this support, but it is a limitation of the current code and settings.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by judisohn** [comment]
@davidhabib good one. I'm frankly surprised this hasn't come up already... in the meantime, should anyone review this, a workaround would be a workflow rule or process that copies the value to a custom field?

**Comment by davidhabib** [comment]
that might work, but having workflows run during data import is probably not a good practice.

**Comment by judisohn** [comment]
I was thinking the workflow rule would fire when the external ID was added by the app, which is not necessarily in bulk.

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 7)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110

**Comment by Agroag** [comment]
I can no longer see fields we were using for custom mapping - if there is another issue or article that could help that would be great.  I'm not sure how to get fields we were using for custom account and contact ID matching to show up again.  They were there and now they're not.  What could have changed to make them not available? Thanks!

**Comment by mpusto** [comment]
https://github.com/SalesforceFoundation/Cumulus/releases/latest says "The Batch Data Import Configuration Options for Contact Custom Unique ID and Account Custom Unique ID now only display fields that are marked Unique or External ID. Additionally, those fields can now come from other managed packages."  That means the field needs to be marked as Unique in the custom field set up. This prevents errors for scenarios where two records could have the same ID (if not marked unique) and then data could be overwritten.

**Comment by Agroag** [comment]
Hi - Thanks for the quick response.  We were using a formula field to match.  Do we need to create a new external ID field and a workflow to populate it with the IDs from our custom ID field? Do you have any recommendations?

**Comment by mpusto** [comment]
Yes that would be the best way. It can be either an external Id field or simply marked as "unique"
