### ISSUE TITLE
If Opportunity Contact Role Value does not match API Name, soft credit rollup does not work

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2704]
Salesforce now has API Name in Opportunity Contact Role definition. NPSP Settings selects values based on Value. However, if a value is selected where the API name is different than the value, then the soft credit rollups will not work.

Steps to repeat:

1. Create 2 Contact Role values. Salesforce automatically sets the API Name to match the Value entered. Edit one to have a different API name.
2. in NPSP Settings, select both values to receive soft credit rollup.
3. Create an opportunity and assign 2 different contacts soft credit, one with each value.
4. Rollup Donation Batch job.
5. Observe that one contact with the matching API-Value has properly received the soft credit, while the one with the mismatch value did not.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007qTOTAA2" target="_blank">W-020126</a>

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)
