### ISSUE TITLE
Update Soft Credit rollups to count Organizational gifts with a soft credit Opportunity Contact Role marked Primary

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2708]
For a Household opportunity, the Primary Contact field on the opportunity automatically creates an Opportunity Contact Role (OCR) record, set to the donor role and checked as primary. This is right and gives that contact full soft credit and the gift rolls up to the Household. Good.

However, we do not have distinct behavior for Business gifts and this is challenging. Organizations want to track who the grant officer/primary contact is on those gifts from organizations, so it's logical to use the Primary Contact field on the Opportunity. And they want that contact to receive soft credit. When they populate the Primary Contact field, that automatic OCR is created and checked as Primary. NPSP ignores that OCR since it won't roll up as hard credit and with the primary box checked (and using the donor role) it won't roll up as soft credit either. Requires manual editing to correct.

Suggest we have settings allowing the admin to specify the specific behavior for Individual gifts vs the behavior for Organization gifts when it comes to the Primary Contact.

Thread [here](https://powerofus.force.com/0D58000003avBWO), [here](https://powerofus.force.com/0D58000003WgGqB) and [here](https://powerofus.force.com/0D58000003HShda) - and I'm sure there are quite a few more.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007a9HpAAI" target="_blank">W-020199</a>

**Comment by njjc** [comment]
This issue was partially fixed in #3027 which corrects the soft credit rollup behavior. @joy-sfdo will soon be delivering a new setting for the default role for Organization gifts that will fully fix this issue.

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)
