### ISSUE TITLE
With SmartyStreets address verification, Verification Status field not updating correctly

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2713]
Hub thread [here](https://powerofus.force.com/0D58000003btFpg).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000813gdAAA" target="_blank">W-020226</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.109 (Beta 5)

**Comment by mpusto** [comment]
Has been reported with Google API as well

**Comment by cpolcyn** [comment]
Included in production release rel/3.109
