### ISSUE TITLE
When a payment currency code is automatically change from the parent Opportunity, the true payment amount is not retained

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2720]
To reproduce:

- Multi-Currency Org
- Configure at least one additional currency
- Create a Donation in USD with a single Payment for $100
- Change the Donation Currency to a different currency
- Should: The Payment currency should be updated to match the Opportunity **and** the payment amount value should still exactly match the Opportunity.
- Actual: The Payment currency code is updated, but the Payment Amount is converted by Salesforce using the previous currency code's rate

**Comment by force2b** [comment]
** lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000818D0AAI" target="_blank">W-020256</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.107 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
