### ISSUE TITLE
Bug in Recurring Donations testOpenEndedMonthlyEndDates() Test

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2729]
There is a bug in this unit test when calculating the number of generated installments using the current month.

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000081H3nAAE" target="_blank">W-020316</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.107 (Beta 6)

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
