### ISSUE TITLE
Health Check false positive of a Trigger Handler error on PMT_Payment_TDTM on object npe01__OppPayment__c

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2732]
[Thread.](https://powerofus.force.com/0D58000003dBd0t)

Confirmed in test org with latest 3.106 release. 

![image](https://user-images.githubusercontent.com/4614343/30120442-d1d5a554-92f6-11e7-97e9-c552f37bae6f.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005uY5RAAU" target="_blank">W-020336</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.107 (Beta 9)

**Comment by cpolcyn** [comment]
Included in production release rel/3.107
