### ISSUE TITLE
Trigger Handler Null Pointer Exception when the Trigger Action is empty

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2742]
The trigger action field is not required and can be nulled out by an end user. This will result in an error message for both Health Check and when the trigger is ran on the object: "System.NullPointerException: Attempt to de-reference a null object Class.TDTM_ObjectDataGateway.getClassesToCallForObject: line 74, column 1 External entry point Class.TDTM_TriggerHandler.run: line 89, column 1 Trigger.TDTM_Account: line 34, column 1"

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008F6wYAAS" target="_blank">W-020423</a>

**Comment by manikrai29** [comment]
I would like to fix this bug.

**Comment by coriobriensfdo** [comment]
Hi @manikrai29, that's great thank you!! Would this be on behalf of your company (Traction I believe) or as an individual contribution?

I can see you've included the code changes from your personal GitHub org. Are you able to create a PR for it here in the Cumulus repo and link it to this fix? http://developer.salesforce.org/Cumulus/Contributor/Submit-Your-Feature.html

Also, would you mind sending me your email and full name as we'll need to send you a CLA to sign (or for Traction to sign if you've used company time/properly to submit the fix). 

Thank you!!

**Comment by manikrai29** [comment]
@coriobriensfdo as suggested I opened a new pull request. Secondly, this is on behalf of Traction; so, you can forward me the CLA at mmanik@tractionondemand.com

**Comment by coriobriensfdo** [comment]
Great, thanks! Can you tell me your full name?

**Comment by coriobriensfdo** [comment]
Great, can you tell me your full name @manikrai29? If you prefer you can email me that information at cori.obrien@salesforce.com
