### ISSUE TITLE
Task tab disappeared with latest update

### ISSUE THREAD

**Issue by koenwesselman** [SalesforceFoundation/Cumulus#2746]
We recently updated the NPSP in our org and the Task tab seems to have disappeared. When looking at the App in the App Manager, we can't re-add the tab either.

**Comment by judisohn** [comment]
This would have nothing to do with NPSP, which doesn't touch any standard Salesforce tabs as you're describing. Please post in the [Power of Us Hub](http://powerus.force.com) or [Success Community](http://success.salesforce.com) and I'm sure you'll get the resolution you're looking for.

**Comment by koenwesselman** [comment]
@judisohn , are you sure it's not to do with the fact that the NPSP app is created as a Classic (Lightning enabled) app? I can't add the Task tab to it, but I am able to add the Task tab to Lightning apps that aren't created for Classic originally.

**Comment by judisohn** [comment]
That may very well be it. There is nothing stopping you from creating your own App and adding whatever tabs to it that you like. Our aim is to support both Lightning and Classic at this time.

**Comment by koenwesselman** [comment]
Cool, I'll give that a try - thanks @judisohn ! I'd be happy to commit a Lightning-specific version here if that's helpful? I'd appreciate if that's not a path you want to go down at this point in time though.
