### ISSUE TITLE
Not using label to name field in Manage Household page

### ISSUE THREAD

**Issue by Yanuk** [SalesforceFoundation/Cumulus#2750]
Hello,

I encountered a problem when using the manage household page, the fields label were not translated.

I think the issue comes from this file : Cumulus/src/aura/HH_Container/HH_Container.cmp
The 'Household Name', 'Formal Greeting' and 'Informal Greeting' are hardcoded. I think they should use label like this : {!$Label.npo02.LabelName}.

Is it possible to correct this issue ?

Thank you

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008FDMFAA4" target="_blank">W-020451</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.111 (Beta 8)

**Comment by cpolcyn** [comment]
Included in production release rel/3.111
