### ISSUE TITLE
Contact Merge: If Primary Affiliation on non-master Contact, clean up is removing Primary Affiliation from Contact record

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2753]
Steps to repeat:

1. Contact1 w/Primary Affiliation to organization
2. Contact2 with no Primary Affiliation
3. Contact Merge, selecting the Primary Affiliation value from the non-master record

When the clean up runs to delete the duplicate Affiliation record, the correct Affiliation record checked as Primary remains, the duplicate is deleted, however the Primary Affiliation value is cleared from the Contact record incorrectly.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008FH2HAAW" target="_blank">W-020499</a>

**Comment by judisohn** [comment]
My guess as to what's happening is that by the time the delete of the dupe Affiliation is happening, it's been checked as 'Primary' because of the Primary Affiliation to the same Organization on the Contact. Then it's being deleted and that's firing the code to remove the Primary Affiliation from the Contact, even though there is still another Affiliation record that remains.

**Comment by force2b** [comment]
I wonder if this is a side affect of the static flags work - allowing the trigger to run a second time when it probably shouldn't.

**Comment by judisohn** [comment]
Another [thread](https://powerofus.force.com/0D58000003iOe7Y).

**Comment by coriobriensfdo** [comment]
Another [thread](https://powerofus.force.com/0D51E00004aIxDI). 

In this case there is a Primary Affiliation to the same account on both contacts being merged. Result is that affiliation is removed from master contact once merged. 

During Merge:
<img width="1076" alt="screen shot 2018-11-06 at 8 21 22 am" src="https://user-images.githubusercontent.com/37851761/48078160-b5bd5780-e19d-11e8-8152-ccf23d5ff48c.png">

Master after Merge:
<img width="448" alt="screen shot 2018-11-06 at 8 26 56 am" src="https://user-images.githubusercontent.com/37851761/48078190-c372dd00-e19d-11e8-9b56-02fcc7cf9ffc.png">

**Comment by judisohn** [comment]
Another [thread](https://powerofus.force.com/0D51E00004niO3f).

**Comment by judisohn** [comment]
Another [thread](https://powerofus.force.com/s/question/0D51E00004pv2FfSAI/why-are-affiliations-removed-when-contacts-are-merged).

**Comment by mrbelvedere** [comment]
Included in beta release 3.157 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.157
