### ISSUE TITLE
Add confirmation dialogue box to 'Delete All Data Import Records' button on the DI object

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#2756]
On the Data Import object, there is a button for Delete All Data Import Records. When a user clicks this, it immediately deletes with no confirmation. Users can easily click the button and accidentally delete many records. A confirmation step would prevent accidental deletion.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008LJNIAA4" target="_blank">W-020516</a>

**Comment by davisagli** [comment]
Included in production release 3.146
