### ISSUE TITLE
When Opportunity Amount is updated from null to a value, Payment is not created

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2763]
[Thread.](https://powerofus.force.com/0D58000003f8sTO)

I'm 99% sure this worked correctly previously, so not sure when a regression was introduced. I know we intentionally had the Payment being created to allow for Opportunity Product line items. 

I replicated the issue in a 3.108 managed scratch org with a Closed/Won Opportunity, but it behaves correctly with an Open one (customer reported having issue with Open opportunity, however).

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cUabAAE" target="_blank">W-020653</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.115 (Beta 9)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.115
