### ISSUE TITLE
When Contact Merge tab is selected, the Contact tab is highlighted instead of Contact Merge

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2772]
Resolution is to add a tabStyle="Contact_Merge__tab" tag to apex:page definition

This is only an issue with Classic, the correct tab is highlighted in LEX.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cUX5AAM" target="_blank">W-020652</a>

**Comment by jesslopez-sf** [comment]
This is Classic-only. Closing Issue.
