### ISSUE TITLE
Manage Save Button is not Disabling When Allocating Amount exceeds Parent Amount

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2781]
After the page was updated to the latest version of SLDS the Save button is no longer disabling when the Allocated Amount exceeds the Parent Amount.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003cbiMAAQ" target="_blank">W-020706</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.110 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/3.110
