### ISSUE TITLE
When a default allocation is enabled, deleting all allocations on an Opportunity automatically recreates the default

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2782]
Steps to reproduce:
* Enable a default allocation in NPSP Settings
* Create a new Opportunity. Ensure the default allocation is created.
* Delete the Allocation on the Opportunity
* Refresh the page.
* Expected: There are no Allocations on the Opportunity
* Actual The default allocation is recreated

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ccYbAAI" target="_blank">W-020723</a>

**Comment by njjc** [comment]
Duplicate of #2384
