### ISSUE TITLE
Affiliation Trigger for Person Accounts

### ISSUE THREAD

**Issue by danhowellnz** [SalesforceFoundation/Cumulus#2793]
I know NPSP doesn't officially support person accounts. But, I think one day it might and more and more orgs are using person accounts as they are a simplier structere

Can the trigger detect whether a npsp_primary_contact___c is the PersonContact on the account and if so don't  insert a new affiliation. Just a couple of lines of check to make sure contacts don't affiliate to their own person account
/src/classes/AFFL_Affiliations_TDTM.cls

**Comment by judisohn** [comment]
@danhowellnz We don't officially support Person Accounts as part of NPSP functionality and as far as I know, we have no short term plans to do so. Feel free to submit this [as an Idea in the Hub](https://powerofus.force.com/hub-ideas), and should this be considered in the future, this issue can be reopened at that time. Thanks!
