### ISSUE TITLE
Scheduled Job should use Batch Size as set in NPSP Settings

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2794]
[Thread.](https://powerofus.force.com/0D58000003iOM1U)

Bug?

While it appeared to me that the [code](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RLLP_OppContactRollup_BATCH.cls#L44) [should](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/RLLP_OppRollup_UTIL.cls#L234) be using the same Batch Size as set in NPSP Settings > Donations > Donor Statistics, it appears to be using the default of 200. Running Bulk Data Processes > Rollup Donations Batch uses the correct NPSP Setting value.

Process run manually in test org with a batch size of 5:

![image](https://user-images.githubusercontent.com/4614343/31544628-b2fd9848-afe9-11e7-8be0-b5b94e49992b.png)

Scheduled Job ran automatically a few hours later with no other change to settings:

![image](https://user-images.githubusercontent.com/4614343/31544645-d21020b6-afe9-11e7-9050-4f7df5b96e01.png)

Confirmed that batch size is still set to 5.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001S09JAAS" target="_blank">W-020878</a>

**Comment by mHiscock** [comment]
Hi 
Can anyone provide an update on this accepted bug please.
Can someone indicate if this is on the road-map for inclusion in a forthcoming release. 
Many thanks

**Comment by davidhabib** [comment]
it's currently being worked on and will be included (safeharbor) in our next release, which I believe will be near the end of the month.

**Comment by mrbelvedere** [comment]
Included in beta release 3.112 (Beta 11)

**Comment by cpolcyn** [comment]
Included in production release rel/3.112
