### ISSUE TITLE
BDI: Improve error message and user experience if custom field is misconfigured

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2797]
If the user has created a custom field in the NPSP Data Import object and it's mapped incorrectly to an invalid or read-only field, the error is immediate upon launching Data Import page rather than within the processed records. It's difficult for the end user to determine exactly which field is incorrect on which object. 

![image](https://user-images.githubusercontent.com/4614343/31568666-a80f30c2-b043-11e7-8afb-d11bd04bf09a.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001S19XAAS" target="_blank">W-020881</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.160 (Beta 10)
