### ISSUE TITLE
Investigate resolution to intermittent UNABLE_TO_LOCK_ROW errors in rollups

### ISSUE THREAD

**Issue by danhowellnz** [SalesforceFoundation/Cumulus#2804]
We have find with multiple clients that they receive "UNABLE_TO_LOCK_ROW" errors every now and then from the overnight rollups. 

I am assuming there a process builds in place that interacts between the contacts and accounts. Changing the batch size would help as per another issue. But, not running them at the same time seems to make sense.

The workaround I am doing:
1.Rescheduling the timings of the rollups so the contacts, accounts and households don't all start at the same time. I leave an hour between them. 

The more robust solution that comes to mind:
2. If they hit a roll-up error, store the record id in the logs and then try and reprocess them later. More robust, more work

**Comment by judisohn** [comment]
@danhowellnz We are aware of the issue, but haven't decided on the exact solution yet. I'll add this issue to our backlog as a launching point for further investigation. Will rename to better address the problem. :-)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SDI2AAO" target="_blank">W-020956</a>

**Comment by danhowellnz** [comment]
Can I suggest that a short term fix would be to change the schedule times so not the same hour:
UTIL_MasterSchedulableHelper.cls


A longer term solution I would use is to batch chain the schedules, so on the finish of one batch it starts the next.

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.128

**Comment by danhowellnz** [comment]
Hello. Can you please let me know what solution you decided on so I can understand my work arounds. I can't find it in the release notes

**Comment by judisohn** [comment]
@danhowellnz This is addressed in the new Customized Rollups feature coming in this release. If you enable the new feature (please try it when it hits your sandbox!) you should see this improvement.
