### ISSUE TITLE
Lead Conversion page is defaulting to Default Lead Status instead of Converted

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2805]
[Thread. ](https://powerofus.force.com/0D58000003j20E0)

Replicated in clean scratch org - should be Converted Status, not Default.

![image](https://user-images.githubusercontent.com/4614343/31771830-84461c52-b4ab-11e7-8647-c95d0a8951f3.png)

![image](https://user-images.githubusercontent.com/4614343/31771887-b43f6f6c-b4ab-11e7-82f5-6f7d2fcb0afc.png)

This was either introduced in Winter '18 or in the recent SLDS update, since this page wasn't touched otherwise in a recent release.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SFDDAA4" target="_blank">W-020959</a>

**Comment by mpusto** [comment]
Thanks Judi. Pretty sure it was Winter '18 which has a revised Lead conversion behavior. But yes, we should fix this!

**Comment by judisohn** [comment]
@mpusto I'm sure you're right. Thanks!

**Comment by judisohn** [comment]
Another related thread [here](https://powerofus.force.com/0D58000003OAwbl). It appears that if the organization has lead statuses off the default, it's causing an error.

**Comment by mrbelvedere** [comment]
Included in beta release 3.111 (Beta 3)

**Comment by cpolcyn** [comment]
Included in production release rel/3.111

**Comment by kaddae** [comment]
I'm still encountering this issue leading to an error during lead conversion (error screenshot attached). 
![image](https://user-images.githubusercontent.com/14282990/32909007-5a0d9788-cad3-11e7-9d01-c7f4071900c8.png)

**Comment by judisohn** [comment]
Hi @kaddae - I replied to your post in the Hub. That is the same error, but your screen shot in the Hub shows you are getting the correct default status as this bug fixed. Are you changing it back by any chance?
