### ISSUE TITLE
Split Allocation Issue

### ISSUE THREAD

**Issue by Agroag** [SalesforceFoundation/Cumulus#2810]
One of our gift processors is having an issue and opportunities not holding multiple GAU Allocations.  From her email.  Please let me know if you have any questions regarding the post. 

"A donor has pledged $100 gift for 2 different funds split 50/50 between “General Unrestricted”, and “Program Support”.

The recurring donation is then set as a recurring donation with the “split allocation” checkbox filled, and the GAU overwrite set to “General Unrestricted”. The campaign is not relevant to the problem here – RDs and associated opportunities always share the same campaign regardless of GAU or installment distribution.

Once the opportunity is automatically created, I go in and split the GAU’s – the split allocation box on the opportunity is checked, no errors happen.

I go back and check on the pledged opportunity a while later (on a different day, sometimes in the next week), and the GAU has reset itself to only the “General Unrestricted” fund – the split did not hold, and the opportunity looks like the default opportunity that the RD made when created initially.

The same issue occurs should I change the amounts. Say instead of splitting a pledge by fund, a donor decides that the $100 pledge will be paid by a gift of $25 in September, and $75 which will come in April. The installment number on the RD will be set to 2, as there will be 2 installments. Once opportunities are created, I go in and change one opportunity from $50 to $25 and the other from $50 to $75.

This change also will not hold – after a few days, the 2 opportunities go back to being $50 each. This will happen no matter how many times I do this."

**Comment by judisohn** [comment]
Hi @Agroag - Please post in the Power of Us Hub in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) and someone will be able to assist you. NPSP does not have a 'Split Allocations' checkbox, so it sounds like you are running into challenges with some customizations in your org. The Hub community will be able to walk through that with you and hopefully point you in the right direction. 

We reserve Github issues for items that have been verified as bugs/issue in the code for our developers to address, and not for general troubleshooting. Thanks for understanding and see you in the Hub!
