### ISSUE TITLE
Required fields are not being marked required by default.

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2813]
On pages using the new UTIL_InputField component, the required field is defaulting to false. This is overriding the native apex:inputField required tag being set automatically on Visualforce pages.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SNGjAAO" target="_blank">W-020983</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.112 (Beta 9)

**Comment by cpolcyn** [comment]
Included in production release rel/3.112
