### ISSUE TITLE
Cannot Create New Levels in Classic Interface

### ISSUE THREAD

**Issue by cleverlemming** [SalesforceFoundation/Cumulus#2814]
Unable to create new Levels  from Level edit page in Salesforce Classic because required fields (npsp__Source_Field__c, npsp__Level_Field__c, and npsp__Previous_Level_Field__c) do not populate. 

Steps to recreate (Salesforce Classic interface):

1. From Levels tab, click "New"
2. Choose a Target.

Same sequence of actions in Lightning will populate aforementioned fields.

**Comment by judisohn** [comment]
@cleverlemming This is a known issue. You must start typing the name of the level first, before selecting the Target. Once the Name has value, and the Target selected afterwards, then the remaining fields will work properly.

In the future, feel free to post in the [NPSP Group in the Power of Us Hub](https://powerofus.force.com/0F980000000CjRe). We prefer to Github Issues only be used for items actionable by developers. The best way to ask questions of the entire community and report what you think may or may not be a bug is on the Hub. Thanks for understanding!
