### ISSUE TITLE
Affiliation auto creation is setting Status to Translated Value

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2817]
[Thread.
](https://powerofus.force.com/0D58000003k4u0f)
Steps to replicate:
Set Spanish as User's language
Set Primary Affiliation on a Contact Record
View Status Field on Affiliation Object and note new value added "Actual"

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001ScXyAAK" target="_blank">W-021037</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 53)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
