### ISSUE TITLE
Recurring Donations Batch Job runs after every package update

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2821]
Hub Post: https://powerofus.force.com/0D58000003kLyML

Remove the execution of the RD_InstallScript_BATCH job during a package update

**Comment by force2b** [comment]
** lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008j5QeAAI" target="_blank">W-021078</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.112 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.112
