### ISSUE TITLE
Auto-infer Relationships

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#283]
_Issue by **[kbromer](https://github.com/kbromer)** from Wednesday Dec 12, 2012 at 22:33 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Relationships/issues/1_

---

http://code.google.com/p/npsp/issues/detail?id=310

If I have mother-daughter, and mother-son, the packages should know we have siblings, etc.

**Comment by kbromer** [comment]
https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000007PsqE&tab=sfdc.ProfilePlatformFeed&fId=0D580000027GQvd&fromEmail=1

**Comment by davidhabib** [comment]
**lurch: attach W-007169

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cS2AAI" target="_blank">W-007169</a>

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
