### ISSUE TITLE
When logged in as Partner Community user, Manage Household page does not display correctly

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2836]
[Thread.](https://powerofus.force.com/0D58000003lU1uX)

@jjbennett has determined the fix needed to the VF page.

![image](https://user-images.githubusercontent.com/4614343/32392351-b812ae4a-c0ab-11e7-8605-28efdfe53e40.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008jFaGAAU" target="_blank">W-021122</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.112 (Beta 6)

**Comment by cpolcyn** [comment]
Included in production release rel/3.112
