### ISSUE TITLE
Required Field Error when Payment Method is not the last field in the Payment Wizard Field Set

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2842]
The page is requiring both the date and payment method when the payment method is not the last field in the field set on the Payment Wizard Schedule page.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008n6eEAAQ" target="_blank">W-021153</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.113 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.113
