### ISSUE TITLE
User Defined Rollup error in rollup batch

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2849]
[Post.](https://powerofus.force.com/0D58000003mxV0w)

Replicated in test org. Create custom currency field on Opportunity, custom currency field on Contact. Create SUM UDR. Populate a record. Run batch. Error is:

First error: SObject row was retrieved via SOQL without querying the requested field: Contact.Test_Currency_Rollup__c

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008nN6dAAE" target="_blank">W-021237</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.114 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.114
