### ISSUE TITLE
NPSP Data Import Failure When Updating Existing Account with Address

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#2859]

**Comment by jesslopez-sf** [comment]
If existing Account with an Address is imported via the NPSP Data Import tool, an error is thrown: `SObject row was retrieved via SOQL without querying the requested field: Account.BillingCity`

**Steps to Reproduce:**
1. Turn off organization address management in NPSP Settings
2. Import new Account with Address.
3. Import same Account with Address via NPSP Data Imports tool.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008nUF6AAM" target="_blank">W-021287</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.115 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.115

**Comment by samara990c** [comment]
@jesslopez-sf I'm still hitting this bug in Production when importing new Account records (not update to existing records). Are there any work arounds? I waited several days for fix and need to finish this import for a client. Thx for any help! @mrbelvedere

**Comment by davidhabib** [comment]
The release with this fix is being pushed to production orgs tomorrow evening.  You can get it sooner if you want:

Push Schedule

Sandbox orgs: 2017-11-22
Production orgs: 2017-11-28
Use the Installation URL below to install this release before the scheduled push dates.

Installation URL

https://login.salesforce.com/packaging/installPackage.apexp?p0=04t1Y000001I8xg

**Comment by samara990c** [comment]
Thanks @davidhabib I installed the update and the error is resolved. Many thanks!!
