### ISSUE TITLE
Health Check needs to gracefully handle invalid ID's

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2862]
hub post: https://powerofus.force.com/0D58000003nLqrT

invalid grant id is causing Health Check to throw an exception, rather than detected and reported as a specific Health Check error.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008rBgCAAU" target="_blank">W-021295</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.122 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.122
