### ISSUE TITLE
Auto created Paid Payment when Opp updated from null to value is populating Scheduled Date instead of Payment Date

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2869]
NPSP 3.115

STR: Create Closed/Won opp, leave amount blank. Update Opportunity to a value. Note Payment created is properly checked as 'Paid' however Scheduled Date is populated rather than Payment Date. Scheduled Date should be blank, Payment Date should be Today.

![image](https://user-images.githubusercontent.com/4614343/33143749-d6a0344a-cf88-11e7-9138-f039660faa34.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008rK68AAE" target="_blank">W-021334</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.116 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.117
