### ISSUE TITLE
Non-System Administrators are unable to save/update records

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2875]
System Administrators are able to create and update records normally, however in various situations, other users are unable to save record and get errors such as:

`Apex trigger npsp.TDTM_Opportunity caused an unexpected exception, contact your administrator: npsp.TDTM_Opportunity: execution of AfterInsert caused by: System.TypeException: DML operation INSERT not allowed on npe01__OppPayment__c: (npsp).`

Error/object may vary.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008vHElAAM" target="_blank">W-021404</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.116 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.116
