### ISSUE TITLE
BDI: error when referring to contact fields on existing household contacts

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2880]
when NPSP was querying for additional household contacts from the set of Contacts first matched for C1 and C2, it was not including all referenced Contact fields.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by davidhabib** [comment]
hub post: https://powerofus.force.com/0D58000003pO5YB

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008z0MBAAY" target="_blank">W-021426</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.118 (Beta 2)
