### ISSUE TITLE
NPSP: First Gift Date not auto-populating

### ISSUE THREAD

**Issue by savvyjd** [SalesforceFoundation/Cumulus#2883]
Issue only occurred with NPSP Data Imports from 11/21 and 11/22.

The NPSP giving fields on Account record didn't populate on those dates. I can't figure out how to force the First Gift Date field to populate after they didn't originally do so. The donations are all visible on the Contact and related HH Account records, but that NPSP First Gift Date field is blank. 

Do I need to clone all these and then delete the originals? That seems to work -just wondering if anyone else experienced this -figured I should log it even though it doesn't seem to be persistent after those dates.

![account tracks giving history accurately](https://user-images.githubusercontent.com/31014409/33678123-b98e8d38-da6f-11e7-8f56-744fdc7ca573.png)
![account related donation](https://user-images.githubusercontent.com/31014409/33678124-b9bc2b3a-da6f-11e7-9494-072f6ff746f3.png)
![account no npsp donation fields populated](https://user-images.githubusercontent.com/31014409/33678125-b9dc5158-da6f-11e7-871f-4445bada4022.png)

**Comment by judisohn** [comment]
Hi @savvyjd In the future, please post your question in the [NPSP Group in the Power of Us Hub](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) as we don't provide support in Github. 

In the Hub [we also have this article](https://powerofus.force.com/articles/Resource/NPSP-Troubleshoot-Rollups) that might help you troubleshoot why rollups didn't work for those records.
