### ISSUE TITLE
BDI: Configuration Options, unable to edit Contact and Account Custom Unique IDs

### ISSUE THREAD

**Issue by jeffhonnold** [SalesforceFoundation/Cumulus#2884]
When running Data Import in the NPSP back end, and trying to edit the "Contact Custom Unique ID" and "Account Custom Unique ID" boxes, the boxes don't appear.  I need to go into the Custom Settings and edit there manually.  In screenshot, note absence of a box to enter or select a unique ID.

![image](https://user-images.githubusercontent.com/5323286/33798995-f865bd8c-dcf0-11e7-8799-045652ec70cc.png)

**Comment by davidhabib** [comment]
You need to enable field level security on your profile for all of the fields on the NPSP Data Import Batch object.
