### ISSUE TITLE
In Lightning Experience, standard New button on Opportunity related list produces duplicate Primary Opportunity Contact Role records

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2885]
While our best practice recommendation is to use an Action on Contact to create an Opportunity from a Contact record, Winter '18 introduced a change in behavior that allows a user to create an Opportunity directly from the standard New button on the Opportunity related list on Contact. Previously, this button in Lightning Experience created a new Contact Role record only for an already-existing Opportunity.

With this change to the 'New' button, Salesforce automatically creates an Opportunity Contact Role record in Lightning Experience. NPSP is also creating an OCR so one ends up with 2 records incorrectly:

![image](https://user-images.githubusercontent.com/4614343/33904907-ef48ff46-df4a-11e7-95d8-a840c7f2336b.png)

In Classic, the standard New button does not create a duplicate Contact Role with the exact same fields populated with the same values (Opp Name, Amount, Close Date, Stage):

![image](https://user-images.githubusercontent.com/4614343/33905010-36b50dd4-df4b-11e7-87db-0ad762735f33.png)

As it is likely the creation of the OCR is the desired behavior by Salesforce for general purposes, our code should not create a duplicate and instead correctly populate the role on the OCR if it exists.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000935LrAAI" target="_blank">W-021508</a>

**Comment by mpusto** [comment]
**lurch: detach

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x8000000935LrAAI" target="_blank">W-021508</a>

**Comment by mpusto** [comment]
**lurch: attach W-022087

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009FLHCAA4" target="_blank">W-022087</a>

**Comment by judisohn** [comment]
**lurch: attach W-022952

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009rCxHAAU" target="_blank">W-022952</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.126 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.126

**Comment by coriobriensfdo** [comment]
For those looking for assistance with the creation of duplicate primary contact roles when using the standard New button on the Contact record Opportunity related list, please create a Lightning Action using the instructions in this doc: https://powerofus.force.com/articles/Resource/NPSP-LEX-Known-Issues#!#ariaid-title2

To clean up any existing double OCR's, you can run the batch called "Remove Duplicate Primary OCRs" within the Bulk Data Processes area in NPSP Settings.
