### ISSUE TITLE
In NPSP Settings > Rollup Donations Batch no longer shows batch job name

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2888]
This is a regression of prior behavior. Previously, the name of the batch job appeared in the list when Rollup Donations Batch was clicked in NPSP Settings > Bulk Data Processes. Now the name does not appear, making it more difficult for admins to troubleshoot errors without moving to another screen (Error Log or Setup > Apex Jobs).

![image](https://user-images.githubusercontent.com/4614343/34008449-561b7daa-e0d3-11e7-859b-da1a97b89744.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000093C3vAAE" target="_blank">W-021567</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.125 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.125
