### ISSUE TITLE
Replace Notes and Attachments with Files

### ISSUE THREAD

**Issue by danhowellnz** [SalesforceFoundation/Cumulus#2891]
Update the page layouts to use files instead of "Notes and Attachments" for future support. 

You could also enable enhanced notes and add the notes related list

**Comment by judisohn** [comment]
Hi @danhowellnz Changes to page layouts won't push out to existing orgs, but we'll keep this in mind going forward in the package. Also note that we do keep our page layouts as compatible with Classic as we can until we're sure that all customers have made the switch.
