### ISSUE TITLE
First error: npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by TannerWells-IdealistConsulting** [SalesforceFoundation/Cumulus#2893]
The error is being caused by the batch run of the 'RLLP_OppContactRollup_BATCH' class (see screenshot attached) and also by an iATS Brickwork Batch process (which creates and updates opportunity records). Note that there is similar query error noted for the 'RD_RecurringDonations_BATCH' class as well (noted in screenshot).

I've adjusted the batch size for iATS down to 50 records and also the NPSP Donor Statistics rollup batch size to 50 and the error is still occurring. Please see attached the NPSP error log noting the error list and one of the errors. Please let me know how I can help troubleshoot this further. 

Thanks!
<img width="729" alt="error detail" src="https://user-images.githubusercontent.com/7259094/34309302-e0f97cee-e716-11e7-9ca3-093685de05a5.png">
<img width="642" alt="error list" src="https://user-images.githubusercontent.com/7259094/34309303-e12db554-e716-11e7-9710-6799a29cd6fe.png">
<img width="1183" alt="npsp error" src="https://user-images.githubusercontent.com/7259094/34309305-e159f542-e716-11e7-841e-39db0d261d73.png">

**Comment by judisohn** [comment]
@TannerWells-IdealistConsulting We don't provide troubleshooting and support here in Github. Please post in the Power of Us Hub and feel free to tag the IATS folks as well. Thanks for understanding.
