### ISSUE TITLE
Changing Membership record type label or name breaks rollup to Membership Level and Origin on Account and Contact

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#2896]
Using fresh NPSP 3.117:

1. Create a new Opportunity for a Contact by pressing the New Contact Donation button.  Choose Record Type "Membership", Member Level "Gold", Membership Origin "New".  Save, then verify that the associated Account shows Last Membership Level "Gold" and Last Membership Origin "New".
2. In Settings, change the label of the existing Opportunity record type "Membership" to "Received Membership" (don't create a new record type - update the existing one).
3. Visit NPSP Settings to verify that the Membership record type name now shows "Received Membership" (do not change this setting, just leave it at its default).
3. Create another new Opportunity for a Contact by pressing the New Contact Donation button.  Choose Record Type "Received Membership", Member Level "Silver", Membership Origin "Renewal".  Save the Opp.

Issue: On the associated Account and Contact records, Last Membership Level still shows "Gold" and Last Membership Origin still shows "New" - the rollup of the most recent Opportunity failed.

Related Info: Changing the existing Opportunity record type *name* from "Membership" to another name also causes this failure - and then changing both label and name back to "Membership" does *not* repair the rollup failure.  Changing the NPSP Setting for membership rollup to another, newly created, Opportunity record type does repair the failure, and then changing this setting back to the original default Membership record type also does repair the failure.  I tested these related scenarios pretty well but didn't completely sort out the precise sequences that cause failures and those that repair the failure.

**Comment by johnfine** [comment]
Did some more testing, can no longer dup this issues, I am closing it.

**Comment by davidhabib** [comment]
thanks for following up @johnfine
