### ISSUE TITLE
Lead Conversion Style Missing when used in the Sales Console

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#2898]
Issue reported in the Power of Us Hub - https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006kYB4&tab=sfdc.ProfilePlatformFeed&fId=0D58000003tmVhV
![screen shot 2018-01-02 at 11 50 08 am](https://user-images.githubusercontent.com/450473/34526657-c364e79e-f068-11e7-94a4-efafaade7dfe.png)

This looks very similar to the issue resolved for the Manage Household Page in the Partner Community #2837. The fix there was to change the outer div from slds to slds-scope.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009BEfYAAW" target="_blank">W-021812</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.120 (Beta 6)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
