### ISSUE TITLE
Nightly Membership Rollups were causing all Accounts and Contacts to be updated when a blank LastMembershipLevel value did not match the null value in the record.

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2909]
If nightly rollup settings included a specific record type for Memberships and that caused the LastMembershipLevel or LastMembershipOrigin rollups to result in a blank ("") value, comparing that "" value to the value in the record (null) did not match; causing all of those records to be updated. At a database level, Field History did not capture the change because the blank ("") value was effectively equivalent to null - keeping this from showing up in the Field History lists.

The fix is to convert "" to null for the LastMembershipLevel or LastMembershipOrigin calculated rollup values before comparing to the existing values in the record.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009FAnQAAW" target="_blank">W-021948</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.119 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.119
