### ISSUE TITLE
Unable to insert new donations Via Apex after update on January 5

### ISSUE THREAD

**Issue by ppostma1** [SalesforceFoundation/Cumulus#2914]
We have no custom validation rules, no changes to code or required fields, and after the update, all calls to `insert donations;` in all unit tests results in: 
```
System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Opportunity: execution of AfterInsert

caused by: System.DmlException: Insert failed. First exception on row 0; first error: UNKNOWN_EXCEPTION, invalid parameter value: []

(npsp)



: []
```

There has been no change in the behavior using the salesforce interface

**Comment by judisohn** [comment]
Hi @ppostma1 - we don't provide direct support of individual issues here in Github. Please post to the [Nonprofit Salesforce Developers group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjxL) in the Hub and be sure to include as much detail about your code as you can, and someone can help you there. Thanks!
