### ISSUE TITLE
Broken css styling in lightning experience

### ISSUE THREAD

**Issue by danhowellnz** [SalesforceFoundation/Cumulus#2917]
We haven't touched anything in static resources and yet with this client the visualforce pages are not displaying correctly. 

An example page:
npsp__OPP_SendAcknowledgmentBTN
It states:  Last Modified By 10/01/2018 10:05 PM (so looks up to date)

![capture](https://user-images.githubusercontent.com/21028276/34921581-63e328dc-f9e9-11e7-9b59-1cdd880f3fc1.PNG)
![capture2](https://user-images.githubusercontent.com/21028276/34921582-640c56ee-f9e9-11e7-9c3f-4b797671b9a5.PNG)

I granted login access for salesforce.org support

**Comment by judisohn** [comment]
HI @danhowellnz - Please post this in the NPSP Group in the Power of Us Hub or [open a support ticket](https://powerofus.force.com/articles/Customer_Service/How-to-Create-a-Technical-Support-Case-with-Salesforce-Support). We don't directly support issues here in Github. Thanks for understanding!
