### ISSUE TITLE
Excluding Usernames for TDTM Triggers does not work if the Usernames case does not exactly match

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#2918]
The issue is that Set.contains() is case-sensitive. Can be fixed easily by forcing everything to upper or lower case before using contains().
https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/TDTM_ObjectDataGateway.cls#L74

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KBq2AAG" target="_blank">W-022118</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.161 (Beta 1)
