### ISSUE TITLE
Percentage-based Opportunity GAU Allocations can't be updated to Amount-based

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2921]
[Thread.](https://powerofus.force.com/0D58000003vfSSf)

Confirmed in scratch org.

1. Create 2 GAU records
2. Create Campaign and split 50% between each GAU
3. Create Opportunity (closed/won, but stage shouldn't matter) for Amount = $100, Primary Campaign source set to above
4. 'Manage Allocation' and delete % and change first to 90, second to 10. Save.

![image](https://user-images.githubusercontent.com/4614343/35009064-8ffab9e2-facc-11e7-89e8-5a4f0effd753.png)

5. Note that the GAU Allocation related list retains the original 50% split

![image](https://user-images.githubusercontent.com/4614343/35009160-b45487aa-facc-11e7-83db-47f8e69e80fb.png)

If the percentage is changed (for example 80/20) then the change is saved.

**Comment by njjc** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KFz2AAG" target="_blank">W-022179</a>

**Comment by judisohn** [comment]
When investigating this issue, please also review case 18194113.

**Comment by mrbelvedere** [comment]
Included in beta release 3.123 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.123
