### ISSUE TITLE
Removal of Recurring Donation metadata blocking upgrades from NPSP 2

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2922]
[Thread.](https://powerofus.force.com/0D58000003vDCYz)

Since we removed Recurring Donation metadata in NPSP 3.118 release, users are unable to upgrade from NPSP 2. They are getting this error message:

`This app can't be upgraded., Details: Salesforce has blocked this package upgrade because the new package version removes some Apex code that one or more Visualforce pages or global Visualforce components need in order to function. Please contact your partner with this error information. Provide these component names to your partner. Visualforce Pages: RecurringDonationsSettings, RecurringDonations_AddDonationsBTN.`

The workaround is to manually install Recurring Donation 3.10 from [this](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t80000000tpCB) link, then they can continue with the NPSP 3+ upgrade as usual.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KFzyAAG" target="_blank">W-022185</a>

**Comment by judisohn** [comment]
We are working in instructions for the workaround in to the installer. As there is nothing more code-wise that can be done, this issue is closed.
