### ISSUE TITLE
Contact updates made in Managed HH do not populate Account Related List without refresh

### ISSUE THREAD

**Issue by jessingrass** [SalesforceFoundation/Cumulus#2930]
Login to a lightning org

1. create a household account
2. go to manage HH
3. add a contact from the manage HH page
4. save
5. notice that the related list for the household does not update 
6. refresh the page
7. then the related list updates

expected behavior is to see the related list update at step 5, with no need for refresh

**Comment by jessingrass** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UaRwAAK" target="_blank">W-022485</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.120 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
