### ISSUE TITLE
Expand support of currency symbols in Opportunity Naming

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#2931]
[Thread.](https://powerofus.force.com/0D58000003xKB5n)

Our code currently only supports a narrow set of currency symbols in Opportunity Naming. We should allow for customization to expand the supported symbols for organizations that need it.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UcIgAAK" target="_blank">W-022486</a>

**Comment by coriobriensfdo** [comment]
[Another Thread](https://powerofus.force.com/s/question/0D51E00004yQLiMSAW/opportunity-naming-with-multiple-currencies)
