### ISSUE TITLE
Unable to Save Contact after running the NPSP installer (NPSP 3.0 Upgrade)

### ISSUE THREAD

**Issue by nashlash17** [SalesforceFoundation/Cumulus#2934]
I see the following error when I try to update a contact after upgrading to NPSP3.0:

Error: Invalid Data. 
Review all error messages below to correct your data.
Apex trigger npsp.TDTM_Contact caused an unexpected exception, contact your administrator: npsp.TDTM_Contact: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 003A000001xDynAIAS; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Contact: execution of AfterUpdate caused by: System.StringException: Invalid id: In-Kind (npsp) : []: (npsp)

![downloadnpsp](https://user-images.githubusercontent.com/35969268/35580535-9a3c6e64-05e9-11e8-937f-3af35316b36c.png)

**Comment by judisohn** [comment]
Hi @nashlash17 - in the future, you can get a faster response if you post directly in the NPSP Group in the Power of Us Hub. We don't handle support issues here in Github. 

In this case, it's a known issue in upgrades where RecordType Names in Settings are not being properly translated to IDs. 

That issue #2890 (<- click the number) has the resolution -you need to make some edits in Custom Settings, but where it says 'Membership' replace by looking for 'In-Kind'
