### ISSUE TITLE
BDI: new Open Opps should not have Payment Date set on unpaid payments

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2938]
If you specify a new Donation in BDI, and its stage is an open stage (not closed won), the payment under the Opp is correctly marked unpaid, but both Scheduled Date and Payment Date are set to the Donation Date.  Payment Date should remain empty for unpaid Payments BDI creates.

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UkjsAAC" target="_blank">W-022581</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.120 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
