### ISSUE TITLE
BDI: matched Payments should get marked Paid regardless of other field updates

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2939]
Due to bug #2938, an imported Donation that matched an existing unpaid Payment would NOT get updated with Paid, if no other BDI payment fields were specified.  BDI must ensure that it updates Paid, regardless of other fields being updated or not

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UkkRAAS" target="_blank">W-022582</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.120 (Beta 5)

**Comment by cpolcyn** [comment]
Included in production release rel/3.120
