### ISSUE TITLE
Recurring Donation fields not updated when Opps deleted

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/Cumulus#2944]
- create a fixed length recurring donation
- update several of the Opps to a closed won stage
- note how Paid Amount and Total Paid Installments are updated correctly.
- now delete one of the paid Opps
- note how Paid Amount and Total Paid Installments have not been updated
- empty the Recycle Bin (in case you thought that was why!)
- Paid Amount and Total Paid Installments still have not been updated

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009a4hgAAA" target="_blank">W-022677</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.124 (Beta 1)
