### ISSUE TITLE
First error: npsp:Too many query rows: 50001

### ISSUE THREAD

**Issue by JesusIglesias-S4G** [SalesforceFoundation/Cumulus#2962]
We're receiving this error for batches npsp__RLLP_OppAccRollup_BATCH and npsp__RLLP_OppContactRollup_BATCH. It's blocking the generation of new recurrent donations

The org works with this volume of data:

Contacts: 260.000 aprox
Accounts: 262.000 aprox
Opportunities: 1.070.000 aprox

The log doesn't specify much more but I'm assuming this is related to the opportunities. Here's the screenshot of the NPSP error log. Is there any way we can change the batch size at least as a quick fix?

![image](https://user-images.githubusercontent.com/36759393/36586340-b038a250-1881-11e8-8704-2f1f262b89be.png)

**Comment by judisohn** [comment]
Hi @JesusIglesias-S4G - In the future, it's best to post in the [NPSP Group](url) in the Power of Us Hub as that's where we troubleshoot and support issues. 

Yes, you can lower the batch size in NPSP Settings > Donations > Donor Statistics. That should help with the error you reported. However, we are currently investigating a completely unrelated issue with the Recurring Donation job which is what creates the recurring donation opportunities. It wouldn't be related to this error. We should have an update on that posted as an issue soon. In the meantime. if you have follow up to this please post in the Hub, not here, for best attention. Thanks!

**Comment by judisohn** [comment]
@JesusIglesias-S4G for the issue where you said the recurring donation job didn't run, #2963 may help.
