### ISSUE TITLE
Previously Scheduled Recurring Donation Job Not Using Batch Size

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#2963]
Latest NPSP release (3.120) uses a custom setting to control batch size for the Recurring Donation scheduled job. If the custom setting field is not set, the class defaults the batch size to 50. Previously scheduled jobs  are not re-instantiating the class to get the new batch size value and are therefore defaulting it to null. An error is captured on the originally scheduled Apex job for the RD_RecurringDonations_BATCH (i.e. when NPSP initially scheduled the job, so it could be from a long time ago and is not clear when looking at recent Apex jobs). The Status is Failed and the Status Detail will say something like this: "Scheduler: failed to execute scheduled job: jobId: 707f4000000rpWY, class: common.apex.async.AsyncApexJobObject, reason: batchSize must not be null".

Subsequent runs of the RD_RecurringDonations_BATCH job do not actually execute.  We have reproduced this in several orgs. (FYI -- I have 2 and @judisohn  has 1 that we can use to test).

There are 2 workarounds until we get a fix in place:
1. Delete the RD_RecurringDonations_BATCH job in Scheduled Jobs and go to NPSP Settings to reschedule jobs. Or
2. Run the Recurring Donation Batch job manually in NPSP Settings -->Bulk Data Processes --> Recurring Donations Batch

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009lvqVAAQ" target="_blank">W-022927</a>

**Comment by jesslopez-sf** [comment]
Original hub post: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Gz2z&fId=0D580000040hWzN

**Comment by mrbelvedere** [comment]
Included in beta release 3.121 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.121
