### ISSUE TITLE
Clearing Account Name from an Organizational Contact creating Anonymous Household

### ISSUE THREAD

**Issue by mhiman** [SalesforceFoundation/Cumulus#2976]
This client is using a mixed Contact model (some Contacts with Household Accounts, some Contacts directly associated to their Organizational Account - they are a Foundation with Organizational Members).

At the end of January, contacts that previously would get a Household created would now get the Anonymous Household created when clearing the Account Name from the Contact page.

This is happening inconsistently, and was difficult to duplicate. It appears to happen when the Contact is question already has multiple Affiliations. If the Contact only has one Affiliation at the time of clearing the Account name, it does not happen.
![screen shot 2018-02-27 at 3 23 10 pm](https://user-images.githubusercontent.com/16232565/36763254-06710722-1bdc-11e8-94f2-ad10d556433f.png)

**Comment by judisohn** [comment]
@mhiman Please post in the Partner and/or NPSP group in the Hub for further troubleshooting. If a bug is isolated, we can reopen this issue with steps to repeat and action for developers to take. Thanks!
