### ISSUE TITLE
Implemented internal TDTM enhancements of NPSP to support future development

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/Cumulus#2995]
This issue is created to enhance NPSP support for TDTM.

**Comment by weizsforg** [comment]
**lurch: attach W-021135

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008mwimAAA" target="_blank">W-021135</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.126 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/3.126
