### ISSUE TITLE
Corrected Dutch translations were not updated in NPSP 3.120

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3000]
[NPSP 3.120](https://github.com/SalesforceFoundation/Cumulus/releases/tag/rel%2F3.120) contained a refresh of corrected Dutch translations, however it appears that prior incorrect values were not replaced as expected.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000A8EjyAAF" target="_blank">W-023394</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.134 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.134
