### ISSUE TITLE
Merge Failed for HH accounts 

### ISSUE THREAD

**Issue by ShathaJ** [SalesforceFoundation/Cumulus#3016]
I use an app called duplicate check for Salesforce when I try to merge the HH accounts, an Error message appears.

Error Message: Merge Failed: Merge failed. First exception on row 0 with id -Acc ID - ;
first error: DELETE_FAILED, npsp.TDTM_Account: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id -Acc ID -;
first error: SELF_REFERENCE_FROM_TRIGGER, Object -Acc ID - is currently in a merge operation, therefore a trigger can not update it.: [] (npsp) : []

I use NPSP Version 3.124

**Comment by judisohn** [comment]
Hi @ShathaJ We don't provide support or issue troubleshooting here in Github. Please post in the [NPSP Group in the Hub](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) or more likely, [open a support ticket with Salesforce](https://powerofus.force.com/articles/Customer_Service/How-to-Create-a-Technical-Support-Case-with-Salesforce-Support) as it appears you have other custom code or customization which is causing this issue. Thanks!
