### ISSUE TITLE
Validation of GAU record needed in NPSP Settings

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3020]
This has come up on the Hub a few times and in cases. If for whatever reason a GAU record that is referenced as the Default Allocation is deleted or changed, users are unable to create an Opportunity due to this error:

`Unable to create new Opportunities. npsp.TDTM_Opportunity: execution of AfterInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: a0....: [] (npsp)`

Where the reference ID refers to a GAU record.

This happens most frequently in new sandboxes.

Suggest that NPSP Settings check for record with ID referenced, and if it does not exist 'Default Allocation' is unchecked and value removed.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJfaeAAD" target="_blank">W-023674</a>
