### ISSUE TITLE
Consider use cases for difference accounting methods in NPSP

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#304]
_Issue by **[greenstork](https://github.com/greenstork)** from Monday Nov 12, 2012 at 17:49 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Recurring_Donations/issues/22_

---

Behavior should vary based on whether or not the organization is using Cash basis vs. Accrual basis accounting.  This would be a handy setting to allow our code (e.g. for creating recurring donations) to behave according to the best practices of the accounting method being used.

**Comment by njjc** [comment]
Payment based rollups for cash based accounting. Good candidate for an external add-on package, which would be preferable to replacing existing rollup functionality.

**Comment by kbromer** [comment]
**lurch: attach W-007266

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYCAAY" target="_blank">W-007266</a>

**Comment by cpolcyn** [comment]
Included in beta release 3.128 (Beta 7)
