### ISSUE TITLE
NPSP Settings should be updated to latest version of SLDS

### ISSUE THREAD

**Issue by Czimmerman-KELL** [SalesforceFoundation/Cumulus#3053]
I've noticed in a few orgs, when running the rollup donation batch processing within classic, the styling returns an odd result for default SFDC links. This seems to only happen when you click 'run batch'. Screenshot below/attached. 
![chrome_2018-04-20_14-27-39](https://user-images.githubusercontent.com/37848708/39067537-ff2af89e-44a6-11e8-9764-bce3b668420c.png)

**Comment by judisohn** [comment]
We did have an open issue in our backlog that would have addressed this, so I'll reopen and attach.

**Comment by judisohn** [comment]
**lurch: attach W-017879

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005FM7PAAW" target="_blank">W-017879</a>

**Comment by davisagli** [comment]
A fix for this was included in NPSP 3.142
