### ISSUE TITLE
Add recurring rollup fields to contact for reporting ease

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#306]
_Issue by **[greenstork](https://github.com/greenstork)** from Monday Nov 12, 2012 at 18:12 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Recurring_Donations/issues/24_

----

Right now, it's very hard to filter recurring donors in and out of reports because there is no information on a contact's record as to whether or not he/she is a recurring donor.  These fields can be rolled up and it would be a good idea to port these new rollups over from the Groundwire code.

https://github.com/greenstork/GWBase/blob/master/src/classes/GW_BATCH_OppRollup.cls
https://github.com/greenstork/GWBase/blob/master/src/classes/GW_OppRollups.cls

**Comment by njjc** [comment]
This should be resolved with cross filters or custom rollups. We don't plan on including separate rollups for recurring donations.
