### ISSUE TITLE
HH_ManageHHAccount page does not pass url params to standard account page

### ISSUE THREAD

**Issue by ckoppelman** [SalesforceFoundation/Cumulus#3061]
### Use Case

I am sending my user to edit a non-Household account and passing some extra URL parameters. (I am sending `saveURL`, specifically, but I can imagine sending any number of URL params.)

I would like NPSP to get out of my way since this has nothing to do with NPSP.  However, the account edit override (`HH_ManageHHAccount.page`) only passes `retURL` and `RecordType` to the nooverride edit page.

Instead, `HH_ManageHHAccount.page` should blindly pass all URL parameters sent by the user.

### Steps to reproduce

1. Run the below Apex from a VF page (see below) or simply go to a URL like `/001xxxxxxxxxxxx/e?retURL=%2F500xxxxxxxxxxxx&saveURL=%2F300xxxxxxxxxxxx%2Fe`
2. On the first edit page press Save

#### Expected behavior
You are redirected to the saveURL (`/300xxxxxxxxxxxx/e`)

#### Actual behavior
Since `saveURL` is not passed to the "nooverride" account edit page, you are redirected to the `retURL` (`/500xxxxxxxxxxxx`).

Example Apex controller (not tested):
```java
public class TestController {
  public TestController(ApexPages.StandardController stdController) {}

  public PageReference goToAccount() {
    Account acct = [SELECT Id FROM Account WHERE npe01__SYSTEM_AccountType__c != 'Household Account' LIMIT 1];
    Contact cnt = [SELECT Id FROM Contact LIMIT 1];
    String editUrl = new ApexPages.StandardController(acct).edit().getUrl();
    String saveUrl = new ApexPages.StandardController(cnt).edit().getUrl();
    String combined = editUrl + '?saveURL=' + EncodingUtil.urlEncode(saveUrl, 'UTF-8');
    return new PageReference(combined);
}
```

Example VF page (not tested):
```html
<apex:page standardController="Case" extensions="TestController">
  <apex:outputLink value="{!goToAccount}">Go</apex:outputLink>
</apex:page>
```

**Comment by judisohn** [comment]
Hi @ckoppelman - the Account Edit override you're talking about was long changed a separate 'Manage Household' button and we no longer recommend using any Account override. As such, I'll close this issue but of course, you are welcome to implement your own solution to meet your needs and use that instead of the code that is still provided for backwards compatibility.

**Comment by ckoppelman** [comment]
oh wow!  that's good news.  thank you!  Can you send me to the documentation on how to make the upgrade?
