### ISSUE TITLE
Data Inconsistencies With Translated Custom Labels for Recurring Donation Opportunities

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3062]
The package includes language translations for two Custom Labels that are used by the Recurring Donation code to either create Pledged Opportunities or set them to Closed Lost. 

1. RecurringDonationStageName: (Pledged)
2. RecurringDonationClosedLostOpportunityStage: (Closed Lost)

This results in inconsistent data. For example, if my org language is English and my user language is Dutch and I create an Opportunity, my Stage picklist values are in English. However, if I create a Recurring Donation, NPSP code creates Opportunities with a translated Stage of "Toegezegd". If I close a Recurring Donation, the Stage changes to "Gesloten Verloren".

If I run a report and group by Stage, the English and Dutch Stages will be treated as separate Stages. Also, because these translated Stage values don't exist in the Opportunity Stage picklist values (except as Inactive), integrations won't know about them. 

**Workaround:**
Override these two Custom Labels with English values.

**Steps to Repeat:**
1. Set User language to Nederlands in Settings --> Language & Time Zone.
2. Create an Opportunity and note that Stage picklist values are in English. Choose Pledged.
3. Create a Recurring Donation (Open Ended Status = Open, Bedrag = $1, Termijn Periode = Monthly).
4. Open one of the newly created Opportunities. The Stage Name is not Pledged. It's "Toegezegd".

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AVvCzAAL" target="_blank">W-024264</a>

**Comment by jjbennett** [comment]
Included in production release 3.136
