### ISSUE TITLE
Remove Duplicate Primary OCR bulk job: If two Primary OCRs have Roles that do not match default in NPSP Setting, one is removed when it should log as an error

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3063]
NPSP 3.126

STR:

1. Use LEX standard New button on related list to create Opportunity from Contact. 
2. Manually edit the duplicate OCR roles to select different roles (such as 'Decision Maker' and 'Influencer)
3. Run the new Bulk Process batch to resolve duplicates

Should report an error since it can't resolve which OCR is the correct one to retain. Instead, one OCR is deleted and unrecoverable.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AVy0ZAAT" target="_blank">W-024280</a>

**Comment by mrbelvedere** [comment]
Included in production release rel/3.127
