### ISSUE TITLE
Cannot update percent based GAU Allocations

### ISSUE THREAD

**Issue by pcave** [SalesforceFoundation/Cumulus#3088]
When I try to update an existing allocation I get an error message stating percent-based allocations cannot exceed 100%. However, if I manually sum the total of all allocations associated with an opportunity the result is 99.999999% so I'm not sure why it's throwing that error. Does anyone have any ideas?

**Comment by judisohn** [comment]
Hi @pcave - Could you do me a favor and post this in the [NPSP Group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) in the Power of Us Hub? That's where we can provide you with some community support and troubleshooting. Be sure to include as much detail as you can about exactly what values you entered so we can replicate the issue, and if it is indeed a bug then we can come back and log it here. Thanks!
