### ISSUE TITLE
Recurring Donations can Trigger Oppty Rollups Async Error

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#312]
_Issue by **[kbromer](https://github.com/kbromer)** from Tuesday Sep 24, 2013 at 04:39 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Recurring_Donations/issues/30_

---

https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000000t7FYo&OpenCommentForEdit=1&fromEmail=1

"Errors were encountered when trying to insert new Opportunities for your open-ended Recurring Donations. This can adversely affect your forecasting and functionality of your Salesforce.com instance. Addressing these errors as soon as possible can prevent bad data from entering your system. The Recurring Donation and associated Opportunity insert error are listed below, and can be found in the Recurring Donations Settings tab under 'Batch Settings'.

Errors:
https://na14.salesforce.com/a08d000000XOHQmAAP Error Message: npo02.OpportunityRollup: execution of AfterInsert caused by: System.AsyncException: Future method cannot be called from a future or batch method: npo02.OpportunityRollups.rollupContactsandHouseholdsForTrigger(SET<Id>) (npo02)" #NPSP
Topics:   NPSP

**Comment by cdcarter** [comment]
Hey Guys,

I have a client on NPSP2 who is running into this issue right now. Is there a resolution for v2 users who aren't ready to upgrade to Cumulus?

**Comment by davidhabib** [comment]
we aren't updating 2.0 packages.  the only solution is to upgrade.  note that they should be able to upgrade painlessly and stay with their current account model.
