### ISSUE TITLE
FY Bug with HH Rollups

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#316]
_Issue by **[drewpiston](https://github.com/drewpiston)** from Friday Oct 26, 2012 at 18:22 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Households/issues/14_

----

Rollups are calculating for the wrong year when:
1. the fiscal year was set to start in January
2. the "year" for that fiscal year was set to be determined by the end month, like this: http://screencast.com/t/nYs11CIM99C
3. FY Rollups are enabled

When the fiscal year starts in January it seems like it shouldn't matter whether the end month or start month sets the year, as both Jan and Dec will be in the same year, but changing this setting still affected which donations were showing up in "this" year or "last" year.

If those three things are true, though, a Contact with a donation with a close date of 10/1/2012 will have that donation show up in the wrong year for her HH Rollups.

Happy to provide more info if needed.

Cheers,
 Drew

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fl2AAA" target="_blank">W-008233</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.55 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.55
