### ISSUE TITLE
Household Mailing List ID set to invalid report

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#318]
_Issue by **[tet3](https://github.com/tet3)** from Wednesday Jan 23, 2013 at 16:19 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Households/issues/23_

----

This is noted in the v2.4 Release Notes as being fixed, with a link to [Issue 328]{http://code.google.com/p/npsp/issues/detail?id=328) on the GCode repository. But it is still happening (or happening again?) with v2.4.4 

What does "TT change" mean in the comment on that issue mean?

**Comment by davidhabib** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fl7AAA" target="_blank">W-008234</a>

**Comment by kbromer** [comment]
@davidhabib this was reopened by mrbelvedere at some point, is there a reason we didn't just reclose it again? I don't think this is an issue any more

**Comment by kbromer** [comment]
closing this as fixed
