### ISSUE TITLE
Customizable Rollups UI breadcrumb for Back to NPSP Settings doesn't work

### ISSUE THREAD

**Issue by bethbrains** [SalesforceFoundation/Cumulus#3195]
In an org with Customizable Rollups enabled, click on the breadcrumb link to go back to NPSP Settings, and get the following error: 
![image](https://user-images.githubusercontent.com/12188165/40453358-cf466f20-5e99-11e8-92eb-ee5b860db07b.png)

**Comment by judisohn** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXPSmAAP" target="_blank">W-024988</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.130 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.130
