### ISSUE TITLE
Customizable Rollups incorrectly converts MIN/MAX Date UDRs to Smallest/Largest Operation

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3198]
User Defined Rollups for Date fields using MIN or MAX operations are converting to Smallest/Largest instead of First/Last in new rollups engine.

**Steps to Repeat:**
1. Create custom Date field on Contact (UDR Min Close Date).
2. Create User Defined Rollup for MIN Close Date and target the new UDR Min Close Date field.
3. Create an Opportunity on a Contact with 5/1/18 Close Date and $1000 as Amount. Create another Opportunity on the same Contact with 5/20/18 as Close Date and $10 as Amount.
4. Run Rollups Donation job in Bulk Data Processes. The UDR Min Close Date will show 5/1/18.
5. Turn on customizable rollups.
6. Run the Rollups Donation job again and the UDR Min Close Date will show 5/20/18.

![con history](https://user-images.githubusercontent.com/29731456/40492160-e11b3e66-5f3d-11e8-96da-2295c954a6b2.jpg)

![udr min close date](https://user-images.githubusercontent.com/29731456/40491891-405dfb80-5f3d-11e8-813e-68199d618cb7.jpg)

**Comment by jesslopez-sf** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXRqZAAX" target="_blank">W-025004</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.130 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.130
