### ISSUE TITLE
Customizable Rollups should give User Defined Rollups Unique Names When Converted

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3199]
UDRs that use the same Opportunity field cause an error on enablement. Screenshot:
![metadata deploy error](https://user-images.githubusercontent.com/29731456/40496725-7608fee6-5f48-11e8-8650-bf693eb8e28c.jpg)

This is the list of User Defined Rollups:
![scratch org udrs](https://user-images.githubusercontent.com/29731456/40496751-808a3538-5f48-11e8-8250-8d399da7be1a.jpg)

**Comment by jesslopez-sf** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXSBQAA5" target="_blank">W-025012</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.130 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.130
