### ISSUE TITLE
Household Mailing Street Line Breaks

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#320]
_Issue by **[kbromer](https://github.com/kbromer)** from Friday Apr 26, 2013 at 13:22 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Households/issues/29_

----

The Household mailing street field does not support line breaks and multiple line addresses. Likely need to convert the Mailing Street field from straight Text to a TextArea

**Comment by davidhabib** [comment]
@kbromer @jlantz any idea why this was reopened and the wontfix label removed by mrbelevedere?  did we do this, or some automation accidentally do this.  I'd think we'd close this since I don't believe we will fix it in the old address object.
