### ISSUE TITLE
Rollups: Account Hard Credit batch job fails when "Total Number of Memberships" rollup is disabled

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#3217]
Error Message:
`SObject row was retrieved via SOQL without querying the requested field: Account.npo02__NumberOfMembershipOpps__c`.

Only occurs if there was no Membership record type defined in NPSP Settings prior to enabling Customizable Rollups.

**Comment by force2b** [comment]
** lurch:add

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
