### ISSUE TITLE
Household Contact Roles not Working with non 1X1 accounts

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#322]
_Issue by **[pvanriper](https://github.com/pvanriper)** from Monday Jun 24, 2013 at 19:40 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Households/issues/35_

----

In the 1X1 model, f you create an individual opportunity for a contact in a household whose account is a non 1X1 account, it will not pull in any household members and give them the household member contact role.  It only adds the contact role for the initial contact.  I tested this in a couple of different orgs, both of which had no exclusions in place for record types, etc.

**Comment by davidhabib** [comment]
@kbromer @jlantz another closed/wontfix that mrbelvedere undid!  on purpose?  I'm guessing there may be others, but I won't comment on them anymore!

**Comment by kbromer** [comment]
Take that @mrbelvedere
