### ISSUE TITLE
Bulk Data Processes > Batch Process Settings : Ensure GAU Batch Size Persists

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/Cumulus#3225]
When I go to Bulk Data Processes > Batch Process Settings and click "Edit," the number in the "GAU Batch Size" disappears in the UI. This should persist, like the other numbers do.

STEPS:
1. NPSP Settings > Bulk Data Processes > Batch Process Settings
2. Note that the GAU Batch Size has '1000' in it
3. Click "Edit"

- Expected Result : GAU Batch Size remains 1000
- Actual Result : GAU Batch Size is blank.

See screencast : https://drive.google.com/open?id=1Wn9f6UIW4A7YEz36pDcSPQ2NOhCYd0tA

**Comment by dgamboni** [comment]
**lurch:add

**Comment by dgamboni** [comment]
**lurch: add

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXokkAAD" target="_blank">W-025174</a>

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXoxGAAT" target="_blank">W-025176</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
