### ISSUE TITLE
Customizable Rollups: Using a Sum and Count Operator with the same Filter Group causes Sum calculation issue

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3242]
See Hub Post: https://powerofus.force.com/0D58000004GE4od

When a Filter Group is created for Opportunity, then used to first create a Sum rollup using a custom currency field, adding a Count rollup causes the Sum rollup to recalculate based on the standard Amount field rather than the specified currency field. Deactivating the Count rollup fixes the issue.

**Steps to reproduce:**

1. Create a custom filter group on Opty with filters, such as:
- Opty Record Type equals In Kind
- Won equals True

2. Create a custom currency field on Contact for Total Amount In kind Donations
3. Create a custom number field on Contact for Total Number In Kind Donations
4. Create a new In Kind donation related to a Contact. Enter $100 as the standard Amount value, and enter $150 as the Fair Market Value.
5. Create a custom roll up to Sum the NPSP opty "Fair Market Value" with the following parameters:
 - Operation: Sum
- Time Frame: All Time
- Rollup Type: Opportunity -> Contact (Hard Credit)
- Filter Group (the one you had created)
- Amount Field: Opportunity: Fair Market Value

6. Navigate to the Contact page and refresh/recalculate rollups to see the value of $150 appear in the new rollup field as expected. 
7. Create a custom roll up to Count the number of related In Kind donations with the following parameters:
 - Operation: Count
- Time Frame: All Time
- Rollup Type: Opportunity -> Contact (Hard Credit)
- Filter Group (the one you had created)

8. Navigate back to the Contact page and refresh/recalculate rollups to see the number of related in kind donations appear (say 1). Notice the amount sum rollup has now changed from $150 to $100. 
9. Deactivate the Count number rollup, and notice the amount sum rollup has changed back to $150. 

This issue has been tested/verified in separate orgs with same results.

**Comment by coriobriensfdo** [comment]
**Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AXs6sAAD" target="_blank">W-025191</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
