### ISSUE TITLE
Customizable Rollups: Persistent Java Script error on various pages

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3244]
An error message is appearing at the bottom of a variety of pages related to Customizable Rollup settings, filter groups, and on the new rollup page:

_This page has an error. You might just need to refresh it. Access Check Failed! AttributeSet.get(): attribute 'filterRuleList' of component 'markup://npsp:CRLP_RollupsContainer {6:0}' is not visible to 'markup://aura:if {94:0}'. Failing descriptor: {aura:if}_

<img width="1295" alt="screen shot 2018-06-01 at 10 02 09 am" src="https://user-images.githubusercontent.com/37851761/40853418-df20f862-6582-11e8-89cf-28560ec89a93.png">

Happens in both Lightning and Classic. Appears even after logging out/in, Incognito browser or not, disable/enable CRLP's, etc. Org is a production org originating as Trail. Received CRLP's via general production push.

So far this has not be replicated in any other org as far as we know. 

Error message appears to remain the same regardless of the page, although @randi274  believes she saw a different error message once when logged into my org.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
