### ISSUE TITLE
Customizable Rollups : Error When Deleting Filter Groups with Inactive Rollups

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/Cumulus#3268]
Issue 1: The section indicating "Active Rollups Using this Filter Group" has Inactive Rollups in the list
Issue 2: The user gets an unhelpful error at the bottom of the page when trying to delete a Filter group that has Inactive Rollups using it, and cannot easily get back to where they were working

Suggestion: Remove the reference to "Active" in the section header and help text, and provide a useful error toast if the user tries to delete a Filter Group that has Active or Inactive Rollups using it.

Steps:

1. Before Enabling CRLP, go to NPSP Settings > Contact Roles > Edit
2. Uncheck the "Enable Soft Credit Rollups" checkbox
3. Change "Soft Credit Roles" to "None"
4. Save
5. Enable Customizable Rollups

* Actual & Expected -- The Soft Credit Rollups are "Inactive" (have an "X" in the "Active" column)

![image](https://user-images.githubusercontent.com/3886084/41069392-87e12576-69a2-11e8-8f3a-44655b6f3273.png)

6. Click on "View Filter Groups"
7. Click on the "Opps: Won (SC)" Filter Group

* Actual : Section heading is "Active Rollups Using this Filter Group"; Help Text refers to "active rollups"; this section has a list of Rollups using the Filter Group (even though they are inactive)
* Expected : The Section heading & help text do not have the word "Active" in it, ie: "Rollups Using this Filter Group") _(Note that we could expect this list to be blank, since there are no **active** Rollups using the filter group. However, I think it would be preferred to simply remove the reference to "active" so users do not accidentally delete all the Rollups when they delete a Filter Group.)_ 

![image](https://user-images.githubusercontent.com/3886084/41069415-a11ef8f6-69a2-11e8-9e7d-dbcbee38a332.png)

8. Click on "Delete" to Delete the Filter Group

* Actual : Error message at the bottom of the page, "...Action failed: c:CRLP_FilterGroup$controller..." (see image)
* Expected : An Error Toast at the top of the page explaining why the Filter Group cannot be deleted and what steps to take next.

![image](https://user-images.githubusercontent.com/3886084/41069307-2d5ccf06-69a2-11e8-90da-14f9e2134923.png)

See screencast : https://drive.google.com/open?id=13NYii4S27B-wyP2q3_UUQvGQFHik8Kqx

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AY8IwAAL" target="_blank">W-025353</a>

**Comment by dgamboni** [comment]
I've closed the related AA ticket so I'll close this issue as well.
