### ISSUE TITLE
Customizable Rollups: First/Last/Smallest/Largest operators should respect a Years Ago time frame

### ISSUE THREAD

**Issue by bethbrains** [SalesforceFoundation/Cumulus#3276]
A rollup with a single result operator (first/last/smallest/largest) and a Years Ago time frame does not behave as expected. It ignores the time frame and returns the requested value from the First or Last record based on All Time. It should respect the time frame as defined.
Example use cases: What was the first campaign this Household donated to Last Year? What was the value of their last donation Last Year?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYAohAAH" target="_blank">W-025459</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
