### ISSUE TITLE
Customizable Rollups: Smallest/Largest operators should roll up Field to Roll Up if defined

### ISSUE THREAD

**Issue by bethbrains** [SalesforceFoundation/Cumulus#3279]
Currently, Smallest/Largest always roll up Amount field, ignoring Field To Roll Up. Rollups that use Smallest or Largest operator should evaluate which record to use based on Amount field, but then roll up the Field to Roll Up as defined.
Example use case: What Campaign brought in this donor's largest donation? What was the check number (i.e., a number field as Field to Roll Up) of their largest donation?

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYAogAAH" target="_blank">W-025458</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
