### ISSUE TITLE
Customizable Rollups Error Related to Field Level Security

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3280]
If a non-System Administrator creates a Won Opportunity or sets an existing Opportunity to Closed Won (triggering rollups) and they don't have permissions on fields referenced in customizable rollups, an error is captured in the Error object. These should not be dependent on FLS of the current user.

**Error Type** = System.SObjectException
**Full Message:** SObject row was retrieved via SOQL without querying the requested field
{Name of Field}

The majority of reports involve the Opportunity's Primary Contact field, but we've also replicated with a custom field where the creating user did not have permissions. When a System Administrator uses the Recalculate Rollups button, no errors occur. Likewise, if the running user of the scheduled job has permissions, there are no errors.

![primary contact](https://user-images.githubusercontent.com/29731456/41248507-46ba1806-6d7f-11e8-8b72-22e4d9d1da0b.png)
![custom field](https://user-images.githubusercontent.com/29731456/41248514-48a0d060-6d7f-11e8-8a8c-71520dad58ae.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYAoqAAH" target="_blank">W-025461</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
