### ISSUE TITLE
NPSP Contact Delete Override giving error message in Lightning - Delete Action still works

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3319]
Hub Post: https://powerofus.force.com/0D58000004I9aXQ

When using the Contact Delete Override button on the Contact record in Lightning and Summer '18, an error message is produced: "This page isn't available in Salesforce Lightning Experience or Mobile App". 
The Delete action still works, and there is no issue in Classic. 

Steps to repro in production org:

1. Create Contact/Household in NPSP.
2. Using override "CON_DeleteContactOverride" button on Contact while in Lightning, click the Delete button. 
3. Select either to delete whole Household Account or just Contact (either produces the error).
4. Note error. 
5. Note Contact/Household is deleted. 

<img width="1347" alt="screen shot 2018-06-18 at 3 03 51 pm" src="https://user-images.githubusercontent.com/37851761/41565565-2a383be4-730c-11e8-881c-97fffac2f224.png">

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYB74AAH" target="_blank">W-025685</a>

**Comment by spilzer** [comment]
Thanks for giving this issue attention! I thought it might be related to the URL format since I'm experiencing the same thing with a couple of other custom Visualforce pages. Is there a way for me to update the code in my Org or should I just wait for a new version of the package to be published?

**Comment by jesslopez-sf** [comment]
@spilzer: Unfortunately, no. The Visualforce page code is managed, so you won't be able to make any changes to it. Redirects definitely work in some ares of the platform and not others. :/ Barring any major issues, we're slated to fix this in the release delivered to sandboxes in 2 weeks (we didn't make it in time for tomorrow's sandbox release).

**Comment by mrbelvedere** [comment]
Included in beta release 3.134 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 3.134
