### ISSUE TITLE
Deleting a 1:1 contact, does not show up in Recycle Bin, so can't be undeleted.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#332]
_Issue by **[kbromer](https://github.com/kbromer)** from Friday Oct 12, 2012 at 20:37 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/8_

----

http://code.google.com/p/npsp/issues/detail?id=342
and
https://groups.google.com/forum/?fromgroups=#!topic/npsf/5pcBKQExlmc

**Comment by kbromer** [comment]
https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006R7l2&tab=sfdc.ProfilePlatformFeed&fId=0D580000027GDF2&emtm=1431698490202&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterPostNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000003egB0

**Comment by mrbelvedere** [comment]
Included in beta release version 3.48 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.48

**Comment by Filikin** [comment]
Great to see this fix, any chance this will be retrofitted to V2?

**Comment by njjc** [comment]
Hi @Filikin, we're not updating any of the NPSP 2 packages, and we strongly recommend upgrading to 3.

**Comment by Filikin** [comment]
thanks for the reply Nicolas, but with 300 projects all on V2 each with their own customisations, we can't afford the risk that upgrading to V3 might break something.

regards,

Eamon

Eamon Kelly
ENCLUDE - Technology Donations and Solutions for Irish Charities
Drumcondra Business Centre
120 Drumcondra Road Upper
Dublin 9
Main Phone:      (01) 6535099
Support Phone: (01) 4853435
Mobile: 085 7130794
Web: http://www.enclude.ie<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.enclude.ie>

ENCLUDEit - technology donation website http://www.encludeit.org<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.encludeit.org%2f>



________________________________

**Comment by njjc** [comment]
Understood, although I'd say it's still worth a try to upgrade. You can test customizations in a sandbox first.

The actual fix for this issue is a simple controller class and visualforce page that overrides the contact delete button. You could fairly easily self implement this feature in an unmanaged context.

**Comment by Filikin** [comment]
thanks Nicolas,

I suspect we will used a mixed approach, upgrading to V3 where we can justify it and adding the fix manually where we can't

regards,

Eamon

Eamon Kelly
ENCLUDE - Technology Donations and Solutions for Irish Charities
Drumcondra Business Centre
120 Drumcondra Road Upper
Dublin 9
Main Phone:      (01) 6535099
Support Phone: (01) 4853435
Mobile: 085 7130794
Web: http://www.enclude.ie<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.enclude.ie>

ENCLUDEit - technology donation website http://www.encludeit.org<https://dbxprd0411.outlook.com/owa/redir.aspx?C=LQUfhFY4-kGcKgsvZ25WphfbGLfIKdAIm_Tcv_dDBy9ufPET69psI2tY2rOaFHkGW1M636IUrUI.&URL=http%3a%2f%2fwww.encludeit.org%2f>



________________________________
