### ISSUE TITLE
NPSP Contact Merge Should Respect Portal User Status

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3338]
The NPSP Contact Merge utility allows you to merge Contacts regardless of whether or not they are Partner or Customer Portal (Communities) Users. Because we aren't displaying portal status on the field set for each Contact on the merge screen, you can easily select a Master that is not a portal user and ultimately lose portal access after the merge. Ideally, we can display portal status and also prevent the non-portal status as master.

The native (non-NPSP) Classic version of Contact Merge prevents this from happening. Here are screenshots and Steps to Repeat for the more desired outcome:

**Step 1:** Merge Contacts
![step 1](https://user-images.githubusercontent.com/29731456/41745725-f229a096-7575-11e8-90a0-6a46c7c3aae1.jpg)

**Step 2:** Select Contacts to Merge. Note the columns showing Customer and Partner Portal "status".
![step 2](https://user-images.githubusercontent.com/29731456/41745748-058c7c08-7576-11e8-887a-d62945948c46.jpg)

**Step 3:** On screen showing field values for each Contact, note the Portal User option. In this Case, the Partner Portal Contact is selected as Master, but the "Not a Portal User" option is selected in the Portal User column. 
![step 3](https://user-images.githubusercontent.com/29731456/41745800-38522886-7576-11e8-9fec-8cdd1a4b29d5.jpg)

**Step 4:** This scenario results in an error.
![step 4](https://user-images.githubusercontent.com/29731456/41745826-489734f2-7576-11e8-8b0f-481f6ad3ce40.jpg)

**Super Condensed Steps to Repeat**
1. Set up and activate a Community in your scratch org. Add Partner Community User and Partner Community Login User Profiles as Members of the Community. (If you want a demo of setting up a Community, let me know).
2. Create a Contact named Jack Black. The Black Household is automatically created.
3. Add a Contact called Jackie Black to the Black Household.
4. Edit the Contact Page Layout so that you have the Enable Partner User and Disable Partner User buttons in the Custom Buttons section (for Classic) and the Actions versions of these in the Salesforce Mobile and Lightning Experience Actions section.
5. Go to the Black Household Account page. Click the button to Enable as Partner.
6. Go to Jack Black's Contact page. Click the button to Enable Partner User. This takes you to a User screen with his info filled out. Choose the Partner Community Login role/profile.
7. First try merging using the classic non-NPSP Contact Merge to merge Jack and Jackie Black. Your actions will mirror the screenshots above and you won't be able to merge.
8. Then go to the NPSP Contact Merge tab. Try to merge Jack and Jackie Black and you can. Selecting Jackie as master will remove the new merged Contact as a Partner User.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBHdAAP" target="_blank">W-025816</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.135 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 3.135
