### ISSUE TITLE
Customizable Rollups: New OCR values are not included in Manage Soft Credits role list

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3342]
Thread

Org with CRLP enabled.

1. Add roles to Setup > Contact Roles on Opportunities
2. Go to an Opportunity and click Manage Soft Credits - Role list does not have all values

Example OCRs:

![image](https://user-images.githubusercontent.com/4614343/41796663-6d7ab216-7635-11e8-963b-b63e1ad8a54c.png)

Available values in MSC:

![image](https://user-images.githubusercontent.com/4614343/41796677-7a32334e-7635-11e8-8e15-0a1d4f680e8f.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBKSAA5" target="_blank">W-025851</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
