### ISSUE TITLE
Increase Customizable Rollups' Deployment Timeout to 3 Minutes

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3346]
Users may receive timeout error messages while creating or deleting Filter Groups, even though the Custom Metadata Type records eventually deploy. After hitting the Create or Delete button, the deployment is shown as in progress in Setup --> Deployment Status. When it does finish (after a few minutes), it shows as succeeded. However, the LEX page displays the following error to the user via a toast at the top of the page: 

Saving the Filter Group has timed out. Please see the Customizable Rollups documentation for more information.

Screenshot of initial "saving..." message:
![filter group 1](https://user-images.githubusercontent.com/29731456/41856093-21e2c8b2-788c-11e8-801c-f6e652f20057.png)

Screenshot of false error:
![filter group 2](https://user-images.githubusercontent.com/29731456/41856099-24596984-788c-11e8-8265-6de9f6c10e34.png)

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBMYAA5" target="_blank">W-025874</a>

**Comment by randi274** [comment]
Closing manually since this was merged with #3475.
