### ISSUE TITLE
OCR TDTM throws Exception for blank AccountId on Opportunity

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3353]
This was introduced in the 3.132 release. If the AccountId is cleared from an Opportunity and our OPP_OpportunityContactRoles_TDTM Trigger Handler fires, a null pointer Exception is thrown.

`TDTM_Opportunity: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object Class.OPP_OpportunityContactRoles_TDTM.upsertContactRolesAfterUpdate: line 382, column 1 Class.OPP_OpportunityContactRoles_TDTM.run: line 75, column 1 Class.TDTM_TriggerHandler.runClass: line 183, column 1 Class.TDTM_TriggerHandler.run: line 105, column 1 Trigger.TDTM_Opportunity: line 34, column 1`

This was originally surfaced by a customer using a custom trigger in their sandbox which seemed to clear the Account Id from the Opportunity, which on update, triggered our OCR TDTM to run.

I reproduced in a scratch org.

Steps to Repeat:
1. Create a new Account Record Type called One-to-One.
2. On the page layout you chose for the new Record Type, edit the Account Name properties so that it is not required.
3. Go to NPSP Settings-->People --> Account Model and set the Account Model to "One-to-One" and the One-To-One Record Type to "One-to-One".
4. Create a Contact. This will create an Account with the same name.
5. Create an Opportunity for that Contact. Do not fill in the Account Name. (But do fill in the Contact).
6. Save the record and you will see the error. [Screenshot attached]
![ocr tdtm](https://user-images.githubusercontent.com/29731456/41877968-2d436ae2-78cb-11e8-904b-711f732949b4.png)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBOAAA5" target="_blank">W-025894</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.133 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 3.133
