### ISSUE TITLE
Allow users to choose column fields in Found Contacts page of Contact Merge

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#336]
_Issue by **[kenjiy27](https://github.com/kenjiy27)** from Friday May 17, 2013 at 14:14 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/22_

----

Column fields in Found Contacts page of Contact Merge are currently fixed. There are six fields - Name, Account Name, Email, Title, Phone, Owner.

However, in many organizations, Address and some External IDs are needed to display. It is awfully helpful if organizations can choose column fields in Found Contacts page of Contact Merge.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40

**Comment by kenjiy27** [comment]
Setting the Field Set changes the column fields. It's cool! Thank you for following up this issue!
