### ISSUE TITLE
Allow users to change display conditions of row fields in Selected Contacts page of Contact Merge

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#337]
_Issue by **[kenjiy27](https://github.com/kenjiy27)** from Friday May 17, 2013 at 14:53 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/23_

----

Row fields in Selected Contacts page of Contact Merge are currently fixed.

There is a display condition. The condition seems:

 - Fields that are updatable
 - Fields allowed a user to access by Profile and Field Level Security

Then, if values in a same row are different, radio buttons are displayed to choose a value.

Because of this conditions, some system field and some "hidden" fields that, for example, sytem administrators hide from Page Layouts to avoid unwanted changes are now displayed in the Selected Contacts page.

It is inconvenient for both users and administrators to show such fields.

On the other hand,  in the standard merge page, the system field and the "hidden" fields shown in the Selected Contacts page are not shown. Row fields in the standard merge page seems to be same as fields in Page Layouts.

It is very helpful if organizations can change display conditions of row fields in Selected Contacts page of Contact Merge.

**Comment by davidhabib** [comment]
@judisohn @kbromer I've implemented to things in Contact Merge UI.  I have a list of all our rollup fields that we set, and now these show up as readonly in Contact Merge.  I also have a list of npsp fields we don't want to show in Contact Merge.  I've put the three _system fields on that list.

I think this is good enough, and probably better than introducing another field set that users need to learn about how to modify.

agreed that this is good enough?

**Comment by judisohn** [comment]
Yes, I can't think of any other field that would cause confusion. Thanks @davidhabib

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
