### ISSUE TITLE
Customizable Rollups (CRLPs) - Allocation Amount is Not Showing as a Field to Roll Up Option

### ISSUE THREAD

**Issue by dgamboni** [SalesforceFoundation/Cumulus#3376]
When creating a New GAU CRLP, the GAU Allocation Amount is not showing up in the Field To Roll Up Picklist.

STR:

1) Create a Custom "Amount" field (ie, field type = Currency) on the GAU Object
2) Go to Customizable Rollups > New Rollup
- Target Object = GAU
- Target Field = Custom "Amount" field
- Operation = Last [or 'Largest']
- Rollup Type = GAU Allocation -> General Accounting Unit
- Field to Roll Up
-- Expected : GAU Allocation Amount is available for selection
-- Actual : Only Opportunity fields are available for selection

![image](https://user-images.githubusercontent.com/3886084/42115567-54678f38-7ba8-11e8-93e6-5d2b8675463d.png)

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBbYAAX" target="_blank">W-026055</a>

**Comment by mrbelvedere** [comment]
Included in production release 3.135
