### ISSUE TITLE
REQUIRED_FIELD_MISSING- Required fields are missing: [Formal_Greeting__c]

### ISSUE THREAD

**Issue by tstone6** [SalesforceFoundation/Cumulus#3394]
All admins are receiving REQUIRED_FIELD_MISSING- Required fields are missing: [Formal_Greeting__c] when Formal_Greeting__c is not updated, however, Formal_Greeting__c is not a required field and Apex Exception Emails are only set to 1 user

![image](https://user-images.githubusercontent.com/27711656/42172876-5c90982c-7deb-11e8-93d8-55787c5b9f89.png)

![image](https://user-images.githubusercontent.com/27711656/42172957-9069551c-7deb-11e8-99bf-e1fce2d8620c.png)

**Comment by judisohn** [comment]
@tstone6 We don't do support here in Github - your best bet is to post to the [NPSP group](https://powerofus.force.com/0F980000000CjRe) in the Hub.

However, it does appear that you have a custom field on the Contact record for Formal Greeting and it's set as Required at the field definition level. Could you check again? If you're still having trouble, post in the above group. Thanks.
