### ISSUE TITLE
Informal Greeting displaying as Contact 1, Contact 2 instead of Contact 1 and Contact 2 

### ISSUE THREAD

**Issue by virkudp** [SalesforceFoundation/Cumulus#3405]
I have set NPSP Household setting Contact Overun Count as 2 and Name Overrun is blank. I have a flow that excludes Teens from Household Name and Formal and Informal Greeting. The flow also excludes Duplicate Adults (Only 1 is counted). For any DML operation on a Contact, the Household name and Formal Greeting displays correctly. But the Informal Greeting displays as Contact1, Contact2 instead of Contact1 and Contact 2 when there's a 3rd Adult Contact 3. If I change Contact 2 to Teen, the Informal Greeting displays correctly Contact 1 and Contact 3. Why does it display comma in certain situations?

**Comment by judisohn** [comment]
Hi @virkudp - in the future, please post your question in the [NPSP group](https://powerofus.force.com/0F980000000CjRe) in the Hub. We don't do direct support here.

However, I can tell you in this case that what you're describing is already a known issue #2965 that I hope our developers can look at in the near future.
