### ISSUE TITLE
Salesforce to salesforce shared contacts cannot be merged

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#341]
_Issue by **[Filikin](https://github.com/Filikin)** from Friday Jul 12, 2013 at 10:19 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/28_

----

I am using Salesforce to Salesforce to share client details with charities in the same area.
When I attempt to use contact merge to merge a client who has come from another salesforce instance with a local client, I get an error as soon as I select the two clients from the search page and press "Next".

The error is:
Attempt to de-reference a null object
Error is in expression '{!nextStep}' in page npe01:contactmerge

The steps are:
1) Given two instances of Salesforce, A and B. Set up a connection between them. (mine is bi-directional, once a contact is shared, either side can make changes)
2) Create a contact in both A and B
3) Share the contact in A with B
4) In B, select Contact Merge and find the two contacts
5) Press Next
Error appears

**Comment by davidhabib** [comment]
After doing all the contact merge redesign, I just tested this with org contacts and it worked fine.

**Comment by davidhabib** [comment]
also fine with contacts using the household account model.

**Comment by davidhabib** [comment]
also fine with contacts using the one-to-one account model.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
