### ISSUE TITLE
Default GAU allocation amount is incorrectly calculated if there are multiple allocations to the default GAU in one Opportunity

### ISSUE THREAD

**Issue by pedrodalcol** [SalesforceFoundation/Cumulus#3434]
### Steps to reproduce:

1. Enable default allocations and set a default GAU. 
2. Create a new Opportunity and set amount to $1000 (It will be automatically allocated to default GAU)
3. Click manage allocations and add an allocation for $500 (or any other amount) to the the default GAU (from step 1).
4. Click save and return to the list of allocations. There will be two allocations for $1000 each even thought the Opportunity total amount is $1000.
5. If you try editing the records using the standard UI, only one can be modified, the other one keeps getting reset to $1000. 

### Suggested solution: 

* Allow only 1 allocation to the default GAU on the same Opportunity.
* Detect and delete duplicate default GAU allocations, and combine all amounts into one allocation.

**Comment by annejackson** [comment]
This is fixed with https://github.com/SalesforceFoundation/Cumulus/pull/3513

**Comment by mrbelvedere** [comment]
Included in beta release 3.136 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 3.136
