### ISSUE TITLE
RD's Next Pledged Opportunity has Different Close Date if Next Donation Date Blank and Last Payment Day within 28-31 Range

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3455]
This issue is related to Issue #3126, but this provides a much tighter scenario/use case for it occurring. The issue is that future pledged Opportunities are being created based on the Date Established day of the month as opposed to the most recent Opportunity's Close Date day of the month when that day falls within the 28-31 of the month. It works as expected if the day falls within the 1-27 range of the month. Specifically, this occurs when the Next Donation Date is blank. This should only ever be the case if no future pledged Opportunities exist (this is dependent on the Opportunity Forecast Months setting in NPSP Settings). 

For example, if the Opportunity Forecast Months setting in NPSP Settings is 3 and I create a quarterly Open-Ended Recurring Donation with a Date Established of today, one pledged Opportunity will be created with a Close Date of today. If I then set that Opportunity's stage to Closed Won, the Next Donation Date field remains blank until the nightly RD script creates the next pledged Opportunity. 

Things get a bit more complicated when the day of the Date Established is different from the day of the Next  Donation Date (definitely a realistic scenario). 

* Scenario 1 (the control): the Date Established is 7/1/2018 and the Next Donation Date is 7/15/2018. When that Opportunity is set to Closed Won, the Next Donation Date will remain blank until the script creates the next one. In this case, the Close Date of the pledged Opportunity uses the date of the most recent Opportunity's Close Date: *10/15/2018*.

* Scenario 2 (the bug): the Date Established is 7/1/2018 and the Next Donation Date is 7/28/2018. When that Opportunity is set to Closed Won, the Next Donation Date will remain blank until the script creates the next one. In this case, the Close Date of the pledged Opportunity uses the date of the Date Established vs. the day of the most recent Opportunity's Close Date: *10/1/2018*.

**Steps to Repeat:**
We need to delete an Opportunity for each scenario to replicate exactly.

1. Set Opportunity Forecast Months to 3 in NPSP Settings → Recurring Donations → Recurring Donations.

2. Create the Scenario 1 (Control) data.
    1. Create a Contact.
    2. Create a new Recurring Donation (Contact = your Contact, Amount = 10, Open Ended Status = Open, Date Established = 6/1/2018, Next Donation Date = 6/1/2018, Installment Period = Quarterly).
    3. Two pledged Opportunities are created with Close Dates of 6/1/2018 and 9/1/2018.
    4. Delete the 9/1/2018 Opportunity. (so we can automatically add it later).
    5. Set the 6/1/2018 Stage to Closed Won.
    6. The Recurring Donation's Next Donation Date will be blank because there are no future pledged Opportunities.
    7. Click the Refresh Opportunities button on the Recurring Donation to simulate the nightly script running.
**_The newly created Opportunity will have a Close Date of 9/1/2018. [May need to refresh a few times if you're using Lightning...] This is created as expected._**

3. Create the Scenario 2 (Bug) Scenario:
    1. Create a new Recurring Donation (Contact = your Contact, Amount = 20, Open Ended Status = Open, Date Established = 6/1/2018, Next Donation Date = 6/28/2018, Installment Period = Quarterly).
    2. Two pledged Opportunities are created with Close Dates of 6/28/2018 and 9/28/2018.
    3. Delete the 9/28/2018 Opportunity. (so we can automatically add it later).
    4. Set the 6/28/2018 Stage to Closed Won.
    5. The Recurring Donation's Next Donation Date will be blank because there are no future pledged Opportunities.
    6. Click the Refresh Opportunities button on the Recurring Donation to simulate the nightly script running.
**_The newly created Opportunity will have a Close Date of 9/1/2018. [May need to refresh a few times if you're using Lightning...] We would expect a Close Date of 9/28/18._**

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBrqAAH" target="_blank">W-026252</a>
