### ISSUE TITLE
Error When Clicking Recalculate Rollups Button on General Accounting Unit

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3478]
Clicking on the Recalculate Rollups button on any General Accounting Unit record results in a Visualforce page error:

`SObject row was retrieved via SOQL without querying the requested field: npsp__General_Accounting_Unit__c.Name 
`

The batch still runs, however, and rollups are recalculated. @force2b and @bethbrains have come up with a likely fix for forcing the name to load from the standard controller. (All other Recalculate Rollups buttons work fine -- on Account, Contact, and Recurring Donation).

**Steps to Repeat:**
1. Create a General Accounting Unit record. 
2. Click the Recalculate Rollups button.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBvOAAX" target="_blank">W-026308</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.135 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.135
