### ISSUE TITLE
URL Broken in Volunteers for Salesforce App help tab

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3482]
Clicking on the Resources link on the "Volunteers Help" tab in the V4S app results in a broken URL message.  
URL: https://powerofus.force.com/kA0f2000000oYWv
<img width="1265" alt="screen shot 2018-07-16 at 8 23 04 am" src="https://user-images.githubusercontent.com/37851761/42767408-c31e25fa-88d1-11e8-8499-86742fc9d0e4.png">
<img width="907" alt="screen shot 2018-07-16 at 8 23 13 am" src="https://user-images.githubusercontent.com/37851761/42767421-cac650e8-88d1-11e8-8b73-29cfd4ffb5e7.png">

I believe the correct destination is: https://powerofus.force.com/articles/Resource/Volunteers-for-Salesforce

Steps to Repro:

1. Log into a Salesforce Org with V4S installed. 
2. Navigate to the Volunteers Help tab.
3. Click on Step 2, Volunteers for Salesforce Explore more V4S Resources. 
4. Error is shown in new window for broken link.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBwMAAX" target="_blank">W-026320</a>

**Comment by coriobriensfdo** [comment]
Created against incorrect product. New issue: https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/349
