### ISSUE TITLE
Enhance Contact Merge Page

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#349]
_Issue by **[jamesmelville](https://github.com/jamesmelville)** from Tuesday Dec 03, 2013 at 22:23 GMT_
_Originally opened as https://github.com/SalesforceFoundation/Contacts_and_Organizations/issues/37_

----

The page should implement pagination over the returned list of Contacts. For example it is possible to have a case where the search criteria match a large number of records and it is not possible to refine the criteria further to limit that list. If the records you want to merge don't appear in the top 20 then you're out of luck. (and SOSL can now return up to 2,000 results).

**Comment by davidhabib** [comment]
I've increased the limit from 20 to 100 on the page.  I think that is good enough and we should not consider doing pagination support at this time.  It is not clear to me that a future version based on Lightning and being mobile ready would use pagination.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
