### ISSUE TITLE
Contact Delete Override Button Errors Out With Console Navigation

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3493]
Related to #3319, which fixed the issue for standard navigation within a Lightning app. It appears that if a Lightning app is set up to use console navigation instead of standard navigation, the delete button still produces an error.

**_Steps to Repeat:_**
1. Create a Lightning App with Console navigation. Make sure to add the Contacts tab and enable it for System Administrators.
2. Create a Contact.
3. Click the Delete button. You will see an error that says "This page isn't available in Salesforce Lightning Experience or mobile app."

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBy8AAH" target="_blank">W-026342</a>

**Comment by dnorman1014** [comment]
This has been open for awhile, Do we have a ETA for the fix?

**Comment by jesslopez-sf** [comment]
This is unfortunately an issue with core Salesforce.com functionality. Visualforce button overrides are not supported in console apps (https://success.salesforce.com/issues_view?id=a1p3A000000EAa3QAG). 

As a workaround for this issue, we need to "trick" the console app into using a custom "delete" button using the following steps:

1. Setup → Object Manager → Contacts
2. Click Buttons, Links, and Actions.
3. Click New Button or Link
4. Label / Name = Delete 2 (for now so you can distinguish between the other one)
5. Display Type = Detail Page Button
6. Behavior = Display in Existing Window With Sidebar
7. Content Source = Visualforce Page
8. Content = CON_DeleteContactOverride
9. Save
10. Add the button to your page layouts and remove the other Delete button.

Thank you to @bethbrains  and @cdcarter  for this workaround!
