### ISSUE TITLE
Rollup Donation Info on Account is Confusing

### ISSUE THREAD

**Issue by jamesward** [SalesforceFoundation/Cumulus#3545]
I was working with a nonprofit who was entering donation info into the rollup fields on an Account.  The values then disappeared because they seem to be rolled up automatically from Opportunities.  But the UI doesn't indicate this and it is confusing that the fields are user editable.

**Comment by judisohn** [comment]
Hi @jamesward - our documentation covers this [here](https://powerofus.force.com/articles/Resource/Troubleshooting-the-NPSP#!#ariaid-title4). The fields are set as read-only in our layouts, the challenge is that System Administrators can have the setting to Write to Read Only fields and we use standard UI so it's difficult to communicate this information to end users.

**Comment by jamesward** [comment]
Thanks for the quick response.  It seems like it'd be good to have the UI indicate this since it should be able to be looked up.  For instance:
> These fields are editable due to your settings, but the values will be overwritten so do not enter data here.
