### ISSUE TITLE
NPSP Recurring Donations Imports without creating opportunities.

### ISSUE THREAD

**Issue by BoChengHuang** [SalesforceFoundation/Cumulus#3594]
When my user uploaded CSV file from NPSP data import, NPSP should automatically help create corresponding opportunities. For example, a record with 12 monthly donations will create 12 opportunities.

If my user uploaded 100 records which are all have 12 monthly donations, opportunities will be created. (1200)
But if they uploaded more records (such 500) with monthly donations (range from 12 to 50) opportunities will not be created.

Please let me is this a bug or restricted by governors limit in SFDC.
Thank you!!

**Comment by judisohn** [comment]
@BoChengHuang We don't provide direct customer support here in Github. Instead, please post your question in the [NPSP Group in the Power of Us Hub](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe) along with as much detail (screen shots are great too) as you can and exactly what errors you are seeing. Thanks!
