### ISSUE TITLE
NPSP Data Import Still Calculating Customizable Rollups When Calculate Donation Rollups with Batch is Unchecked in Managed NPSP

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3630]
When the “Calculate Donation Rollups With Batch” field is unchecked (the default) on the NPSP Data Import configuration screen, rollups still fire when Customizable Rollups are enabled. 

**_Note: this works as expected in unmanaged NPSP, so when testing, please install the managed version of NPSP._**

**Steps to Repeat:**

1. Go to NPSP Settings → Donations → Customizable Rollups and enable Customizable Rollups.

2. If using an org with unmanaged NPSP, modify the Start Data Import button (Setup →Object Manager → NPSP Data Import → Buttons, Links, and Actions → Edit Start Data Import button. Copy/paste the following URL instead.
`/apex/BDI_DataImport?retURL={!URLFOR($Action.DataImport__c.Tab, $ObjectType.DataImport__c)}
`
3. Create a record in the NPSP Data Imports object (sample file attached to Work Item). The key is to have Donation Information which will trigger the rollups to fire.

4. Go to the NPSP Data Imports Tab and switch your View to “To Be Imported”

5. Click the Start Data Import button

6. Verify that “Calculate Donation Rollups With Batch” is unchecked (the default).

7. Start the import.

8. When the import completes, go to the newly created Contact and you'll see that rollup fields have been calculated. 

In contrast, legacy rollups do respect this setting. If testing in a scratch org with unmanaged NPSP, this setting is also respected.

**Comment by mrbelvedere** [comment]
Included in beta release 3.139 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 3.139
