### ISSUE TITLE
Customizable Rollups: Error due to 'Best Gift Year' number not removing '.' separator for non-English locales

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3640]
[Thread.](https://powerofus.force.com/0D58000004SYnPZ)

Even though the year is a number, Customizable Rollups knows to remove the comma so 2018 is 2018 and not 2,018 for English/USA and other locales that use "," However, Spanish and Italian (and probably others) separate with a "." and this is causing an error.

`STRING_TOO_LONG- Best Gift Year: data value too large: 2.018 (max length=4)`

Steps to repeat:

1. With English as Locale/Language, enable Customizable Rollups
2. Create an Opportunity and verify no errors in rollups
3. Change Language to Italian and Locale to Italian (Italy) for your user
4. Create an Opportunity of any amount - closed/won
5. Observe error in rollup:

![image](https://user-images.githubusercontent.com/4614343/45487774-4db63c00-b72d-11e8-9c62-321a7a2c7d3c.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by mrbelvedere** [comment]
Included in beta release 3.140 (Beta 9)

**Comment by mrbelvedere** [comment]
Included in production release 3.140
