### ISSUE TITLE
Error when Merging Contacts with the Contact Merge page

### ISSUE THREAD

**Issue by conrjac** [SalesforceFoundation/Cumulus#3653]
When using the CON_ContactMerge visual-force page, to merge two contacts, getting the following error message:

> SOQL statements cannot query more than 35 different parent types. Error is in expression '{!nextStep}' in component in page npsp:con_contactmerge: (npsp) 
> An unexpected error has occurred. Your solution provider has been notified. (npsp)

The following Apex Exception email is also sent:

> Apex script unhandled exception by user/organization: [REMOVED]
> Visualforce Page: /apex/npsp__CON_ContactMerge
> caused by: System.UnexpectedException: SOQL statements cannot query more than 35 different parent types.
> Class.npsp.CON_ContactMerge_CTRL.loadMergeCandidates: line 318, column 1
> Class.npsp.CON_ContactMerge_CTRL.nextStep: line 246, column 1

Contacts can be merged by the user, using the Salesforce standard contact merge tool, or by using executing anonymously a merge DML operation.

**Comment by coriobriensfdo** [comment]
Hi @conrjac, thank you for posting details but we don't actually do any support via GitHub. Can you please post in the Power of Us Hub, in the NPSP group: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe

Please include the above details.

Thanks!
