### ISSUE TITLE
Feature: Add "Primary Contact" field to Opp

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#366]
Feature request: Add a lookup field on Opp that is populated with the OCR record that is primary, if there is one.

Benefits:
* Contact info could be displayed on Opp list views.
* "Send an Email" button on Opp could use Contact-related SF merge fields (like first name for "Dear Jane") via the creation of x-obj formula fields based off of this new Primary contact field.
* Lower-end 3rd party mail merge addins that don't know how to traverse Opp-OCR-Contact would still work via x-obj formula fields on Opp.

**Comment by judisohn** [comment]
This feature has been implemented.
