### ISSUE TITLE
Engagement Plan on Level not supported on custom object due to invalid name error

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3687]
[Thread.](https://powerofus.force.com/0D58000004WvNLY)

_Don't troubleshoot this in a scratch org with unmanaged NPSP - must replicate in an org with managed package only._

**Issue:**

An Engagement Plan attached to a Level will cause the Level batch to fail with the error: `Invalid field Custom_Object__c__c for npsp__Engagement_Plan__c`

**Steps to Repeat:**

1. Create custom object, be sure to check to allow for Activities
2. Create custom fields on object: Level (lookup to Level object), and a Number field (to increment the Level)
3. Create an Engagement Plan Template. Add some tasks, it doesn't matter how many or how they're constructed.
4. Edit Level Target field picklist value on Level to include the correct full API name of the custom object, including the __c
5. Create a Level record with the object as the Target. It doesn't matter the number for Min/Max, use the custom number field as the Source field and the Level field as the Level. Select the Engagement Plan template for the Engagement Plan on the Level.
6. Create a record in the custom object, put a value in the number field that is within the Min/Max of the Level.
7. Run the Level batch

**Expected Result:**

The Engagement Plan should fire and populate the tasks.

**Actual Result**

The Level batch fails with the above error.

If you change the Target picklist to not include the __c, such as 'Custom_Object' instead of 'Custom_Object__c' then you get an immediate error upon trying to create the Level.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOZQAA2" target="_blank">W-029028</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.142 (Beta 13)
