### ISSUE TITLE
Feature Request: UDRs to custom object

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#369]
Feature Request: UDRs to custom object.

Use case: Opportunities representing restricted donations to funds managed by a foundation.  Funds have to be a custom object rather than Accounts because a donation can be received *from* an Account (Opp.Account), with that donation "residing in" a restricted Donor Advised Fund.  The Donor Advised Fund (DAF) is a standard construct of foundations and can have contact info associated with it so it needs to be an object.  If UDRs could rollup to custom objects, then the total of donations into the fund, and dispersed grants out of the fund, could be UDR fields on the Fund record.

Current solution is to use 3rd party vendor RollupHelper.

**Comment by kbromer** [comment]
GAUs should solve for this
