### ISSUE TITLE
Feature Request: Improved UI for New OCR

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#370]
Feature Request: current UI for creating a new OCR manually via the New button in the Contact Role related list under Opp is unintuitive as follows:
- Long list of Contacts is unwieldy.
- Knowing that choosing a role value other than --None-- to create a new OCR record is not obvious.
- Knowing that a Contact not in the list can be found by typing over an prefilled row is not obvious.

Consider a custom UI.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fpyAAA" target="_blank">W-008260</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
