### ISSUE TITLE
Feature Request: Recurring donations: Allow Opp.RecordType to be chosen per recurring donation

### ISSUE THREAD

**Issue by johnfine** [SalesforceFoundation/Cumulus#373]
Feature Request: Allow the user to set the recordtype of the gen'd Opps from a recurring donation.

Use case: Cash donations are one recordtype, in-kind another (need record types because the data entry fields are so different between the two).  Can't use recurring gifts for regular in-kind donations of use of facilities because have to set default for all recurring donations to Gift.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fqRAAQ" target="_blank">W-008261</a>

**Comment by kbromer** [comment]
Nooooooooooooooooooooo!!!!!
