### ISSUE TITLE
Prevent XSS on Lead Convert Label Translation

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#3745]
Prevent the ability for XSS on the Convert Lead Override page.

**Comment by jjbennett** [comment]
**lurch: attach W-026034

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBZhAAP" target="_blank">W-026034</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.143 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release 3.143
