### ISSUE TITLE
Customizable Rollups Null Pointer Exception When RecordTypeId Referenced in Filter Rule with Null Value

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3747]
This surfaced in an org without a Membership Record Type. The Memberships: Won Filter Group contains a Filter Rule for Opportunity Record Type ID In List, where the value is null:

![null rec type id](https://user-images.githubusercontent.com/29731456/47580671-542afc80-d904-11e8-8266-28a5ee98da34.jpg)

When a Closed Won Opportunity is inserted, there is a Null Pointer Exception.
`
Stacktrace available at the time of saving the record - Class.CMT_FilterRule.<init>: line 131, column 1 Class.CMT_FilterRuleEvaluation_SVC.evaluateFilterGroup: line 96, column 1 Class.CRLP_RollupContact_SVC.processRollups: line 83, column 1 Class.CRLP_RollupProcessor_SVC.completeRollupForParent: line 303, column 1 Class.CRLP_RollupProcessor_SVC.startRollupProcess: line 115, column 1 Class.CRLP_RollupQueueable.runRollupsForIds: line 149, column 1 Class.CRLP_RollupQueueable.execute: line 73, column 1`

The line throwing the error is in CMT_FilterRule (Line 131):
    `    } else if (filterRule.Field__r.QualifiedApiName == 'RecordTypeId' && !filterRule.Constant__c.contains(recordTypeIdPrefix)) {
`

**_Temporary Workaround if you don't have a Membership Record Type:_**
Disable all of the Membership Rollups that are associated with the Memberships: Won Filter Group.

**Steps To Repeat:**
1. Delete the Membership Opportunity Record Type.
2. Enable Customizable Rollups in NPSP Settings --> Donations --> Customizable Rollups.
3. Create a Contact (First Name = Jess; Last Name = Lopez).
4. Create an Opportunity for that Contact (Name = Test; Amount = 100; Close Date = today; Record Type = Donation, Stage = Closed Won)
5. The Opportunity saves, but the error is captured in the NPSP Errors object.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP1KQAU" target="_blank">W-029366</a>

**Comment by seanpat09** [comment]
Fixed by #3846

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 49)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
