### ISSUE TITLE
Limit Affiliations Query for Automated Soft Credits

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3748]
If an org has more than 50,000 Affiliations for an Account and an Opportunity is associated for that Account, Salesforce + NPSP return the "too many query rows: 50001" error. This is as expected since this is a Salesforce limit. The recommendation would be to distribute these for data skew purposes, however, I don't think we should be preventing Opportunities from being inserted. **_This is affecting integrations._** Can we add a 50000 Limit to the query on line 181 of OPP_AutomatedSoftCredits.cls?

**Current query:**
```
List<npe5__Affiliation__c> allAffiliations
            = new List<npe5__Affiliation__c>([SELECT Id, Name, npe5__Organization__c, npe5__Contact__c, Related_Opportunity_Contact_Role__c
                                                FROM npe5__Affiliation__c
                                                WHERE npe5__Organization__c IN :accountIds
                                                ORDER BY CreatedDate DESC]);
```

**Suggested Query:**
```
List<npe5__Affiliation__c> allAffiliations
            = new List<npe5__Affiliation__c>([SELECT Id, Name, npe5__Organization__c, npe5__Contact__c, Related_Opportunity_Contact_Role__c
                                                FROM npe5__Affiliation__c
                                                WHERE npe5__Organization__c IN :accountIds
                                                ORDER BY CreatedDate DESC LIMIT 50000]);
```

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP1eQAE" target="_blank">W-029370</a>
