### ISSUE TITLE
Customizable Rollups: Rollup data not cleared when Opportunity is reparented

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3752]
[Thread](https://powerofus.force.com/0D51E00004aI1V5)

When Customizable Rollups are enabled, if an Opportunity is moved from one Account to another, the rollup values are not cleared from the original Account.

Steps to repeat:

1. Enable CRLP (leave default Filter Groups and Rules)
2. Create 2 Accounts: Organization A, Organization B
3. Create Opportunity (any record type), Closed/Won, $80, Account = Organization A
4. Note that rollups are correct for $80/Today on Organization A
5. Edit Opportunity and change Account from Organization A to Organization B
6. Note that rollups are correct for $80/Today on Organization B

Return to Organization A and rollups are still same as when Opportunity was attached.

Run NPSP Settings > Bulk Data Processes > Rollup Donation Batch. Note that Organization A still has same rollup values, but no connected Opportunity.

Run Recalculate Rollups button on Organization A and then and only then are the values cleared as expected.

Also note that rollups are cleared correctly if the Opportunity is deleted, not if it's reparented.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP5vQAE" target="_blank">W-029419</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.143 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.143
