### ISSUE TITLE
The search icon for Default General Accounting Unit in Allocation Settings is no longer visible

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/Cumulus#3755]
As a result, it's impossible to select a GAU to use as the default GAU.

![image](https://user-images.githubusercontent.com/801017/47734585-f1f23480-dc40-11e8-9a5c-d1366deb5694.png)

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP7SQAU" target="_blank">W-029435</a>

**Comment by coriobriensfdo** [comment]
Workaround: Type the exact name (or copy/paste) of the GAU and save NPSP Settings. This saves the value properly without the need to use the lookup search icon.

**Comment by mrbelvedere** [comment]
Included in beta release 3.143 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 3.143
