### ISSUE TITLE
Opportunity FMV Workflow Rule does not account for when Amount is $0 and FMV has not been populated

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3761]
[Thread](https://powerofus.force.com/0D58000004Q1GM1)

Currently, the criteria on the workflow rule is:

`((Opportunity: Amount EQUALS 0) OR (Opportunity: AmountEQUALS null)) AND (Opportunity: Fair Market Value NOT EQUAL TO 0)`

The way it currently is, if an Opportunity of any record type is created with a $0 Amount, it is being blanked out by the workflow rule.

The criteria needs to be changed to:

`((Opportunity: Amount EQUALS 0) OR (Opportunity: AmountEQUALS null)) AND (Opportunity: Fair Market Value GREATER THAN 0)`

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fP9TQAU" target="_blank">W-029460</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 7)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
