### ISSUE TITLE
Payment Allocations: With refunds, the Manage Allocations page is not showing the correct amounts, or totaling refund allocations correctly

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/Cumulus#3816]
User type (As a...) Goal (I want to...) Reason (so that...) Additional Details
The Payment allocations related list is showing correctly but the Manage Allocations page is not showing the negative/refund allocation totals correctly.

Steps to reproduce:
Setup: Payment allocations enabled and a default gau choosen. I created an opportunity of $100 and left the oppt allocation at 100% for the default gau. I also had a payment that was paid for $100 already.
1. Create another payment of -20 and paid with today's date. The payment allocation by default was (20) for default gau.
2. I went to manage allocations page and I couldn't quite allocate the amount correctly (because of this issue), so instead I clicked the new button on the payment allocations related list and did a -5 allocation to a misc gau. It shows up correctly as (15) default gau and (5) as misc gau. 
3. Go to the manage allocations page. It shows -5 for each, that is not correct. 
4. If I try to change misc as -15 on this page it matches the default fund and shows -15 for it as well (even though the payment is only -20 total.

We need to update the VF page to show the correct default GAU amount.

We need to make sure that the manage allocations page still works well for positive allocation amounts as well.

**Comment by lparrott** [comment]
**lurch: attach W-029630

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPNBQA2" target="_blank">W-029630</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.144 (Beta 11)
