### ISSUE TITLE
When Payment Amount is larger than the related Opportunity Amount, marking Payment as Paid is not auto-closing Opportunity

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3824]
Issue:
If the Amount of the Payment is higher than the Amount of the Opportunity, the Opty stage is not changed to a Closed/Won status when the Payment record is marked Paid. 

Steps to Repro:
1. Create an open stage Opportunity for $40. Notice the resulting Payment record for $40. 
2. Open Payment record and click Edit. 
3. Change Payment Amount to $42, and mark as Paid. Enter today's date as the Payment Date.
4. Go back to Opty and notice the stage of the Opty is still open, and has not been changed to Posted or any Closed/Won value.

Thanks to @bethbrains for catching/reporting this one.

**Comment by coriobriensfdo** [comment]
**lurch: Add

**Comment by coriobriensfdo** [comment]
And, it would be great to auto-update the Opty amount to the higher Payment Amount automatically to keep the Opty in sync with the Payment Amount.

Also, found this old Issue in the backlog that could potentially be addressed at the same time? https://github.com/SalesforceFoundation/Cumulus/issues/1794

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPk4QAE" target="_blank">W-029957</a>

**Comment by mpusto** [comment]
@coriobriensfdo The issue you reference seems like it would be the other way--from Opp to Payment. You are suggesting updating from Payment to Opp. I agree that if the total of Payments is larger than the Opportunity total, the Oppty should be Closed Won and updated to match the total of the Payments.

**Comment by lmeerkatz** [comment]
@pedrodalcol How do you handle payments on an opportunity that exceed the opportunity amount?

**Comment by mpusto** [comment]
@coriobriensfdo  You hit the nail on the head. It's hard to know a user's intent if the Opp amount is updated and there are multiple payments. We can't make that decision for them.

**Comment by mrbelvedere** [comment]
Included in beta release 3.157 (Beta 10)

**Comment by mrbelvedere** [comment]
Included in production release 3.157
