### ISSUE TITLE
Recurring Donation: Day of Month is not taking Date Established into account so Next Donation can be in the past

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#3829]
[Thread](https://powerofus.force.com/0D51E00004c0jSr)

If the Day of Month is set to a date that is less than the date in the month that the Recurring Donation is established, the Next Donation date is being set in the past. For example, an established date of 11/21/2018 with Day of Month = 2

![image](https://user-images.githubusercontent.com/4614343/48847226-07094180-ed6f-11e8-9ebb-d16c91a0d56a.png)

The Next Donation date should be 12/2/2018, not 11/2/2018

**Comment by mrbelvedere** [comment]
Included in beta release 3.147 (Beta 17)
