### ISSUE TITLE
Relationship Viewer Labels XSS Vulnerability

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#3843]
To prevent XSS, the Custom Labels on the Relationship Viewer should be properly escaped.

**Comment by jjbennett** [comment]
**lurch: attach W-027002

**Comment by jjbennett** [comment]
**lurch: attach W-025132

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fMMyAAM" target="_blank">W-027002</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 55)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
