### ISSUE TITLE
Household converter "Begin Conversion Process" button stuck greyed out

### ISSUE THREAD

**Issue by bourqui** [SalesforceFoundation/Cumulus#3847]
Hello!

After following the documentation for the household conversion process, running health check successfully, and generally trying everything I can to make sure we've covered our bases, and checking all checkboxes, I still have a greyed out "Begin Conversion Process" checkbox. Also having some strange formatting issues (see screenshot), not sure if that's related.

![screencapture-ncclf-full-npsp-cs19-visual-force-apex-conv_account_conversion-2018-11-30-14_03_11](https://user-images.githubusercontent.com/5061260/49317291-c0bb8d00-f4a8-11e8-8232-1da5af28d8de.png)

Eric Magnusson at Exponent Partners suggested I post here since it's a time sensitive issue. I really appreciate any help you can offer!

Related Power of Us Hub post: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D51E00004c1gOQ

Thanks
Martin

**Comment by coriobriensfdo** [comment]
Hi @bourqui We actually don't provide any support here on GitHub, so waiting on a response from the community in the Hub group is your best bet. I'll need to close this.
