### ISSUE TITLE
Customizable Rollup Settings Page Tooltips Should Be Wider

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3853]
**Issue:**
The tooltips (or help icons) on the Customizable Rollups Settings page are very narrow, causing the text to run on in a very long popup.
<img width="490" alt="screen shot 2018-12-03 at 3 11 06 pm" src="https://user-images.githubusercontent.com/37851761/49452854-cd84fd00-f796-11e8-9806-1db07923f837.png">

**Steps to Repro:**

1. Log into any org that has Customizable Rollups enabled. 
2. Click on NPSP Settings ->Donations ->Customizable Rollups.
3. Click on Configure Customizable Rollups (or enable them if not yet enabled).
4. Click on any existing rollup, then click Edit.
5. Hover over any of the help icons and notice the shape of the popup.

Per @jesslopez-sf and @randi274:
"It seems to be using ".slds-popover_small" to determine its width (there are medium and large styles as well for slds popovers/tooltips). Medium may be a better fit."
"I'd like to fix them and actually put in the SLDS base popovers. There was an issue with the popovers that caused me to create this manually, but I think the base icon is working fine now. Just changing the style to medium would be a faster change."

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQ1oQAE" target="_blank">W-030177</a>

**Comment by mpusto** [comment]
This was resolved at some point. I tested today and cannot reproduce.
