### ISSUE TITLE
Creating a new primary Affiliation is not changing prior Affiliation Status to Former or adding End Date value

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#3860]
[Case](https://org62.lightning.force.com/one/one.app#/sObject/5000M00000msIeGQAU/view)

Creating a new primary Organization Affiliation record on a Contact is not updating the existing primary Affiliation record to Former status and adding End Date value as documented.

**Steps to Repro:**
1. Navigate to a Contact Record. 
2. If not existing, create an Organization Affiliation record (Affiliation #1). Make Primary checkbox = True and Status = Current. Set Start to a date in the past and leave End Date empty.
3. Once created, notice the Primary Affiliation field is populated on the Contact with that Organization name (Affiliation #1).
4. Create a second Organization Affiliation on the Contact record, for a different Organization (Affiliation #2). Make Primary checkbox = True and Status = Current. Set Start date to today and leave End Date empty.
5. Once created, notice the Primary Affiliation field is populated on the Contact with that new Organization name as expected (Affiliation #2).
6. View Affiliation #1 record.

 **What is expected:** 
- Primary Checkbox = False
- Status = Former
- End Date = Today's date

**What is happening:**
- Primary Checkbox = False (as expected)
- Status = Current
- End Date = blank

Affiliation #2 (Current):
<img width="647" alt="screen shot 2018-12-06 at 12 05 41 pm" src="https://user-images.githubusercontent.com/37851761/49609086-6199c480-f94f-11e8-97d2-5965843a12f5.png">

Affiliation #1 (Former):
<img width="644" alt="screen shot 2018-12-06 at 12 06 07 pm" src="https://user-images.githubusercontent.com/37851761/49609104-6cecf000-f94f-11e8-8132-0bd81b51f6b2.png">

Documentation reference to changing both Status and End Date values:
![screen shot 2018-12-06 at 12 08 32 pm](https://user-images.githubusercontent.com/37851761/49609294-e97fce80-f94f-11e8-8002-162a642f9849.png)

**Comment by coriobriensfdo** [comment]
**Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQ78QAE" target="_blank">W-030243</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 53)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
