### ISSUE TITLE
Downloaded Relationship Starter pack, as a user - arrow to navigate to page 2 of Reciprocal Relationship settings broken, won't navigate

### ISSUE THREAD

**Issue by crownbl** [SalesforceFoundation/Cumulus#3866]
I was trying to update the relationship types on the Relationship Settings tab of the Relationship Starter pack and it won’t navigate to the second page of Reciprocal Relationship ‘types'.  I click the arrow and it shows that the browser is “thinking” but never flips to the other page. Any ideas of how to fix this?

**Comment by coriobriensfdo** [comment]
@crownbl We don't provide customer support here in GitHub. Can you post your issue in the Power of Us Hub, in the [Nonprofit Success Pack group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe)?

One thing to note when you post in the HUB is where you downloaded the app from, and what version it is.

**Comment by crownbl** [comment]
No, I’m not a Salesforce.org user. I have an Enterprise license. Any other avenues I can take to try to get an idea of why this issue is occurring? 


Britany Crown
365 Member Experience
C 303.917.6203
britany@collaborativegain.com <mailto:britany@collaborativegain.com>

CollaborativeGain.com <http://collaborativegain.com/>

**Comment by coriobriensfdo** [comment]
@crownbl Where did you download the package from, and what version is it? Normally the Recurring Donation app is only downloaded as one part of the full Nonprofit Success pack, which includes many packages.

**Comment by crownbl** [comment]
It’s the Relationship Start pack - not the Donation. 

Here’s where I got it: 
https://appexchange.salesforce.com/listingDetail?listingId=a0N30000003GLGPEA4

It’s Version 2.0.2

Britany Crown
365 Member Experience
C 303.917.6203
britany@collaborativegain.com <mailto:britany@collaborativegain.com>

CollaborativeGain.com <http://collaborativegain.com/>

**Comment by coriobriensfdo** [comment]
Sorry @crownbl, meant Relationship not Recurring Donation!

That link points to an old listing and you've got a very old version in 2.0.2. The apps are no longer available for individual download, and the current version of the Relationships package is 3.8. 

You can install the full NPSP from here if you like, which gives you access to the Relationship object and features.

https://powerofus.force.com/articles/Resource/NPSP-Install

**Comment by crownbl** [comment]
Thank you for your help! I’ll check it out! 

Britany Crown
365 Member Experience
C 303.917.6203
britany@collaborativegain.com <mailto:britany@collaborativegain.com>

CollaborativeGain.com <http://collaborativegain.com/>

**Comment by judisohn** [comment]
If it helps, what you're describing was a known issue with Relationships 2x that was fixed in the latest release. However, you can't upgrade just that one package.
