### ISSUE TITLE
Contact person E-mail field is set read-only but still editable

### ISSUE THREAD

**Issue by RaphBode** [SalesforceFoundation/Cumulus#3869]
I put the E-mail field on the page layout and on all the profiles, permission set etc on Read-Only but it still appears on the screen and is editable. There is no label, but just the input area. 

The E-mail field is under the field 'Telefoon' It looks like the input foor 'Telefoon' but it isn't. 
![schermafbeelding 2018-12-11 om 17 02 33](https://user-images.githubusercontent.com/45795761/49812857-a023ea80-fd66-11e8-9e76-5057d60bfe78.png)

**Comment by coriobriensfdo** [comment]
@RaphBode We don't provide support here in GitHub. Can you post your question in the Power of Us Hub instead? I'd recommend the [System Administrators](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CkCM) group.

**Comment by RaphBode** [comment]
It's NOT a support question is a bug!!!


Raph.


________________________________
Van: coriobriensfdo <notifications@github.com>
Verzonden: dinsdag 11 december 2018 17:19:53
Aan: SalesforceFoundation/Cumulus
CC: Raph. Bode; Mention
Onderwerp: Re: [SalesforceFoundation/Cumulus] Contact person E-mail field is set read-only but still editable (#3869)


Closed #3869<https://github.com/SalesforceFoundation/Cumulus/issues/3869>.

**Comment by judisohn** [comment]
@RaphBode those with the System Administrator profile can edit read only fields.

https://help.salesforce.com/articleView?id=000225548&type=1

Furthermore, there is nothing in NPSP that would control or influence this Salesforce platform behavior.

**Comment by RaphBode** [comment]
I know this, I?m not a newby.
But the screen I showed in my mail is a end user screen! And all the permission setting and security settings are double checked!

But, oke I?ll create a case for sfdc in my partner portal!



Op di 11 dec. 2018 om 21:33 schreef Judi Sohn <notifications@github.com>

@RaphBode<https://github.com/RaphBode> those with the System Administrator profile can edit read only fields.

https://help.salesforce.com/articleView?id=000225548&type=1

Furthermore, there is nothing in NPSP that would control or influence this Salesforce platform behavior.

?
