### ISSUE TITLE
Allow Contact Merge through Apex Api

### ISSUE THREAD

**Issue by stenebenau** [SalesforceFoundation/Cumulus#3892]
Hi, 

As a developer of another Salesforce managed package it is sometimes wise to leverage existing NPSP code to accomplish things. 

We currently have the merge logic of NPSP copied into our own merge logic. However, it would be easier for both our combined customers and ourselves to just leverage the Merge logic in the NPSP package. 

My suggestion is to create a global Apex Api on top of the CON_ContactMerge class. So any external developer can merge contact records. 

Ideally via the new Callable interface so there are no code dependencies.  https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_interface_System_Callable.htm 

I'm happy to implement this feature myself. 

Thanks,

Sten Ebenau
Duplicate Check for Salesforce

**Comment by judisohn** [comment]
Hi @stenebenau - We use Github issues for active bug tracking, so I'm closing this as an issue for now.  I've created [this Idea on the Power of Us Hub](https://powerofus.force.com/hub-ideas/1458) on your behalf (which I know you can't see). I'll also mention this to our ISV partner team so they can be in touch. Thanks!

**Comment by stenebenau** [comment]
Hi @judisohn - Thanks. Is there any indication whatsoever? This kind of important to us and a lot of our combined customers and I'm willing to invest some time to get this implemented.
