### ISSUE TITLE
Customizable Rollups: Lingering References to Previous Fields After Modification

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3945]
When User Defined Rollups are converted to Customizable Rollups, we add their Opportunity field to multiple fields on the Rollup record. If an admin modifies this rollup to use another field via the Customizable Rollups interface (for example, a non-formula field), that field is updated on the Custom Metadata Type record, but may still be referenced on other fields on the Custom Metadata Type. As a result, these fields are being pulled into SOQL queries and slowing down calculations. 

The Work Item will contain a link to my full investigation. For one org, I manually edited the affected CMTs and there was a noticeable performance increase in the scheduled jobs because unnecessary formula fields were no longer being queried. Rollups were also being grouped by Filter Groups much more efficiently (logs attached to Work Item).

**STEPS TO REPEAT**

### _**Setup:**_

1. Create new fields on Opportunity:
    1. Name: Gift Amount if Three Years Ago
        1. Data Type: Formula
        2. Formula Return Type: Currency (2 decimal places)
        3. Formula:  `IF ( YEAR (CloseDate) = ( YEAR (TODAY()) - 3 ), Amount, NULL)` 
    2. Name: Number of Gifts If Three Years Ago
        1. Data Type: Formula
        2. Formula Return Type: Number (0 decimal places)
        3. Formula: `IF ( YEAR (CloseDate) = ( YEAR (TODAY()) - 3 ), 1, NULL)`
2. Create new fields on Contact:
    1. Name: Gift Amount Three Years Ago
        1. Data Type: Currency
        2. Length: 16
        3. Decimal Places: 2
    2. Name: Number of Gifts Three Years Ago
        1. Data Type: Number
        2. Length: 18
        3. Decimal Places: 9
3. Create User Defined Rollups using these formula fields (do not enable Customizable Rollups yet!). 
    1. Go to NPSP Settings → Donations → User Defined Rollups
    2. Click New User Defined Rollup
        1. Opportunity Field: Gift Amount if Three Years Ago
        2. Rollup Operation: SUM
        3. Target Object: Contact
        4. Target Field: Gift Amount Three Years Ago
        5. Create Rollup
    3. Click New User Defined Rollup
        1. Opportunity Field: Number of Gifts If Three Years Ago
        2. Rollup Operation: SUM
        3. Target Object: Contact
        4. Target Field: Number of Gifts Three Years Ago
        5. Create Rollup

### **_Enable Customizable Rollups and View the converted User Defined Rollups._**

1. Enable Customizable Rollups in NPSP Settings → Donations → Customizable Rollups
2. Click the Configure Customizable Rollups button.

Click the Contact: Gift Amount Three Years Ago Rollup. It has been converted with the following values:
    1. Target Object: Contact
    2. Target Field: Gift Amount Three Years Ago
    3. Operation: Sum
    4. Time Frame: All Time
    5. Rollup Type: Opportunity → Contact (Hard Credit)
    6. Filter Group: Opps: Won (HC)
    7. Amount Field: Gift Amount If Three Years Ago

<img width="927" alt="pre change gift amount three" src="https://user-images.githubusercontent.com/29731456/50519981-a23ab880-0a8b-11e9-8f1c-576281766411.png">

The Custom MetaData Type for that record looks like this (in Setup → Custom Metadata Types → Manage Records (next to Rollups). Note that the Field to Roll Up and Amount Fields both point to the Gift Amount If Three Years Ago field.

<img width="984" alt="pre gift amount cmt" src="https://user-images.githubusercontent.com/29731456/50519984-a6ff6c80-0a8b-11e9-9763-34e728e52d39.png">

Click the Contact: Number of Gifts Three Years Ago Rollup. It has been converted with the following values:
    1. Target Object: Contact
    2. Target Field: Number of Gifts Three Years Ago
    3. Operation: Sum
    4. Time Frame: All Time
    5. Rollup Type: Opportunity → Contact (Hard Credit)
    6. Filter Group: Opps: Won (HC)
    7. Amount Field: Number of Gifts If Three Years Ago

<img width="939" alt="pre change num gifts three" src="https://user-images.githubusercontent.com/29731456/50519988-ad8de400-0a8b-11e9-8f8a-c9184a21a0ff.png">

The Custom MetaData Type for that record looks like this (in Setup → Custom Metadata Types → Manage Records (next to Rollups). Note that the Field to Roll Up and Amount Fields all point to the Number of Gifts If Three Years Ago field.

<img width="1001" alt="pre num gifts cmt" src="https://user-images.githubusercontent.com/29731456/50519993-b979a600-0a8b-11e9-8968-a9963ccfc634.png">

### **_Both of these rollups can be edited to use native Customizable Rollups functionality. Make the following edits and see what happens to the Custom Metadata Type records._**

1. Go to NPSP Settings → Donations → Customizable Rollups. Click the Configure Customizable Rollups button.

Edit the Contact: Gift Amount Three Years Ago Rollup and change it to the following values:
    1. Target Object: Contact
    2. Target Field: Gift Amount Three Years Ago
    3. Operation: Sum
    4. Time Frame: Years Ago
    5. Years Ago: 3 Years Ago
    6. Rollup Type: Opportunity → Contact (Hard Credit)
    7. Filter Group: Opps: Won (HC)
    8. Date Field: Close Date
    9. Amount Field: Opportunity: Amount
    10. Save (now there are no references to the formula field on the Opportunity).

<img width="935" alt="post crlp gift amount" src="https://user-images.githubusercontent.com/29731456/50520019-d615de00-0a8b-11e9-8d92-55e316db9a45.png">

Changes were reflected on the Custom Metadata Type record, but the reference to the formula field remained in the Field to Roll Up field. (The Amount field was successfully changed).

<img width="975" alt="post cmt gift amount" src="https://user-images.githubusercontent.com/29731456/50520020-dc0bbf00-0a8b-11e9-9032-f6c13af5d123.png">

Edit the Contact: Number of Gifts Three Years Ago Rollup and change it to the following values:
    1. Target Object: Contact
    2. Target Field: Number of Gifts Three Years Ago
    3. Operation: Count
    4. Time Frame: Years Ago
    5. Years Ago: 3 Years Ago
    6. Rollup Type: Opportunity → Contact (Hard Credit)
    7. Filter Group: Opps: Won (HC)
    8. Date Field: Opportunity: Close Date
    9. Save (now there are no references to the formula field on the Opportunity).

<img width="949" alt="post num crlp" src="https://user-images.githubusercontent.com/29731456/50520026-e8901780-0a8b-11e9-8e40-929c97716f5b.png">

Changes were reflected on the Custom Metadata Type record, but the reference to the formula field remained in both the Field to Roll Up and Amount fields:
<img width="977" alt="post cmt num gifts" src="https://user-images.githubusercontent.com/29731456/50520036-f9d92400-0a8b-11e9-9313-fd0dc6efe280.png">

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQSaQAM" target="_blank">W-030505</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.151 (Beta 14)

**Comment by mrbelvedere** [comment]
Included in production release 3.151
