### ISSUE TITLE
Cascade delete Payment Allocations when related Payment is deleted

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/Cumulus#3949]
When a Payment record is deleted its related Allocations records become orphaned. This can cause incorrect GAU rollup calculations.

**Comment by lparrott** [comment]
**lurch: attach W-027724

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fN0UAAU" target="_blank">W-027724</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.145 (Beta 32)

**Comment by mrbelvedere** [comment]
Included in production release 3.145
