### ISSUE TITLE
Add Configurable Batch Size for Levels Batch Jobs

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3977]
Most of our NPSP batch jobs have configurable batch sizes. It would be great to have one for our Levels jobs. Currently, the Levels Scheduler (LVL_LevelAssign_SCHED) executes batches of LVL_LevelAssign_BATCH for each object where Levels have been configured. Because we don't specify a batch size (and don't provide a configurable option), batches are running with a batch size of 200. As we then cycle through every single record on each object 200 records at a time, it would potentially be more performant to allow admins to configure batch sizes up to 2000.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQelQAE" target="_blank">W-030656</a>

**Comment by jesslopez-sf** [comment]
(Duplicate of another Work Item) -- This is being addressed in PR #3992
