### ISSUE TITLE
Search bar in Manage Household button is not working 

### ISSUE THREAD

**Issue by preeti-lightful** [SalesforceFoundation/Cumulus#3978]
Issue on:
Household(account) I have a button called 'Manage Household' and it has a search bar to search Contacts, which is not working.

NPSP version :
Nonprofit Success Pack | Salesforce.org | 3.144

Error statement:
getting an error in the log which is 
"This page has an error. You might just need to refresh it. Error in $A.getCallback() [] Callback failed: apex://npsp.HH_AutoCompleteDataProvider_LCTRL/ACTION$queryObjects Failing descriptor: {npsp:autocomplete}"

Snapshot:
![image](https://user-images.githubusercontent.com/32099339/50898263-8974c000-1406-11e9-89ea-4288c4f5fc7f.png)

Looking forward to hear as soon as possible.

cheers,
Preeti Agarwal

**Comment by force2b** [comment]
Thank you for the heads up on this. The root cause is a change (or possible bug) in Spring '19. We found this as well while doing our pre-(Salesforce) release testing. The work item is already in our sprint and should be available in Sandboxes in a couple of weeks.

**Comment by force2b** [comment]
**lurch: attach W-030566

**Comment by preeti-lightful** [comment]
Thanks Michael Smith, This will help.

**Comment by mrbelvedere** [comment]
Included in beta release 3.147 (Beta 13)

**Comment by mrbelvedere** [comment]
Included in production release 3.147

**Comment by rachel-clearmind-test** [comment]
Is anyone else still experiencing this bug? I am seeing it today. Is there anything I can do to fix this?

**Comment by rachel-cmc** [comment]
Is anyone else still experiencing this bug? I am seeing it today. Is there anything I can do to fix this?

**Comment by jamesbsfdc** [comment]
Hi Rachel, we don't offer support via GitHub issues. 

Would you mind posting about this on the Hub? Feel free to @message me

**Comment by rachel-cmc** [comment]
Hi James, thanks for getting back to me.... I actually found the issue, but I appreciate you directing me where to do. If you want me to delete my comments, let me know. Thanks!

**Comment by kirstenblaze** [comment]
@rachel-cmc could you please tell me what the issue was that you found? I am having this issue today. Thank you!
