### ISSUE TITLE
Map Opportunity Stages to Committed and Finalized

### ISSUE THREAD

**Issue by jbrandolinisf** [SalesforceFoundation/Cumulus#3987]
* *feature*

* **What is the current behavior?**

Do not know what Stages mean an Opportunity is Committed, and What Stages mean an Opportunity is finalized.  This varies customer to customer.

* **What is the expected behavior?**

That, for a given opportunity, we can determine if it's Opportunity Stage is Committed or Finalized depending on Custom Settings.

* **What is the motivation / use case for changing the behavior?**

Abacus needs to know for accounting purposes whether an Opportunity is Uncommitted (meaning the cannot count it as revenue yet), Committed (meaning they should count it as revenue), or Finalized (meaning no further changes are needed/expected with this Opportunity).

* **Acceptance Criteria**

  - **Given**: an Opportunity Stage, and Given populated Custom Settings Mapping Committed Stages and Finalized Stages
  - **When**: I call a Utility class method and Pass it an Opportunity Stage 
  - **Then**: I will receive back a value of Committed if the Opportunity Stage is one of the ones defined as a Committed Stage, a value of Finalized if the Opportunity Stage is one of the ones defined as a Finalized Stage, and Uncommitted Otherwise

* **Keyboard Acceptance Criteria**

  N/A (API Only)

* **Screenreader Acceptance Criteria**

  N/A (API Only)

**Comment by jbrandolinisf** [comment]
**lurch: attach W-030114

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPwjQAE" target="_blank">W-030114</a>
