### ISSUE TITLE
Customizable Rollups: Years Ago Rollup Fields Are Not Accurate When Rollup Does Not Use Opps: Won (HC) Filter Group

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#3988]
When a Customizable Rollup uses the Years Ago Time Frame, values are incorrect when Filter Groups do not explicitly include Won Opportunities using the Opps: Won (HC) Filter Group. The Days Back filter does work as expected (for Won and Open Opportunities). Please see the Steps to Repeat / Tests below:

> 1.  Test 1 shows incorrect values when no Filter Group is used.
> 2. Test 2 shows correct values because we associate the rollups to the Opps: Won Filter Group
> 3. Test 3 shows incorrect values because we associate the rollups with the Opps: Open Filter Group
> 4. Test 4 shows correct values when rollups use Days Ago with no Filter Group.
> 5. Test 5 shows incorrect values when rollups use Years Ago with a Filter Group filtering to a Stage that has a type of Closed/Won.
> 6. Test 6 shows incorrect values when rollups use Years Ago with a Filter Group that matches the Opps: Won (HC) filter group exactly.

### Steps to Repeat

1. Create 3 fields on the Contact object
    1. Total All Time (Type = Number)
    2. Total This Year (Type = Number)
    3. Total Last Year (Type = Number)

2. Enable Customizable Rollups in NPSP Settings → Donations → Customizable Rollups
3. Create a Contact (First Name = Jess; Last Name = Lopez)
4. Create 2 Opportunities
    1. Opportunity 1 (this year)
        1. Name = This Year; Account Name = Lopez Household; Amount = 1000; Close Date = 1/1/2019; Stage = Closed Won
    2. Opportunity 2 (last year)
        1. Name = Last Year; Account Name = Lopez Household; Amount = 500; Close Date = 1/1/2018; Stage = Closed Won

### TESTS

***Test 1: Incorrect Values using Hard Credit, Years Ago (Calendar), No Filter Group***
This results in incorrect values because the rollup could include non-Won Opportunities

1. Create 3 Customizable Rollups based on Close Date and Calendar Year (No Filter Group).
    1. Rollup 1
        1. Target Object = Contact
        2. Target Field = Total All Time
        3. Operation = Count
        4. Time Frame = All Time
        5. Rollup Type = Opportunity → Contact (Hard Credit)
        6. Filter Group: No Filter Group (Include All Records)
    2. Rollup 2
        1. Target Object = Contact
        2. Target Field = Total This Year
        3. Operation = Count
        4. Time Frame = Years Ago
        5. Years Ago = This Year
        6. Rollup Type = Opportunity → Contact (Hard Credit)
        7. Filter Group: No Filter Group (Include All Records)
        8. Date Field = Close Date
    3. Rollup 3
        1. Target Object = Contact
        2. Target Field = Total Last Year
        3. Operation = Count
        4. Time Frame = Years Ago
        5. Years Ago = Last Year
        6. Rollup Type = Opportunity → Contact (Hard Credit)
        7. Filter Group: No Filter Group (Include All Records)
        8. Date Field = Close Date
2. Go to Contact record for Jess Lopez. Clear out values in Total This Year, Total Last Year, and Total All Time fields. Click the Recalculate Rollups button.
3. Confirm the following values
    1. Total All Time = 2
    2. Total This Year = 0 (should be 1)
    3. Total Last Year = 0 (should be 1)
4. But, our standard NPSP fields hooked to a filter group work correctly 
    1. Number of Gifts This Year = 1
    2. Number of Gifts Last Year = 1

***Test 2: Correct Values using Hard Credit, Years Ago (Calendar), Opps Won (HC) Filter Group***
Here we explicitly only include “Won” Opportunities and it works as expected.

1. Modify the 3 Rollups created in Test 1 so that they are associated with the Opps Won (HC) Filter Group
2. Clear out the Total All Time, Total This Year, and Total Last Year fields on the Jess Lopez Contact record.
3. Click the Recalculate Rollups button.
4. Confirm the following correct values:
    1. Total All Time = 2
    2. Total This Year = 1
    3. Total Last Year =1

***Test 3: Incorrect Values using Hard Credit, Years Ago (Calendar), Opps:Open Filter Group***
This test fails because we explicitly do not include Won Opportunities, based on our Filter Group.

1. Modify the 3 Rollups created in Test 1 so that they are associated with the Opps Open Filter Group
2. Modify the stage of both Opportunities to “Prospecting”
3. Clear out the Total All Time, Total This Year, and Total Last Year fields on the Jess Lopez Contact record.
4. Confirm the following values
    1. Total All Time = 2
    2. Total This Year = 0 (should be 1)
    3. Total Last Year = 0 (should be 1)

***Test 4: Correct Values using Hard Credit, DAYS Ago (Calendar), No Filter Group***
This test confirms that the Days Ago filter works as expected, regardless of Won Opportunities. 
(Note: Field Names aren't super relevant anymore since we're rolling up data as of X days ago)

1. Modify the 3 Rollups created in Test 1:
    1. Contact: Total All Time
        1. Filter Group = No Filter Group (Include All Records)
    2. Contact: Total Last Year
        1. Filter Group = No Filter Group (Include All Records)
        2. Time Frame = Days Back
        3. Days Back = 400
    3. Contact: Total This Year
        1. Filter Group = No Filter Group (Include All Records)
        2. Time Frame = Days Back
        3. Days Back = 11
2. Clear out the Total All Time, Total This Year, and Total Last Year fields on the Jess Lopez Contact record.
3. Confirm the following values
    1. Total All Time = 2
    2. Total This Year =1
    3. Total Last Year = 2

***Test 5: *Incorrect Values using Hard Credit, Years Ago (Calendar), Filter Group Using Filter Rule for Stage with a Type of Closed/Won****

1. Create a new Opportunity Stage (Name = “Completed”; Type = Closed/Won; Probability = 100)
2. Create a new  Customizable Rollups Filter Group (Name = Completed Opps) with the following Filter Rule:
    1. Object = Opportunity
    2. Field = Stage
    3. Operator = Equals
    4. Value = Completed
3. Modify the 3 Rollups created in Test 1:
    1. Contact: Total All Time
        1. Filter Group = Completed Opps
    2. Contact: Total Last Year
        1. Filter Group = Completed Opps
        2. Time Frame = Years Ago
        3. Days Back = Last Year
    3. Contact: Total This Year
        1. Filter Group = No Filter Group (Include All Records)
        2. Time Frame = Days Back
        3. Days Back = 11
4. Modify the Stage for the 2 Opportunities to be “Completed”
5. Clear out the Total All Time, Total This Year, and Total Last Year fields on the Jess Lopez Contact record.
6. Click the Recalculate Rollups button.
7. Confirm the following incorrect values
    1. Total All Time = 2
    2. Total This Year = 0 (should be 1)
    3. Total Last Year = 0 (should be 1)

***Test 6: *Incorrect Values using Hard Credit, Years Ago (Calendar), Filter Group with Filter Rules Matching Opps: Won (HC) Filter Group****
This one has me stumped. I would expect this one to work because it mirrors that Filter Group.

1. Edit the Completed Opps Filter Group
    1. Remove the previous Filter Rule
    2. Add the Following Filter Rules
        1. Object = Opportunity
        2. Field = Amount
        3. Operator = Not Equals
        4. Value = <blank>
        5. Save
        6. Object = Opportunity
        7. Field = Won
        8. Operator = Equals
        9. Value = true
2. Clear out the Total All Time, Total This Year, and Total Last Year fields on the Jess Lopez Contact record.
3. Click the Recalculate Rollups button.
4. Confirm the following incorrect values
    1. Total All Time = 2
    2. Total This Year = 0 (should be 1)
    3. Total Last Year = 0 (should be 1)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQhaQAE" target="_blank">W-030691</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
