### ISSUE TITLE
Merging Contacts(Old) object From NPSP pack

### ISSUE THREAD

**Issue by krishnateqforce** [SalesforceFoundation/Cumulus#4001]
I have Created two contact records with same account then one is customer portal User and Other one is Non customer portal user.
so, I have installed NPSP pack and there I am merging the Duplicate Contact records. When I am Merging the above those contacts I am getting this error.

Error: Update failed. First exception on row 0 with id 003d0000038BKQKAA4; first error: FIELD_INTEGRITY_EXCEPTION, A portal user's contact record must include an account. Furthermore, the owner of the account must be associated with a role.: [AccountId].

could you please suggest me how can i avoid that error or can you please tell me on which criteria i need to create contact records.

Thanks.

**Comment by coriobriensfdo** [comment]
@krishnateqforce  We don't provide support here in GitHub. Instead, please post your question and the above details to the Power of Us Hub group for NPSP. [Here is the link. ](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe)
