### ISSUE TITLE
2 contact role records created for primary contact when opportunity created on primary contact

### ISSUE THREAD

**Issue by preeti-lightful** [SalesforceFoundation/Cumulus#4003]
Hi Amazing Team,

I am not sure what's happening but this the issue I am facing.

2 contact role records created for primary contact of a HouseHold Account when opportunity created on primary contact.

Using Lightning UI
attached screenshot.

1. contact roles on the opportunity created on primary contact.
2. NPSP setting in Org.
3. NPSP setting in Org.

![npsp setting 2](https://user-images.githubusercontent.com/32099339/51267850-9b320680-19b6-11e9-8ad4-e45b81a053d9.png)
![npsp setting 1](https://user-images.githubusercontent.com/32099339/51267851-9b320680-19b6-11e9-8da9-82f0084a1480.png)
![2 contact roles ex](https://user-images.githubusercontent.com/32099339/51267852-9bca9d00-19b6-11e9-89cc-cf2d7e3a2464.png)

Looking forward to hearing from you soon.

Cheers,
Preeti

**Comment by coriobriensfdo** [comment]
@preeti-lightful  We don't provide support here in GitHub. Instead, please post your question and the above details to the Power of Us Hub group for NPSP. [Here is the link.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe)

That said, for assistance with the creation of duplicate primary contact roles when using the standard New button on the Contact record Opportunity related list, please create a Lightning Action using the instructions in this doc: https://powerofus.force.com/articles/Resource/NPSP-LEX-Known-Issues#!#ariaid-title2

To clean up any existing double OCR's, you can run the batch called "Remove Duplicate Primary OCRs" within the Bulk Data Processes area in NPSP Settings.

**Comment by huuse** [comment]
Hi, I have the same Issue. Can you please provide new links to the related discussion?

**Comment by jamesbsfdc** [comment]
@huuse We don't provide assistance via GitHub. If you want support please log a support case or post in the Nonprofit Success Pack group in the Trailblazer Community

https://help.salesforce.com/s/articleView?id=sfdo.SFDO_How_to_Create_a_Tech_Support_Case.htm&type=5

Thanks
