### ISSUE TITLE
Customizable Rollups Soft Credit Queries Pull All OCRs and Partial Soft Credits vs. for Single Entity

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4014]
When our Customizable Rollups run on soft credits, the [CRLP_Batch_Base](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/CRLP_Batch_Base.cls#L287-L289) class pulls all OCRs and Partial Soft Credits for a list of Opportunity Ids vs. just for the related entity Ids. This is happening for both single Contacts/Accounts using the Recalculate Rollups button and all Contacts/Accounts using the batch jobs. 

**Real World Example:**
Donor One gives monthly through a workplace giving program. There is an Opportunity for each monthly donation (Account = the workplace giving Account) and hundreds of OCRs/Partial Soft Credits for each donor on each Opportunity. When we calculate Donor One's Soft Credits, we find all her Opportunities and then all of her Opportunities' OCRs and Partial Soft Credits, rather than just hers.

This results in the following errors:
1. Inline query has too many rows for direct assignment, use FOR loop
2. First error: npsp:Too many query rows: 50001

Stacktrace available at the time of saving the record - 
`Class.npsp.CRLP_Batch_Base.buildPartialSoftCreditRecordsFromOCRs: line 290, column 1 Class.npsp.CRLP_Batch_Base_Skew.execute: line 289, column 1`

This is the line of code that @force2b pointed as the culprit, in [CRLP_Batch_Base (Lines 287-289)](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/CRLP_Batch_Base.cls#L287-L289): 
`    String oppQuery = CRLP_Query_SEL.buildDetailObjectQueryForRollup(Opportunity.SObjectType,
                new List<SObjectType>{ OpportunityContactRole.SObjectType, Partial_Soft_Credit__c.SObjectType }) +
                ' WHERE Id IN :oppIds';`

**_Which then looks like this:_**
`SELECT Id,IsWon,Amount,RecordTypeId,RecordType.DeveloperName,IsClosed,CloseDate,CampaignId,npe01__Member_Level__c,npe01__Membership_Origin__c,npe01__Membership_End_Date__c,npe01__Membership_Start_Date__c,AccountId,npsp__Primary_Contact__c,npe03__Recurring_Donation__c, (SELECT Id,ContactId,Contact.AccountId,OpportunityId,Role FROM OpportunityContactRoles), (SELECT Id,npsp__Role_Name__c,npsp__Amount__c,npsp__Opportunity__c,npsp__Contact__c,npsp__Contact__r.AccountId FROM npsp__Partial_Soft_Credits__r), Account.npe01__SYSTEMIsIndividual__c FROM Opportunity WHERE Id IN :oppIds
`

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQwLQAU" target="_blank">W-030871</a>

**Comment by mrbelvedere** [comment]
Included in production release 3.148
