### ISSUE TITLE
Opportunity Payment writeoff page is not taking existing written off payments into consideration

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#4036]
This was raised by the GEM QA team

**Issue:** If Payment(s) are written off by checking the Written Off box, the Write Off Payments VF page behaves and displays information incorrectly.

**Steps to Repeat:** 

1. Create Open Opportunity for $300
2. Schedule for 6 installments, mark the first two installments as Paid
3. Edit Payment 3 and check Written Off. Save.
4. Now click Write Off Payments (assuming at a later date, the remaining payments are to be written off)

**Expected:**

VF page should display 'You are preparing to write off 3 Payment(s) totaling $150.00' as one payment has previously been written off.

**Actual:**

![image](https://user-images.githubusercontent.com/4614343/52150889-50afbb80-263f-11e9-9261-22cd3c987568.png)

5. Click Write Off Payments button

**Expected:**

Total Amount written off should be $200 ($50 previous plus $150 just written off)

**Actual:**

Previous written off payment is deleted.

![image](https://user-images.githubusercontent.com/4614343/52151036-ba2fca00-263f-11e9-9db2-dd8ebc323091.png)

As a result, Roll Up Summary fields not reflecting correct values.

![image](https://user-images.githubusercontent.com/4614343/52151083-e1869700-263f-11e9-8845-4d55c7b8ecc6.png)

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fRDgQAM" target="_blank">W-031086</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.152 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release 3.152
