### ISSUE TITLE
Contact Merge does not use Customizable Rollups for Account post-merge rollup fixing

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/Cumulus#4071]
When a contact is merged using the NPSP Contact Merge tab, the trigger calls a method to fixup the account which includes a call to rollup on the accounts, that method is hard-coded to call the legacy rollups engine even if Customizable Rollups is enabled. Similar to the contact rollup, we should check to see if customizable rollups are enabled and call the correct rollup method.

**Comment by jjbennett** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll0VQAS" target="_blank">W-031429</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.151 (Beta 15)

**Comment by mrbelvedere** [comment]
Included in production release 3.151
