### ISSUE TITLE
Opportunity Naming Batch Hits 50 Million Row QueryLocator Limit

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4087]
The OPP_OpportunityNaming_BATCH currently runs for all Opportunities, so if an org has more than 50 million Opportunities, they will hit the governor limit.

![50 million row error](https://user-images.githubusercontent.com/29731456/53652456-8fb93880-3c0e-11e9-8cd6-8fea9ec3c436.jpg)

This is not a nightly scheduled job, but it is one that a customer can schedule. Requesting that we implement batch chunking for this job.

**Comment by jesslopez-sf** [comment]
**Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlEDQA0" target="_blank">W-031598</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.150 (Beta 26)

**Comment by mrbelvedere** [comment]
Included in production release 3.150
