### ISSUE TITLE
Manage Allocations: If a new Allocation entry is added between other entries, the values are saved incorrectly

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#4101]
_Reference case 21751108_

**Issue:** The Manage Allocations page is overwriting with incorrect data if a new row is not added at the bottom.

**Steps to Repeat:**

1. Org with default Allocation settings (no default)
2. Create 4 GAU records (A, B, C, D)
3. Create an Opportunity - does not matter Account, Date or Stage. Pick any.
4. Add 3 GAU Allocations using Manage Allocations screen for A, B, C - does not matter whether Amount or Percentage is selected
5. Save and confirm the 3 Allocations are created on the Opportunity related List
6. Manage Allocations again, and making sure to click 'Add Row' on the bottom row, add a 4th entry for GAU D

![image](https://user-images.githubusercontent.com/4614343/53909217-33478600-401f-11e9-9fbd-2197cf6faee7.png)

7. Save and Confirm that the 4 Allocations are added correctly
8. Repeat steps 3-5 on a different Opportunity
9. Now click 'Add Row' below the first entry instead of the last. Again, select GAU D

![image](https://user-images.githubusercontent.com/4614343/53909299-67bb4200-401f-11e9-8ba2-945fa0065201.png)

**Expected behavior:**

On save, you should see the same 4 entries as when added from the bottom.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/4614343/53909435-ad780a80-401f-11e9-8c51-3d560c5d2162.png)

The second entered Allocation is replaced with the 3rd GAU and the new GAU is written for the final row instead.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlODQA0" target="_blank">W-031724</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.150 (Beta 25)
