### ISSUE TITLE
SFDC login leads to "Welcome to SFDC/NPSP" screen with no nav

### ISSUE THREAD

**Issue by bradstruss** [SalesforceFoundation/Cumulus#4114]
On occasion when I log into an NPSP client instance I get the "Welcome to Salesforce and the Nonprofit Success Pack" getting started page with NO navigation at the top of the screen. The only way to access the org is to use urls from my browser history to go to a different page in the org. I don't have repo steps as it seems to come and go.

Browser is Chrome (Version 72.0.3626.121) on a Mac (Mojave 10.14).

I've only experienced this over the past 2-3 weeks. Never before.

![image](https://user-images.githubusercontent.com/1907660/54217039-1b9d5100-44a8-11e9-8b28-993ca9c9b43a.png)

**Comment by coriobriensfdo** [comment]
Hi @bradstruss, we don't provide this type of support here in GitHub. Can you post to the Hub instead? The Open Source partner group would be best for this issue I think. We can help investigate from there and will create a GitHub issue if one is needed. 

Thanks!

**Comment by bradstruss** [comment]
Hi Cori, I'm not looking for support, just reporting an issue. It sounds like the "New Issue" isn't for external folks though. Yes, I'll try to post to Hub about this later today.

**Comment by coriobriensfdo** [comment]
@bradstruss  great, thank you! 
The 'New Issue" is sometimes used by external members of the community, but unless it's a proven bug in the code, we'll generally close it and ask that it be discussed in the Hub first. Often what initially looks like a bug in the package is actually an issue the customer org. When/if it's determined there is an actual bug, we'll create the Issue here in GitHub so that we can include all the details the Engineers need like Steps to repo, workarounds, etc.

**Comment by judisohn** [comment]
@bradstruss So you know, this is a known issue that's out of our control when you login as another user and they're using the old Nonprofit CRM Lightning tab. To get out of it, highlight the address after domain.my.salesforce.com/ in your URL and delete and then you should land on the standard Home page.

**Comment by davidchengIC** [comment]
@judisohn Is there a way to force-change all users away from the old Nonprofit CRM Lightning tab and force a new default tab?

**Comment by judisohn** [comment]
@davidchengIC Good question. I just hit this same issue this morning with V4S when logging in as a user. Good ole Visualforce.

What happens if you go to App Manager, edit it, and remove it from all the Profiles?

Or were you asking if there was a way that Salesforce could do it? If so, likely not.
