### ISSUE TITLE
UTIL_OrgTelemetry_SObject_BATCH Hits 50 Million QueryLocator Limit

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4119]
Orgs with more than 50 million Opportunities associated with open-ended Recurring Donations will see an error when the UTIL_OrgTelemetry_SObject_BATCH runs its query on Lines 78-79.

`First error: npsp:Too many query locator rows: 50000001`

**Comment by jesslopez-sf** [comment]
**Lurch: Add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlcUQAS" target="_blank">W-031902</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.151 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.151
