### ISSUE TITLE
NPSP Trigger Exception when calling merge from batch job

### ISSUE THREAD

**Issue by daveb-501commons** [SalesforceFoundation/Cumulus#4134]
Have the latest NPSP Version: 3.149 installed

Built a Mass Merging process in Salesforce, using DML Database.Merge(masterAccount, duplicateAccounts, false), which is working fine until I added support to Batch process the merging with the Flex Queue Jobs.

When calling the same merge code from a batch thread, using Database.executeBatch, with the exact same sample accounts getting Exceptions in NPSP code.

Merge attempt on 2 Household Accounts with Name, Email, and Birthdate populated

VARIABLE_ASSIGNMENT|[55]|err|"Error [statusCode=DELETE_FAILED, code=[xmlrpc=1209, statusCode=DELETE_FAILED, exceptionCode=null, scope=PublicApi, http=400], message=npsp.TDTM_Account: execution of AfterDelete\n\ncaused by: System.DmlException: Update failed. First exception on row 0 with id 0012g000001nlCjAAI; first error: SELF_REFERENCE_FROM_TRIGGER, Object 0012g000001nlCjAAI is currently in a merge operation, therefore a trigger can not update it.: []\n\n(npsp)\n\n\n\n\n\n\n\n, fields=null]"|0x578018ed
Merge Exception: npsp.TDTM_Account: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id 0012g000001nlCjAAI; first error: SELF_REFERENCE_FROM_TRIGGER, Object 0012g000001nlCjAAI is currently in a merge operation, therefore a trigger can not update it.

Merge attempt on 2 Organization Accounts w/ Address fields populated

VARIABLE_ASSIGNMENT|[50]|res|"MergeResult [success=false, id=0012g000002OBOcAAO, errors=[Error [statusCode=DELETE_FAILED, code=[xmlrpc=1209, statusCode=DELETE_FAILED, exceptionCode=null, scope=PublicApi, http=400], message=npsp.TDTM_Account: execution of AfterDelete\n\ncaused by: System.DmlException: Delete failed. First exception on row 0 with id a1Q2g00000000UhEAI; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Address: execution of AfterDelete\n\ncaused by: System.NullPointerException: Attempt to de-reference a null object\n\n(npsp)\n\n\n\n: []\n\n(npsp)\n\n\n\n\n\n\n\n, fields=null]], mergedRecordIds=null, updatedRelatedIds=null]"|0x11b0cfe1

VARIABLE_ASSIGNMENT|[55]|err|"Error [statusCode=DELETE_FAILED, code=[xmlrpc=1209, statusCode=DELETE_FAILED, exceptionCode=null, scope=PublicApi, http=400], message=npsp.TDTM_Account: execution of AfterDelete\n\ncaused by: System.DmlException: Delete failed. First exception on row 0 with id a1Q2g00000000UhEAI; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Address: execution of AfterDelete\n\ncaused by: System.NullPointerException: Attempt to de-reference a null object\n\n(npsp)\n\n\n\n: []\n\n(npsp)\n\n\n\n\n\n\n\n, fields=null]"|0x4ea8e4e5

Are the NPSP Triggers safe when called from a batch thread? 

There are several posts that talk about this same scenario (some around demand tools) but didn’t see any resolutions/workarounds posted. 

I started debugging through the Cumulus code but thought I’d reach out to the group before continuing to debug to see if anyone else has some thoughts.

Here is the Public Repository for the code if that helps w/ anyone that wants to investigate and/or use the Mass Merging Process.  Supports manual merging from a VisualForce mass merge page or automated merging based on a machine learning merge confidence value.

https://github.com/501Commons/Salesforce-Bulk-MergeNPSP

**Comment by coriobriensfdo** [comment]
@daveb-501commons I'm sorry but we don't provide support here in GitHub. I see your post in the [Hub Tooling Group](https://powerofus.force.com/0D51E00004kVzyB), and just added the Salesforce Developers group in to see if they can help you with your code.
