### ISSUE TITLE
[BGE] Double-clicking 'Begin Data Import Process' creates duplicate Opportunities

### ISSUE THREAD

**Issue by melissabarber** [SalesforceFoundation/Cumulus#4153]
Found this issue while testing a double-click Save bug for gem.
Built a scratch org out of the GEM depo, 'QA Org' plan/flow, feature/sge-fixes branch.
NPSP version 3.147, HEDA version 1.70

Steps:
1. Create a new BGE
2. Add a $25,000 donation to an existing Donor and click 'Save' button 1x (See Screenshot_1.jpg)
3. Click 'Process Batch button 1x
4. Click 'Begin Data Import Process' button 2x
5. On screen refresh, go to Opportunities All List view (or Recently Viewed).

Expected Result: Only 1 Opportunity is created
Actual Result: Duplicate Opportunities from the BGE are created  (See Screenshot_2.jpg)

Defect: When double clicking 'Begin Data Import Process' button in BGE, duplicate Opportunities are created.

**Comment by mrbelvedere** [comment]
Included in beta release 3.151 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.151
