### ISSUE TITLE
Manage Partial Soft Credits - Deleting records from the top of the list and then adding new ones corrupts the list

### ISSUE THREAD

**Issue by patrick-yan-sf** [SalesforceFoundation/Cumulus#4154]
When there are more than three soft credits on the manage partial soft credits page. And the user deletes one of the first two records and then adds a new record.  The last record in the list is overwritten with the 2nd to last record's contact info.

**Comment by force2b** [comment]
**lurch: attach W-031957

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlgvQAC" target="_blank">W-031957</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.151 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release 3.151
