### ISSUE TITLE
Payments should not be allowed to be marked as "Paid" and "Written Off"

### ISSUE THREAD

**Issue by mpusto** [SalesforceFoundation/Cumulus#4159]
When a user creates an Opportunity with Payments, an individual Payment record can have both the "Paid" and "Written Off" checkbox marked. This can cause issues with data integrity and should be prevented upon save or update to the Payment record.

**Comment by mpusto** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmCcQAK" target="_blank">W-032340</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.154 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 3.154
