### ISSUE TITLE
Getting Started Page: Trailhead Link is Broken

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4165]
The "Learn with Trailhead" Tile includes a link to an NPSP Trailmix:
https://trailhead.salesforce.com/users/00550000006yYDZAA2/trailmixes/npsp?

Internal request to change to :
https://trailhead.salesforce.com/en/content/learn/modules/nonprofit-cloud-basics

More details on Work Item.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmJ4QAK" target="_blank">W-032418</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.154 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release 3.154
