### ISSUE TITLE
Customizable Rollups: Cannot Select Custom Fields for Account Soft Credit Rollups

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4171]
When creating a Customizable Rollup of type Opportunity → Account (Account Soft Credit), customers are not able to choose any field on the Account Soft Credit beyond Amount and Role (i.e. no custom fields, or system fields like created/modified date). In contrast, they can select custom fields/system dates across the rest of our rollup Types. This affects all field types — currency, number, text, and dates. [Note that there is a manual workaround at the bottom of this issue].

### *Steps to Repeat*

1. Create 4 fields on the Account Soft Credit object.
    1. ASC Currency (Type = Currency; 16,2)
    2. ASC Date (Type = Date)
    3. ASC Number (Type = Number, 18)
    4. ASC Text (Type = Text, 255)
2. Create 4 fields on the Account object
    1. ASC Currency (Type = Currency; 16,2)
    2. ASC Date (Type = Date)
    3. ASC Number (Type = Number, 18)
    4. ASC Text (Type = Text, 255)
3. Enable Customizable Rollups in NPSP Settings → Donations —> Customizable Rollups

***Test 1: Currency Rollup***
Create a new Customizable Rollup with the following options:

*Target Object*: Account
*Target Field*: ASC Currency
*Operation*: Sum
*Time Frame*: All Time
*Rollup Typ*e: Opportunity → Account (Account Soft Credit)
*Filter Group*: No Filter Group
*Amount Field:* The expected behavior is that I could choose the ASC Currency field, but my only option is “Account Soft Credit: Amount”.

***Test 2: Date Rollup***
Create a new Customizable Rollup with the following options:

*Target Object*: Account
*Target Field*: ASC Date
*Operation*: First
*Time Frame*: All Time
*Rollup Typ*e: Opportunity → Account (Account Soft Credit)
*Filter Group*: No Filter Group
*Field to Roll up:* my only options are Opportunity fields; should I expect to see Account Soft Credit date fields here?
*Date Field:* my only options are Opportunity fields; should I expect to see Account Soft Credit date fields here?

***Test 3: Number Rollup***
Create a new Customizable Rollup with the following options:

*Target Object*: Account
*Target Field*: ASC Number
*Operation*: Average
*Time Frame*: All Time
*Rollup Typ*e: Opportunity → Account (Account Soft Credit)
*Filter Group*: No Filter Group
*Amount Field*: The expected behavior is that I could choose the ASC Number field, but my only option is “Account Soft Credit: Amount”.

***Test 4: Text Rollup***
Create a new Customizable Rollup with the following options:

*Target Object*: Account
*Target Field*: ASC Text
*Operation*: Last
*Time Frame*: All Time
*Rollup Typ*e: Opportunity → Account (Account Soft Credit)
*Filter Group*: No Filter Group
*Field to Roll up:* I have the Account Soft Credit: Role field as an option, along with Opportunity fields. I would expect to also see my custom ASC Text field listed.
*Date Field:* my only options are Opportunity fields; should I expect to see Account Soft Credit date fields here?

-----------------
### Workaround
This is only affecting the Customizable Rollups user interface. You can still select the custom fields on the Custom Metadata Type records and our rollup engine will use them.

1. Create your Account Soft Credit Rollup using the available fields on Account Soft Credit (i.e. Amount or Role, depending upon your criteria.)
2. Go to Setup --> Custom Metadata Types and click on the Manage Records link next to Rollups.
3. Sort by Rollup Name (any you create will not start with "NPSP_".
4. Click Edit next to the one you just created and choose your custom fields in either the Field to Rollup or Amount field (depending on what operation you are using).
5. Save.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmPqQAK" target="_blank">W-032498</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.157 (Beta 20)

**Comment by mrbelvedere** [comment]
Included in production release 3.157
