### ISSUE TITLE
TDTM_Account

### ISSUE THREAD

**Issue by daveb-501commons** [SalesforceFoundation/Cumulus#4178]
Account merging throws exception in TDTM_Account AfterDelete Trigger failure in batchable context

Contact merging was just fixed w/ the latest NPSP.
CON_ContactMerge_TDTM cannot be run from batch apex
https://github.com/SalesforceFoundation/Cumulus/issues/2463

There was an issue related to this issue closed in Feb 2016
TDTM_Account AfterDelete Trigger calls future method which fails if running in Batchable context
https://github.com/SalesforceFoundation/Cumulus/issues/1927

https://github.com/SalesforceFoundation/Cumulus/pull/1928
pull request says was fixed but when calling account merge in batchable context still getting an exception.

@sfdcmatt 
@judisohn 
@davidhabib 
@stenebenau
@jjbennett 
@rponti-sforg

**Comment by judisohn** [comment]
@daveb-501commons Would you mind posting the specifics of the issue along with the exact steps to repeat in the Hub and use the #Nonprofit Success Pack topic? Once confirmed, we can re-open the issue here with further replication detail for the development team. Thanks!
