### ISSUE TITLE
BDI - Missing FLS on populated DI field causes all data imports on batch to return permission error on Dry run / Processing

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/Cumulus#4179]
Missing permission on the user for a field thats currently being used on a DI will cause all of the data imports on that batch, even the ones that dont use it, to return the following permissions error: “You do not have permission to modify *field*” when running dry run / processing
 
Pre-conditions:
- Missing FLS for current user on a field used by data imports (I will be using Check / Reference Number )
- Having 2 or more DI created on BDI, one of which has a value inputted on Check / Reference Number field
 
Steps to reproduce:
1- Acces the BDI tab from app launcher
2- Click on Start Data Import button to go to processing page in BDI
3- Click on Begin Dry Run/ Begin data import process
4- Click close after it ends and go back to BDI list view
 
Expected Result:
The DI with the field for which the user has no FLS will return a permission error after dry run / processing is completed and the others will successfully be validated or processed
 
Actual Result:
All of the DIs in the batch, depending on value from Batch Process Size (default is 50) will return an error

**Comment by cpose** [comment]
**lurch: attach W-032547

**Comment by cpose** [comment]
**lurch: attach W-032547

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LmTnQAK" target="_blank">W-032547</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.160 (Beta 10)
