### ISSUE TITLE
Contact Merge Still Queries for User-Defined Rollups Fields After Customizable Rollups are Enabled

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4184]
If a customer deletes a field previously referenced by User Defined Rollups and they have Customizable Rollups enabled, they receive the following error during Contact Merge:

**First error: Invalid field: 'Opportunity.Amount_This_Year__c'**
(where _Amount This Year_ is a custom field I created and deleted).

*Stacktrace:*
```
Failed to invoke future method 'public static void rollupContactsandHouseholdsForTriggerFuture(Set<Id>)' on class 'npsp.RLLP_OppRollup' for job id 'xxxxxxxxxxx'
caused by: 
System.QueryException: Invalid field: 'Opportunity.Amount_This_Year__c'

Class.npsp.RLLP_OppRollup.rollupContacts: line 525, column 1
Class.npsp.RLLP_OppRollup.rollupContactsandHouseholdsForTrigger: line 163, column 1
Class.npsp.RLLP_OppRollup.rollupContactsandHouseholdsForTriggerFuture: line 132, column 1
```

### Steps to Repeat

1. Create field on Opportunity
    1. Name = Amount This Year
    2. Type = Formula (Currency)
    3. Formula: IF(YEAR( TODAY()), Amount, 0)
2. Create field on Contact
    1. Name = Total Amount This Year
    2. Type = Currency (16,2)
3. Create User Defined Rollup in NPSP Settings → Donations → User Defined Rollups
    1. Opportunity Field = Amount This Year
    2. Rollup Operation = SUM
    3. Target Object = Contact
    4. Target Field = Total Amount This Year
    5. Create Rollup
4. Enable Customizable Rollups
5. Create a Contact and a Closed Won Opportunity for that Contact.
6. Edit the Rollup using the NPSP Settings User Interface and switch to the following values:
    1. Change Operation to Sum
    2. Change Time Frame to Years Ago and Years Ago to This Year.
    3. Make Sure the Date Field = Close Date
    4. Change the Amount field to Amount
    5. Hit Save.
7. Manually delete the Rollup record in Setup → Custom Metadata Types → Rollups
8. Delete the Opportunity field called Amount This Year.
9. Create a second Contact with the same name.
10. Merge the 2 Contacts using the NPSP Contact Merge object.
11. Confirm the following error in NPSP Settings → System Tools → Error LogFirst error: Invalid field: 'Opportunity.Amount_This_Year__c'

### Workaround:
Go to Setup → Custom Settings → User Rollup Field Settings and delete the record that references the field you deleted.

**Comment by jesslopez-sf** [comment]
**lurch: attach W-031664

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlJSQA0" target="_blank">W-031664</a>
