### ISSUE TITLE
as a user, I want to filter and delete a subset of errors from the Error Log, so I don't have to delete them all at once.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#419]

**Comment by kbromer** [comment]
**lurch: attach W-007361

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZjAAI" target="_blank">W-007361</a>

**Comment by mpusto** [comment]
With the removal of the NPSP Error log in 3.83, this item is no longer relevant.

**Comment by davidhabib** [comment]
we didn't remove the error log.  we are just storing less often into the log.  that said, i do agree with closing this item.
