### ISSUE TITLE
BGE: Internal Server Error when using Custom Field Mapping in Batch

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#4201]
Thread [1](https://powerofus.force.com/s/question/0D51E00004puPf3SAE/custom-fields-in-batch-gift-entry-possible-causing-internal-server-errors) and [2](https://powerofus.force.com/s/question/0D51E00004puQaaSAE/resolving-batch-gift-entry-server-error) from the Hub. 

**Issue:**
Using custom mapped fields in BGE is preventing the batch from being created properly, and giving an Internal Server error. 
<img width="778" alt="Screen Shot 2019-04-24 at 2 01 45 PM" src="https://user-images.githubusercontent.com/37851761/56693950-7a0a4180-669a-11e9-8475-d1ad938116ef.png">

**To Reproduce:**

1. Create a custom date field on the Opportunity, say Custom Date 1, Type of Date, with API Name as Custom_Date_1__c
<img width="990" alt="Screen Shot 2019-04-24 at 2 04 15 PM" src="https://user-images.githubusercontent.com/37851761/56694535-c5711f80-669b-11e9-9311-da26ccdd9305.png">

2. Create a custom date field on the NPSP Data Import object, say Custom Date 1, Type of Date, and ensure the help text is Opportunity.Custom_Date_1__c
<img width="965" alt="Screen Shot 2019-04-24 at 2 17 18 PM" src="https://user-images.githubusercontent.com/37851761/56694543-ca35d380-669b-11e9-989e-cbfa60dcb5c4.png">

3. Create a new BGE batch, called Test Batch 1, and only include the standard fields (don't include your new custom date field). Notice the batch saves correctly and you can add New Gifts. 
4. Create a new BGE batch, called Test Batch 2, and include the new Custom Date 1 field. Click save to save/close the batch and note the error. Expected behaviour is that the batch will save and allow data to be entered into the custom mapped fields. 

**Impact:**
This is having an impact on our customers as they cannot save batches that include custom fields.

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uGaQAI" target="_blank">W-032724</a>

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
