### ISSUE TITLE
BGE Grid - Unpaid payments from Closed Opportunities showing on review donations modal

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/Cumulus#4272]
Unpaid payments belonging to Closed Opportunities are currently being incorrectly shown in the Review Donations modal from the BGE grid.
Review donations modal should display only the following:
 
For Payments:
Unpaid Payments from open opportunities with multiple unpaid payments
Unpaid Payments from open opportunities with both paid and unpaid payments
Unpaid Payments from open opportunities with a single unpaid payment
 
For Opportunities:
Opportunities in any open stage with no payments
Opportunities in any open stage with multiple paid payments
 

Preconditions:
Having a closed opportunity with an unpaid payment
Being in BGE grid
 
Steps to reproduce:
Go to BGE and open access any batch
Use the lookup field to look for the Contact/Account for the closed opportunity
Click on Review Donations
 
Expected results:
A spinner will briefly load but no Review Donations link will be shown since there are no valid Payments or Opportunities to be shown in the modal.
 
Actual results:
Review Donations link appears and the modal displays the Payments belonging to a closed opportunity.

**Comment by cpose** [comment]
**lurch: attach W-031021

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fR8RQAU" target="_blank">W-031021</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.156 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.156
