### ISSUE TITLE
Recurring Donations Donation Dates weren't updated

### ISSUE THREAD

**Issue by Criszhy** [SalesforceFoundation/Cumulus#4278]
Good day!

Our team encountered an NPSP issue that we want to confirm if it's a bug or not.

There's a Recurring Donation record in our client's Salesforce Org:
Installment Period - Monthly
Open-Ended Status - Open

NPSP Settings > Opportunity Forecast Months - 2
Current version of NPSP - 3.155 installed on the 22nd of May, 2019.

Here's the issues we have encountered:

We noticed that some opportunities marked as Closed Won on 5th of May, 2019 did not trigger the creation of the next future opportunity, in this case July2019 donation. Consequently, the Recurring Donations Next Donation Date field was not updated, in this case suppose to be June2019 date and the Total Paid Installments stays the same.

We also noticed that some Recurring Donations: Next Donation Date weren't updated, even though we already run the Recurring Donations Batch in the NPSP Settings, manually as well as the Refresh Opportunities button in the RD record page.
![Empty Next Donation Date](https://user-images.githubusercontent.com/50934854/58219558-efbb0900-7d3d-11e9-8f15-87465b73bc7c.png)

We suspect that the issue is on the NPSP version installed in the client's org on that day 5thMay2019 which could be version 3.153 based on the NPSP Release Schedule.

Any thoughts and help to clarify this scenario would be gladly appreciated as we couldn't  think of any other reason why the RD data is behaving this way.

**Comment by coriobriensfdo** [comment]
@Criszhy we don't provide support here directly in GitHub. Can you please post in the [Power of Us Hub](https://powerofus.force.com/s/topic/0TO80000000DlHzGAK/nonprofit-success-pack)?

Take a look at other comments regarding the Recurring Donation schedule, for example this post: https://powerofus.force.com/s/question/0D51E00004pvsvcSAA/open-ended-recurring-donations-when-do-new-child-opps-get-created
