### ISSUE TITLE
NPSP Error

### ISSUE THREAD

**Issue by Criszhy** [SalesforceFoundation/Cumulus#4279]
We've received this error in NPSP and tried to lower down the batch job size of NPSP into half but we are still receiving the same email.
Could you please help us to fix this? 

Organization: Act for Peace (00D28000001KHkzEAG)
User: ncca@alphasys.com.au (005280000042oX5AAI)

Salesforce reported the below errors as NPSP was attempting to execute its batch jobs, or at a time when it was unable to display error messages directly to a user. It's likely that NPSP was attempting to update summary fields on Accounts and Contacts, but was unable to save certain records. This failure might have been caused by a variety of issues unrelated to NPSP, such as custom code or validation rules.

Read this article on the Power of Us Hub to learn how these Scheduled Jobs work: https://powerofus.force.com/NPSP_Scheduled_Jobs

If you're not sure how to resolve these errors, post a message in the Nonprofit Success Pack group in the Power of Us Hub: https://powerofus.force.com/HUB_NPSP_Group

Errors:

----------
 Error #1:

Error Type: Batch Apex error
Error Date: 2019-05-21 14:43:50
Message: "First error: npsp:Too many query rows: 50001"
Context: npsp__RLLP_OppAccRollup_BATCH

Stack Trace:
 null

**Comment by coriobriensfdo** [comment]
Hi @Criszhy, We don't provide support here directly in GitHub. Instead, can you please post your error in the Power of Us Hub, using the [Topic tag Nonprofit Success Pack](https://powerofus.force.com/s/topic/0TO80000000DlHzGAK/nonprofit-success-pack)?

I would also recommend searching the error in the Hub search area as you'll find a number of solutions related to the error. Likely you'll want to keep reducing the batch until it is successful. Often we see folks who have one offender Account that has thousands of related records which causes the issue. If you reduce the batch to 1 it may point it out if you aren't sure which one it is.
