### ISSUE TITLE
Batch Gift Entry: Update Opportunity Feature May Overwrite Opportunity Fields

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4286]
If Payments are enabled in an org and a customer is using Batch Gift Entry, they have the option to Update Opportunity or Apply New Payment to a matched gift if the Opportunity has no payments or all payments have been paid. Selecting the “Update Opportunity” option may lead to unintended Opportunity field changes — Amount and Close Date, for instance. The Stage will also change to Closed Won.

Recent work will address this by changing the options that appear for a matched gift:

- When Payments are enabled and a matched Opportunity has no payments, we will only display an “Apply New Payment” option. We will remove the “Update Opportunity” link.

- When Payments are not enabled and a matched Opportunity has no payments, there will be an option to Update Opportunity.

**Comment by jesslopez-sf** [comment]
**lurch: attach W-033025

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uerQAA" target="_blank">W-033025</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.160 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 3.160
