### ISSUE TITLE
Component dataProviderInterface duplicated

### ISSUE THREAD

**Issue by Zosoled** [SalesforceFoundation/Cumulus#4291]
Within /src/aura/dataProviderInterface, there are 2 component files and their respective XML files. dataProviderInterface and dataProviderInterfaceInterface. The latter is identical in content to the former, but it is not referenced anywhere else in code nor is it deployed with the NPSP installer.

If it's truly an invalid duplication, dataProviderInterfaceInterface.intf and dataProviderInterfaceInterface.intf-meta.xml should be removed from source.

**Comment by coriobriensfdo** [comment]
**lurch: attach W-033409

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087v9qQAA" target="_blank">W-033409</a>

**Comment by coriobriensfdo** [comment]
@Zosoled As mentioned in the PR, unfortunately we are unable to delete the component. I've had our engineers review the request, and they've let me know that because the component is packaged and released, it's non-deletable and we can't remove it.

**Comment by coriobriensfdo** [comment]
@Zosoled Whoops, seems we had a bit of an internal misunderstanding of what you were referring to. We can in fact delete the dataProviderInterfaceInterface.intf file, inside the bundle. I've reopened the Issue and PR. Again, thank you for contributing this!
