### ISSUE TITLE
Modify Opportunity Stage to State Mapping to utilize a Custom Metadata Type

### ISSUE THREAD

**Issue by KietTruongSFDO** [SalesforceFoundation/Cumulus#4299]
The Opportunity Stage to State Mapping needs to be updated to use a New Custom Metadata Type so that it is more flexible. This allows the users to pick which Opportunity stages will be mapped to which State.

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-031903

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlcZQAS" target="_blank">W-031903</a>

**Comment by KietTruongSFDO** [comment]
This issue was mistakenly created. It should not have been created in the first place.
