### ISSUE TITLE
Health Check: Incorrect Report and language referenced in Error Alert

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#4306]
[Thread in Hub](https://powerofus.force.com/s/question/0D51E00004sGJslSAG/why-is-my-health-readiness-report-showing-errors-that-arent-true)

When running Health Check, Household Accounts that have no related Contacts produce an error so the Admin can correct or delete. The language used in the Health Check error is misleading however, and refers to the old Household custom object, rather than the Household Account object. 

Error message when HH Account model is enabled, and there are zero Household custom Object records in the Org: 

"There are 5 Household Accounts that have no Contacts. 
Consider deleting these unused Household object records to save space. If you have completed a conversion to the Household Account model and no longer need the data on the Household object records, you can safely delete them. View these Household object records by running the Empty Household Objects report in the NPSP Health Check reports folder."

Instead of referring to the custom Household object and pointing to the Empty Household Object report, the content of the error should refer to the Account object for Household record type, and point to the Empty Household Accounts report.

<img width="992" alt="Screen Shot 2019-06-06 at 10 25 41 AM" src="https://user-images.githubusercontent.com/37851761/59060026-00e33a00-8855-11e9-808b-d08e5e1cfea6.png">

Example showing zero custom Household objects exist
<img width="1358" alt="Screen Shot 2019-06-06 at 10 26 45 AM" src="https://user-images.githubusercontent.com/37851761/59060067-18babe00-8855-11e9-9d3a-751f6b5b69bd.png">
:

**Comment by coriobriensfdo** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vQ7QAI" target="_blank">W-033612</a>

**Comment by force2b** [comment]
Included in production release 3.159 via #4393
