### ISSUE TITLE
Batch Gift Entry: Spinner on Pre-filled Lookup Fields when chosen as selected field 

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4309]
In Summer '19 orgs, if a customer selects any lookup field (for example, the Donation Campaign Source field) as a selected field within a batch (for Batch Gift Entry) and pre-fills a value, the field does not show the value on the entry screen. Instead it shows a spinner in the lookup field. See animated gif here:
![2019-06-10_14-35-36 (1)](https://user-images.githubusercontent.com/29731456/59218516-6fdecc80-8b8e-11e9-8278-82a39ba6e20b.gif)

I replicated this in both a sandbox with Summer '19 and a prerelease scratch org. A scratch org with Spring '19 was fine.

### Steps to Repeat
1. Create a prerelease scratch org and run the qa_org flow.
2. Assign the Batch Gift Entry Permission Set to your User.
3. Create a Campaign (Name = 'Summer Campaign')
4. Go to the Batch Gift Entry tab and click the New Batch button.
5. Enter a name for the batch. Click Next.
6. Click the Donation Campaign Source field and move it from the Available Fields to the Selected Fields list. Click Next.
7. Enter "Summer Campaign" into the Donation Campaign Source field and click Next. Then hit Save.

There will be a "loading" spinner within the Donation Campaign Source field. Refreshing the page doesn't help.

I'll attempt to capture some logs and add to the Work Item.

---
**Chrome Console Logs:**
Uncaught (in promise) Error: @wire(getRecordUi) parameter recordIds must be a string or string array.
    at ke (lds.js:2)
    at Object._serviceGetRecordUi (lds.js:2)
    at eval (lds.js:2)
    at aura_prod.js:13
    at Set.forEach (<anonymous>)
    at b (aura_prod.js:13)
    at d (aura_prod.js:13)

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vUnQAI" target="_blank">W-033670</a>

**Comment by askebongsaxe** [comment]
Hi. I reported this issue to Salesforce Support on 5th May (case #23186112) because it was happening in my Summer '19 preview sandbox. Do you know if there is an expected timeline for this to be fixed, e.g., before Summer '19 is released?

**Comment by jesslopez-sf** [comment]
Hi @askebongsaxe , I don't have a delivery date yet. We are skipping this release due to the Summer '19 release. The workaround at the moment is to select the value manually (which we realize defeats the purpose of the pre-filled lookup). Our Product Management team is aware of the issue.

**Comment by askebongsaxe** [comment]
Alright, thank you @jesslopez-sf.

**Comment by mrbelvedere** [comment]
Included in beta release 3.157 (Beta 12)

**Comment by mrbelvedere** [comment]
Included in production release 3.157
