### ISSUE TITLE
Batch Data Import Help Text Mapping Case Sensitivity Causing Failures

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4319]
If a customer maps two NPSP Data Import fields to the same target field using the relevant relationship (i.e. Contact1 vs. Contact2), but is not consistent with the case of the field's API name in the help text, a failure occurs.

```
System.QueryException
ERROR at Row 1:Column:359
duplicate field selected: Favorite_Color__c
```

![Screen Shot 2019-06-13 at 5 06 47 PM](https://user-images.githubusercontent.com/29731456/59468179-6ad48400-8dff-11e9-9e49-bce8534f0dd6.png)

I believe this occurs because we add the field names to a set of Strings, which is case-sensitive, so it treats Favorite_Color__c and FAVORITE_COLOR__c as two different values. When we then add this set of String/fields to a SOQL Query, this is not case-sensitive, so it reports a duplicate field when both Favorite_Color__c and FAVORITE_COLOR__c are in the query. 

### Steps to Repeat

1. Create a new Contact Field
    1. Type = Text
    2. Field Label = Favorite Color
    3. Length = 255
    4. Field Name = Favorite_Color
2. Create 2 new fields on the NPSP Data Import object. *The Case of the Help Text matters greatly.*
    1. Field 1
        1. Type = Text
        2. Name = Contact1 Favorite Color
        3. Length = 255
        4. Help Text = Contact1.Favorite_Color__c
    2. Field 2
        1. Type = Text
        2. Name = Contact2 Favorite Color
        3. Length = 255
        4. Help Text = Contact2.FAVORITE_Color__c
3. Create an NPSP Data Import Record
    1. Contact1 First Name = Jess
    2. Contact2 Last Name = Lopez
4. Switch to the _To Be Imported_ List View and click the **Start Data Import** button.
5. Keep the defaults and click the Begin Data Import Process.
6. The BDI record shows a Status of “Failed” and the Failure information is:

account1_website__c,account1_zip_postal_code__c,account2importstatus__c
    ^
    ERROR at Row:1:Column:359
    duplicate field selected: Favorite_Color__c

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vaqQAA" target="_blank">W-033734</a>

**Comment by jesslopez-sf** [comment]
Closing this as there is a very simple workaround -- ensure that the case for the API name of the mapped field matches between each relationship's help text mapping.
