### ISSUE TITLE
BDI: Home Address Imported field missing from Document and Data Importer Template

### ISSUE THREAD

**Issue by dbrenner23** [SalesforceFoundation/Cumulus#4338]
It looks like matching by the Home Address Imported field is still supported in the NPSP Data Import Wizard. But there's no reference to it in the following:

[NPSP Administrator's Guide to Importing Donor Data](https://powerofus.force.com/articles/Resource/NPSP-Administrators-Guide-to-Importing-Donor-Data)

[Data Importer Template](https://powerofus.force.com/articles/Resource/NPSP-Data-Importer-Documentation)

**Comment by coriobriensfdo** [comment]
@dbrenner23 can you instead start a conversation with one of the internal members of the Doc team or create a WI for this? We reserve GitHub Issues for reproducible bugs in the product. 

Thanks!
