### ISSUE TITLE
Enabling Customizable Rollups the first time does not fully enable the feature

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#4346]
When you Enable CRLP for the first time, the “Deployment in progress” page never seems to refresh despite the deployment completing. You need to refresh that page and enable CRLP again in order to see that they are enabled.

## Steps to reproduce

* Open *NPSP Settings > Donations > Customizable Rollups* and enable CRLP
* Page should load and display “Deployment in progress. You can leave this page. This page will reload when deployment is finished”
* In another tab/window, open the *Deployment Status *page* *again and make sure the deployment has completed (you can tell because it should have a different timestamp from all the other deployments from the initial push to the scratch org)
* The page in NPSP Settings still has not reloaded.
* In another tab/window, open up *Setup > Custom Settings > Customizable Rollup Settings > Manage*. You should see that “*Enable Customizable Rollups*” is still unchecked.
* Go back to NPSP Settings. Refresh the page and go to* Donations > Customizable Rollups* and enable CRLP again.
* Page will eventually refresh and show that CRLP has been enabled.
* If you go to the custom settings again, you will also see that “*Enable Customizable Rollups*” is now checked

Thanks to @seanpat09 for documenting.

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6maQAC" target="_blank">W-034034</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.159 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 3.159

**Comment by carlosgallardosfdc** [comment]
Just curious...what was the real issue? When I enabled Customizable Rollups last fall it worked for me on the first try. Not sure if this is even the right channel to ask this question? Let me know if not. Thanks team!

**Comment by coriobriensfdo** [comment]
@carlosgallardosfdc would you mind posting in the Hub instead? Tag me on it and I'd be happy to loop in someone to give you a bit more technical detail.

**Comment by carlosgallardosfdc** [comment]
@coriobriensfdo Sounds good! I saw the issue closed and got excited. Will do. Thanks!
