### ISSUE TITLE
Remaining Balance formula causes writeoffs to be double-counted

### ISSUE THREAD

**Issue by MikeD72** [SalesforceFoundation/Cumulus#4368]
Trailhead and PowerOfUs advises users to "change the Opportunity amount from the original pledge to the actual amount you received" when writing off payments (this makes sense, since we don't want rollups to reflect written off amounts). The "Remaining Balance" npe01__Amount_Outstanding__c formula field then subtracts the writeoff amounts AGAIN. The result is that users will end up with a negative Remaining Balance.

Remaining Balance Formula field:
![image](https://user-images.githubusercontent.com/24308950/60747950-ea0c3200-9f3d-11e9-992e-30c0c7bfef6f.png)

Sample donation record with a writeoff:
![image](https://user-images.githubusercontent.com/24308950/60747954-f98b7b00-9f3d-11e9-973c-7cafef789c4c.png)

Trailhead instructions (see step 5 for writing of payments): 
https://trailhead.salesforce.com/en/content/learn/modules/donation-management-basics-with-nonprofit-success-pack/create-or-edit-payments

PowerOfUs (step 6 for Write Off One of More Scheduled Payments): 
https://powerofus.force.com/s/article/NPSP-Manage-Multiple-Payment-Donations#ariaid-title4

**Comment by judisohn** [comment]
Hi @mikeD72 - Best place to have a conversation about this functionality is on the Power of Us Hub. Would you mind starting [a thread there ](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack)instead of here? We reserve Github Issues only for replicable and actionable issues for our development team. Thanks for understanding and see you on the Hub!

**Comment by judisohn** [comment]
Hi @mikeD72 - wanted to let you know that I brought this to our documentation team's attention and they're going to get the text updated to no longer recommend editing the Opportunity amount. Instead, I'd advise you to not edit the Opportunity and instead use Customizable Rollups to count payments accurately on Account/Contact records. Post in the Hub if you need assistance with this and thanks for bringing this to our attention.

**Comment by MikeD72** [comment]
Hi @judisohn , thanks for looking into this! I would suggest that the current documentation instruction to reduce the opportunity amount by the written off amount is correct. If this is not done, soft credits on Accounts and Contacts will be too large, i.e. they will summarize the collectible and written off amounts instead of just the collectible amount.

I'd be happy to converse on the Power of Us Hub if you think that is a better forum for the time being?

**Comment by judisohn** [comment]
Yes, feel free to continue on the Hub @mikeD72 - I might argue that it's better to create Partial Soft Credit entries in that case?
