### ISSUE TITLE
Default GAU Allocation of $0 not created when $0 Opportunity created

### ISSUE THREAD

**Issue by melissabarber** [SalesforceFoundation/Cumulus#4384]
Before #4290 in the 3.157 release, default $0 GAU Allocations would be created when a $0 Opportunity was created. Release 3.157 stopped that default behavior.

**Comment by melissabarber** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7aEQAS" target="_blank">W-034448</a>
