### ISSUE TITLE
Make Written Off payments not count as open payments in BDI

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/Cumulus#4389]
Currently NPSP Batch Data Import will match to written off payments while matching donations.

In #4282 we've got the front end work done to exclude written off payments from donation matching - basically, not considering written off payments as open payments.

**Comment by ptewson-sfdo** [comment]
**lurch: attach W-034100

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C6ruQAC" target="_blank">W-034100</a>

**Comment by mrbelvedere** [comment]
Included in beta release 3.160 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 3.160
