### ISSUE TITLE
Encrypted Account Name Causing Errors in CMT_MetadataAPI_TEST

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4465]
When the Account Name is encrypted via Shield Platform Encryption, the [CMT_MetadataAPI_Test](https://github.com/SalesforceFoundation/Cumulus/blob/master/src/classes/CMT_MetadataAPI_TEST.cls) class throws the following error:

```
Description FROM Account WHERE Name = :SUCCESS_HANDLER_EXECUTED
 ^
ERROR at Row:1:Column:49
field 'Name' can not be filtered in a query call
```

### Steps to Repeat
1. Create Permission Set with the "Manage Encryption Keys" System Permission.
2. Assign the Permission Set to your User record.
3. Go to Setup --> Key Management and click the Generate Tenant Secret button.
4. Go to Setup --> Encryption Policy and click the Encrypt Fields link.
5. Click Edit and check off the Account Name.
6. Save
7. You will receive an email with an error that says: 
```
Encryption enablement has failed for the following fields:
Account.Account Name: 
    Apex Class: CMT_MetadataAPI_TEST, line 70, column 34: field 'Name' can not be filtered in a query call
    Apex Class: CMT_MetadataAPI_TEST, line 78, column 20: field 'Name' can not be filtered in a query call
```

-----

I'll provide resources for how we've resolved this in the past on the generated Work Item.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8dRQAS" target="_blank">W-034958</a>
