### ISSUE TITLE
Default GAU Percent

### ISSUE THREAD

**Issue by bfank** [SalesforceFoundation/Cumulus#4482]
Description: When synching a Payment Allocation back to the Opportunity there should not be a percent on the Default GAU for the Opportunity Allocation.

Steps:
1. 5,000 Prospecting Oppty, 100% GAU1 Allocated, schedule 5 equal monthly payments.
2. Mark PMT1 as Paid, 100% GAU1 allocated.
3. Mark PMT2 as Paid, 100% GAU1 allocated.
4. Update PMT2 to a negative -$1,000 Refund. PMT2 Allocation updated to -$1,000 GAU1
5. Update PMT2 Allocation to 50% (-$500) GAU1, -$500 Default GAU

Results: No Percent on the Default GAU

**Comment by bfank** [comment]
**lurch: attach W-033736

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vb0QAA" target="_blank">W-033736</a>
