### ISSUE TITLE
Profile must have access to Payment Object to use the Manage Allocations Button

### ISSUE THREAD

**Issue by coriobriensfdo** [SalesforceFoundation/Cumulus#4483]
[**Hub Thread**](https://powerofus.force.com/s/question/0D51E00004xzTSfSAM/non-admin-users-are-getting-error-when-trying-to-manage-allocation-is-anyone-else-having-this-issue)

**Issue:** User is unable to utilize the Manage Allocations button on an Opportunity record unless Payment full CRED access is provided. 

Likely introduced with [this PR](https://github.com/SalesforceFoundation/Cumulus/pull/3743/files#diff-9b349cf3a142bbe0ba79af9f09d391ffR188-R193).

**Steps to repeat:**
1. On any custom profile, remove CRED access to Payment Object. (Assuming GAU feature is already setup for the profile).
2. Navigate to existing Opty, or create a new one. 
3. On the GAU Allocations related list, click the Manage Allocations button. 

_Expected Behaviour:_
Manage Allocations Visualforce page should open, allowing the user to modify GAU Allocations related to the Opty. 

_Actual Behaviour:_
GACK error is produced: "npsp__util_pagemessages: system.security.NoAccessException: You do not have sufficient privileges to access the controller: UTIL_HtmlOutput_CTRL"

**Issues to resolve:**
1. There shouldn't be a dependency on the Payment Object to use the Manage Allocations button when the Payment Allocations feature is not enabled.
2. Permissions error should be more specific to what object/permissions are required.

 Further details will be added to resulting work item (debug log, etc.)

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C92lQAC" target="_blank">W-035127</a>

**Comment by coriobriensfdo** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9mkQAC" target="_blank">W-035495</a>
