### ISSUE TITLE
Opportunity.RecordType.Membership Disappears When Pushed Directly To Org

### ISSUE THREAD

**Issue by veaux** [SalesforceFoundation/Cumulus#4514]
After installing NPSP into an Enterprise scratch org, NPSP Settings displays the Membership setup as expected including selection of Opportunity.RecordTypes. If the Opportunity.RecordType.Membership is then pushed to that org from DX the NPSP Membership setting option for Opportunity.RecordType "disappears". Can not get to reappear even with updated NPSP install on same org. Observed this with 2 different scratch orgs over different days.

Removal of the Opportunity.RecordType from metadata push seemed to be the workaround.

**Comment by judisohn** [comment]
@veaux If possible, it would be awesome if we could continue this conversation on the Power of Us Hub in the [NPSP](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack) or [DevOps](https://powerofus.force.com/s/group/0F980000000PSRHCA4/salesforceorg-devops-tooling) Group. 

Be sure you're pushing the ID and not the RecordType.Name - that's my first guess as to the issue you're facing. 

We don't offer support here in Github, so I'm going to close the issue and look forward to continuing to help you troubleshoot on the Hub. Thanks.

**Comment by veaux** [comment]
@judisohn not quite sure my comment was understood. This is a bug in the NPSP software, not support request. "Push" as in DX push, it pushes the full metadata, there isn't an option to push ID, Name, etc. There is a problem with the VF page associated with Membership in this case.

**Comment by coriobriensfdo** [comment]
@veaux it could be a bug, but we normally prefer to confirm in our own clean orgs ourselves, then to create Issues here in Github for bugs we've confirmed. If you can still post in the Hub instead, then we can test it and get some internal folks to validate it. We can always re-open this Issue if needed. 

Thank you!

**Comment by veaux** [comment]
@coriobriensfdo I understand. We are consultants implementing for an NPSP customer and don't have access to Hub so I'll have to skip this one.
