### ISSUE TITLE
As a developer, after Cumulus has been released and installed into most organizations, we can delete old tabs from the old packages, in order to reduce the number of tabs the user will see in setup.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#456]
We're in the deprecation pilots for the base NPSP orgs - lets mark those old settings tabs deprecated and get rid of them. 

see notes on the gitHub issue #456.

**Comment by njjc** [comment]
Old tabs are correctly redirected, and there are too many considerations with upgrades that we're leaving as is.

**Comment by force2b** [comment]
I typically change the visibility of all the old tabs after
upgrading/installing v3, as well as rename some of the old tabs and even
the Household object to include "DEPRECATED" in the name so it's really
obvious not to use those. Maybe a good way to approach this is with a
knowledge doc that lists out the tabs and possibly objects that an admin
might want to hide and/or rename.

**Comment by njjc** [comment]
Great idea. @jvarese
