### ISSUE TITLE
Winter '20 error Manage Soft Credits in multi-currency org

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#4574]
Winter '20 release 222.5.100 (also in 222.4)

**Issue**

With multiple currencies enabled in an org, the Manage Soft Credit page produces an error when attempting to add a new contact soft credit.

![image](https://user-images.githubusercontent.com/4614343/64521833-9f69b600-d2f0-11e9-90f5-f80b059b1902.png)

**Steps to Repeat**

- create new org and enable multiple currencies (used USD and GBP with USD as corporate)
- create Contact (select currency same as corporate) and add a gift (amount, stage likely doesn't matter)
- select _Manage Soft Credits_ action from drop-down
- click _add another soft credit_ link

Immediately get the error: `Invalid field CurrencyIsoCode for SObject OpportunityContactRole`

Note: Could be related to new Opportunity Contact Role object in Winter '20.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CATPQA4" target="_blank">W-035868</a>

**Comment by judisohn** [comment]
Further testing - standard editing of Contact Roles do not have error, nor is there an error with automated soft credits.

**Comment by force2b** [comment]
Closed after a Winter '20 fix was released.
