### ISSUE TITLE
Contact Merge: NPSP allows user without Delete on Contact/Account to merge

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/Cumulus#4579]
As per [Standard Salesforce documentation](https://help.salesforce.com/articleView?id=contacts_merge_lex.htm&type=5), Delete on the Contact object is required to complete a merge using their standard functionality. However, it appears that our custom Contact Merge page does not respect that permission requirement and didn't previously.

[Power of Us Hub post](https://powerofus.force.com/s/question/0D51E000051BAUWSA4/potential-bug-profile-succesfully-merged-contacts-with-contact-merge-even-though-they-do-not-have-deletemodify-all-permissions-on-contacts-or-accounts)

**Summary:**

User without Delete on the Contact object is able to use NPSP Contact Merge to merge contacts, where a duplicate match in standard Salesforce prevents this action. We should not be allowing this action.

**Steps to replicate:**

1. Create Profile with Create/Read/Edit only on all objects (Std and Custom). Verify that both Modify and View All Data is not checked.
3. Activate NPSP duplicate/matching rule.
4. Create User with this new profile.
5. Login as the new user.
6. Create two Contacts with same name/email. Verify that the contact is matched and that you are unable to select for merge in standard UI
7. Use NPSP Contact Merge and you can now select the Contacts and merge them
8. Switch to Classic (if not Winter '20) and confirm that non-master contact was deleted

**Comment by judisohn** [comment]
**lurch: attach W-035925

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAY0QAO" target="_blank">W-035925</a>

**Comment by sam-knox** [comment]
@judisohn - This Issue can be closed per this PR going into the next release: https://github.com/SalesforceFoundation/Cumulus/pull/4629
