### ISSUE TITLE
Error in Opportunity Naming when there is no mapped Currency Symbol for Opp Currency 

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#4612]
Steps to reproduce:

1. Enable Multi-Currency in a Scratch Org
1. Create a new currency for the "Bolivian Boliviano" (BOB), leaving the default as USD
1. Configure an Opportunity Naming Pattern using NPSP Settings (`{!Account.Name} {!Amount} {!RecordType.Name} {!CloseDate}`)
1. Create a new Opportunity for a Household Contact with a currency of USD putting "Curr Test" in the Opp Name field. See that the Opp is "named" properly.
1. Create a new Opportunity with a currency of BOB putting "Curr Test" in the Opp Name field. See that the Opp Name field is left unchanged after saving.
1. Return to NPSP Settings and open SystemTools->Error Log. See that a new log record is created for a the OPP_OpportunityNaming class.

===========================================================
Failed to process batch for class 'npsp.OPP_OpportunityNaming_BATCH'

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.npsp.OPP_OpportunityNaming.getFieldValue: line 443, column 1
Class.npsp.OPP_OpportunityNaming.replaceFieldNamesWithValues: line 395, column 1
Class.npsp.OPP_OpportunityNaming.refreshOppNames: line 90, column 1
Class.npsp.OPP_OpportunityNaming_BATCH.execute: line 96, column 1

**Comment by force2b** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAvyQAG" target="_blank">W-036136</a>

**Comment by jesslopez-sf** [comment]
Related Issue: #3015

**Comment by judisohn** [comment]
And #2931
