### ISSUE TITLE
npe03__Total_Paid_Installments__c & npe03__Paid_Amount__c not updating correctly with non-paid installments

### ISSUE THREAD

**Issue by gonzalos4g** [SalesforceFoundation/Cumulus#4617]
1. Monthly Recurring Donation set up with 10$ amount.
2. First Donation is paid  --> Total paid Installments= 1; Paid Amount = 10
3. 2nd Donation is paid --> Total paid Installments= 2; Paid Amount = 20
4. 2nd donation payment is unpaid (Close Lost)--> Total paid Installments= 2; Paid Amount = 20
This situation is because of direct debits being unpaid or returned the receipt. Here it should be:
Total paid Installments= 1; Paid Amount = 10

**Comment by coriobriensfdo** [comment]
Hi @gonzalos4g, we don't actually manage customer support issues here in Github. Can I ask you to post in the Power of Us Hub, in the [Nonprofit Success Pack group](https://powerofus.force.com/s/group/0F980000000CjReCAK/nonprofit-success-pack)? Before we create Issues here in GitHub we need to ensure it's reproducible in an independant org (and then our staff will create issues here).

**Comment by gonzalos4g** [comment]
Ok, but this is not a customer issue, this is an issue of NPSP package for Recurring Donation rollups.  Of total paid installments. IT happens in all NPSP orgs. Thopse field in recurring donations only summons, do not substract.
