### ISSUE TITLE
NPSP Settings JSON Error When Sandbox Spun Up From Advanced Mapping Enabled Org

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/Cumulus#4623]
If you create a sandbox from an org with BDI Advanced Mapping enabled, you receive the following error when going to the NPSP Settings page: "Malformed JSON: Expected '{' at the beginning of object". (My sandbox was on Summer '19).

![Screen Shot 2019-09-20 at 2 24 22 PM](https://user-images.githubusercontent.com/29731456/65351924-500c6b00-dbb7-11e9-8d7f-9836b9f5e7d3.png)

### Relevant StackTrace
```
14:26:54:257 FATAL_ERROR System.JSONException: Malformed JSON: Expected '{' at the beginning of object
14:26:54:000 FATAL_ERROR Class.System.JSON.deserialize: line 15, column 1
14:26:54:000 FATAL_ERROR Class.npsp.CMT_MetadataAPI.getDeploymentResult: line 141, column 1
14:26:54:000 FATAL_ERROR Class.npsp.STG_PanelDataImportAdvancedMapping_CTRL.setDeploymentStatus: line 310, column 1
14:26:54:000 FATAL_ERROR Class.npsp.STG_PanelDataImportAdvancedMapping_CTRL.<init>: line 133, column 1
```

I will attach the full debug log to the Work Item. A few other things to note in the logs:
```
14:26:54:189 CALLOUT_REQUEST [139]|System.HttpRequest[Endpoint=https://jlnpspltrial--AdvMapping.cs43.my.salesforce.com/services/data/v44.0/metadata/deployRequest/0Af3l0000191VpfCAE?includeDetails=true, Method=GET]
14:26:54:255 CALLOUT_RESPONSE [139]|System.HttpResponse[Status=Bad Request, StatusCode=400]
```

### Steps to Repeat
1. Enable BDI Advanced Mapping in NPSP Settings
2. Create a Sandbox
3. Navigate to NPSP Settings in the Sandbox
4. The error shows at the top of the page and prevents any content from loading.

**Comment by jesslopez-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CB2BQAW" target="_blank">W-036190</a>

**Comment by zeugin18** [comment]
I'm getting this error in my sandbox. In order to access the NPSP settings again just remove the field values saved in the custom setting "Data Import Settings".

**Comment by coriobriensfdo** [comment]
@zeugin18 This appears to be an issue with Winter 20. Can you please post in the Hub, so we can let you know when we have a fix? Glad you found the workaround. 

CC @judisohn @mbeaty-sf

**Comment by coriobriensfdo** [comment]
Same as issue #4699
