### ISSUE TITLE
Multiple clicks on Write off Payments button creates multiple written off payments for opportunity

### ISSUE THREAD

**Issue by melissabarber** [SalesforceFoundation/Cumulus#4638]
Text contents of this field will be sent in initial record creation only
On the Write Off Remaining Balance page for Write Off Payments on an opportunity there is a button called Write Off Payments at the bottom of the screen which is shown on the attached image and video. Clicking multiple times on this button creates as many written off payments as clicks are made by the user
 
Pre-conditions
1 Having an account with an open opportunity
 
Steps to reproduce
1- Access the opportunity from pre-conditions
2- In the payments section, click on the expandable menu and select Write Off Payments
3- Click multiple times on the Write Off Payments button at the bottom of the screen
 
Expected result:
The amount of payments created should match the number of payments displayed in the “You are preparing to write off # Payments totaling” message
 
Actual result
Depending on the amount of clicks, as many Written off payments are created for the opp.

**Comment by melissabarber** [comment]
**lurch: attach W-033803

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vgPQAQ" target="_blank">W-033803</a>
