### ISSUE TITLE
TDTM_Allocation: Excluded User still hit with Inactive Fund

### ISSUE THREAD

**Issue by chasefriedman** [SalesforceFoundation/Cumulus#4640]
I've excluded the user from the TDTM that sits on Allocation__c but when I try to update an Allocation connected to an inactive GAU, I still get the validation error that the GAU is inactive. 

Is this not the correct to bypass the validation?

**Comment by coriobriensfdo** [comment]
@chasefriedman we don't provide support here in GitHub. Can you post your question, with images and steps to repeat in the [Power of Us Hub](https://powerofus.force.com/s/) NPSP Group?

**Comment by chasefriedman** [comment]
Thanks for the thought however we don't have access to that community as we're not a non-profit. Do you have another place we could go for support?

**Comment by coriobriensfdo** [comment]
@chasefriedman are you are Consultant working with a Nonprofit? If so, you can request access to the Hub for support. If you can email me at cori.obrien@salesforce.com I can help further if that's the case.
