### ISSUE TITLE
NPSP Data Import: Cannot map text field on DataImport__c to a Relationship field on Target Object

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/Cumulus#4684]
Currently, a DI text field cannot be mapped to a relationship field on the target object (although it can be the relationship field defined in the object mapping). There are valid scenarios where a DI text field should be mapped to a relationship field on a target object, such as an Account1 RecordType ID (which can only be stored as text on the DI, since you cannot create a relationship field to record type of a different object) but must be mapped to the RecordTypeId relationship on the Account. 

Current allowed target mappings for a DI text field are "String" and "Picklist", but this list should be expanded to include "Reference"  (validTargetTypesBySourceType in bdiFieldMappingModal.js).

Steps to reproduce:
Add text field to DataImport__c, "Account1 RecordTypeId"
Navigate to Advanced Mapping setup, Account1 Object group
New Field mapping, select "Account1 RecordTypeId" as Source Field
EXPECTED: RecordTypeId as option in target fields
ACTUAL: No RecordTypeId field

**Comment by ptewson-sfdo** [comment]
**lurch: attach W-036683

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBpDQAW" target="_blank">W-036683</a>
