### ISSUE TITLE
Limit matching Data Types when editing field mappings in Advanced Mapping.

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/Cumulus#4697]
When trying to edit a field mapping on an Object, we are showing fields of all different datatypes instead of only the ones that are supported for source data types.

**Comment by cpose** [comment]
**lurch: attach W-036530

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CBXxQAO" target="_blank">W-036530</a>

**Comment by jstvz** [comment]
Included in beta release 3.163 (Beta 43)
