### ISSUE TITLE
NPSP - Advanced Mapping - Checkbox not displaying as available target field for True/False

### ISSUE THREAD

**Issue by cpose** [SalesforceFoundation/Cumulus#4698]
We recently restricted the allowed values for mapping Picklist to Boolean to True or False.
Picklists created with these values are not causing our checkbox fields to appear as available target fields

Pre-conditions:
1- Source field is a picklist with values True or False
2- Checkbox created on target object

Steps:
1- Access object group for corresponding target object
2- Click on “New Field Mapping”
3- Select picklist from pre-conditions as source
4- Expand picklist for target field

Expected:
Checkbox is selectable as long as picklist values are True or False

Actual:
Checkbox field not appearing as available for selection

**Comment by cpose** [comment]
**lurch: attach W-036829

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CC7bQAG" target="_blank">W-036829</a>
