### ISSUE TITLE
Malformed JSON Error when Accessing NPSP Settings

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/Cumulus#4699]
When accessing NPSP Settings, error appearing:

> Malformed JSON: Expected '{' at the beginning of object
> An unexpected error has occurred. Your solution provider has been notified. (System)

**Steps to recreate**
1. In NPSP Settings > System Tools > Data Import Advanced Mapping > Set to **ON**
2. Leave NPSP Settings
3. In Setup > Custom Settings > Data Import Settings > Click "Manage" > Click "Edit" and change 1 character in the CMT Deployment ID Field. Changing 1 character ensures that the ID length stays the same and doesn't cause an "Invalid ID" error.
4. Come back to NPSP Settings and encounter above error.

**Workaround**
1. Go to Setup
2. Quick find "Custom Settings"
3. Click on "Data Import Settings"
4. Click "Manage" button
5. Click on "Edit" button
6. Clear out the "CMT Deployment ID" value in that field
7. Hit "Save"

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CCCWQA4" target="_blank">W-036882</a>

**Comment by coriobriensfdo** [comment]
Same as issue #4623

**Comment by coriobriensfdo** [comment]
Another [Hub Thread](https://powerofus.force.com/s/question/0D51E000053yDSbSAM/npsp-settings-error).

**Comment by coriobriensfdo** [comment]
[Hub Thread](https://powerofus.force.com/s/question/0D51E000053xXT4SAM/npsp-settings-malformed-json-error)
