### ISSUE TITLE
Data Import Batch showing blank screen

### ISSUE THREAD

**Issue by harrislapiroff** [SalesforceFoundation/Cumulus#4715]
I'm trying to test a batch import flow in my sandbox, but I can't get anything to show up when I view a data import batch. The interface just goes blank! See attached gif:

![data-import-batch-bug](https://user-images.githubusercontent.com/296631/67282265-5c7a3100-f49f-11e9-8d27-dc5da94c1eb4.gif)

Here are the steps I'm able to reproduce it with:

1. Log in
2. Click the App Launcher icon in the top left corner
3. Type "Data Import Batch" into the search bar
4. Click "NPSP Data Import Batches"
5. Click "New" to create and save a new data import batch
6. Click the name of the data import batch from the list

Browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by conorsch** [comment]
Curious whether console errors are shown. I've had a few misadventures, particularly with Firefox ESR, where Salesforce assets fail to load, resulting in a degraded experience much like what's in the GIF you kindly prepared.

**Comment by harrislapiroff** [comment]
I checked the console and didn't see any errors—just a bunch of logs from `BeaconLibrary.js` which I am reasonably sure aren't related.

**Comment by judisohn** [comment]
Hi @harrislapiroff First, we don't offer direct support here in Github. If you can't resolve this, please post in the [Power of Us Hub](https://powerofus.force.com) or open a support ticket. Thanks!

We've had various reports of this and it appears to be a Chrome-related [issue](https://success.salesforce.com/issues_view?id=a1p3A000001HlBdQAK).
