### ISSUE TITLE
global OPP_OpportunityNaming

### ISSUE THREAD

**Issue by adplatonov** [SalesforceFoundation/Cumulus#4717]
It would be nice to have an ability to invoke OPP_OpportunityNaming.refreshOppNames from apex. Currently, we use Page.OPP_OpportunityNamingBTN.getContent() in order to keep opp names up to date.

**Comment by coriobriensfdo** [comment]
@adplatonov we actually don't record new idea suggestions here in GitHub as issues. Instead, we use the Idea's functionality in the [Power of Us Hub](https://powerofus.force.com/s/ideas). Can you log your suggestion there instead?

Thanks!
