### ISSUE TITLE
NPSP - BDI - Donation matching fails when matching against Opportunity (and not payment)

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/Cumulus#4744]
**Issue:**

If a customer is using BDI or BGE to match an opportunity, the match will not find any matched records. This occurs only when matching against an open opportunity with no unpaid payments.

**Steps to repeat:**

Create Contact & Opportunity, $100, Closed Date = today Stage = Pledged
Remove any payments from the newly created Opportunity
Set up Batch, set Donation matching rule to match Donation on Amount and Date
Populate Data Import:
- Contact Imported (Contact from previous)
- Donation Donor = Contact1
- Donation Date = today
- Donation Amount = $100 
Process Batch with matching to Single match or create

**Expected Result:** 

Match to previously created donation

**Actual Result**

Donation created new

**Comment by ptewson-sfdo** [comment]
**lurch: attach W-037136

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HnwxQAC" target="_blank">W-037136</a>
