### ISSUE TITLE
BGE - Deleting a field mapping present on a Batch through UI, makes “Attempt to de-reference null object” error message display every time the batch is opened.

### ISSUE THREAD

**Issue by melissabarber** [SalesforceFoundation/Cumulus#4746]
If a field mapping present on a BGE Batch is deleted through Advanced Mapping UI, whenever the Batch is opened it displays an error message (even if the field mapping is not used on a gift).
 
Pre-Conditions: Advanced Mapping should be on with help texts migrated
 
Steps to reproduce:
1- Add a migrated or UI mapped Opportunity/Payment field to a new batch on BGE.
2- Can add and process a gift or leave batch empty (same result)
3- Go to the Advanced Mapping UI and delete the field mapping.
4- Go back to batch from steps 1 & 2.
 
Expected Result: Batch should not map on that field but should not display this error message. Instead, the batch should display a helpful error message, telling them that the field mapping has been deleted, and how to fix the issue.
 
Actual Result: “Attempt to de-reference null object” error message is displayed.
 
Workaround: Batch is still accessible to edit with “edit” button and saving without the deleted mapping makes the batch usable again.

**Comment by ravensisco** [comment]
Included in beta release 1.0 (Beta 2)
