### ISSUE TITLE
BGE: Update opportunity functionality creates new Gift for Gifts with multiple written-off payments instead of updating selected Gift

### ISSUE THREAD

**Issue by kenlewis-sfdo** [SalesforceFoundation/Cumulus#4765]
In the Batch Gift Entry wizard Review Donations component, Update Opportunity should update the amount and date for the user selected Opportunity in the modal. Currently, the function creates a completely new Donation and ignores the users selection from the modal. The new donation will have a new payment created from processing using the inputted donation amount and date from the entry form.
 
Pre-conditions:
- Having an open opportunity with multiple written off payments
- Being in BGE Gift Entry wizard
 
Steps to reproduce:
1- Access a batch and use donor lookup to select Account/Contact with the opportunity from pre-conditions
2- Open Review Donations modal and select Update Opportunity for the one in pre-conditions
3- Input values on the entry form, hit save and process the batch
4- The status column should display a new donation instead of the one selected previously
 
Expected Result:
The updated opportunity is the one selected previously from the modal
 
Actual Result:
A new donation is created and processed, ignoring the selection.

**Comment by kenlewis-sfdo** [comment]
**lurch: attach W-034578

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C7vRQAS" target="_blank">W-034578</a>
