### ISSUE TITLE
NPSP Settings in Version 3.165 Offset Incorrectly in Classic

### ISSUE THREAD

**Issue by mbeaty-sf** [SalesforceFoundation/Cumulus#4847]
**Issue**
User in a Classic Org, accessing NPSP Settings page finds that upon clicking on certain sections in the index tree on the left side of the page, the page is offset underneath its expected location, beneath the bottom of the page (see image below). **Note** this is only occurring from the "Recurring Donations" index tree section and below. Anything above Recurring Donations is not affected.

![image](https://user-images.githubusercontent.com/53280203/69667071-29006880-1042-11ea-8f1a-83e1a49d26f7.png)

**Steps to Recreate**

1. Ensure that instance is on NPSP 3.165
2. Click NPSP Settings
3. Click on "Recurring Donations" in the index tree
4. Click "Recurring Donations" under the previously clicked sub-heading
5. Click on any other items in the index tree from Recurring Donations and below, and find that the expected options appear unformatted below the bottom of the page

**Workaround**

Currently this issue only affects users who are navigating in Classic, the issue does not appear in Lightning. If possible, temporarily toggle Lightning experience for the user attempting to make changes to the NPSP Settings section to allow for the proper rendering of the page.

**Comment by mbeaty-sf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HpM4QAK" target="_blank">W-037854</a>

**Comment by mbeaty-sf** [comment]
Related Hub Post - https://powerofus.force.com/s/question/0D51E0000570LBtSAM/npsp-settings-not-rendering-correctly-since-today
