### ISSUE TITLE
Be able to manually recalculate NPSP rollups in Flow

### ISSUE THREAD

**Issue by ssk42** [SalesforceFoundation/Cumulus#4858]
You should be able to call an action in a Flow to be able to force a recalculation on an NPSP rollup.

**Comment by coriobriensfdo** [comment]
Hi @ssk42, we actually don't long community ideas for new features here in GitHub. Instead we log those in the [power of us hub](https://powerofus.force.com/s/) as Ideas. 

As a starting point, can you post to the hub and asked for feedback from the community? There is a recalculate rollup button in the NPSP today, however I'm not sure if it can be called via a flow.
