### ISSUE TITLE
As a beta tester, I want to have the option to allow the installer to permanently store the oauth connection to my org so it can automatically install new beta releases in my org.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#486]
- Allow for disconnecting an org
- Allow to turn off updates
- Build push upgrade functionality into mpinstaller
- Build api for triggering pushes from Jenkins

**Comment by kbromer** [comment]
@jlantz same here - should this be in mrbelvedere?
