### ISSUE TITLE
As a release manager, I want to investigate the viability of using TrialForce to provision clean orgs for CI use so I can ensure a consistent org configuration for each build.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#493]
We can do a clean through the metadata api for most of the metadata we handle in Cumulus.  However, there are some types, specifically RecordTypes, which cannot be deleted through the metadata api.  Most of our build related issues are caused by persistent data left in the org from a previous build.

Also, if we could spin up orgs dynamically as part of the build, we could run multiple feature branch builds in parallel to speed up the build process after Cumulus_dev_to_feature runs and updates all feature branches.

**Comment by kbromer** [comment]
@jlantz also mrbelvedere??
