### ISSUE TITLE
As an administrator, when closing existing opportunities, the app should respect the Written_Off__c flag and not automatically delete those closed payments. 

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#504]
Modify to check the Written_Off__c flag as well: 
https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/PMT_PaymentCreator.cls#L226

**Comment by kbromer** [comment]
@njjc Not sure why this was re-opened - a mistake perhaps? The fix looks to still be in place for this. 

I'm going to re-close this.
