### ISSUE TITLE
BUG: Some orgs have 1:1 contacts that cannot be deleted

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#508]
From: Daniel Trimble <DTrimble@kidango.org>
Date: Mon, Mar 10, 2014 at 5:46 PM

It appears to now be consistent in terms of when it happens.  At present, I CAN delete contacts that are assigned to any ordinary SFDC account record.  Those delete fine, whether through SFDC itself, Apsona, DTL, etc.  Works as it should.  However…
 
Contacts that were assigned to individual accounts created by NPSP fail every time now.  So I create a new contact with NPSP installed, leave the Account field blank, and NPSP creates the contact and an account of the same name as the contact and assigns it to that.  These contacts can’t be deleted, 100% of the time.  Doesn’t matter if I’m using SFDC, Apsona, or another tool; they all generate the same error of thinking the contact was already deleted.
 
Now, given such accounts automatically redirect to the contact with NPSP installed, the only way I figured I could try to delete the account first as a workaround, would be through Apsona or another data tool.  But when I try that, the account doesn’t even show up; only the contact.
 
If I reassign the contact record to a different account—any account other than the one NPSP created to match up with the individual contact—it deletes the contact fine.  It also leaves behind the original individual account record, but I can then go in and delete that one too.
 
So I have a temporary workaround.  Inconvenient, but it works.
 
Salesforce Foundation support has been granted login access for me for a month, under dtrimble@kidango.org if you feel it’d be useful to to play with it.  You’ll see a contact/account called Barack Obama that you can try with, and you’re welcome to create other contacts/accounts as well to test.
 
Cheers,
Dan
 
 
Dan Trimble
Director, Development & Communications
Kidango, Inc.
44000 Old Warm Springs Blvd.
Fremont, CA  94538
510-897-6913   direct
415-203-8047   mobile
510-897-6909   fax
dtrimble@kidango.org
http://www.kidango.org

**Comment by kbromer** [comment]
We'll call it platform for now and see if it resurfaces w/o 1x1s
