### ISSUE TITLE
As a developer, I would like to merge the Relationships package install script into the Cumulus install script

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#622]
Some of the advantages of using the install script in Cumulus are that it catches exceptions and sends emails on error. If for any reason the install script in Relationships failed, users would not be able to install Cumulus.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001frKAAQ" target="_blank">W-008264</a>
