### ISSUE TITLE
As a User, I'd like to see Opportunity rollups also total from child to parent Account.

### ISSUE THREAD

**Issue by salk31** [SalesforceFoundation/Cumulus#646]
We use a "parent" Account as the main container for everything related to a particular deceased person and an Account within that for each fundraising page (JustGiving etc)

We would like it if the parent Account showed totals for donations on that Account and child Accounts.

Thanks

Sam

**Comment by njjc** [comment]
I'd suggest posting on the [Power of Us Hub](https://powerofus.force.com/) to continue this conversation if needed.
