### ISSUE TITLE
As a tester (and developer?), I would like my buttons in the unmanaged package work the same as in the managed package

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#655]
Currently some buttons in the old packages give you a "URL No Longer Exists" error (see for example "Refresh Opportunities" in Recurring Donation). To get them to work both in the managed and unmanaged package we could change them from "Content Source: URL" to "Content Source: JavaScript", and wrap the URL redirect in a try-catch. 

Example of how to use try-catch for resolving the prefix issue when creating a Managed Package
var toggleAccount = function(value) {
try {
        sforce.apex.execute(&quot;TBS.TrustAccountHelper&quot;, 
                             &quot;toggleTrustAccount&quot;, 
                              { AccountId: &quot;{!Account.Id}&quot;, 
                                      value: value } );
} catch (e) {
        sforce.apex.execute(&quot;TrustAccountHelper&quot;, 
                               &quot;toggleTrustAccount&quot;, 
                               { AccountId: &quot;{!Account.Id}&quot;,
                                         value: value } );
            }
    };

**Comment by kbromer** [comment]
**lurch: attach W-007350

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZYAAY" target="_blank">W-007350</a>

**Comment by davisagli** [comment]
This was resolved recently in the qa_org configuration by deploying button overrides that don't use namespaces in the URLs.
