### ISSUE TITLE
As a user, I want to be able to manually rollup large numbers of donation in aggregate, but I may need to reduce the query size of the batch job to do so, so that I can rollup any number of donor/donations in my org. 

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#688]
- Consider surfacing the query limit parameter associated with the manual rollups tab

**Comment by kbromer** [comment]
**lurch: attach W-007347

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZVAAY" target="_blank">W-007347</a>

**Comment by mpusto** [comment]
This can now be accomplished through modifying the batch size settings in NPSP Settings.
