### ISSUE TITLE
As a user, I want the Get Started tab in Salesforce1 to work on narrow devices without side scrolling

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#707]

**Comment by njjc** [comment]
The new Get Started page (formerly known as NPSP Resources) is currently available in Salesforce1, although only new orgs through the DOT will get it in mobile navigation by default. Other orgs will have to enable it. I've added a docs story to update our mobile ready page.

There is a little bit of side scrolling for narrow devices, I'll leave this story open as a reminder to fix the responsive design.

**Comment by njjc** [comment]
Also verify all page links from a mobile device.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fZeAAI" target="_blank">W-008172</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.52 (Beta 11) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.52
