### ISSUE TITLE
As a user, I want to be able to see a version of the NPSP Settings with my main settings on a mobile device

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#708]
Low priority. 
It will only include the main settings.
Only view, not edit.

**Comment by kbromer** [comment]
**lurch: attach W-007321

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ5AAI" target="_blank">W-007321</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
