### ISSUE TITLE
As a user, I'd like the Membership Record Type Name set up by default

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#717]
As reported by John Fine (Hood River County School District Foundation):

 In NPSP Settings, Donations and Money, Memberships: No Membership Record Type Names are set upon installation. 'Membership' needs to be chosen in order for membership Opp totals to rollup.

**Comment by jlantz** [comment]
The setting is set correctly in the template for new trial orgs.  The change can be easily made by the user and the post install doc outlines how to make the change.
