### ISSUE TITLE
As a developer, I would like to have access to a demo org where I can play around with the NPSP

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#719]
All AE and Sales Engineers (and anyone else interested) should have an account created in a demo org where they can try the NPSP. 

The org should be preconfigured. It could have Volunteers for Salesforce (and any other package that is free for nonprofits and widely used) also installed.

**Comment by kbromer** [comment]
**lurch: attach W-007258

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cY4AAI" target="_blank">W-007258</a>

**Comment by davisagli** [comment]
We've had a trial org template for quite a while.
