### ISSUE TITLE
As a user, I want household members grouped by ID instead of by last name in the Households and Donations report

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#750]
As reported by Sam Knox (501 Commons):

---

This may all be changing in version 3, but I came across a packaged report today which I think could be improved. The report is called Households and Donations. It groups donations by household with a subtotal for each household. The problem is that it groups by name only so all of the Adams, Smiths, and Johnsons are grouped together even though they don't in fact share a household. For a client, I just added the Household ID as a second tier of grouping so they could see which Adams were supposed to be grouped together. Just a suggestion for an improvement!

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001froAAA" target="_blank">W-008266</a>

**Comment by judisohn** [comment]
Closing as this is related to NPSP 2/One to One functionality and the Household custom object.
