### ISSUE TITLE
As a user, I'd like the ability to automatically add the primary contact or all contact roles of an opportunity associated with a campaign as campaign members of that campaign.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#758]

**Comment by bermager** [comment]
any other info on this ticket?

**Comment by davidhabib** [comment]
more likely a custom setting that was something like "Automatically Add Opportunity Contacts to Campaign" with the values of None, Primary only, All.  I don't think we'd make this an attribute of each campaign, but rather a custom setting that affected all campaigns.  Unfortunately, there are not triggers on Opportunity Contact Role creation or modification, so we could only do this logic when we are first automatically adding any OCR's to the Opp.  later OCR's the user adds would not be affected.  Anyways, that just my thoughts.  we haven't discussed this.

**Comment by kbromer** [comment]
probably a better mechanism for this than what's suggested here... going to close it for now

**Comment by judisohn** [comment]
For those following/searching this, this thread might have some helpful info on declarative solutions: https://powerofus.force.com/0D58000002J0aWF

http://biggerboatconsulting.com/how-to-updating-campaign-member-status-via-process-builder-and-flow/
