### ISSUE TITLE
As a user, I would like a "new opportunity" button on the detail view of a contact in the mobile version of the app

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#762]
Which behaves like the "New Contact Donation" button in the web version.

It cannot be a Global Action because there is no parent Contact in context. I cannot be a Publisher Action either because there is no way to pass parameters and fill the parent contact (contact role ID). 

We need to investigate further and post a question to the pertinent org62 chatter group if we don't find a good solution. So far a custom VF page that uses the standard contact controller and that is called from a Publisher Action seems like the best option.

**Comment by kbromer** [comment]
**lurch: attach W-007324

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZ8AAI" target="_blank">W-007324</a>

**Comment by mpusto** [comment]
We created custom actions in our trial to prepare for Lightning. These are not packaged but we will provide instructions for customers to create them.
