### ISSUE TITLE
As a user, I want to be able to quickly add campaign members on the go through Salesforce1.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/Cumulus#766]
New custom VF page to add campaign members.

**Comment by kbromer** [comment]
**lurch: attach W-007239

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXlAAI" target="_blank">W-007239</a>

**Comment by mpusto** [comment]
There is also an IdeaExchange post for this: https://success.salesforce.com/ideaView?id=08730000000l0L6AAI

**Comment by njjc** [comment]
This has been marked as "Never" internally.
