### ISSUE TITLE
As a user, when I mark the last payment as paid, I'd like my Opportunity automatically updated to a Closed Won Stage, so I don't have to manually do this.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#795]
We'd probably need to a new setting for the user to specify what the Won Closed stage is that we should use.  I assume users want this and someone must have asked about it in the past?  It seems so basic to me if you are using Opps with payments.

**Comment by judisohn** [comment]
This is old, but I'm going through for Lurch. This is a very common request, currently accomplished via workflow rule that when the RUS fields of Payment Amount Received + Writeoff Amount = Amount the stage is changed. Stage Name doesn't have to be stored, just when Stage is changed to any Won value from a previously Open value.

**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fllAAA" target="_blank">W-008239</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 3.57 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.57
