### ISSUE TITLE
As a developer, get all datatable font's in our Settings UI to use the bootstrap font.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#814]
item for Shannon.

**Comment by davidhabib** [comment]
this may have been done, but I do notice that when one of the progress components is used, it is loading some resource that causes all fonts in our settings page to change size.

**Comment by kbromer** [comment]
**lurch: attach W-007373

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZwAAI" target="_blank">W-007373</a>

**Comment by mpusto** [comment]
Delivered in 3.39
