### ISSUE TITLE
As a developer, I want the be able to deprecate metadata when deployed to the packaging org in a way which doesn't break deployments to DE orgs and can be stored in the repository

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#873]
Using @deprecated against a DE org generates the error: "Only managed identifiers can be marked deprecated".

Current thoughts are to use a placeholder in a comment and add functionality to the build scripts to replace the comment with @deprecated when deploying to the packaging org.  This would allow DE orgs to deploy fine since the deprecated flag lives in a comment.

**Comment by kbromer** [comment]
@jlantz another one for the CCI repo?
