### ISSUE TITLE
As a user, I would like to use the error notification framework for my own errors

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#908]
From: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001MFVTL

---------

As a developer, if I write custom code on top of the NPSP, is it possible to log my own errors to NPSP's log? I perused Github and these classes don't look global, so my guess is no. But I'd be happy to be wrong.

If not, is that something you guys might consider opening up to us hackers? Would really save time coding our own error handling, and would provide a seamless experience for the admins.

-------------

Very good question. Even if the classes aren't global, we could use Apex to write directly to the Error__c object. Would the email/chatter-group alerts still work if our custom apex code wrote directly to the Error__c object?

**Comment by mrbelvedere** [comment]
Included in beta release version 3.32 (Beta 8) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.32
