### ISSUE TITLE
When looking at the affiliated contacts for an account in SF1 the name is not shown

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#924]
Only Role, Status and Start Date are shown. However, the affiliation Compact Layout does show Affiliation Name, Organization Name, and Contact Name. It seems like the Compact Layout shown is not defining the fields shown in the Record Preview Card.

Reported at https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CmVX&fId=0D58000001NRRcj

**Comment by tet3** [comment]
Or `npe5__Contact__r.Name`,  which would include the new standard Middle & Suffix fields if being used.

**Comment by samknox** [comment]
You can go one step further and make the name clickable by wrapping a hyperlink function around the name:

HYPERLINK("/"+ npe5__Contact__r.Id ,npe5__Contact__r.FirstName + ' ' + npe5__Contact__r.LastName)

Looks like you need to create a custom compact layout too cuz you can't edit the packaged one. Also if you need to access Affiliations from the parent you'll be viewing the related list, not the compact layout. As such your new formula field needs to be one of the first four columns in your related list. Don't like it? Vote this up: https://success.salesforce.com/ideaView?id=08730000000l5EpAAI
