### ISSUE TITLE
As a user, I can turn on custom household naming and have it update all household names in my database, without trying to detect which names might have previously been customized.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#928]
basically users want a way to update all households to the new household custom naming support, but they are running into cases where old households aren't being updated, because our code is pretty conservative about overwriting existing data.  We might need an additional option to force it.  need to review the code to make sure we aren't being too conservative due to a logic issue.  here is the hub thread:

https://powerofus.force.com/0D58000000OLG45

**Comment by kbromer** [comment]
I'm marking this as wontfix.  

I don't think we want to get into a scenario where a user can force us to overwrite data they previously forced us not to over-right.  Sounds like a messy proposition AND there's no way to undo it. If they really want this, they can update the Accounts before running the naming to no longer be overwritten, then run the renaming.
