### ISSUE TITLE
as a user, I want to be able to merge households when merging contacts, so I don't lose information.

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#94]
in the short term, HH Accounts will be merged just like 1:1 accounts, where one will be dropped.  A better solution may be to provide some enhancement in our Merge Contacts interface to do something smart.

**Comment by davidhabib** [comment]
Our ContactMerge page is now smart enough that if the contact is the only one in their household, we do an account merge as well as the contact merge.

Our ManageHouseholdUI page also provides options to both add a single contact from a household to the current household, or to add all members of a household to the current household.  Our triggers for Contact Account changing will move over all of the important related objects on these contacts.

**Comment by mrbelvedere** [comment]
Included in beta release version 3.39 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.39
