### ISSUE TITLE
As a developer, I want to carefully define the ADDR_IValidator interface before making it global

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/Cumulus#950]
We should build some services, test it for some time, and make adjustments until we are comfortable that we can make it global. 

Once it's global the community can create additional services.

**Comment by davidhabib** [comment]
**lurch: attach W-007310

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cYuAAI" target="_blank">W-007310</a>

**Comment by kbromer** [comment]
This should include testing framework for it as well so a user implementation can properly return the correct mocks, etc.

**Comment by njjc** [comment]
This has been marked as "Never" internally.
