### ISSUE TITLE
As a user, I want changes to Opportunities to immediately refresh rollups for all household members, so I don't see incorrect data

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/Cumulus#96]
Currently, when opps are inserted one at a time, we correctly update rollups for all household members.  But this code does not fire if the opp is just being updated.  Ideally it would also cause rollups to refire, at least in the case where only 1 opp is being updated.

**Comment by davidhabib** [comment]
**lurch: attach W-007360

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cZiAAI" target="_blank">W-007360</a>

**Comment by njjc** [comment]
This has been marked as "Never" internally.
