### ISSUE TITLE
As a user, I'd like to have OCRs automatically created for Contacts based on relationship defined through the realtionship object so I can manage board referrals, etc. 

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/Cumulus#961]
"Is there a way for contact relationships to automatically translate into an opportunity contact role?
Our Board has a minimum give/get requirement that we have to track. Our Board members provide us with their solicitation lists, which we have uploaded into relationships in Salesforce with the Board member as "referrer" and their prospect as "referee." For every single time the prospect gives, we would like this relationship to automatically translate into a "referrer" contact role in the donation opportunity, so that we can then attribute soft credit. This would make it significantly easier to track their give/get requirement."
https://powerofus.force.com/0D58000001OrXDY

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001fsSAAQ" target="_blank">W-008274</a>

**Comment by mpusto** [comment]
Also this Idea here: https://powerofus.force.com/hub-ideas/1040

**Comment by mrbelvedere** [comment]
Included in beta release 3.131 (Beta 11)

**Comment by mrbelvedere** [comment]
Included in production release 3.131
