### ISSUE TITLE
Lead Conversion page uses "Opportunity" as label instead of "Donation"

### ISSUE THREAD

**Issue by force2b** [SalesforceFoundation/Cumulus#965]
The use of "Opportunity" instead of "Donation" might be confusing to some users who are not familiar with standard Salesforce architecture. I recommend using the object label {!$ObjectType.Opportunity.Label} on the VF page. This same is true on the Lead Settings page.

https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/pages/LD_LeadConvertOverride.page

**Comment by mrbelvedere** [comment]
Included in beta release version 3.40 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 3.40
